In [8]:
import os
import re
import glob
import numpy as np
import pandas as pd
from pathlib import Path
import shutil
from tqdm import tqdm

In [15]:
# Pandas :: view ALL
pd.set_option('display.max_rows', None)
pd.set_option('display.max_columns', None)
pd.set_option('display.width', None)
pd.set_option('display.max_colwidth', None)

In [18]:
# Pandas :: Default view
pd.reset_option('display.max_rows')
pd.reset_option('display.max_columns')
pd.reset_option('display.width')
pd.reset_option('display.max_colwidth')

In [2]:
# Defines
def analyse_dataframe(df):
    nan_cnt = df.isnull().sum()
    nan_rto = df.isnull().mean()*100
    unique_vals_cnt = df.nunique()

    ana_result = pd.DataFrame({
        'NaN Counts' : nan_cnt
        , 'NaN Ratio (%)' : nan_rto
        , 'Unique Values' : unique_vals_cnt
    })
    return ana_result

In [9]:
## PRE
out = r"D:\JHAhn\files"
src_root = Path(r'D:\JHAhn\8641_conductivity\DTI_ALPS\DTI_ALPS_Result\2_Dementia')
dst_root = Path(r'E:\MR\Dataset')

In [4]:
sheets = pd.read_excel(os.path.join(ALPS_DIR, "Auto_ALPS_index_19-24_0731.xlsx")
                       , sheet_name=["Sheet1", "8641", "8641_Dementia"]
                      )
dfS1 = sheets["Sheet1"]    # base
df8641 = sheets["8641"]    # CN
dfDem = sheets["8641_Dementia"]    # Dementia


def clean_pad_pid(df):
    """PID 컬럼을 8자리 0-패딩 문자열로 변환 (결측값은 그대로)"""
    if "PID" not in df.columns:
        return df

    mask = df["PID"].notna()                                 # 결측이 아닌 행
    df.loc[mask, "PID"] = (
        df.loc[mask, "PID"]
          .astype(str)                                        # → 문자열
          .str.replace(r"\.0$", "", regex=True)               # ① 끝 '.0' 제거
          .str.replace(r"[^\d]", "", regex=True)              # ② 혹시 남은 비숫자 제거
          .str.zfill(8)                                       # ③ 8자리 0-패딩
    ).astype("string")                                        # ④ dtype 문자열 고정
    return df

for df in (dfS1, df8641, dfDem):
    clean_pad_pid(df)


print(dfS1.shape, df8641.shape, dfDem.shape, '\n')
print(dfS1, df8641, dfDem)

(206, 52) (58, 105) (209, 105)

     건대분석정보                 인원    DDX     AD_MWI_Code    미수코드  \
0    NL(39)                NaN    NaN             NaN     NaN
1       Yea                NaN     NL     EPT2022AD40     NaN
2        No                NaN     NL     EPT2023AD09     NaN
3       Yes                  1     NL        MWI_CN01  8641.0
4       Yes                  2     NL        MWI_CN04  8641.0
..      ...                ...    ...             ...     ...
201     Yes             9탈락3-2  NaMCI  MWI_CN66(ver2)  8641.0
202     Yes            10탈락3-3  NaMCI  MWI_CN67(ver2)  8641.0
203     Yes            13탈락3-4  NaMCI  MWI_CN70(ver2)  8641.0
204     Yes      탈락-infarction  NaMCI   MREPT2020AD10     NaN
205     Yes  탈락-venous anomaly  NaMCI   MREPT2020AD27     NaN

                 논문사용       PID Name   Age ChiQSM  ... MR_3DT1_TFE  \
0                 NaN       NaN  NaN   NaN    NaN  ...         NaN
1          2022 상반기영상  09463703  유길종  74.0  CNL02  ...           O
2                 NaN  08787368  이송웅  81.0  CNL03  ...         NaN
3           HFC,LFC사용  00145616  강난희  70.0  CNL04  ...         NaN
4              HFC 사용  02716077  송승숙  62.0  CNL05  ...         NaN
..                ...       ...  ...   ...    ...  ...         ...
201  newMWI_CN 27명 추가  00766581  조수연  71.0  CNM25  ...         NaN
202  newMWI_CN 27명 추가  09577263  김오심  82.0  CNM26  ...         NaN
203  newMWI_CN 27명 추가  02202449  이청자  80.0  CNM27  ...         NaN
204               NaN  08276845  조영자  73.0  CNM29  ...           O
205               NaN  00577752  양정자  71.0  CNM30  ...           O

    MR_3DGRASE_MWI MR_3DGRASE_REF MREPT_TSE    NODDI MREPT_3DbFFE  \
0              NaN            NaN       NaN      NaN          NaN
1                O              O         O  NODDI32            X
2              NaN            NaN       NaN      NaN          NaN
3              NaN            NaN       NaN      NaN          NaN
4              NaN            NaN       NaN      NaN          NaN
..             ...            ...       ...      ...          ...
201            NaN            NaN       NaN      NaN          NaN
202            NaN            NaN       NaN      NaN          NaN
203            NaN            NaN       NaN      NaN          NaN
204              O              O         O  NODDI32            X
205              O              O         O  NODDI32            X

     Unnamed: 48  conductivity                MWF  Chi
0            NaN           NaN                NaN  NaN
1            NaN             O                  O    O
2            NaN             O                  O    O
3            NaN             O                  O    O
4            NaN             O                  O    O
..           ...           ...                ...  ...
201          NaN             O                  O    O
202          NaN             O                  O    O
203          NaN             O                  O    O
204          NaN           NaN      탈락-infarction  NaN
205          NaN           NaN  탈락-venous anomaly  NaN

[206 rows x 52 columns]     Unnamed: 0                   PDI       PID    DDX    Year  Age sex  \
0            1  MWI_CN01_KNH_NODDI32  00145616     NL  2019.0   70   F
1            2  MWI_CN04_SSS_NODDI32  02716077     NL  2019.0   62   F
2            3  MWI_CN05_LSS_NODDI32  00469852     NL  2019.0   72   M
3            4  MWI_CN06_KDS_NODDI32  02296061     NL  2019.0   72   M
4            5  MWI_CN07_KSB_NODDI32  00316024     NL  2019.0   66   M
5            6  MWI_CN09_YKJ_NODDI32  00080969  NaMCI  2019.0   65   F
6            7  MWI_CN10_CJS_NODDI32  01147259  Other  2019.0   66   F
7            8  MWI_CN12_LJK_NODDI32  05871888     NL  2019.0   66   F
8            9   MWI_CN13_KH_NODDI32  06476189  SaMCI  2019.0   69   M
9           10  MWI_CN14_PYJ_NODDI32  04341115  NaMCI  2019.0   66   F
10          11  MWI_CN15_YCJ_NODDI32  01607233  Other  2019.0   75   F
11          12  MWI_CN16_LCS_NODDI32  01190888  NaMCI  2019.0   74   M
12          13  MWI_CN17_LPS_NODDI32  04825611  MaMCI  2019.0   63   F
13          14  MWI_CN18_HCS_NODDI32  02022033  MaMCI  2019.0   68   F
14          15  MWI_CN19_CSO_NODDI32  04073053     NL  2019.0   64   F
15          16  MWI_CN20_PYJ_NODDI32  01382411     NL  2020.0   68   M
16          17  MWI_CN21_PYB_NODDI32  04086417     NL  2020.0   66   F
17          18  MWI_CN22_YYJ_NODDI32  00875397     NL  2020.0   66   F
18          19  MWI_CN23_HJL_NODDI32  08481071     NL  2020.0   64   F
19          20  MWI_CN24_PKJ_NODDI32  08481058     NL  2020.0   72   M
20          21  MWI_CN25_NKJ_NODDI32  08500417  MaMCI  2020.0   79   F
21          22  MWI_CN26_LSR_NODDI32  08510171  MaMCI  2020.0   69   F
22          23  MWI_CN27_LSJ_NODDI32  08510155     NL  2020.0   68   M
23          24  MWI_CN28_KOS_NODDI32  00213101     NL  2020.0   68   F
24          25  MWI_CN29_KSH_NODDI32  00243749  SaMCI  2020.0   70   F
25          26  MWI_CN30_PYS_NODDI32  08519137  MaMCI  2020.0   61   F
26          27  MWI_CN31_LOH_NODDI32  02528398  MaMCI  2020.0   75   F
27          28  MWI_CN32_KYH_NODDI32  08664289  SaMCI  2020.0   81   M
28          29  MWI_CN33_LSH_NODDI32  01206895     NL  2020.0   68   F
29          30  MWI_CN34_OJS_NODDI32  04727886     NL  2020.0   77   F
30          31  MWI_CN35_LES_NODDI32  08696493     NL  2020.0   61   F
31          32  MWI_CN36_KER_NODDI32  00738146  SaMCI  2020.0   64   F
32          33  MWI_CN37_KJR_NODDI32  01283958  NaMCI  2020.0   65   M
33          34  MWI_CN38_JJB_NODDI32  02022042     NL  2020.0   71   M
34          35  MWI_CN39_LTS_NODDI32  00613165     NL  2020.0   77   M
35          36  MWI_CN40_LDS_NODDI32  08129675     NL  2020.0   72   F
36          37  MWI_CN41_JHL_NODDI32  04920375     NL  2020.0   83   F
37          38  MWI_CN57_YHY_NODDI32  08527223     NL  2022.0   76   F
38          39  MWI_CN58_LSB_NODDI32  00213324     NL  2022.0   70   M
39          40  MWI_CN61_CHS_NODDI32  01422655     NL  2022.0   76   M
40          41  MWI_CN65_PYS_NODDI32  09524528     NL  2022.0   72   F
41          42  MWI_CN66_CSY_NODDI32  00766581  NaMCI  2022.0   71   F
42          43  MWI_CN67_KOS_NODDI32  09577263  NaMCI  2022.0   82   F
43          44  MWI_CN68_CDL_NODDI32  00641619  MaMCI  2022.0   74   F
44          45  MWI_CN69_LSL_NODDI32  09588015     NL  2022.0   69   F
45          46  MWI_CN70_LCJ_NODDI32  02202449  NaMCI  2022.0   80   F
46          47  MWI_CN71_LSH_NODDI32  00863315     NL  2022.0   73   F
47          48  MWI_CN73_GIS_NODDI32  04074843  MaMCI  2022.0   74   F
48          49  MWI_CN74_LKY_NODDI32  09605724  SaMCI  2022.0   71   F
49          50  MWI_CN75_KKS_NODDI32  09605754  SaMCI  2022.0   73   M
50          51  MWI_CN76_PHJ_NODDI32  00359871     NL  2022.0   78   F
51          52  MWI_CN77_PJC_NODDI32  07090169     NL     NaN   68   M
52          53  MWI_CN79_CYE_NODDI32  10412739  SaMCI  2023.0   72   F
53          54  MWI_CN80_LSR_NODDI32  10474812  MaMCI     NaN   78   F
54          55  MWI_CN81_CSH_NODDI32  10482577  SaMCI  2024.0   66   M
55          56  MWI_CN82_LMR_NODDI32  10412747  SaMCI  2023.0   74   M
56          57  MWI_CN83_LYS_NODDI32  10474783     NL     NaN   74   F
57          58  MWI_CN84_LHS_NODDI32  10474798  MaMCI  2024.0   74   F

    Education_yr  LT_ALL_Dxx_proj  LT_ALL_Dyy_proj  ...  \
0           16.0         0.853582         0.731372  ...
1           12.0         0.721595         0.654347  ...
2           16.0         0.648850         0.534350  ...
3            6.0         0.776232         0.855603  ...
4            9.0         0.760503         0.692654  ...
5           12.0         0.721305         0.585058  ...
6            9.0         0.766402         0.500861  ...
7           12.0         0.809517         0.506511  ...
8           16.0         0.661128         0.740881  ...
9            0.5         0.667318         0.716731  ...
10           6.0         0.783634         0.542104  ...
11          12.0         0.750492         0.767349  ...
12           7.0         0.812866         0.996424  ...
13           6.0         0.805717         0.608529  ...
14           9.0         0.637047         0.484846  ...
15          12.0         0.649847         0.728100  ...
16          14.0        89.345674        85.156431  ...
17          16.0         0.771681         0.663884  ...
18          12.0         0.861621         0.685175  ...
19          16.0         0.780769         0.805937  ...
20           6.0         0.809053         0.628974  ...
21           6.0         0.651656         0.516872  ...
22           9.0         0.785996         0.609021  ...
23           9.0         0.821979         0.734907  ...
24          12.0         0.652968         0.485778  ...
25           9.0         0.659945         0.500463  ...
26           0.0         0.636865         0.624176  ...
27           9.0         0.696205         0.723061  ...
28          12.0         0.638877         0.698796  ...
29           8.0         0.687721         0.524964  ...
30          12.0         0.763828         0.533087  ...
31          12.0         0.747137         0.516512  ...
32          12.0         1.267064         1.244017  ...
33           3.0         0.697029         0.773143  ...
34          12.0         0.676112         0.748491  ...
35          12.0         0.680826         0.595489  ...
36           6.0         0.730996         0.606768  ...
37           NaN         0.629832         0.574801  ...
38           NaN         0.707732         0.692642  ...
39           NaN         0.691838         0.513470  ...
40           NaN         0.742088         0.611022  ...
41           NaN         0.663827         0.725533  ...
42           NaN         0.625652         0.643337  ...
43           NaN         0.825319         0.661257  ...
44           NaN         0.567737         0.528092  ...
45           NaN         0.771396         0.632500  ...
46           NaN         0.635816         0.511072  ...
47           NaN         0.614696         0.510977  ...
48           NaN         0.636038         0.581639  ...
49           NaN         0.839752         0.745258  ...
50           NaN         0.974929         0.802987  ...
51           NaN         0.666742         0.643739  ...
52           NaN         0.753935         0.504262  ...
53           NaN         0.602834         0.559894  ...
54           NaN         0.638415         0.664246  ...
55           NaN         0.789849         0.802365  ...
56           NaN         0.572063         0.531833  ...
57           NaN         0.647483         0.572705  ...

    EC_RT_ParaHippocampus  HFC_RT_Thalamus  IC_RT_Thalamus  EC_RT_Thalamus  \
0                0.569473         0.826935        0.271682        0.555182
1                0.489838         0.761443        0.233806        0.527660
2                0.544412         0.850338        0.298828        0.551536
3                0.573242         1.072521        0.284065        0.788510
4                0.536905         0.884778        0.235095        0.649583
5                0.545306         0.986288        0.226849        0.759351
6                0.449067         0.874900        0.364917        0.509969
7                0.462334         0.860930        0.293146        0.567797
8                0.522063         1.011569        0.237576        0.773883
9                0.527500         1.189327        0.276960        0.912264
10               0.558958         0.972299        0.285758        0.686471
11               0.525401         0.972692        0.239256        0.733374
12               0.480014         0.887022        0.244920        0.642013
13               0.486360         0.826049        0.303949        0.522080
14               0.517200         0.867916        0.234691        0.633179
15               0.554155         0.865996        0.253210        0.612668
16               0.463821         0.833821        0.252496        0.581255
17               0.513835         0.807599        0.227501        0.580202
18               0.539687         0.925020        0.218422        0.706476
19               0.470152         0.945116        0.257279        0.687774
20               0.629807         0.956596        0.254913        0.701614
21               0.462270         0.854853        0.298488        0.556636
22               0.501959         0.844196        0.239438        0.604761
23               0.525605         0.852981        0.264995        0.588012
24               0.665788         0.951107        0.317747        0.633336
25               0.477922         0.836799        0.276130        0.560642
26               0.497597         0.894365        0.197061        0.697566
27               0.518186         0.884590        0.273622        0.610941
28               0.664519         0.911801        0.342418        0.569403
29               0.551505         1.110993        0.328570        0.782494
30               0.483109         0.737282        0.270293        0.467234
31               0.549753         0.842202        0.219193        0.622979
32               0.454507         0.749496        0.225184        0.524271
33               0.630026         1.024894        0.292525        0.732272
34               0.507875         0.930561        0.273329        0.657178
35               0.469159         0.850163        0.383543        0.466574
36               0.592879         0.840836        0.299190        0.541651
37               0.508168         0.798943        0.220934        0.578004
38               0.245936         0.840967        0.212460        0.628435
39               0.518160         0.928442        0.273525        0.655068
40               0.495931         0.822200        0.190986        0.631176
41               0.436440         0.765378        0.181157        0.584184
42               0.583334         0.786152        0.203446        0.582679
43               0.546697         0.882832        0.250534        0.632197
44               0.535490         0.870760        0.208700        0.662040
45               0.494867         0.793464        0.218678        0.574741
46               0.629526         0.790673        0.190738        0.600125
47               0.413912         0.850759        0.284682        0.566028
48               0.495830         0.807041        0.192684        0.614290
49               0.457684         0.936529        0.214338        0.722082
50               0.594984         0.899423        0.214330        0.685096
51               0.434339         0.813729        0.177067        0.636584
52               0.423002         0.822054        0.257318        0.564671
53               0.753751         0.807771        0.185336        0.622558
54               0.451643         0.789196        0.212962        0.576243
55               0.474700         0.901093        0.220515        0.680470
56               0.526787         0.860828        0.222414        0.638332
57               0.343942         0.769077        0.179261        0.590332

    HFC_Whole_CC  IC_Whole_CC  EC_Whole_CC  HFC_Whole_Precuneus  \
0       0.596481     0.212770     0.383751             0.628513
1       0.482623     0.188198     0.294517             0.592590
2       0.560023     0.178677     0.381515             0.707167
3       0.623203     0.149430     0.473831             0.774144
4       0.540163     0.201650     0.338564             0.664265
5       0.528989     0.166927     0.362146             0.656091
6       0.502285     0.193763     0.308677             0.674751
7       0.561543     0.224490     0.337122             0.663349
8       0.517119     0.085755     0.431430             0.617109
9       0.568219     0.154569     0.413899             0.629691
10      0.571364     0.164050     0.407373             0.660082
11      0.567984     0.149137     0.418912             0.704890
12      0.525424     0.176074     0.349367             0.651993
13      0.526794     0.191792     0.335063             0.605105
14      0.473566     0.186737     0.286957             0.652881
15      0.566002     0.194978     0.371117             0.668789
16      0.499714     0.180962     0.318732             0.580333
17      0.492460     0.184134     0.308399             0.621884
18      0.469806     0.144857     0.325102             0.593628
19      0.453864     0.144097     0.309865             0.666179
20      0.634575     0.254143     0.380491             0.701145
21      0.618233     0.267933     0.350261             0.667676
22      0.539841     0.188142     0.351836             0.712939
23      0.550044     0.135748     0.414328             0.672186
24      0.554084     0.151098     0.403054             0.741013
25      0.485406     0.202200     0.283275             0.625345
26      0.598659     0.160472     0.438273             0.669564
27      0.586860     0.148645     0.438361             0.789711
28      0.516731     0.177462     0.339318             0.643531
29      0.529869     0.155402     0.374542             0.698818
30      0.530641     0.231312     0.299411             0.644428
31      0.518357     0.178988     0.339459             0.626832
32      0.516256     0.186873     0.329481             0.668951
33      0.595624     0.129663     0.466013             0.676542
34      0.603205     0.151556     0.451843             0.707243
35      0.605229     0.194116     0.411091             0.717616
36      0.623312     0.125874     0.497510             0.775225
37      0.477151     0.142118     0.335096             0.681972
38      0.535565     0.151260     0.384363             0.636286
39      0.508125     0.141542     0.366679             0.679949
40      0.567236     0.182091     0.385219             0.673377
41      0.495296     0.163504     0.331894             0.637991
42      0.560845     0.146901     0.414069             0.751461
43      0.546445     0.152043     0.394534             0.662188
44      0.539993     0.129953     0.410144             0.622445
45      0.502785     0.165001     0.337965             0.682435
46      0.657349     0.209189     0.448150             0.686114
47      0.614579     0.217501     0.397129             0.779806
48      0.540094     0.154422     0.385784             0.672241
49      0.555994     0.167777     0.388274             0.695768
50      0.509969     0.174463     0.335585             0.675825
51      0.469045     0.150621     0.318576             0.601623
52      0.516003     0.183478     0.332622             0.641243
53      0.633271     0.170613     0.462788             0.697514
54      0.533376     0.141496     0.391933             0.594671
55      0.488034     0.144081     0.344001             0.621078
56      0.536061     0.155244     0.380953             0.602585
57      0.535888     0.157677     0.378221             0.599822

    IC_Whole_Precuneus  EC_Whole_Precuneus
0             0.125133            0.503758
1             0.139421            0.453941
2             0.123957            0.582434
3             0.129967            0.644462
4             0.148808            0.523295
5             0.120433            0.535400
6             0.154631            0.521590
7             0.132673            0.526265
8             0.129431            0.483453
9             0.130360            0.501892
10            0.112985            0.543710
11            0.114604            0.591241
12            0.153292            0.501550
13            0.134528            0.470944
14            0.148644            0.506357
15            0.158707            0.511535
16            0.151689            0.433268
17            0.129900            0.490079
18            0.125361            0.469178
19            0.139076            0.526869
20            0.141241            0.559319
21            0.160014            0.509432
22            0.161860            0.556985
23            0.121256            0.549712
24            0.150816            0.590936
25            0.134644            0.494961
26            0.118688            0.554970

In [5]:
dfS1

,건대분석정보,인원,DDX,AD_MWI_Code,미수코드,논문사용,PID,Name,Age,ChiQSM,...,MR_3DT1_TFE,MR_3DGRASE_MWI,MR_3DGRASE_REF,MREPT_TSE,NODDI,MREPT_3DbFFE,Unnamed: 48,conductivity,MWF,Chi
0,NL(39),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Yea,NaN,NL,EPT2022AD40,NaN,2022 상반기영상,09463703,유길종,74.0,CNL02,...,O,O,O,O,NODDI32,X,NaN,O,O,O
2,No,NaN,NL,EPT2023AD09,NaN,NaN,08787368,이송웅,81.0,CNL03,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,O,O,O
3,Yes,1,NL,MWI_CN01,8641.0,"HFC,LFC사용",00145616,강난희,70.0,CNL04,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,O,O,O
4,Yes,2,NL,MWI_CN04,8641.0,HFC 사용,02716077,송승숙,62.0,CNL05,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,O,O,O
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
201,Yes,9탈락3-2,NaMCI,MWI_CN66(ver2),8641.0,newMWI_CN 27명 추가,00766581,조수연,71.0,CNM25,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,O,O,O
202,Yes,10탈락3-3,NaMCI,MWI_CN67(ver2),8641.0,newMWI_CN 27명 추가,09577263,김오심,82.0,CNM26,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,O,O,O
203,Yes,13탈락3-4,NaMCI,MWI_CN70(ver2),8641.0,newMWI_CN 27명 추가,02202449,이청자,80.0,CNM27,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,O,O,O
204,Yes,탈락-infarction,NaMCI,MREPT2020AD10,NaN,NaN,08276845,조영자,73.0,CNM29,...,O,O,O,O,NODDI32,X,NaN,NaN,탈락-infarction,NaN
205,Yes,탈락-venous anomaly,NaMCI,MREPT2020AD27,NaN,NaN,00577752,양정자,71.0,CNM30,...,O,O,O,O,NODDI32,X,NaN,NaN,탈락-venous anomaly,NaN

In [6]:
def move_to_sgds(df):
    # SGDS 칼럼이 없으면 먼저 만들기
    if "SGDS" not in df.columns:
        df["SGDS"] = pd.NA

    # ① SGDS + 공백
    pat1 = re.compile(r"^SGDS\s*(.+)$")
    mask1 = df["NPI"].astype(str).str.match(pat1, na=False)
    df.loc[mask1, "SGDS"] = df.loc[mask1, "NPI"].str.replace(pat1, r"\1", regex=True).str.strip()
    df.loc[mask1, "NPI"]  = pd.NA

    # ② SGDS=
    pat2 = re.compile(r"^SGDS=(.+)$")
    mask2 = df["NPI"].astype(str).str.match(pat2, na=False)
    df.loc[mask2, "SGDS"] = df.loc[mask2, "NPI"].str.replace(pat2, r"\1", regex=True).str.strip()
    df.loc[mask2, "NPI"]  = pd.NA

    # ③ *(normal)
    pat3 = re.compile(r"^(.+?)\s*\(normal\)$")
    mask3 = df["NPI"].astype(str).str.match(pat3, na=False)
    df.loc[mask3, "SGDS"] = df.loc[mask3, "NPI"].str.replace(pat3, r"\1", regex=True).str.strip()
    df.loc[mask3, "NPI"]  = pd.NA

    return df

dfS1 = move_to_sgds(dfS1)

dfS1[['NPI', 'SGDS']]

        NPI  SGDS
0       NaN   NaN
1     0/144   NaN
2       NaN   NaN
3      0/44   NaN
4     3/144   NaN
..      ...   ...
201     NaN  <NA>
202    <NA>  1/15
203     NaN  <NA>
204   0/144  <NA>
205  27/144  <NA>

[206 rows x 2 columns]

In [7]:
analyse_dataframe(dfS1)

                     NaN Counts  NaN Ratio (%)  Unique Values
건대분석정보                        4       1.941748              8
인원                          101      49.029126             46
DDX                           9       4.368932              5
AD_MWI_Code                   9       4.368932            197
미수코드                        136      66.019417              1
논문사용                         55      26.699029             14
PID                           9       4.368932            195
Name                          9       4.368932            196
Age                           9       4.368932             36
ChiQSM                       14       6.796117            192
Sex                           9       4.368932              2
Education (Year)             60      29.126214             29
Screen fail/Drop 이유         136      66.019417             11
임상정보 추가                      75      36.407767             45
최종진단 DDX                      9       4.368932             33
SNSB StudyDate               26      12.621359            151
MMSE                         11       5.339806             19
CDR                          12       5.825243              4
CDRSB                        27      13.106796             16
GDS                          26      12.621359              5
Barthel A DL                 17       8.252427              5
Instrumental A DL            29      14.077670             46
NPI                          94      45.631068             20
PET(amyloid, FDG)            10       4.854369             17
Unnamed: 24                 206     100.000000              0
TIV                         130      63.106796             76
global GMV                  130      63.106796             76
global WMV                  130      63.106796             76
global CSFV                 130      63.106796             76
Unnamed: 29                 206     100.000000              0
Unnamed: 30                 206     100.000000              0
Unnamed: 31                 206     100.000000              0
Unnamed: 32                 206     100.000000              0
Unnamed: 33                 206     100.000000              0
Unnamed: 34                 114      55.339806             83
보호자정보                       168      81.553398             36
Unnamed: 36                 206     100.000000              0
Unnamed: 37                 187      90.776699              9
Unnamed: 38                 206     100.000000              0
Unnamed: 39                 206     100.000000              0
MRI StudyDate                17       8.252427            167
MRI판독 conclusion             12       5.825243            171
MR_3DT1_TFE                  79      38.349515              2
MR_3DGRASE_MWI               79      38.349515              3
MR_3DGRASE_REF               79      38.349515              3
MREPT_TSE                    79      38.349515              3
NODDI                        79      38.349515              6
MREPT_3DbFFE                 79      38.349515              2
Unnamed: 48                 206     100.000000              0
conductivity                 32      15.533981              1
MWF                          12       5.825243              9
Chi                          32      15.533981              1
SGDS                        194      94.174757              9

In [8]:
def to_pdi(x):
    parts = str(x).split("_")
    return "_".join(parts[:-2]) if len(parts) >= 3 else parts[0]

for df in (df8641, dfDem):
    if "PDI" not in df.columns:
        df["PDI"] = df["PID"].map(to_pdi)

In [9]:
df = dfS1
for column in df.columns:
    print(f"Col name: {column}")
    print(f"Data type: {df[column].dtype}")
    print(f"Unique values: {len(df[column].unique())}")
    print(df[column].unique())
    print('-'*40)

Col name: 건대분석정보
Data type: object
Unique values: 9
['NL(39)' 'Yea' 'No' 'Yes' nan 'SaMCI(41)' 'MaMCI(36)' 'AD (35)'
 'NaMCI(20)']
----------------------------------------
Col name: 인원
Data type: object
Unique values: 47
[nan 1 2 3 4 5 10 17 18 19 20 21 22 8 9 11 14 15 25 6 12 13 '탈락' 27 24 16
 7 '점수미달' 'MREPT2019AD10' 23 28 '탈락-hydrocephalus' 'MREPT2019AD09'
 'MREPT2019AD13' '탈락-SAH' '4탈락-' 'MREPT2019AD11' '7탈락1-2' '12탈락1-5'
 '14탈락1-7' '7탈락2-1' '19탈락2-2' '9탈락3-2' '10탈락3-3' '13탈락3-4' '탈락-infarction'
 '탈락-venous anomaly']
----------------------------------------
Col name: DDX
Data type: object
Unique values: 6
[nan 'NL' 'SaMCI' 'MaMCI' 'AD' 'NaMCI']
----------------------------------------
Col name: AD_MWI_Code
Data type: object
Unique values: 198
[nan 'EPT2022AD40' 'EPT2023AD09' 'MWI_CN01' 'MWI_CN04' 'MWI_CN05'
 'MWI_CN06' 'MWI_CN07' 'MWI_CN12' 'MWI_CN19' 'MWI_CN20' 'MWI_CN21'
 'MWI_CN22' 'MWI_CN23' 'MWI_CN24' 'MWI_CN33' 'MWI_CN35' 'MWI_CN38'
 'MWI_CN39' 'MWI_CN40' 'MWI_CN41' 'MWI_CN44' 'MWI_CN45' 'MWI_CN47'
 'MWI_CN48' 'MWI_CN50' 'MWI_CN51' 'MWI_CN55' 'MWI_CN57(ver2)'
 'MWI_CN58(ver2)' 'MWI_CN61(ver2)' 'MWI_CN63(ver2)' 'MWI_CN65(ver2)'
 'MWI_CN69(ver2)' 'MWI_CN71(ver2)' 'MWI_CN76(ver2)' 'MWI_CN77(ver2)'
 'MWI_CN83(ver2)' 'MWI_CN27' 'MWI_CN43' 'MWI_CN34' 'ADEPT54' 'EPT2022AD03'
 'EPT2022AD06' 'EPT2022AD11' 'EPT2022AD12' 'EPT2022AD29' 'EPT2022AD43'
 'EPT2022AD49' 'EPT2022AD50' 'EPT2022AD67' 'EPT2023AD13' 'EPT2024AD04'
 'HFC2020AD02' 'HFC2021AD06' 'HFC2021AD12' 'HFC2021AD25' 'HFC2021AD37'
 'HFC2021AD39' 'HFC2021AD41' 'HFC2021AD42' 'HFC2021AD47' 'HFC2021AD52'
 'HFC2021AD54' 'HFC2021AD55' 'HFC2021AD57' 'AD2019_BrMRA02'
 'AD2019_BrMRA05' 'MWI_CN13' 'MWI_CN29' 'MWI_CN32' 'MWI_CN36' 'MWI_CN42'
 'MWI_CN54' 'MWI_CN56(ver1.2)' 'MWI_CN74(ver2)' 'MWI_CN75(ver2)'
 'MWI_CN79(ver2)' 'MWI_CN81(ver2)' 'MWI_CN82(ver2)' 'EPT2024AD03'
 'HFC2021AD48' 'AD2019_BrMRA14' 'EPT2022AD22' 'HFC2021AD15' 'HFC2021AD16'
 'HFC2021AD26' 'HFC2021AD40' 'HFC2021AD45' 'MREPT2020AD04' 'MREPT2020AD25'
 'HFC2021AD20' 'ADEPT50' 'EPT2022AD07' 'EPT2022AD18' 'EPT2022AD20'
 'EPT2022AD23' 'EPT2022AD30' 'EPT2022AD31' 'EPT2022AD34' 'EPT2022AD39'
 'EPT2022AD41' 'EPT2022AD44' 'EPT2022AD45' 'EPT2022AD065' 'EPT2023AD01'
 'EPT2024AD02' 'HFC2021AD09' 'HFC2021AD11' 'AD2019_BrMRA08'
 'AD2019_BrMRA10' 'MREPT2020AD06' 'MREPT2020AD20' 'MREPT2020AD26'
 'MWI_CN25' 'MWI_CN26' 'MWI_CN30' 'MWI_CN46' 'MWI_CN53' 'MWI_CN64(ver2)'
 'MWI_CN68(ver2)' 'MWI_CN80(ver2)' 'EPT2022AD24' 'EPT2022AD47'
 'EPT2022AD61' 'HFC2021AD03' 'AD2019_BrMRA01' 'MREPT2020AD05' 'MWI_CN31'
 'EPT2022AD09' 'EPT2022AD13' 'EPT2022AD16' 'EPT2022AD54' 'EPT2023AD22'
 'MWI_CN73(ver2)' 'MREPT2020AD14' 'EPT2022AD01' 'EPT2022AD02'
 'EPT2022AD05' 'EPT2022AD10' 'EPT2022AD17' 'EPT2022AD19' 'EPT2022AD21'
 'EPT2022AD27' 'EPT2022AD38' 'EPT2022AD42' 'EPT2022AD069' 'EPT2022AD070'
 'EPT2023AD04' 'EPT2023AD07' 'EPT2024AD12' 'HFC2021AD04' 'HFC2021AD08'
 'HFC2021AD18' 'HFC2021AD19' 'HFC2021AD21' 'HFC2021AD28' 'HFC2021AD29'
 'HFC2021AD30' 'HFC2021AD35' 'HFC2021AD38' 'HFC2021AD49' 'HFC2021AD50'
 'AD2019_BrMRA09' 'AD2019_BrMRA13' 'MREPT2020AD02' 'MREPT2020AD03'
 'MREPT2020AD08' 'MREPT2020AD12' 'MREPT2020AD15' 'MREPT2020AD22'
 'EPT2024AD05' 'ADEPT44' 'MREPT2020AD09' 'MWI_CN78(ver2)' 'MWI_CN60(ver2)'
 'EPT2022AD28' 'EPT2022AD073' 'EPT2023AD05' 'EPT2023AD06' 'EPT2023AD17'
 'EPT2023AD21' 'EPT2024AD01' 'EPT2024AD06' 'HFC2021AD02' 'HFC2021AD27'
 'HFC2021AD31' 'AD2019_BrMRA11' 'MWI_CN09' 'MWI_CN14' 'MWI_CN16'
 'MWI_CN37' 'MWI_CN49' 'MWI_CN66(ver2)' 'MWI_CN67(ver2)' 'MWI_CN70(ver2)'
 'MREPT2020AD10' 'MREPT2020AD27']
----------------------------------------
Col name: 미수코드
Data type: float64
Unique values: 2
[  nan 8641.]
----------------------------------------
Col name: 논문사용
Data type: object
Unique values: 15
[nan '2022 상반기영상' 'HFC,LFC사용' 'HFC 사용' 'newMWI_CN 27명 추가' '2022 하반기영상'
 '2021 하반기영상' 'HFC,LFC,MWI 사용' 'aMCI07' 'HFC' 'mdMCI04' 'aMCI17' 'mdMCI03'
 'mdMCI21' '사용안함']
----------------------------------------
Col name: PID
Data type: object
Unique values: 196
[nan '09463703' '08787368' '00145616' '02716077' '00469852' '02296061'
 '00316024' '05871888' '04073053' '01382411' '04086417' '00875397'
 '08481071' '08481058' '01206895' '08696493' '02022042' '00613165'
 '08129675' '04920375' '02989539' '00736914' '01551514' '02968625'
 '09138558' '01578465' '01794662' '08527223' '00213324' '01422655'
 '05243616' '09524528' '09588015' '00863315' '00359871' '07090169'
 '10474783' '08510155' '00057983' '04727886' '02459562' '00461257'
 '00710431' '01932252' '02603988' '07641504' '09481613' '09589671'
 '09634219' '01881945' '00235415' '00463081' '08808855' '02296676'
 '09160753' '02421737' '06508701' '06662465' '07400336' '08058412'
 '09038185' '09264085' '09376283' '09403278' '09452145' '04381137'
 '07205823' '06476189' '00243749' '08664289' '00738146' '08402901'
 '09168529' '03261945' '09605724' '09605754' '10412739' '10482577'
 '10412747' '01934947' '09173469' '06762937' '04039744' '00520495'
 '00550122' '02590215' '07053215' '08529975' '01514027' '08655418'
 '01588867' '02657475' '01246647' '03532605' '03633402' '04600082'
 '07740365' '07816717' '08306655' '09295332' '09468039' '09491375'
 '09520331' '01563188' '01408745' '01818063' '06763469' '09101859'
 '08225784' '04569609' '00129148' '08344895' '08655425' '08500417'
 '08510171' '08519137' '09135702' '09168261' '00022375' '00641619'
 '10474812' '05209834' '09572617' '09682931' '01018935' '03735478'
 '02671227' '02528398' '01468626' '02642792' '03157194' '09734851'
 '04074843' '07843678' '00310282' '00454439' '00612238' '01868298'
 '03417996' '03600925' '03929844' '06683962' '09124745' '09481205'
 '03281139' '03677627' '02345264' '09076435' '10130501' '01867289'
 '04495885' '01176028' '01585307' '01812609' '02780063' '03370049'
 '05070395' '06508904' '09187225' '09196258' '01349735' '05118195'
 '04738348' '04717899' '02933875' '08542934' '03076738' '00069764'
 '02750266' '00755865' '05603012' '10412752' '09850469' '06916248'
 '07351639' '04345988' '06318811' '01207865' '05912132' '01727943'
 '03691537' '00657015' '02677574' '03424678' '05065323' '00080969'
 '04341115' '01190888' '01283958' '09138544' '00766581' '09577263'
 '02202449' '08276845' '00577752']
----------------------------------------
Col name: Name
Data type: object
Unique values: 197
[nan '유길종' '이송웅' '강난희' '송승숙' '이순상' '김동선' '김순배' '이재경(부부0)' '최성옥' '박영준(형재1)'
 '박영복(형재1)' '유영재' '하정이(부부1)' '박길조(부부1)' '이순희' '이은숙' '정진배' '이태수' '이동숙'
 '장흥란' '오경석' '김태진' '염규숙' '원현자' '백명자' '박옥수(처형)' '전만수(대흥사)' '윤화영' '임성빈'
 '차현수' '김용자' '박영숙' '이순이' '이송희' '박희자' '박장철' '이영순' '이상준(부부2)' '이순임' '오정순'
 '함춘순' '김교순' '정옥점' '박수일' '신영순' '이경훈' '추덕희' '박춘성' '여영희' '정순옥' '우옥분' '이덕순'
 '김선' '권기옥' '이경희 ' '소흥순 ' '손영희 ' '양택경 ' '문봉수 ' '김은동 ' '이화숙 ' '김송식 ' '권경임 '
 '이강언 ' '박경자 ' '장삼주' '김정인' '김호(부부0)' '김순희' '김인혁' '김은령' '김광덕' '김해선(처형)'
 '김영옥' '이기영(부부)' '김강식(부부)' '최영애' '조수현' '이명렬' '노경숙' '김정민 ' '조미자' '노성천'
 '유옥희 ' '오기윤 ' '유정이 ' '김미숙 ' '오임석 ' '남귀례' '윤선자' '윤순진 ' '이종구' '윤명열' '박광월'
 '김용순' '사공숙혜' '나남옥' '한순분' '김명분' '임정선' '송인자' '이경자' '최현수' '최기수' '김미혜' '하우양'
 '김인대' '김준배' '권헌영' '김정례' '정호권' '이사규' '함명호' '노국자' '이상란(부부2)' '박영순' '김차숙'
 '양명준(처형)' '장홍식' '조덕례' '이순례' '김정숙' '김평궁' '김양자' '이홍영' '김명옥' '박종애' '이옥희'
 '장영식' '신영조' '최금자' '고정자' '구인순' '최이열' '김달고만' '송광명' '김인제두' '황선영' '강현식' '윤주희'
 '김옥자' '김다선' '용영식' '황필분' '이부덕' '김숙현' '김종운' '원계자' '임대식' '한근석' '나효남' '원종철 '
 '구달회 ' '채연순 ' '최영아 ' '이부덕 ' '황광순 ' '김사숙 ' '방명래 ' '이정숙 ' '도기열 ' '이경순'
 '김화숙' '황미자' '권중호' '최영숙' '권옥분' '이한순' '김용호' '김은자' '우덕성' '박정자' '이성남' '배화자'
 '구묘서' '김후례' '전임순' '이순자' '이환구' '박동발' '김정임' '박영광' '신홍섭 ' '이숙희 ' '이종분 '
 '전광순' '유경자' '박영자' '이칠석' '김진람' '최병월' '조수연' '김오심' '이청자' '조영자' '양정자']
----------------------------------------
Col name: Age
Data type: float64
Unique values: 37
[nan 74. 81. 70. 62. 72. 66. 64. 68. 61. 71. 77. 83. 76. 73. 80. 69. 78.
 82. 52. 59. 65. 75. 79. 84. 67. 90. 63. 87. 86. 88. 89. 85. 96. 58. 91.
 60.]
----------------------------------------
Col name: ChiQSM
Data type: object
Unique values: 193
[nan 'CNL02' 'CNL03' 'CNL04' 'CNL05' 'CNL06' 'CNL07' 'CNL08' 'CNL09'
 'CNL10' 'CNL11' 'CNL12' 'CNL13' 'CNL14' 'CNL15' 'CNL17' 'CNL19' 'CNL20'
 'CNL21' 'CNL22' 'CNL23' 'CNL25' 'CNL26' 'CNL27' 'CNL28' 'CNL29' 'CNL30'
 'CNL31' 'CNL32' 'CNL33' 'CNL34' 'CNL35' 'CNL36' 'CNL37' 'CNL38' 'CNL39'
 'CNL40' 'CNL41' 'CNL16' 'CNL24' 'CNL18' 'CNL43' 'CSM16' 'CSM17' 'CSM19'
 'CSM20' 'CSM22' 'CSM23' 'CSM24' 'CSM25' 'CSM18' 'CSM26' 'CSM28' 'CSM29'
 'CSM30' 'CSM31' 'CSM35' 'CSM37' 'CSM38' 'CSM40' 'CSM41' 'CSM43' 'CSM45'
 'CSM46' 'CSM47' 'CSM48' 'CSM01' 'CSM02' 'CSM51' 'CSM52' 'CSM53' 'CSM54'
 'CSM55' 'CSM56' 'CSM57' 'CSM58' 'CSM59' 'CSM60' 'CSM61' 'CSM62' 'CSM27'
 'CSM44' 'CSM03' 'CSM21' 'CSM32' 'CSM33' 'CSM36' 'CSM39' 'CSM42' 'CSM49'
 'CSM50' 'CSM34' 'CSM68' 'CMM15' 'CMM19' 'CMM20' 'CMM21' 'CMM23' 'CMM24'
 'CMM25' 'CMM26' 'CMM27' 'CMM28' 'CMM29' 'CMM33' 'CMM34' 'CMM36' 'CMM38'
 'CMM39' 'CMM02' 'CMM03' 'CMM41' 'CMM42' 'CMM43' 'CMM46' 'CMM47' 'CMM48'
 'CMM50' 'CMM51' 'CMM52' 'CMM53' 'CMM56' 'CMM22' 'CMM30' 'CMM32' 'CMM37'
 'CMM01' 'CMM40' 'CMM49' 'CMM16' 'CMM17' 'CMM18' 'CMM31' 'CMM35' 'CMM55'
 'CAD14' 'CAD15' 'CAD17' 'CAD19' 'CAD20' 'CAD21' 'CAD22' 'CAD23' 'CAD24'
 'CAD25' 'CAD26' 'CAD27' 'CAD28' 'CAD29' 'CAD31' 'CAD33' 'CAD34' 'CAD36'
 'CAD37' 'CAD38' 'CAD39' 'CAD40' 'CAD41' 'CAD42' 'CAD43' 'CAD44' 'CAD45'
 'CAD01' 'CAD02' 'CAD46' 'CAD47' 'CAD48' 'CAD49' 'CAD50' 'CAD51' 'CAD30'
 'CNM08' 'CNM09' 'CNM10' 'CNM11' 'CNM12' 'CNM13' 'CNM15' 'CNM16' 'CNM17'
 'CNM18' 'CNM19' 'CNM01' 'CNM20' 'CNM21' 'CNM22' 'CNM23' 'CNM24' 'CNM25'
 'CNM26' 'CNM27' 'CNM29' 'CNM30']
----------------------------------------
Col name: Sex
Data type: object
Unique values: 3
[nan 'M' 'F']
----------------------------------------
Col name: Education (Year)
Data type: object
Unique values: 30
[nan 18 16 12 6 9 14 3 '18(대학원)' '6(초등졸업)' '11(고중퇴)' '12(고졸)' '6(국졸)'
 '9(중졸)' '4(초등중퇴)' 8 19 7 21 13 '15(대학중퇴)' 1 0 '-' 5 '무학' 4 10 2 0.5]
----------------------------------------
Col name: Screen fail/Drop 이유
Data type: object
Unique values: 12
[nan 'Control 모집' '이학영교수진료' '   이학영교수 환자' '신원철교수 인지장애진료'
 'Control 모집(SNSB, MRI)' '변정익교수 환자' '   이학영교수 Control 모집(SNSB, MRI)'
 'Metal artifact로 탈락' 'non-amnestic' 'non amnestic MCI' 'non-amnestic MCI']
----------------------------------------
Col name: 임상정보 추가
Data type: object
Unique values: 46
[nan 'NL' '  NL' '    subjective memory complaints'
 'NL(CDR 0.5 이나, 세부항목에서의 의미있는 저하는 없음.)'
 'NL(K-BNT 점수가 낮으나, CDR 0으로 일단 정상으로 분류함.)' '(변정익교수진료-수면장애)' 'CN'
 'amnestic MCI' 'amestic MCI' 'aMCI' '    amnestic MCI'
 ' amnestic MCI(이학영)' 'multiple domain aMCI' 'MCI' 'amnestic MCI(갑상선기능저하)'
 '    amnestic MCI with iADL 0.36 (MMSE 18)' '    multiple domain aMCI'
 'amnestic MCI ' 'multiple domain amnestic MCI' 'multiple domain aMCI '
 'mutiple domain aMCI' '알츠하이머형 치매 '
 "Alzheimer's disease dementia, mild degree " '알츠하이머형 치매 CDR2' 'ADD, mild'
 'ADD with CVD, moderate' 'mild AD'
 'moderate AD (with positive amyloid PET)'
 "Dementia of Alzheimer's type, late onset" 'AD, mild degree'
 'AD, moderate d.' 'mild AD  ' 'mild AD ' 'AD, mild'
 "Alzheimer's dementia, late onset" "Alzheimer's dementia, early onset"
 'AD with CVD' 'mild AD with CVD' 'mild AD (with positive amyloid PET)'
 '    AD with CVD' 'non-amnestic MCI' 'non amnestic MCI'
 'MCI, non-amnestic(이학영)' 'non-amnestid MCI'
 'mutiple domain non-amnestic MCI']
----------------------------------------
Col name: 최종진단 DDX
Data type: object
Unique values: 34
[nan 'NL' 'single domain aMCI' '   single domain aMCI'
 ' single domain aMCI(이학영)' 'single domain aMCI(갑상선기능저하)'
 'multiple domain amnestic MCI' 'multiple domain aMCI'
 '    multiple domain aMCI' 'mutiple domain aMCI' '알츠하이머형 치매' '알츠하이머형 치매 '
 "Alzheimer's disease dementia, mild degree " '알츠하이머형치매, 조기발병형'
 '알츠하이머형 치매 CDR2' 'ADD, mild' 'ADD with CVD, moderate' 'mild AD'
 'moderate AD (with positive amyloid PET)'
 "Dementia of Alzheimer's type, late onset" 'AD, mild degree'
 'AD, moderate d.' 'AD, mild' "Alzheimer's dementia, late onset"
 "Alzheimer's dementia, early onset" 'AD with CVD' 'mild AD with CVD'
 'mild AD (with positive amyloid PET)' '    AD with CVD'
 'non-amnestic MCI' 'non amnestic MCI' 'MCI, non-amnestic(이학영)'
 'non-amnestid MCI' 'mutiple domain non-amnestic MCI']
----------------------------------------
Col name: SNSB StudyDate
Data type: object
Unique values: 152
[nan datetime.datetime(2022, 1, 6, 0, 0)
 datetime.datetime(2023, 4, 4, 0, 0) datetime.datetime(2019, 10, 24, 0, 0)
 datetime.datetime(2019, 5, 2, 0, 0) datetime.datetime(2019, 3, 29, 0, 0)
 datetime.datetime(2019, 1, 29, 0, 0) datetime.datetime(2019, 1, 28, 0, 0)
 datetime.datetime(2019, 12, 7, 0, 0) datetime.datetime(2020, 5, 14, 0, 0)
 datetime.datetime(2020, 4, 8, 0, 0) datetime.datetime(2020, 4, 9, 0, 0)
 datetime.datetime(2020, 4, 17, 0, 0) datetime.datetime(2020, 9, 9, 0, 0)
 datetime.datetime(2020, 10, 10, 0, 0)
 datetime.datetime(2019, 11, 15, 0, 0)
 datetime.datetime(2019, 11, 21, 0, 0)
 datetime.datetime(2020, 6, 30, 0, 0) datetime.datetime(2020, 7, 13, 0, 0)
 datetime.datetime(2021, 2, 24, 0, 0) datetime.datetime(2021, 3, 12, 0, 0)
 datetime.datetime(2020, 10, 20, 0, 0) datetime.datetime(2021, 2, 3, 0, 0)
 datetime.datetime(2021, 7, 8, 0, 0) '2021-06-26(09:30)' '2021-07-16 3시'
 datetime.datetime(2022, 2, 15, 0, 0) datetime.datetime(2022, 2, 7, 0, 0)
 datetime.datetime(2022, 1, 25, 0, 0) datetime.datetime(2022, 2, 10, 0, 0)
 datetime.datetime(2022, 2, 4, 0, 0) datetime.datetime(2022, 2, 24, 0, 0)
 datetime.datetime(2022, 3, 11, 0, 0) datetime.datetime(2022, 6, 13, 0, 0)
 datetime.datetime(2023, 11, 14, 0, 0)
 datetime.datetime(2024, 1, 31, 0, 0) datetime.datetime(2020, 5, 12, 0, 0)
 datetime.datetime(2020, 3, 1, 0, 0) datetime.datetime(2020, 9, 8, 0, 0)
 datetime.datetime(2019, 10, 8, 0, 0) datetime.datetime(2022, 3, 4, 0, 0)
 datetime.datetime(2022, 1, 3, 0, 0) datetime.datetime(2022, 4, 26, 0, 0)
 datetime.datetime(2022, 1, 12, 0, 0) datetime.datetime(2022, 1, 17, 0, 0)
 datetime.datetime(2022, 1, 13, 0, 0) datetime.datetime(2022, 5, 13, 0, 0)
 datetime.datetime(2022, 3, 30, 0, 0) datetime.datetime(2022, 8, 23, 0, 0)
 datetime.datetime(2023, 9, 8, 0, 0) datetime.datetime(2024, 3, 1, 0, 0)
 datetime.datetime(2020, 12, 11, 0, 0)
 datetime.datetime(2021, 5, 24, 0, 0) datetime.datetime(2021, 7, 23, 0, 0)
 datetime.datetime(2021, 8, 16, 0, 0)
 datetime.datetime(2021, 12, 15, 0, 0)
 datetime.datetime(2021, 6, 15, 0, 0) datetime.datetime(2021, 12, 1, 0, 0)
 datetime.datetime(2021, 7, 21, 0, 0) datetime.datetime(2021, 11, 9, 0, 0)
 datetime.datetime(2021, 10, 13, 0, 0)
 datetime.datetime(2021, 12, 17, 0, 0)
 datetime.datetime(2021, 12, 20, 0, 0)
 datetime.datetime(2019, 9, 24, 0, 0) datetime.datetime(2019, 10, 7, 0, 0)
 datetime.datetime(2020, 8, 18, 0, 0) datetime.datetime(2021, 6, 4, 0, 0)
 '2021-07-12 3시' '2021-07-27 4시' datetime.datetime(2022, 3, 8, 0, 0)
 datetime.datetime(2023, 11, 22, 0, 0) datetime.datetime(2024, 2, 6, 0, 0)
 datetime.datetime(2023, 12, 20, 0, 0)
 datetime.datetime(2021, 8, 20, 0, 0)
 datetime.datetime(2019, 12, 24, 0, 0)
 datetime.datetime(2021, 9, 23, 0, 0)
 datetime.datetime(2021, 12, 16, 0, 0)
 datetime.datetime(2021, 10, 20, 0, 0)
 datetime.datetime(2021, 11, 1, 0, 0) datetime.datetime(2020, 2, 26, 0, 0)
 datetime.datetime(2020, 8, 25, 0, 0) datetime.datetime(2019, 3, 15, 0, 0)
 datetime.datetime(2021, 12, 9, 0, 0) datetime.datetime(2022, 3, 18, 0, 0)
 datetime.datetime(2022, 1, 19, 0, 0) datetime.datetime(2022, 1, 11, 0, 0)
 datetime.datetime(2021, 12, 30, 0, 0)
 datetime.datetime(2022, 1, 10, 0, 0) datetime.datetime(2022, 1, 4, 0, 0)
 datetime.datetime(2022, 1, 20, 0, 0) datetime.datetime(2022, 9, 7, 0, 0)
 datetime.datetime(2023, 4, 25, 0, 0)
 datetime.datetime(2023, 12, 26, 0, 0) datetime.datetime(2021, 7, 2, 0, 0)
 datetime.datetime(2021, 6, 24, 0, 0)
 datetime.datetime(2019, 11, 19, 0, 0)
 datetime.datetime(2019, 11, 12, 0, 0) datetime.datetime(2020, 1, 3, 0, 0)
 datetime.datetime(2020, 7, 15, 0, 0) datetime.datetime(2020, 4, 21, 0, 0)
 datetime.datetime(2020, 5, 15, 0, 0) datetime.datetime(2021, 6, 19, 0, 0)
 '7월 28일 3시 검사' datetime.datetime(2022, 3, 2, 0, 0)
 datetime.datetime(2022, 3, 14, 0, 0) datetime.datetime(2022, 2, 18, 0, 0)
 datetime.datetime(2022, 5, 31, 0, 0) datetime.datetime(2021, 6, 21, 0, 0)
 datetime.datetime(2019, 11, 4, 0, 0) datetime.datetime(2020, 2, 6, 0, 0)
 datetime.datetime(2022, 5, 11, 0, 0) datetime.datetime(2022, 1, 21, 0, 0)
 datetime.datetime(2022, 5, 25, 0, 0) datetime.datetime(2023, 2, 14, 0, 0)
 datetime.datetime(2022, 5, 4, 0, 0) datetime.datetime(2020, 6, 1, 0, 0)
 datetime.datetime(2022, 2, 28, 0, 0) datetime.datetime(2022, 2, 14, 0, 0)
 datetime.datetime(2022, 1, 18, 0, 0)
 datetime.datetime(2021, 11, 15, 0, 0)
 datetime.datetime(2022, 10, 14, 0, 0) datetime.datetime(2023, 4, 3, 0, 0)
 datetime.datetime(2023, 2, 22, 0, 0) datetime.datetime(2024, 3, 29, 0, 0)
 datetime.datetime(2021, 10, 8, 0, 0)
 datetime.datetime(2020, 12, 20, 0, 0)
 datetime.datetime(2021, 8, 31, 0, 0)
 datetime.datetime(2018, 11, 20, 0, 0)
 datetime.datetime(2019, 12, 11, 0, 0)
 datetime.datetime(2020, 3, 19, 0, 0) datetime.datetime(2020, 5, 22, 0, 0)
 datetime.datetime(2020, 6, 19, 0, 0) datetime.datetime(2019, 7, 4, 0, 0)
 datetime.datetime(2020, 3, 31, 0, 0)
 datetime.datetime(2023, 11, 15, 0, 0)
 datetime.datetime(2022, 8, 25, 0, 0) datetime.datetime(2022, 4, 14, 0, 0)
 datetime.datetime(2022, 7, 6, 0, 0) datetime.datetime(2023, 4, 14, 0, 0)
 datetime.datetime(2023, 1, 5, 0, 0) datetime.datetime(2023, 7, 20, 0, 0)
 datetime.datetime(2023, 12, 21, 0, 0)
 datetime.datetime(2023, 6, 28, 0, 0)
 datetime.datetime(2020, 12, 30, 0, 0)
 datetime.datetime(2021, 11, 8, 0, 0)
 datetime.datetime(2021, 12, 10, 0, 0)
 datetime.datetime(2019, 11, 29, 0, 0)
 datetime.datetime(2019, 11, 2, 0, 0)
 datetime.datetime(2019, 12, 14, 0, 0)
 datetime.datetime(2020, 9, 29, 0, 0) datetime.datetime(2020, 4, 3, 0, 0)
 datetime.datetime(2020, 9, 15, 0, 0)]
----------------------------------------
Col name: MMSE
Data type: float64
Unique values: 20
[nan 29. 30. 28. 26. 27. 25. 21. 23. 24. 18. 17. 19. 22. 20. 16. 13. 10.
  9. 15.]
----------------------------------------
Col name: CDR
Data type: float64
Unique values: 5
[nan 0.  0.5 1.  2. ]
----------------------------------------
Col name: CDRSB
Data type: float64
Unique values: 17
[ nan  0.   0.5  1.   1.5  2.   2.5  3.   3.5  4.   4.5  8.   5.   6.
  6.5 14.  10. ]
----------------------------------------
Col name: GDS
Data type: float64
Unique values: 6
[nan  2.  3.  1.  4.  5.]
----------------------------------------
Col name: Barthel A DL
Data type: object
Unique values: 6
[nan '20/20' '19/20' '18/20' '15/20' '13/20']
----------------------------------------
Col name: Instrumental A DL
Data type: object
Unique values: 47
[nan '1/10=0.1' '0/9=0' '1/11=0.09' '0/11=0' '0/10=0' '1/9=0.11' '1/10=0'
 '3/10=0.3' '6/9=0.67' '2/10=0.2' '0/10=0.1' '2/11=0.18' '2/9=0.22' 0.2
 '0/1=0' '3/9=0.33' '3/11=0.27' '1/11-0/09' '2/7=0.29' '4/11=0.36'
 '1/8=0.13' '1/10=0.10' '3/8=0.38' '2/10=0.18' '0/11' '4/10=0.4'
 '1/11=0.1' '1/10=0.10=' '5/9=0.56' '9/7=1.29' '1/5=0.2' '6/8=0.75'
 '7/10=0.7' '16/8=2.' '4/8=0.5' '7/7=1' '10/8=1.25' '5/10=0.5' '7/11=0.64'
 '6/10=0.6' '4/9=0.44' '6/11=0.55' '2/6=0.33' '2/0=0.18' '2/8=0.25'
 '1/11=0.9']
----------------------------------------
Col name: NPI
Data type: object
Unique values: 22
[nan '0/144' '0/44' '3/144' '4/144' <NA> '7/144' '10/144' '5/144' '2/144'
 0 '6/144' '8/144' '37/144' '12/144' '13/144' '9/144' '14/144' '25/144'
 '27/144' '18/144' '11/144']
----------------------------------------
Col name: PET(amyloid, FDG)
Data type: object
Unique values: 18
[nan 'none' 'Flutemetamol(2025-01-14)'
 'FDG(2023-01-18)\nFDG(2020-06-30)\nFDG(2018-12-18)' 'none '
 'Flutemetamol(2023-06-14)' 'Flutemetamol(2025-01-09)'
 'Flutemetamol(2025-04-09)' 'Flutemetamol(2024-08-27)'
 'Flutemetamol(2020-07-21)' 'Fusion PET(2012-12-28)'
 'FDG(2024-04-24) \nFDG(2022-09-26) \nFDG(2019-05-08) '
 'FDG(2025-04-29)\nFDG(2019-07-05)' 'Flutemetamol(2024-04-11)'
 'FDG(2022-11-11)' 'Flutemetamol(2024-02-27)' 'FP-CIT(2018-10-30)'

In [10]:
# Cols to add
cols_8641 = ["PDI", "PID"
             , "TIV", "global GMV", "global WMV", "global CSFV", "NPI", "SGDS"
             , "MMSE", "CDR", "CDRSB", "GDS", "Barthel A DL", "Instrumental A DL"
             , 'LT_ALL_Dxx_proj', 'LT_ALL_Dyy_proj', 'LT_ALL_Dzz_proj', 'LT_ALL_Dxx_assoc'
             , 'LT_ALL_Dyy_assoc', 'LT_ALL_Dzz_assoc', 'LT_ALL_ALPS index','LT_b800_Dxx_proj'
             , 'LT_b800_Dyy_proj', 'LT_b800_Dzz_proj', 'LT_b800_Dxx_assoc', 'LT_b800_Dyy_assoc'
             , 'LT_b800_Dzz_assoc', 'LT_b800_ALPS index', 'LT_b2000_Dxx_proj', 'LT_b2000_Dyy_proj'
             , 'LT_b2000_Dzz_proj', 'LT_b2000_Dxx_assoc', 'LT_b2000_Dyy_assoc', 'LT_b2000_Dzz_assoc'
             , 'LT_b2000_ALPS index', 'RT_ALL_Dxx_proj', 'RT_ALL_Dyy_proj', 'RT_ALL_Dzz_proj'
             , 'RT_ALL_Dxx_assoc', 'RT_ALL_Dyy_assoc', 'RT_ALL_Dzz_assoc', 'RT_ALL_ALPS index'
             , 'RT_b800_Dxx_proj', 'RT_b800_Dyy_proj', 'RT_b800_Dzz_proj', 'RT_b800_Dxx_assoc'
             , 'RT_b800_Dyy_assoc', 'RT_b800_Dzz_assoc', 'RT_b800_ALPS index', 'RT_b2000_Dxx_proj'
             , 'RT_b2000_Dyy_proj', 'RT_b2000_Dzz_proj', 'RT_b2000_Dxx_assoc', 'RT_b2000_Dyy_assoc'
             , 'RT_b2000_Dzz_assoc', 'RT_b2000_ALPS index'
             , 'HFC_LT_Amygdala', 'IC_LT_Amygdala', 'EC_LT_Amygdala', 'HFC_LT_Hippocampus', 'IC_LT_Hippocampus'
             , 'EC_LT_Hippocampus', 'HFC_LT_Insula', 'IC_LT_Insula', 'EC_LT_Insula', 'HFC_LT_MTG', 'IC_LT_MTG'
             , 'EC_LT_MTG', 'HFC_LT_ParaHippocampus', 'IC_LT_ParaHippocampus', 'EC_LT_ParaHippocampus'
             , 'HFC_LT_Thalamus', 'IC_LT_Thalamus', 'EC_LT_Thalamus', 'HFC_RT_Amygdala', 'IC_RT_Amygdala'
             , 'EC_RT_Amygdala', 'HFC_RT_Hippocampus', 'IC_RT_Hippocampus', 'EC_RT_Hippocampus'
             , 'HFC_RT_Insula', 'IC_RT_Insula', 'EC_RT_Insula', 'HFC_RT_MTG', 'IC_RT_MTG', 'EC_RT_MTG'
             , 'HFC_RT_ParaHippocampus', 'IC_RT_ParaHippocampus', 'EC_RT_ParaHippocampus'
             , 'HFC_RT_Thalamus', 'IC_RT_Thalamus', 'EC_RT_Thalamus', 'HFC_Whole_CC', 'IC_Whole_CC', 'EC_Whole_CC'
             , 'HFC_Whole_Precuneus', 'IC_Whole_Precuneus', 'EC_Whole_Precuneus'
            ]

cols_8641_dem = ["PDI", "PID"
                 , "TIV", "global GMV", "global WMV", "global CSFV", "NPI", "SGDS"
                 , "MMSE", "CDR", "CDRSB", "GDS", "Barthel A DL", "Instrumental A DL"
                 , 'LT_ALL_Dxx_proj', 'LT_ALL_Dyy_proj', 'LT_ALL_Dzz_proj', 'LT_ALL_Dxx_assoc'
                 , 'LT_ALL_Dyy_assoc', 'LT_ALL_Dzz_assoc', 'LT_ALL_ALPS index','LT_b800_Dxx_proj'
                 , 'LT_b800_Dyy_proj', 'LT_b800_Dzz_proj', 'LT_b800_Dxx_assoc', 'LT_b800_Dyy_assoc'
                 , 'LT_b800_Dzz_assoc', 'LT_b800_ALPS index', 'LT_b2000_Dxx_proj', 'LT_b2000_Dyy_proj'
                 , 'LT_b2000_Dzz_proj', 'LT_b2000_Dxx_assoc', 'LT_b2000_Dyy_assoc', 'LT_b2000_Dzz_assoc'
                 , 'LT_b2000_ALPS index', 'RT_ALL_Dxx_proj', 'RT_ALL_Dyy_proj', 'RT_ALL_Dzz_proj'
                 , 'RT_ALL_Dxx_assoc', 'RT_ALL_Dyy_assoc', 'RT_ALL_Dzz_assoc', 'RT_ALL_ALPS index'
                 , 'RT_b800_Dxx_proj', 'RT_b800_Dyy_proj', 'RT_b800_Dzz_proj', 'RT_b800_Dxx_assoc'
                 , 'RT_b800_Dyy_assoc', 'RT_b800_Dzz_assoc', 'RT_b800_ALPS index', 'RT_b2000_Dxx_proj'
                 , 'RT_b2000_Dyy_proj', 'RT_b2000_Dzz_proj', 'RT_b2000_Dxx_assoc', 'RT_b2000_Dyy_assoc'
                 , 'RT_b2000_Dzz_assoc', 'RT_b2000_ALPS index'
                 , 'HFC_LT_Amygdala', 'IC_LT_Amygdala', 'EC_LT_Amygdala', 'HFC_LT_Hippocampus', 'IC_LT_Hippocampus'
                 , 'EC_LT_Hippocampus', 'HFC_LT_Insula', 'IC_LT_Insula', 'EC_LT_Insula', 'HFC_LT_MTG', 'IC_LT_MTG'
                 , 'EC_LT_MTG', 'HFC_LT_ParaHippocampus', 'IC_LT_ParaHippocampus', 'EC_LT_ParaHippocampus'
                 , 'HFC_LT_Thalamus', 'IC_LT_Thalamus', 'EC_LT_Thalamus', 'HFC_RT_Amygdala', 'IC_RT_Amygdala'
                 , 'EC_RT_Amygdala', 'HFC_RT_Hippocampus', 'IC_RT_Hippocampus', 'EC_RT_Hippocampus'
                 , 'HFC_RT_Insula', 'IC_RT_Insula', 'EC_RT_Insula', 'HFC_RT_MTG', 'IC_RT_MTG', 'EC_RT_MTG'
                 , 'HFC_RT_ParaHippocampus', 'IC_RT_ParaHippocampus', 'EC_RT_ParaHippocampus'
                 , 'HFC_RT_Thalamus', 'IC_RT_Thalamus', 'EC_RT_Thalamus', 'HFC_Whole_CC', 'IC_Whole_CC', 'EC_Whole_CC'
                 , 'HFC_Whole_Precuneus', 'IC_Whole_Precuneus', 'EC_Whole_Precuneus'
                ]

priority_cols = ["TIV", "global GMV", "global WMV", "global CSFV", "NPI", "SGDS"
                 , "MMSE", "CDR", "CDRSB", "GDS", "Barthel A DL", "Instrumental A DL"
                ]
skip_cols = set(priority_cols + ["PID", "PDI"])

add_cols_8641 = [c for c in cols_8641 if c not in skip_cols]
add_cols_8641_dem = [c for c in cols_8641_dem if c not in skip_cols]

In [11]:
def fill_missing(base, donor, cols, base_key, donor_key):
    ref = donor[[donor_key] + cols].copy().rename(columns={donor_key: base_key})
    merged = base[[base_key] + cols].merge(ref, on=base_key, how="left",
                                           suffixes=("", "_donor"))
    for col in cols:
        base[col] = base[col].fillna(merged[f"{col}_donor"])
    return base

dfS1 = fill_missing(dfS1, df8641, priority_cols, "PID", "PID")
dfS1 = fill_missing(dfS1, dfDem,  priority_cols, "PID", "PID")
print(dfS1[["TIV", "global GMV", "global WMV", "global CSFV", "NPI", "MMSE"
            , "CDR", "CDRSB", "GDS", "Barthel A DL", "Instrumental A DL"]]
     )

dfS1 = fill_missing(dfS1, df8641, priority_cols, "AD_MWI_Code", "PDI")
dfS1 = fill_missing(dfS1, dfDem,  priority_cols, "AD_MWI_Code", "PDI")

dfS1

             TIV  global GMV  global WMV  global CSFV     NPI  MMSE  CDR  \
0            NaN         NaN         NaN          NaN     NaN   NaN  NaN
1    1550.469470  493.238319  412.905559   639.431894   0/144  29.0  0.0
2            NaN         NaN         NaN          NaN     NaN  30.0  0.5
3    1304.359887  499.301540  344.757090   457.000531    0/44  30.0  0.0
4    1431.074737  517.657305  405.560720   505.216261   3/144  30.0  0.0
..           ...         ...         ...          ...     ...   ...  ...
201          NaN         NaN         NaN          NaN     NaN  27.0  0.5
202          NaN         NaN         NaN          NaN     NaN  21.0  0.5
203          NaN         NaN         NaN          NaN     NaN  28.0  0.5
204  1275.839545  457.229861  392.933175   425.676509   0/144  28.0  0.5
205          NaN         NaN         NaN          NaN  27/144  22.0  0.5

     CDRSB  GDS Barthel A DL Instrumental A DL
0      NaN  NaN          NaN               NaN
1      0.0  2.0        20/20          1/10=0.1
2      0.5  2.0        20/20             0/9=0
3      0.5  2.0        20/20         1/11=0.09
4      0.0  2.0        20/20         1/11=0.09
..     ...  ...          ...               ...
201    1.5  3.0        20/20         1/10=0.10
202    2.0  3.0        20/20          1/10=0.1
203    0.5  3.0        20/20          1/11=0.9
204    1.0  3.0        20/20          3/10=0.3
205    2.0  3.0        20/20          3/10=0.3

[206 rows x 11 columns]

,건대분석정보,인원,DDX,AD_MWI_Code,미수코드,논문사용,PID,Name,Age,ChiQSM,...,MR_3DGRASE_MWI,MR_3DGRASE_REF,MREPT_TSE,NODDI,MREPT_3DbFFE,Unnamed: 48,conductivity,MWF,Chi,SGDS
0,NL(39),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Yea,NaN,NL,EPT2022AD40,NaN,2022 상반기영상,09463703,유길종,74.0,CNL02,...,O,O,O,NODDI32,X,NaN,O,O,O,0/15
2,No,NaN,NL,EPT2023AD09,NaN,NaN,08787368,이송웅,81.0,CNL03,...,NaN,NaN,NaN,NaN,NaN,NaN,O,O,O,NaN
3,Yes,1,NL,MWI_CN01,8641.0,"HFC,LFC사용",00145616,강난희,70.0,CNL04,...,NaN,NaN,NaN,NaN,NaN,NaN,O,O,O,NaN
4,Yes,2,NL,MWI_CN04,8641.0,HFC 사용,02716077,송승숙,62.0,CNL05,...,NaN,NaN,NaN,NaN,NaN,NaN,O,O,O,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
201,Yes,9탈락3-2,NaMCI,MWI_CN66(ver2),8641.0,newMWI_CN 27명 추가,00766581,조수연,71.0,CNM25,...,NaN,NaN,NaN,NaN,NaN,NaN,O,O,O,NaN
202,Yes,10탈락3-3,NaMCI,MWI_CN67(ver2),8641.0,newMWI_CN 27명 추가,09577263,김오심,82.0,CNM26,...,NaN,NaN,NaN,NaN,NaN,NaN,O,O,O,1/15
203,Yes,13탈락3-4,NaMCI,MWI_CN70(ver2),8641.0,newMWI_CN 27명 추가,02202449,이청자,80.0,CNM27,...,NaN,NaN,NaN,NaN,NaN,NaN,O,O,O,NaN
204,Yes,탈락-infarction,NaMCI,MREPT2020AD10,NaN,NaN,08276845,조영자,73.0,CNM29,...,O,O,O,NODDI32,X,NaN,NaN,탈락-infarction,NaN,NaN
205,Yes,탈락-venous anomaly,NaMCI,MREPT2020AD27,NaN,NaN,00577752,양정자,71.0,CNM30,...,O,O,O,NODDI32,X,NaN,NaN,탈락-venous anomaly,NaN,NaN

In [12]:
def append_cols_pid_pdi(base, donor, cols):
    """
    ① PID 로 LEFT JOIN
    ② 남은 NaN 은 AD_MWI_Code ⟷ PDI(부분 문자열)로 보충
    ③ 실제로 생긴 *_donor 컬럼만 정리
    """
    cols = [c for c in cols if c not in ("PID", "PDI")]

    # ── 1) PID 기준 ───────────────────────────────────────────────
    merged = base.merge(
        donor[["PID"] + cols], on="PID", how="left",
        suffixes=("", "_donor")          # 중복시에만 *_donor 생성
    )

    # ── 1-1) 중복 컬럼의 NaN 채우기 ──────────────────────────────
    overlap = [c for c in cols if c in base.columns]
    for c in overlap:
        dcol = f"{c}_donor"
        if dcol in merged.columns:
            merged[c] = merged[c].fillna(merged[dcol])

    # ── 2) AD_MWI_Code ⟷ PDI (부분 문자열) 보충 ───────────────────
    if "AD_MWI_Code" in base.columns and "PDI" in donor.columns:
        d_dict = donor.set_index("PDI")[cols].to_dict("index")
        for pdi_key, vdict in d_dict.items():
            mask = merged["AD_MWI_Code"].astype(str).str.contains(pdi_key, na=False)
            for c, v in vdict.items():
                merged.loc[mask & merged[c].isna(), c] = v

    # ── 3) 실제로 존재하는 *_donor 컬럼만 삭제 ───────────────────
    donor_cols = [c for c in merged.columns if c.endswith("_donor")]
    merged.drop(columns=donor_cols, inplace=True)

    return merged

dfS1 = append_cols_pid_pdi(dfS1, df8641, add_cols_8641)
dfS1 = append_cols_pid_pdi(dfS1, dfDem,  add_cols_8641_dem)

dfS1

,건대분석정보,인원,DDX,AD_MWI_Code,미수코드,논문사용,PID,Name,Age,ChiQSM,...,EC_RT_ParaHippocampus,HFC_RT_Thalamus,IC_RT_Thalamus,EC_RT_Thalamus,HFC_Whole_CC,IC_Whole_CC,EC_Whole_CC,HFC_Whole_Precuneus,IC_Whole_Precuneus,EC_Whole_Precuneus
0,NL(39),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Yea,NaN,NL,EPT2022AD40,NaN,2022 상반기영상,09463703,유길종,74.0,CNL02,...,0.508526,0.863352,0.208503,0.654738,0.545173,0.151938,0.393254,0.678900,0.106224,0.569961
2,No,NaN,NL,EPT2023AD09,NaN,NaN,08787368,이송웅,81.0,CNL03,...,0.447529,0.893360,0.172644,0.720655,0.583949,0.133841,0.450196,0.670014,0.110448,0.559206
3,Yes,1,NL,MWI_CN01,8641.0,"HFC,LFC사용",00145616,강난희,70.0,CNL04,...,0.569473,0.826935,0.271682,0.555182,0.596481,0.212770,0.383751,0.628513,0.125133,0.503758
4,Yes,2,NL,MWI_CN04,8641.0,HFC 사용,02716077,송승숙,62.0,CNL05,...,0.489838,0.761443,0.233806,0.527660,0.482623,0.188198,0.294517,0.592590,0.139421,0.453941
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
201,Yes,9탈락3-2,NaMCI,MWI_CN66(ver2),8641.0,newMWI_CN 27명 추가,00766581,조수연,71.0,CNM25,...,0.436440,0.765378,0.181157,0.584184,0.495296,0.163504,0.331894,0.637991,0.131822,0.508110
202,Yes,10탈락3-3,NaMCI,MWI_CN67(ver2),8641.0,newMWI_CN 27명 추가,09577263,김오심,82.0,CNM26,...,0.583334,0.786152,0.203446,0.582679,0.560845,0.146901,0.414069,0.751461,0.115140,0.640286
203,Yes,13탈락3-4,NaMCI,MWI_CN70(ver2),8641.0,newMWI_CN 27명 추가,02202449,이청자,80.0,CNM27,...,0.494867,0.793464,0.218678,0.574741,0.502785,0.165001,0.337965,0.682435,0.120648,0.561929
204,Yes,탈락-infarction,NaMCI,MREPT2020AD10,NaN,NaN,08276845,조영자,73.0,CNM29,...,0.611423,0.880783,0.222180,0.658885,0.535623,0.164056,0.371696,0.582397,0.128662,0.452970
205,Yes,탈락-venous anomaly,NaMCI,MREPT2020AD27,NaN,NaN,00577752,양정자,71.0,CNM30,...,0.469620,0.787288,0.269163,0.518164,0.557495,0.222879,0.334656,0.734094,0.143633,0.591547

In [13]:
after = "global CSFV"
orig  = list(pd.read_excel(os.path.join(ALPS_DIR, "Auto_ALPS_index_19-24_0731.xlsx")
                       , sheet_name="Sheet1").columns)  # 원본 순서
new   = [c for c in dfS1.columns if c not in orig]
pos   = dfS1.columns.get_loc(after) + 1
ordered = list(dfS1.columns)
for c in reversed(new):
    ordered.insert(pos, ordered.pop(ordered.index(c)))
dfS1 = dfS1[ordered]

print(len(dfS1.columns))
dfS1

137

,건대분석정보,인원,DDX,AD_MWI_Code,미수코드,논문사용,PID,Name,Age,ChiQSM,...,MR_3DT1_TFE,MR_3DGRASE_MWI,MR_3DGRASE_REF,MREPT_TSE,NODDI,MREPT_3DbFFE,Unnamed: 48,conductivity,MWF,Chi
0,NL(39),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Yea,NaN,NL,EPT2022AD40,NaN,2022 상반기영상,09463703,유길종,74.0,CNL02,...,O,O,O,O,NODDI32,X,NaN,O,O,O
2,No,NaN,NL,EPT2023AD09,NaN,NaN,08787368,이송웅,81.0,CNL03,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,O,O,O
3,Yes,1,NL,MWI_CN01,8641.0,"HFC,LFC사용",00145616,강난희,70.0,CNL04,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,O,O,O
4,Yes,2,NL,MWI_CN04,8641.0,HFC 사용,02716077,송승숙,62.0,CNL05,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,O,O,O
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
201,Yes,9탈락3-2,NaMCI,MWI_CN66(ver2),8641.0,newMWI_CN 27명 추가,00766581,조수연,71.0,CNM25,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,O,O,O
202,Yes,10탈락3-3,NaMCI,MWI_CN67(ver2),8641.0,newMWI_CN 27명 추가,09577263,김오심,82.0,CNM26,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,O,O,O
203,Yes,13탈락3-4,NaMCI,MWI_CN70(ver2),8641.0,newMWI_CN 27명 추가,02202449,이청자,80.0,CNM27,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,O,O,O
204,Yes,탈락-infarction,NaMCI,MREPT2020AD10,NaN,NaN,08276845,조영자,73.0,CNM29,...,O,O,O,O,NODDI32,X,NaN,NaN,탈락-infarction,NaN
205,Yes,탈락-venous anomaly,NaMCI,MREPT2020AD27,NaN,NaN,00577752,양정자,71.0,CNM30,...,O,O,O,O,NODDI32,X,NaN,NaN,탈락-venous anomaly,NaN

In [17]:
analyse_dataframe(dfS1)

                        NaN Counts  NaN Ratio (%)  Unique Values
건대분석정보                           4       1.941748              8
인원                             101      49.029126             46
DDX                              9       4.368932              5
AD_MWI_Code                      9       4.368932            197
미수코드                           136      66.019417              1
논문사용                            55      26.699029             14
PID                              9       4.368932            195
Name                             9       4.368932            196
Age                              9       4.368932             36
ChiQSM                          14       6.796117            192
Sex                              9       4.368932              2
Education (Year)                60      29.126214             29
Screen fail/Drop 이유            136      66.019417             11
임상정보 추가                         75      36.407767             45
최종진단 DDX                         9       4.368932             33
SNSB StudyDate                  26      12.621359            151
MMSE                            11       5.339806             19
CDR                             12       5.825243              4
CDRSB                           27      13.106796             16
GDS                             26      12.621359              5
Barthel A DL                    17       8.252427              5
Instrumental A DL               29      14.077670             46
NPI                             94      45.631068             20
PET(amyloid, FDG)               10       4.854369             17
Unnamed: 24                    206     100.000000              0
TIV                             84      40.776699            117
global GMV                      87      42.233010            111
global WMV                      87      42.233010            111
global CSFV                     87      42.233010            111
SGDS                           172      83.495146             15
LT_ALL_Dxx_proj                 62      30.097087            142
LT_ALL_Dyy_proj                 62      30.097087            142
LT_ALL_Dzz_proj                 62      30.097087            142
LT_ALL_Dxx_assoc                62      30.097087            142
LT_ALL_Dyy_assoc                62      30.097087            142
LT_ALL_Dzz_assoc                62      30.097087            142
LT_ALL_ALPS index               62      30.097087            142
LT_b800_Dxx_proj                62      30.097087            142
LT_b800_Dyy_proj                62      30.097087            142
LT_b800_Dzz_proj                62      30.097087            142
LT_b800_Dxx_assoc               62      30.097087            142
LT_b800_Dyy_assoc               62      30.097087            142
LT_b800_Dzz_assoc               62      30.097087            142
LT_b800_ALPS index              62      30.097087            142
LT_b2000_Dxx_proj               62      30.097087            142
LT_b2000_Dyy_proj               62      30.097087            142
LT_b2000_Dzz_proj               62      30.097087            142
LT_b2000_Dxx_assoc              62      30.097087            142
LT_b2000_Dyy_assoc              62      30.097087            142
LT_b2000_Dzz_assoc              62      30.097087            142
LT_b2000_ALPS index             62      30.097087            142
RT_ALL_Dxx_proj                 62      30.097087            142
RT_ALL_Dyy_proj                 62      30.097087            142
RT_ALL_Dzz_proj                 62      30.097087            142
RT_ALL_Dxx_assoc                62      30.097087            142
RT_ALL_Dyy_assoc                62      30.097087            142
RT_ALL_Dzz_assoc                62      30.097087            142
RT_ALL_ALPS index               62      30.097087            142
RT_b800_Dxx_proj                62      30.097087            142
RT_b800_Dyy_proj                62      30.097087            142
RT_b800_Dzz_proj                62      30.097087            142
RT_b800_Dxx_assoc               62      30.097087            142
RT_b800_Dyy_assoc               62      30.097087            142
RT_b800_Dzz_assoc               62      30.097087            142
RT_b800_ALPS index              62      30.097087            142
RT_b2000_Dxx_proj               62      30.097087            142
RT_b2000_Dyy_proj               62      30.097087            142
RT_b2000_Dzz_proj               62      30.097087            142
RT_b2000_Dxx_assoc              62      30.097087            142
RT_b2000_Dyy_assoc              62      30.097087            142
RT_b2000_Dzz_assoc              62      30.097087            142
RT_b2000_ALPS index             62      30.097087            142
HFC_LT_Amygdala                 62      30.097087            142
IC_LT_Amygdala                  62      30.097087            142
EC_LT_Amygdala                  62      30.097087            142
HFC_LT_Hippocampus              62      30.097087            142
IC_LT_Hippocampus               62      30.097087            142
EC_LT_Hippocampus               62      30.097087            142
HFC_LT_Insula                   62      30.097087            142
IC_LT_Insula                    62      30.097087            142
EC_LT_Insula                    62      30.097087            142
HFC_LT_MTG                      62      30.097087            142
IC_LT_MTG                       62      30.097087            142
EC_LT_MTG                       62      30.097087            142
HFC_LT_ParaHippocampus          62      30.097087            142
IC_LT_ParaHippocampus           62      30.097087            142
EC_LT_ParaHippocampus           62      30.097087            142
HFC_LT_Thalamus                 62      30.097087            142
IC_LT_Thalamus                  62      30.097087            142
EC_LT_Thalamus                  62      30.097087            142
HFC_RT_Amygdala                 62      30.097087            142
IC_RT_Amygdala                  62      30.097087            142
EC_RT_Amygdala                  62      30.097087            142
HFC_RT_Hippocampus              62      30.097087            142
IC_RT_Hippocampus               62      30.097087            142
EC_RT_Hippocampus               62      30.097087            142
HFC_RT_Insula                   62      30.097087            142
IC_RT_Insula                    62      30.097087            142
EC_RT_Insula                    62      30.097087            142
HFC_RT_MTG                      62      30.097087            142
IC_RT_MTG                       62      30.097087            142
EC_RT_MTG                       62      30.097087            142
HFC_RT_ParaHippocampus          62      30.097087            142
IC_RT_ParaHippocampus           62      30.097087            142
EC_RT_ParaHippocampus           62      30.097087            142
HFC_RT_Thalamus                 62      30.097087            142
IC_RT_Thalamus                  62      30.097087            142
EC_RT_Thalamus                  62      30.097087            142
HFC_Whole_CC                    62      30.097087            142
IC_Whole_CC                     62      30.097087            142
EC_Whole_CC                     62      30.097087            142
HFC_Whole_Precuneus             62      30.097087            142
IC_Whole_Precuneus              62      30.097087            142
EC_Whole_Precuneus              62      30.097087            142
Unnamed: 29                    206     100.000000              0
Unnamed: 30                    206     100.000000              0
Unnamed: 31                    206     100.000000              0
Unnamed: 32                    206     100.000000              0
Unnamed: 33                    206     100.000000              0
Unnamed: 34                    114      55.339806             83
보호자정보                          168      81.553398             36
Unnamed: 36                    206     100.000000              0
Unnamed: 37                    187      90.776699              9
Unnamed: 38                    206     100.000000              0
Unnamed: 39                    206     100.000000              0
MRI StudyDate                   17       8.252427            167
MRI판독 conclusion                12       5.825243            171
MR_3DT1_TFE                     79      38.349515              2
MR_3DGRASE_MWI                  79      38.349515              3
MR_3DGRASE_REF                  79      38.349515              3
MREPT_TSE                       79      38.349515              3
NODDI                           79      38.349515              6
MREPT_3DbFFE                    79      38.349515              2
Unnamed: 48                    206     100.000000              0
conductivity                    32      15.533981              1
MWF                             12       5.825243              9
Chi                             32      15.533981              1

In [19]:
dfS1.to_excel(os.path.join(ALPS_DIR, 'Auto_ALPS_index_19-24_0801.xlsx')
              , index=False
             )

In [22]:
from pathlib import Path
import shutil
from tqdm import tqdm

src_root = Path(r'D:\JHAhn\8641_conductivity\DTI_ALPS\DTI_ALPS_Result\2_Dementia')
dst_root = Path(r'E:\MR\Dataset')

# 1단계 폴더(예: 개인 ID) 순회
for lvl1 in tqdm([p for p in src_root.iterdir() if p.is_dir()],
                 desc='1st-level', unit='folder'):
    # 2단계 폴더 순회
    for lvl2 in [p for p in lvl1.iterdir() if p.is_dir()]:
        stats_dir = lvl2 / 'Stats'
        if not stats_dir.exists():
            continue

        dest = dst_root / lvl1.name / lvl2.name / 'Stats'
        if dest.exists():
            tqdm.write(f'!!!!! Already exits! SKIPPING . . . : {dest}')
            continue

        dest.parent.mkdir(parents=True, exist_ok=True)
        shutil.copytree(stats_dir, dest)

1st-level: 100%|█████████████████████████████████████████████████████████████████████| 7/7 [00:20<00:00,  2.89s/folder]

In [21]:
cols = [
    "Measure:volume",
    "Left-Thalamus","Left-Hippocampus","Left-Amygdala","Left-choroid-plexus",
    "Right-Thalamus","Right-Hippocampus","Right-Amygdala","Right-choroid-plexus",
    "CC_Posterior","CC_Mid_Posterior","CC_Central","CC_Mid_Anterior","CC_Anterior",
    "ctx-lh-middletemporal","ctx-lh-parahippocampal","ctx-lh-precuneus","ctx-lh-insula",
    "ctx-rh-middletemporal","ctx-rh-parahippocampal","ctx-rh-precuneus","ctx-rh-insula",
    "EstimatedTotalIntraCranialVol","Left-Lateral-Ventricle","CSF","Right-Lateral-Ventricle",
    "ctx-lh-entorhinal","ctx-rh-entorhinal"
]

# 2단계 하위 폴더의 Stats에서 대상 파일 수집
files = list(src_root.glob(r'*/*/Stats/eTIV_NormalizedBrainVolumeStats.csv'))

rows = []
for fp in tqdm(files, desc='Reading', unit='file'):
    try:
        df = pd.read_csv(fp)
        df = df[cols].copy()  # 지정 열만
    except Exception as e:
        tqdm.write(f'!!!! Skipping : No Col(s) | File problem(s) : {fp} → {e}')
        continue

    # 개인 ID = <lvl2> 폴더명(…\2_Dementia\<lvl1>\<lvl2>\Stats\file)
    subject = fp.parent.parent.name
    if subject.endswith('_Results'):
        subject = subject[:-len('_Results')]
    df.insert(0, 'Subject', subject)

    # 수치형 변환 (Measure:volume 제외)
    num_cols = [c for c in cols if c != 'Measure:volume']
    df[num_cols] = df[num_cols].apply(pd.to_numeric, errors='coerce')

    rows.append(df)

if not rows:
    raise SystemExit('Not available datasets')

merged = pd.concat(rows, ignore_index=True)
merged

Reading: 100%|████████████████████████████████████████████████████████████████████| 269/269 [00:02<00:00, 112.82file/s]

,Subject,Measure:volume,Left-Thalamus,Left-Hippocampus,Left-Amygdala,Left-choroid-plexus,Right-Thalamus,Right-Hippocampus,Right-Amygdala,Right-choroid-plexus,...,ctx-rh-middletemporal,ctx-rh-parahippocampal,ctx-rh-precuneus,ctx-rh-insula,EstimatedTotalIntraCranialVol,Left-Lateral-Ventricle,CSF,Right-Lateral-Ventricle,ctx-lh-entorhinal,ctx-rh-entorhinal
0,MWI_CN01_KNH_NODDI32,MWI_CN01_KNH_NODDI32,0.636927,0.320623,0.151001,0.055123,0.621512,0.349313,0.168211,0.057446,...,1.153423,0.145693,0.949497,0.551550,100.0,1.369492,0.136431,1.042649,0.188636,0.152508
1,MWI_CN04_SSS_NODDI32,MWI_CN04_SSS_NODDI32,0.809188,0.428989,0.201388,0.047482,0.767186,0.411734,0.217380,0.062679,...,1.370355,0.198570,0.981591,0.529487,100.0,0.467099,0.083311,0.579552,0.237150,0.215680
2,MWI_CN05_LSS_NODDI32,MWI_CN05_LSS_NODDI32,0.587279,0.355454,0.160146,0.079509,0.556028,0.396543,0.156755,0.071776,...,1.128888,0.162656,0.730390,0.536571,100.0,1.008765,0.145763,0.864571,0.182624,0.175534
3,MWI_CN06_KDS_NODDI32,MWI_CN06_KDS_NODDI32,0.478851,0.285343,0.124687,0.057938,0.454111,0.293534,0.141689,0.052879,...,0.892694,0.126733,0.639348,0.434330,100.0,1.240260,0.091902,1.122332,0.140422,0.141195
4,MWI_CN07_KSB_NODDI32,MWI_CN07_KSB_NODDI32,0.612925,0.354023,0.142393,0.050115,0.590602,0.364602,0.164676,0.058506,...,1.075945,0.141411,0.716557,0.478708,100.0,1.080631,0.090091,1.042915,0.196452,0.192596
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
264,EPT2024AD09_CSO_NODDI32,EPT2024AD09_CSO_NODDI32,0.388010,0.211934,0.081108,0.045172,0.401554,0.207772,0.070913,0.053696,...,0.778733,0.063002,0.559156,0.311999,100.0,2.167420,0.169744,1.343576,0.130880,0.082595
265,EPT2024AD10_KCJ_NODDI32,EPT2024AD10_KCJ_NODDI32,0.668859,0.344226,0.134545,0.089703,0.631830,0.379854,0.161534,0.080121,...,1.089978,0.179310,0.706567,0.482590,100.0,1.155754,0.136460,1.046001,0.180641,0.187852
266,EPT2024AD11_KHJ_NODDI32,EPT2024AD11_KHJ_NODDI32,0.436845,0.234100,0.117182,0.068399,0.326249,0.261052,0.124230,0.053842,...,0.811449,0.113046,0.510056,0.293556,100.0,1.648145,0.101376,1.362230,0.142228,0.136102
267,EPT2024AD12_LDS_NODDI32,EPT2024AD12_LDS_NODDI32,0.393478,0.208205,0.078369,0.086453,0.343730,0.216806,0.094104,0.085581,...,0.870929,0.085079,0.465506,0.423018,100.0,1.663795,0.159006,1.314226,0.099974,0.105460
268,EPT2024AD13_LTO_NODDI32,EPT2024AD13_LTO_NODDI32,0.408078,0.159037,0.074043,0.047150,0.384378,0.156326,0.074958,0.046229,...,0.592968,0.106970,0.520866,0.297415,100.0,1.313796,0.071996,1.204305,0.080052,0.082487

In [22]:
assert merged['Subject'].astype(str).eq(merged['Measure:volume'].astype(str)).all(), \
       "!!!! Mismatch Found : Between col 'Subject' & 'Measure:volume' in rows"

In [23]:
merged.drop(columns='Subject', inplace=True)

In [26]:
# [1]
if 'EstimatedTotalIntraCranialVol' in merged.columns:
    order = list(merged.columns)
    order.remove('EstimatedTotalIntraCranialVol')
    mv_idx = order.index('Measure:volume') + 1
    order.insert(mv_idx, 'EstimatedTotalIntraCranialVol')
else:
    order = list(merged.columns)

# [2]
cc_cols = [c for c in merged.columns if c.startswith('CC_')]
if cc_cols:
    merged['CorpusCallosum'] = merged[cc_cols].sum(axis=1, min_count=1)
    first_cc_idx = min(order.index(c) for c in cc_cols)
    if 'CorpusCallosum' in order:
        order.remove('CorpusCallosum')
    order.insert(first_cc_idx, 'CorpusCallosum')
merged = merged[order]

# [3]
name_map = {c: c for c in merged.columns}
name_map['Measure:volume'] = 'PDI'
name_map['TIV'] = 'Normalised_TIV'
name_map['Left-Thalamus'] = 'LT_Thalamus'
name_map['Left-Hippocampus'] = 'LT_Hippocampus'
name_map['Left-Amygdala'] = 'LT_Amygdala'
name_map['Left-choroid-plexus'] = 'LT_ChoroidPlexus'
name_map['Right-Thalamus'] = 'RT_Thalamus'
name_map['Right-Hippocampus'] = 'RT_Hippocampus'
name_map['Right-Amygdala'] = 'RT_Amygdala'
name_map['Right-choroid-plexus'] = 'RT_ChoroidPlexus'
name_map['CC_Posterior'] = 'Pos_CC'
name_map['CC_Mid_Posterior'] = 'MidPos_CC'
name_map['CC_Central'] = 'Central_CC'
name_map['CC_Mid_Anterior'] = 'MidAnt_CC'
name_map['CC_Anterior'] = 'Ant_CC'
name_map['ctx-lh-middletemporal'] = 'LT_MiddleTemporal_CTX'
name_map['ctx-lh-parahippocampal'] = 'LT_ParaHippocampal_CTX'
name_map['ctx-lh-precuneus'] = 'LT_Precuneus_CTX'
name_map['ctx-lh-insula'] = 'LT_Insula_CTX'
name_map['ctx-rh-middletemporal'] = 'RT_MiddleTemporal_CTX'
name_map['ctx-rh-parahippocampal'] = 'RT_ParaHippocampal_CTX'
name_map['ctx-rh-precuneus'] = 'RT_Precuneus_CTX'
name_map['ctx-rh-insula'] = 'RT_Insula_CTX'
name_map['EstimatedTotalIntraCranialVol'] = 'TIV'
name_map['Left-Lateral-Ventricle'] = 'LT_Lat_Ventricle'
name_map['CSF'] = 'CSF'
name_map['Right-Lateral-Ventricle'] = 'RT_Lat_Ventricle'
name_map['ctx-lh-entorhinal'] = 'LT_Entorhinal_CTX'
name_map['ctx-rh-entorhinal'] = 'RT_Entorhinal_CTX'
merged.rename(columns=name_map, inplace=True)

merged

,PDI,Normalised_TIV,LT_Thalamus,LT_Hippocampus,LT_Amygdala,LT_ChoroidPlexus,RT_Thalamus,RT_Hippocampus,RT_Amygdala,RT_ChoroidPlexus,...,LT_Insula_CTX,RT_MiddleTemporal_CTX,RT_ParaHippocampal_CTX,RT_Precuneus_CTX,RT_Insula_CTX,LT_Lat_Ventricle,CSF,RT_Lat_Ventricle,LT_Entorhinal_CTX,RT_Entorhinal_CTX
0,MWI_CN01_KNH_NODDI32,100.0,0.636927,0.320623,0.151001,0.055123,0.621512,0.349313,0.168211,0.057446,...,0.528590,1.153423,0.145693,0.949497,0.551550,1.369492,0.136431,1.042649,0.188636,0.152508
1,MWI_CN04_SSS_NODDI32,100.0,0.809188,0.428989,0.201388,0.047482,0.767186,0.411734,0.217380,0.062679,...,0.506306,1.370355,0.198570,0.981591,0.529487,0.467099,0.083311,0.579552,0.237150,0.215680
2,MWI_CN05_LSS_NODDI32,100.0,0.587279,0.355454,0.160146,0.079509,0.556028,0.396543,0.156755,0.071776,...,0.487687,1.128888,0.162656,0.730390,0.536571,1.008765,0.145763,0.864571,0.182624,0.175534
3,MWI_CN06_KDS_NODDI32,100.0,0.478851,0.285343,0.124687,0.057938,0.454111,0.293534,0.141689,0.052879,...,0.435603,0.892694,0.126733,0.639348,0.434330,1.240260,0.091902,1.122332,0.140422,0.141195
4,MWI_CN07_KSB_NODDI32,100.0,0.612925,0.354023,0.142393,0.050115,0.590602,0.364602,0.164676,0.058506,...,0.511546,1.075945,0.141411,0.716557,0.478708,1.080631,0.090091,1.042915,0.196452,0.192596
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
264,EPT2024AD09_CSO_NODDI32,100.0,0.388010,0.211934,0.081108,0.045172,0.401554,0.207772,0.070913,0.053696,...,0.303329,0.778733,0.063002,0.559156,0.311999,2.167420,0.169744,1.343576,0.130880,0.082595
265,EPT2024AD10_KCJ_NODDI32,100.0,0.668859,0.344226,0.134545,0.089703,0.631830,0.379854,0.161534,0.080121,...,0.453843,1.089978,0.179310,0.706567,0.482590,1.155754,0.136460,1.046001,0.180641,0.187852
266,EPT2024AD11_KHJ_NODDI32,100.0,0.436845,0.234100,0.117182,0.068399,0.326249,0.261052,0.124230,0.053842,...,0.316960,0.811449,0.113046,0.510056,0.293556,1.648145,0.101376,1.362230,0.142228,0.136102
267,EPT2024AD12_LDS_NODDI32,100.0,0.393478,0.208205,0.078369,0.086453,0.343730,0.216806,0.094104,0.085581,...,0.406796,0.870929,0.085079,0.465506,0.423018,1.663795,0.159006,1.314226,0.099974,0.105460
268,EPT2024AD13_LTO_NODDI32,100.0,0.408078,0.159037,0.074043,0.047150,0.384378,0.156326,0.074958,0.046229,...,0.294572,0.592968,0.106970,0.520866,0.297415,1.313796,0.071996,1.204305,0.080052,0.082487

In [27]:
analyse_dataframe(merged)

                        NaN Counts  NaN Ratio (%)  Unique Values
PDI                              0            0.0            269
Normalised_TIV                   0            0.0              1
LT_Thalamus                      0            0.0            269
LT_Hippocampus                   0            0.0            269
LT_Amygdala                      0            0.0            269
LT_ChoroidPlexus                 0            0.0            269
RT_Thalamus                      0            0.0            269
RT_Hippocampus                   0            0.0            269
RT_Amygdala                      0            0.0            269
RT_ChoroidPlexus                 0            0.0            269
CorpusCallosum                   0            0.0            269
Pos_CC                           0            0.0            269
MidPos_CC                        0            0.0            269
Central_CC                       0            0.0            269
MidAnt_CC                        0            0.0            269
Ant_CC                           0            0.0            269
LT_MiddleTemporal_CTX            0            0.0            269
LT_ParaHippocampal_CTX           0            0.0            269
LT_Precuneus_CTX                 0            0.0            269
LT_Insula_CTX                    0            0.0            269
RT_MiddleTemporal_CTX            0            0.0            269
RT_ParaHippocampal_CTX           0            0.0            269
RT_Precuneus_CTX                 0            0.0            269
RT_Insula_CTX                    0            0.0            269
LT_Lat_Ventricle                 0            0.0            269
CSF                              0            0.0            269
RT_Lat_Ventricle                 0            0.0            269
LT_Entorhinal_CTX                0            0.0            269
RT_Entorhinal_CTX                0            0.0            269

In [28]:
os.makedirs(out, exist_ok=True)
merged.to_excel(os.path.join(out, 'Normalised_BrainVolume.xlsx'), index=False)

In [30]:
dfg = pd.read_excel(os.path.join(out, 'Auto_ALPS_index_19-24_0801.xlsx'))
dfg['AD_MWI_Code'] = (dfg['AD_MWI_Code']
                        .astype(str)
                        .str.replace(r'\s*\([^)]*\)\s*$', '', regex=True)
                        .str.strip())
dfg

,건대분석정보,인원,DDX,AD_MWI_Code,미수코드,논문사용,PID,Name,Age,ChiQSM,...,MR_3DT1_TFE,MR_3DGRASE_MWI,MR_3DGRASE_REF,MREPT_TSE,NODDI,MREPT_3DbFFE,Unnamed: 48,conductivity,MWF,Chi
0,NL(39),NaN,NaN,nan,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Yea,NaN,NL,EPT2022AD40,NaN,2022 상반기영상,9463703.0,유길종,74.0,CNL02,...,O,O,O,O,NODDI32,X,NaN,O,O,O
2,No,NaN,NL,EPT2023AD09,NaN,NaN,8787368.0,이송웅,81.0,CNL03,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,O,O,O
3,Yes,1,NL,MWI_CN01,8641.0,"HFC,LFC사용",145616.0,강난희,70.0,CNL04,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,O,O,O
4,Yes,2,NL,MWI_CN04,8641.0,HFC 사용,2716077.0,송승숙,62.0,CNL05,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,O,O,O
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
201,Yes,9탈락3-2,NaMCI,MWI_CN66,8641.0,newMWI_CN 27명 추가,766581.0,조수연,71.0,CNM25,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,O,O,O
202,Yes,10탈락3-3,NaMCI,MWI_CN67,8641.0,newMWI_CN 27명 추가,9577263.0,김오심,82.0,CNM26,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,O,O,O
203,Yes,13탈락3-4,NaMCI,MWI_CN70,8641.0,newMWI_CN 27명 추가,2202449.0,이청자,80.0,CNM27,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,O,O,O
204,Yes,탈락-infarction,NaMCI,MREPT2020AD10,NaN,NaN,8276845.0,조영자,73.0,CNM29,...,O,O,O,O,NODDI32,X,NaN,NaN,탈락-infarction,NaN
205,Yes,탈락-venous anomaly,NaMCI,MREPT2020AD27,NaN,NaN,577752.0,양정자,71.0,CNM30,...,O,O,O,O,NODDI32,X,NaN,NaN,탈락-venous anomaly,NaN

In [31]:
df = dfg
for column in df.columns:
    print(f"Col name: {column}")
    print(f"Data type: {df[column].dtype}")
    print(f"Unique values: {len(df[column].unique())}")
    print(df[column].unique())
    print('-'*40)

Col name: 건대분석정보
Data type: object
Unique values: 9
['NL(39)' 'Yea' 'No' 'Yes' nan 'SaMCI(41)' 'MaMCI(36)' 'AD (35)'
 'NaMCI(20)']
----------------------------------------
Col name: 인원
Data type: object
Unique values: 47
[nan 1 2 3 4 5 10 17 18 19 20 21 22 8 9 11 14 15 25 6 12 13 '탈락' 27 24 16
 7 '점수미달' 'MREPT2019AD10' 23 28 '탈락-hydrocephalus' 'MREPT2019AD09'
 'MREPT2019AD13' '탈락-SAH' '4탈락-' 'MREPT2019AD11' '7탈락1-2' '12탈락1-5'
 '14탈락1-7' '7탈락2-1' '19탈락2-2' '9탈락3-2' '10탈락3-3' '13탈락3-4' '탈락-infarction'
 '탈락-venous anomaly']
----------------------------------------
Col name: DDX
Data type: object
Unique values: 6
[nan 'NL' 'SaMCI' 'MaMCI' 'AD' 'NaMCI']
----------------------------------------
Col name: AD_MWI_Code
Data type: object
Unique values: 198
['nan' 'EPT2022AD40' 'EPT2023AD09' 'MWI_CN01' 'MWI_CN04' 'MWI_CN05'
 'MWI_CN06' 'MWI_CN07' 'MWI_CN12' 'MWI_CN19' 'MWI_CN20' 'MWI_CN21'
 'MWI_CN22' 'MWI_CN23' 'MWI_CN24' 'MWI_CN33' 'MWI_CN35' 'MWI_CN38'
 'MWI_CN39' 'MWI_CN40' 'MWI_CN41' 'MWI_CN44' 'MWI_CN45' 'MWI_CN47'
 'MWI_CN48' 'MWI_CN50' 'MWI_CN51' 'MWI_CN55' 'MWI_CN57' 'MWI_CN58'
 'MWI_CN61' 'MWI_CN63' 'MWI_CN65' 'MWI_CN69' 'MWI_CN71' 'MWI_CN76'
 'MWI_CN77' 'MWI_CN83' 'MWI_CN27' 'MWI_CN43' 'MWI_CN34' 'ADEPT54'
 'EPT2022AD03' 'EPT2022AD06' 'EPT2022AD11' 'EPT2022AD12' 'EPT2022AD29'
 'EPT2022AD43' 'EPT2022AD49' 'EPT2022AD50' 'EPT2022AD67' 'EPT2023AD13'
 'EPT2024AD04' 'HFC2020AD02' 'HFC2021AD06' 'HFC2021AD12' 'HFC2021AD25'
 'HFC2021AD37' 'HFC2021AD39' 'HFC2021AD41' 'HFC2021AD42' 'HFC2021AD47'
 'HFC2021AD52' 'HFC2021AD54' 'HFC2021AD55' 'HFC2021AD57' 'AD2019_BrMRA02'
 'AD2019_BrMRA05' 'MWI_CN13' 'MWI_CN29' 'MWI_CN32' 'MWI_CN36' 'MWI_CN42'
 'MWI_CN54' 'MWI_CN56' 'MWI_CN74' 'MWI_CN75' 'MWI_CN79' 'MWI_CN81'
 'MWI_CN82' 'EPT2024AD03' 'HFC2021AD48' 'AD2019_BrMRA14' 'EPT2022AD22'
 'HFC2021AD15' 'HFC2021AD16' 'HFC2021AD26' 'HFC2021AD40' 'HFC2021AD45'
 'MREPT2020AD04' 'MREPT2020AD25' 'HFC2021AD20' 'ADEPT50' 'EPT2022AD07'
 'EPT2022AD18' 'EPT2022AD20' 'EPT2022AD23' 'EPT2022AD30' 'EPT2022AD31'
 'EPT2022AD34' 'EPT2022AD39' 'EPT2022AD41' 'EPT2022AD44' 'EPT2022AD45'
 'EPT2022AD065' 'EPT2023AD01' 'EPT2024AD02' 'HFC2021AD09' 'HFC2021AD11'
 'AD2019_BrMRA08' 'AD2019_BrMRA10' 'MREPT2020AD06' 'MREPT2020AD20'
 'MREPT2020AD26' 'MWI_CN25' 'MWI_CN26' 'MWI_CN30' 'MWI_CN46' 'MWI_CN53'
 'MWI_CN64' 'MWI_CN68' 'MWI_CN80' 'EPT2022AD24' 'EPT2022AD47'
 'EPT2022AD61' 'HFC2021AD03' 'AD2019_BrMRA01' 'MREPT2020AD05' 'MWI_CN31'
 'EPT2022AD09' 'EPT2022AD13' 'EPT2022AD16' 'EPT2022AD54' 'EPT2023AD22'
 'MWI_CN73' 'MREPT2020AD14' 'EPT2022AD01' 'EPT2022AD02' 'EPT2022AD05'
 'EPT2022AD10' 'EPT2022AD17' 'EPT2022AD19' 'EPT2022AD21' 'EPT2022AD27'
 'EPT2022AD38' 'EPT2022AD42' 'EPT2022AD069' 'EPT2022AD070' 'EPT2023AD04'
 'EPT2023AD07' 'EPT2024AD12' 'HFC2021AD04' 'HFC2021AD08' 'HFC2021AD18'
 'HFC2021AD19' 'HFC2021AD21' 'HFC2021AD28' 'HFC2021AD29' 'HFC2021AD30'
 'HFC2021AD35' 'HFC2021AD38' 'HFC2021AD49' 'HFC2021AD50' 'AD2019_BrMRA09'
 'AD2019_BrMRA13' 'MREPT2020AD02' 'MREPT2020AD03' 'MREPT2020AD08'
 'MREPT2020AD12' 'MREPT2020AD15' 'MREPT2020AD22' 'EPT2024AD05' 'ADEPT44'
 'MREPT2020AD09' 'MWI_CN78' 'MWI_CN60' 'EPT2022AD28' 'EPT2022AD073'
 'EPT2023AD05' 'EPT2023AD06' 'EPT2023AD17' 'EPT2023AD21' 'EPT2024AD01'
 'EPT2024AD06' 'HFC2021AD02' 'HFC2021AD27' 'HFC2021AD31' 'AD2019_BrMRA11'
 'MWI_CN09' 'MWI_CN14' 'MWI_CN16' 'MWI_CN37' 'MWI_CN49' 'MWI_CN66'
 'MWI_CN67' 'MWI_CN70' 'MREPT2020AD10' 'MREPT2020AD27']
----------------------------------------
Col name: 미수코드
Data type: float64
Unique values: 2
[  nan 8641.]
----------------------------------------
Col name: 논문사용
Data type: object
Unique values: 15
[nan '2022 상반기영상' 'HFC,LFC사용' 'HFC 사용' 'newMWI_CN 27명 추가' '2022 하반기영상'
 '2021 하반기영상' 'HFC,LFC,MWI 사용' 'aMCI07' 'HFC' 'mdMCI04' 'aMCI17' 'mdMCI03'
 'mdMCI21' '사용안함']
----------------------------------------
Col name: PID
Data type: float64
Unique values: 196
[      nan  9463703.  8787368.   145616.  2716077.   469852.  2296061.
   316024.  5871888.  4073053.  1382411.  4086417.   875397.  8481071.
  8481058.  1206895.  8696493.  2022042.   613165.  8129675.  4920375.
  2989539.   736914.  1551514.  2968625.  9138558.  1578465.  1794662.
  8527223.   213324.  1422655.  5243616.  9524528.  9588015.   863315.
   359871.  7090169. 10474783.  8510155.    57983.  4727886.  2459562.
   461257.   710431.  1932252.  2603988.  7641504.  9481613.  9589671.
  9634219.  1881945.   235415.   463081.  8808855.  2296676.  9160753.
  2421737.  6508701.  6662465.  7400336.  8058412.  9038185.  9264085.
  9376283.  9403278.  9452145.  4381137.  7205823.  6476189.   243749.
  8664289.   738146.  8402901.  9168529.  3261945.  9605724.  9605754.
 10412739. 10482577. 10412747.  1934947.  9173469.  6762937.  4039744.
   520495.   550122.  2590215.  7053215.  8529975.  1514027.  8655418.
  1588867.  2657475.  1246647.  3532605.  3633402.  4600082.  7740365.
  7816717.  8306655.  9295332.  9468039.  9491375.  9520331.  1563188.
  1408745.  1818063.  6763469.  9101859.  8225784.  4569609.   129148.
  8344895.  8655425.  8500417.  8510171.  8519137.  9135702.  9168261.
    22375.   641619. 10474812.  5209834.  9572617.  9682931.  1018935.
  3735478.  2671227.  2528398.  1468626.  2642792.  3157194.  9734851.
  4074843.  7843678.   310282.   454439.   612238.  1868298.  3417996.
  3600925.  3929844.  6683962.  9124745.  9481205.  3281139.  3677627.
  2345264.  9076435. 10130501.  1867289.  4495885.  1176028.  1585307.
  1812609.  2780063.  3370049.  5070395.  6508904.  9187225.  9196258.
  1349735.  5118195.  4738348.  4717899.  2933875.  8542934.  3076738.
    69764.  2750266.   755865.  5603012. 10412752.  9850469.  6916248.
  7351639.  4345988.  6318811.  1207865.  5912132.  1727943.  3691537.
   657015.  2677574.  3424678.  5065323.    80969.  4341115.  1190888.
  1283958.  9138544.   766581.  9577263.  2202449.  8276845.   577752.]
----------------------------------------
Col name: Name
Data type: object
Unique values: 197
[nan '유길종' '이송웅' '강난희' '송승숙' '이순상' '김동선' '김순배' '이재경(부부0)' '최성옥' '박영준(형재1)'
 '박영복(형재1)' '유영재' '하정이(부부1)' '박길조(부부1)' '이순희' '이은숙' '정진배' '이태수' '이동숙'
 '장흥란' '오경석' '김태진' '염규숙' '원현자' '백명자' '박옥수(처형)' '전만수(대흥사)' '윤화영' '임성빈'
 '차현수' '김용자' '박영숙' '이순이' '이송희' '박희자' '박장철' '이영순' '이상준(부부2)' '이순임' '오정순'
 '함춘순' '김교순' '정옥점' '박수일' '신영순' '이경훈' '추덕희' '박춘성' '여영희' '정순옥' '우옥분' '이덕순'
 '김선' '권기옥' '이경희 ' '소흥순 ' '손영희 ' '양택경 ' '문봉수 ' '김은동 ' '이화숙 ' '김송식 ' '권경임 '
 '이강언 ' '박경자 ' '장삼주' '김정인' '김호(부부0)' '김순희' '김인혁' '김은령' '김광덕' '김해선(처형)'
 '김영옥' '이기영(부부)' '김강식(부부)' '최영애' '조수현' '이명렬' '노경숙' '김정민 ' '조미자' '노성천'
 '유옥희 ' '오기윤 ' '유정이 ' '김미숙 ' '오임석 ' '남귀례' '윤선자' '윤순진 ' '이종구' '윤명열' '박광월'
 '김용순' '사공숙혜' '나남옥' '한순분' '김명분' '임정선' '송인자' '이경자' '최현수' '최기수' '김미혜' '하우양'
 '김인대' '김준배' '권헌영' '김정례' '정호권' '이사규' '함명호' '노국자' '이상란(부부2)' '박영순' '김차숙'
 '양명준(처형)' '장홍식' '조덕례' '이순례' '김정숙' '김평궁' '김양자' '이홍영' '김명옥' '박종애' '이옥희'
 '장영식' '신영조' '최금자' '고정자' '구인순' '최이열' '김달고만' '송광명' '김인제두' '황선영' '강현식' '윤주희'
 '김옥자' '김다선' '용영식' '황필분' '이부덕' '김숙현' '김종운' '원계자' '임대식' '한근석' '나효남' '원종철 '
 '구달회 ' '채연순 ' '최영아 ' '이부덕 ' '황광순 ' '김사숙 ' '방명래 ' '이정숙 ' '도기열 ' '이경순'
 '김화숙' '황미자' '권중호' '최영숙' '권옥분' '이한순' '김용호' '김은자' '우덕성' '박정자' '이성남' '배화자'
 '구묘서' '김후례' '전임순' '이순자' '이환구' '박동발' '김정임' '박영광' '신홍섭 ' '이숙희 ' '이종분 '
 '전광순' '유경자' '박영자' '이칠석' '김진람' '최병월' '조수연' '김오심' '이청자' '조영자' '양정자']
----------------------------------------
Col name: Age
Data type: float64
Unique values: 37
[nan 74. 81. 70. 62. 72. 66. 64. 68. 61. 71. 77. 83. 76. 73. 80. 69. 78.
 82. 52. 59. 65. 75. 79. 84. 67. 90. 63. 87. 86. 88. 89. 85. 96. 58. 91.
 60.]
----------------------------------------
Col name: ChiQSM
Data type: object
Unique values: 193
[nan 'CNL02' 'CNL03' 'CNL04' 'CNL05' 'CNL06' 'CNL07' 'CNL08' 'CNL09'
 'CNL10' 'CNL11' 'CNL12' 'CNL13' 'CNL14' 'CNL15' 'CNL17' 'CNL19' 'CNL20'
 'CNL21' 'CNL22' 'CNL23' 'CNL25' 'CNL26' 'CNL27' 'CNL28' 'CNL29' 'CNL30'
 'CNL31' 'CNL32' 'CNL33' 'CNL34' 'CNL35' 'CNL36' 'CNL37' 'CNL38' 'CNL39'
 'CNL40' 'CNL41' 'CNL16' 'CNL24' 'CNL18' 'CNL43' 'CSM16' 'CSM17' 'CSM19'
 'CSM20' 'CSM22' 'CSM23' 'CSM24' 'CSM25' 'CSM18' 'CSM26' 'CSM28' 'CSM29'
 'CSM30' 'CSM31' 'CSM35' 'CSM37' 'CSM38' 'CSM40' 'CSM41' 'CSM43' 'CSM45'
 'CSM46' 'CSM47' 'CSM48' 'CSM01' 'CSM02' 'CSM51' 'CSM52' 'CSM53' 'CSM54'
 'CSM55' 'CSM56' 'CSM57' 'CSM58' 'CSM59' 'CSM60' 'CSM61' 'CSM62' 'CSM27'
 'CSM44' 'CSM03' 'CSM21' 'CSM32' 'CSM33' 'CSM36' 'CSM39' 'CSM42' 'CSM49'
 'CSM50' 'CSM34' 'CSM68' 'CMM15' 'CMM19' 'CMM20' 'CMM21' 'CMM23' 'CMM24'
 'CMM25' 'CMM26' 'CMM27' 'CMM28' 'CMM29' 'CMM33' 'CMM34' 'CMM36' 'CMM38'
 'CMM39' 'CMM02' 'CMM03' 'CMM41' 'CMM42' 'CMM43' 'CMM46' 'CMM47' 'CMM48'
 'CMM50' 'CMM51' 'CMM52' 'CMM53' 'CMM56' 'CMM22' 'CMM30' 'CMM32' 'CMM37'
 'CMM01' 'CMM40' 'CMM49' 'CMM16' 'CMM17' 'CMM18' 'CMM31' 'CMM35' 'CMM55'
 'CAD14' 'CAD15' 'CAD17' 'CAD19' 'CAD20' 'CAD21' 'CAD22' 'CAD23' 'CAD24'
 'CAD25' 'CAD26' 'CAD27' 'CAD28' 'CAD29' 'CAD31' 'CAD33' 'CAD34' 'CAD36'
 'CAD37' 'CAD38' 'CAD39' 'CAD40' 'CAD41' 'CAD42' 'CAD43' 'CAD44' 'CAD45'
 'CAD01' 'CAD02' 'CAD46' 'CAD47' 'CAD48' 'CAD49' 'CAD50' 'CAD51' 'CAD30'
 'CNM08' 'CNM09' 'CNM10' 'CNM11' 'CNM12' 'CNM13' 'CNM15' 'CNM16' 'CNM17'
 'CNM18' 'CNM19' 'CNM01' 'CNM20' 'CNM21' 'CNM22' 'CNM23' 'CNM24' 'CNM25'
 'CNM26' 'CNM27' 'CNM29' 'CNM30']
----------------------------------------
Col name: Sex
Data type: object
Unique values: 3
[nan 'M' 'F']
----------------------------------------
Col name: Education (Year)
Data type: object
Unique values: 30
[nan 18 16 12 6 9 14 3 '18(대학원)' '6(초등졸업)' '11(고중퇴)' '12(고졸)' '6(국졸)'
 '9(중졸)' '4(초등중퇴)' 8 19 7 21 13 '15(대학중퇴)' 1 0 '-' 5 '무학' 4 10 2 0.5]
----------------------------------------
Col name: Screen fail/Drop 이유
Data type: object
Unique values: 12
[nan 'Control 모집' '이학영교수진료' '   이학영교수 환자' '신원철교수 인지장애진료'
 'Control 모집(SNSB, MRI)' '변정익교수 환자' '   이학영교수 Control 모집(SNSB, MRI)'
 'Metal artifact로 탈락' 'non-amnestic' 'non amnestic MCI' 'non-amnestic MCI']
----------------------------------------
Col name: 임상정보 추가
Data type: object
Unique values: 46
[nan 'NL' '  NL' '    subjective memory complaints'
 'NL(CDR 0.5 이나, 세부항목에서의 의미있는 저하는 없음.)'
 'NL(K-BNT 점수가 낮으나, CDR 0으로 일단 정상으로 분류함.)' '(변정익교수진료-수면장애)' 'CN'
 'amnestic MCI' 'amestic MCI' 'aMCI' '    amnestic MCI'
 ' amnestic MCI(이학영)' 'multiple domain aMCI' 'MCI' 'amnestic MCI(갑상선기능저하)'
 '    amnestic MCI with iADL 0.36 (MMSE 18)' '    multiple domain aMCI'
 'amnestic MCI ' 'multiple domain amnestic MCI' 'multiple domain aMCI '
 'mutiple domain aMCI' '알츠하이머형 치매 '
 "Alzheimer's disease dementia, mild degree " '알츠하이머형 치매 CDR2' 'ADD, mild'
 'ADD with CVD, moderate' 'mild AD'
 'moderate AD (with positive amyloid PET)'
 "Dementia of Alzheimer's type, late onset" 'AD, mild degree'
 'AD, moderate d.' 'mild AD  ' 'mild AD ' 'AD, mild'
 "Alzheimer's dementia, late onset" "Alzheimer's dementia, early onset"
 'AD with CVD' 'mild AD with CVD' 'mild AD (with positive amyloid PET)'
 '    AD with CVD' 'non-amnestic MCI' 'non amnestic MCI'
 'MCI, non-amnestic(이학영)' 'non-amnestid MCI'
 'mutiple domain non-amnestic MCI']
----------------------------------------
Col name: 최종진단 DDX
Data type: object
Unique values: 34
[nan 'NL' 'single domain aMCI' '   single domain aMCI'
 ' single domain aMCI(이학영)' 'single domain aMCI(갑상선기능저하)'
 'multiple domain amnestic MCI' 'multiple domain aMCI'
 '    multiple domain aMCI' 'mutiple domain aMCI' '알츠하이머형 치매' '알츠하이머형 치매 '
 "Alzheimer's disease dementia, mild degree " '알츠하이머형치매, 조기발병형'
 '알츠하이머형 치매 CDR2' 'ADD, mild' 'ADD with CVD, moderate' 'mild AD'
 'moderate AD (with positive amyloid PET)'
 "Dementia of Alzheimer's type, late onset" 'AD, mild degree'
 'AD, moderate d.' 'AD, mild' "Alzheimer's dementia, late onset"
 "Alzheimer's dementia, early onset" 'AD with CVD' 'mild AD with CVD'
 'mild AD (with positive amyloid PET)' '    AD with CVD'
 'non-amnestic MCI' 'non amnestic MCI' 'MCI, non-amnestic(이학영)'
 'non-amnestid MCI' 'mutiple domain non-amnestic MCI']
----------------------------------------
Col name: SNSB StudyDate
Data type: object
Unique values: 152
[nan datetime.datetime(2022, 1, 6, 0, 0)
 datetime.datetime(2023, 4, 4, 0, 0) datetime.datetime(2019, 10, 24, 0, 0)
 datetime.datetime(2019, 5, 2, 0, 0) datetime.datetime(2019, 3, 29, 0, 0)
 datetime.datetime(2019, 1, 29, 0, 0) datetime.datetime(2019, 1, 28, 0, 0)
 datetime.datetime(2019, 12, 7, 0, 0) datetime.datetime(2020, 5, 14, 0, 0)
 datetime.datetime(2020, 4, 8, 0, 0) datetime.datetime(2020, 4, 9, 0, 0)
 datetime.datetime(2020, 4, 17, 0, 0) datetime.datetime(2020, 9, 9, 0, 0)
 datetime.datetime(2020, 10, 10, 0, 0)
 datetime.datetime(2019, 11, 15, 0, 0)
 datetime.datetime(2019, 11, 21, 0, 0)
 datetime.datetime(2020, 6, 30, 0, 0) datetime.datetime(2020, 7, 13, 0, 0)
 datetime.datetime(2021, 2, 24, 0, 0) datetime.datetime(2021, 3, 12, 0, 0)
 datetime.datetime(2020, 10, 20, 0, 0) datetime.datetime(2021, 2, 3, 0, 0)
 datetime.datetime(2021, 7, 8, 0, 0) '2021-06-26(09:30)' '2021-07-16 3시'
 datetime.datetime(2022, 2, 15, 0, 0) datetime.datetime(2022, 2, 7, 0, 0)
 datetime.datetime(2022, 1, 25, 0, 0) datetime.datetime(2022, 2, 10, 0, 0)
 datetime.datetime(2022, 2, 4, 0, 0) datetime.datetime(2022, 2, 24, 0, 0)
 datetime.datetime(2022, 3, 11, 0, 0) datetime.datetime(2022, 6, 13, 0, 0)
 datetime.datetime(2023, 11, 14, 0, 0)
 datetime.datetime(2024, 1, 31, 0, 0) datetime.datetime(2020, 5, 12, 0, 0)
 datetime.datetime(2020, 3, 1, 0, 0) datetime.datetime(2020, 9, 8, 0, 0)
 datetime.datetime(2019, 10, 8, 0, 0) datetime.datetime(2022, 3, 4, 0, 0)
 datetime.datetime(2022, 1, 3, 0, 0) datetime.datetime(2022, 4, 26, 0, 0)
 datetime.datetime(2022, 1, 12, 0, 0) datetime.datetime(2022, 1, 17, 0, 0)
 datetime.datetime(2022, 1, 13, 0, 0) datetime.datetime(2022, 5, 13, 0, 0)
 datetime.datetime(2022, 3, 30, 0, 0) datetime.datetime(2022, 8, 23, 0, 0)
 datetime.datetime(2023, 9, 8, 0, 0) datetime.datetime(2024, 3, 1, 0, 0)
 datetime.datetime(2020, 12, 11, 0, 0)
 datetime.datetime(2021, 5, 24, 0, 0) datetime.datetime(2021, 7, 23, 0, 0)
 datetime.datetime(2021, 8, 16, 0, 0)
 datetime.datetime(2021, 12, 15, 0, 0)
 datetime.datetime(2021, 6, 15, 0, 0) datetime.datetime(2021, 12, 1, 0, 0)
 datetime.datetime(2021, 7, 21, 0, 0) datetime.datetime(2021, 11, 9, 0, 0)
 datetime.datetime(2021, 10, 13, 0, 0)
 datetime.datetime(2021, 12, 17, 0, 0)
 datetime.datetime(2021, 12, 20, 0, 0)
 datetime.datetime(2019, 9, 24, 0, 0) datetime.datetime(2019, 10, 7, 0, 0)
 datetime.datetime(2020, 8, 18, 0, 0) datetime.datetime(2021, 6, 4, 0, 0)
 '2021-07-12 3시' '2021-07-27 4시' datetime.datetime(2022, 3, 8, 0, 0)
 datetime.datetime(2023, 11, 22, 0, 0) datetime.datetime(2024, 2, 6, 0, 0)
 datetime.datetime(2023, 12, 20, 0, 0)
 datetime.datetime(2021, 8, 20, 0, 0)
 datetime.datetime(2019, 12, 24, 0, 0)
 datetime.datetime(2021, 9, 23, 0, 0)
 datetime.datetime(2021, 12, 16, 0, 0)
 datetime.datetime(2021, 10, 20, 0, 0)
 datetime.datetime(2021, 11, 1, 0, 0) datetime.datetime(2020, 2, 26, 0, 0)
 datetime.datetime(2020, 8, 25, 0, 0) datetime.datetime(2019, 3, 15, 0, 0)
 datetime.datetime(2021, 12, 9, 0, 0) datetime.datetime(2022, 3, 18, 0, 0)
 datetime.datetime(2022, 1, 19, 0, 0) datetime.datetime(2022, 1, 11, 0, 0)
 datetime.datetime(2021, 12, 30, 0, 0)
 datetime.datetime(2022, 1, 10, 0, 0) datetime.datetime(2022, 1, 4, 0, 0)
 datetime.datetime(2022, 1, 20, 0, 0) datetime.datetime(2022, 9, 7, 0, 0)
 datetime.datetime(2023, 4, 25, 0, 0)
 datetime.datetime(2023, 12, 26, 0, 0) datetime.datetime(2021, 7, 2, 0, 0)
 datetime.datetime(2021, 6, 24, 0, 0)
 datetime.datetime(2019, 11, 19, 0, 0)
 datetime.datetime(2019, 11, 12, 0, 0) datetime.datetime(2020, 1, 3, 0, 0)
 datetime.datetime(2020, 7, 15, 0, 0) datetime.datetime(2020, 4, 21, 0, 0)
 datetime.datetime(2020, 5, 15, 0, 0) datetime.datetime(2021, 6, 19, 0, 0)
 '7월 28일 3시 검사' datetime.datetime(2022, 3, 2, 0, 0)
 datetime.datetime(2022, 3, 14, 0, 0) datetime.datetime(2022, 2, 18, 0, 0)
 datetime.datetime(2022, 5, 31, 0, 0) datetime.datetime(2021, 6, 21, 0, 0)
 datetime.datetime(2019, 11, 4, 0, 0) datetime.datetime(2020, 2, 6, 0, 0)
 datetime.datetime(2022, 5, 11, 0, 0) datetime.datetime(2022, 1, 21, 0, 0)
 datetime.datetime(2022, 5, 25, 0, 0) datetime.datetime(2023, 2, 14, 0, 0)
 datetime.datetime(2022, 5, 4, 0, 0) datetime.datetime(2020, 6, 1, 0, 0)
 datetime.datetime(2022, 2, 28, 0, 0) datetime.datetime(2022, 2, 14, 0, 0)
 datetime.datetime(2022, 1, 18, 0, 0)
 datetime.datetime(2021, 11, 15, 0, 0)
 datetime.datetime(2022, 10, 14, 0, 0) datetime.datetime(2023, 4, 3, 0, 0)
 datetime.datetime(2023, 2, 22, 0, 0) datetime.datetime(2024, 3, 29, 0, 0)
 datetime.datetime(2021, 10, 8, 0, 0)
 datetime.datetime(2020, 12, 20, 0, 0)
 datetime.datetime(2021, 8, 31, 0, 0)
 datetime.datetime(2018, 11, 20, 0, 0)
 datetime.datetime(2019, 12, 11, 0, 0)
 datetime.datetime(2020, 3, 19, 0, 0) datetime.datetime(2020, 5, 22, 0, 0)
 datetime.datetime(2020, 6, 19, 0, 0) datetime.datetime(2019, 7, 4, 0, 0)
 datetime.datetime(2020, 3, 31, 0, 0)
 datetime.datetime(2023, 11, 15, 0, 0)
 datetime.datetime(2022, 8, 25, 0, 0) datetime.datetime(2022, 4, 14, 0, 0)
 datetime.datetime(2022, 7, 6, 0, 0) datetime.datetime(2023, 4, 14, 0, 0)
 datetime.datetime(2023, 1, 5, 0, 0) datetime.datetime(2023, 7, 20, 0, 0)
 datetime.datetime(2023, 12, 21, 0, 0)
 datetime.datetime(2023, 6, 28, 0, 0)
 datetime.datetime(2020, 12, 30, 0, 0)
 datetime.datetime(2021, 11, 8, 0, 0)
 datetime.datetime(2021, 12, 10, 0, 0)
 datetime.datetime(2019, 11, 29, 0, 0)
 datetime.datetime(2019, 11, 2, 0, 0)
 datetime.datetime(2019, 12, 14, 0, 0)
 datetime.datetime(2020, 9, 29, 0, 0) datetime.datetime(2020, 4, 3, 0, 0)
 datetime.datetime(2020, 9, 15, 0, 0)]
----------------------------------------
Col name: MMSE
Data type: float64
Unique values: 20
[nan 29. 30. 28. 26. 27. 25. 21. 23. 24. 18. 17. 19. 22. 20. 16. 13. 10.
  9. 15.]
----------------------------------------
Col name: CDR
Data type: float64
Unique values: 5
[nan 0.  0.5 1.  2. ]
----------------------------------------
Col name: CDRSB
Data type: float64
Unique values: 17
[ nan  0.   0.5  1.   1.5  2.   2.5  3.   3.5  4.   4.5  8.   5.   6.
  6.5 14.  10. ]
----------------------------------------
Col name: GDS
Data type: float64
Unique values: 6
[nan  2.  3.  1.  4.  5.]
----------------------------------------
Col name: Barthel A DL
Data type: object
Unique values: 6
[nan '20/20' '19/20' '18/20' '15/20' '13/20']
----------------------------------------
Col name: Instrumental A DL
Data type: object
Unique values: 47
[nan '1/10=0.1' '0/9=0' '1/11=0.09' '0/11=0' '0/10=0' '1/9=0.11' '1/10=0'
 '3/10=0.3' '6/9=0.67' '2/10=0.2' '0/10=0.1' '2/11=0.18' '2/9=0.22' 0.2
 '0/1=0' '3/9=0.33' '3/11=0.27' '1/11-0/09' '2/7=0.29' '4/11=0.36'
 '1/8=0.13' '1/10=0.10' '3/8=0.38' '2/10=0.18' '0/11' '4/10=0.4'
 '1/11=0.1' '1/10=0.10=' '5/9=0.56' '9/7=1.29' '1/5=0.2' '6/8=0.75'
 '7/10=0.7' '16/8=2.' '4/8=0.5' '7/7=1' '10/8=1.25' '5/10=0.5' '7/11=0.64'
 '6/10=0.6' '4/9=0.44' '6/11=0.55' '2/6=0.33' '2/0=0.18' '2/8=0.25'
 '1/11=0.9']
----------------------------------------
Col name: NPI
Data type: object
Unique values: 21
[nan '0/144' '0/44' '3/144' '4/144' '7/144' '10/144' '5/144' '2/144' 0
 '6/144' '8/144' '37/144' '12/144' '13/144' '9/144' '14/144' '25/144'
 '27/144' '18/144' '11/144']
----------------------------------------
Col name: PET(amyloid, FDG)
Data type: object
Unique values: 18
[nan 'none' 'Flutemetamol(2025-01-14)'
 'FDG(2023-01-18)\nFDG(2020-06-30)\nFDG(2018-12-18)' 'none '
 'Flutemetamol(2023-06-14)' 'Flutemetamol(2025-01-09)'
 'Flutemetamol(2025-04-09)' 'Flutemetamol(2024-08-27)'
 'Flutemetamol(2020-07-21)' 'Fusion PET(2012-12-28)'
 'FDG(2024-04-24) \nFDG(2022-09-26) \nFDG(2019-05-08) '
 'FDG(2025-04-29)\nFDG(2019-07-05)' 'Flutemetamol(2024-04-11)'
 'FDG(2022-11-11)' 'Flutemetamol(2024-02-27)' 'FP-CIT(2018-10-30)'
 'FP-CIT(2024-04-15)']
----------------------------------------
Col name: Unnamed: 24
Data type: float64
Unique values: 1
[nan]
----------------------------------------
Col name: TIV
Data type: float64
Unique values: 118
[          nan 1550.46947009 1304.35988722 1431.07473657 1519.
 1556.96422008 1351.10774632 1359.65996809 1305.98031994 1453.

In [33]:
# merged = pd.read_excel(os.path.join(out, 'Normalised_BrainVolume.xlsx'))
merged['PDI'] = merged['PDI'].astype(str).str.strip()

def match_pdi(code):
    if not isinstance(code, str):
        return None
    code = code.strip()
    if code == '' or code.lower() == 'nan':
        return None
    s = merged['PDI'].astype(str)
    # 1 : Equal conditions
    eq = s[s == code]
    if len(eq) >= 1:
        return eq.iloc[0]
    # 2 : Contain conditions
    contains = s[s.str.contains(re.escape(code), na=False)]
    if len(contains) >= 1:
        return contains.iloc[0]

    return None

dfg['Matched_PDI'] = dfg['AD_MWI_Code'].apply(match_pdi)
res = dfg.merge(merged, left_on='Matched_PDI', right_on='PDI', how='left')

res

,건대분석정보,인원,DDX,AD_MWI_Code,미수코드,논문사용,PID,Name,Age,ChiQSM,...,LT_Insula_CTX,RT_MiddleTemporal_CTX,RT_ParaHippocampal_CTX,RT_Precuneus_CTX,RT_Insula_CTX,LT_Lat_Ventricle,CSF,RT_Lat_Ventricle,LT_Entorhinal_CTX,RT_Entorhinal_CTX
0,NL(39),NaN,NaN,nan,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Yea,NaN,NL,EPT2022AD40,NaN,2022 상반기영상,9463703.0,유길종,74.0,CNL02,...,0.437793,1.012329,0.158690,0.708591,0.428610,1.165589,0.110753,0.980698,0.189083,0.167442
2,No,NaN,NL,EPT2023AD09,NaN,NaN,8787368.0,이송웅,81.0,CNL03,...,0.346210,0.778912,0.115093,0.610142,0.367369,1.740043,0.103345,1.501742,0.114483,0.142610
3,Yes,1,NL,MWI_CN01,8641.0,"HFC,LFC사용",145616.0,강난희,70.0,CNL04,...,0.528590,1.153423,0.145693,0.949497,0.551550,1.369492,0.136431,1.042649,0.188636,0.152508
4,Yes,2,NL,MWI_CN04,8641.0,HFC 사용,2716077.0,송승숙,62.0,CNL05,...,0.506306,1.370355,0.198570,0.981591,0.529487,0.467099,0.083311,0.579552,0.237150,0.215680
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
201,Yes,9탈락3-2,NaMCI,MWI_CN66,8641.0,newMWI_CN 27명 추가,766581.0,조수연,71.0,CNM25,...,0.450704,1.096321,0.185040,0.878919,0.487818,1.460113,0.137387,1.243020,0.195444,0.205491
202,Yes,10탈락3-3,NaMCI,MWI_CN67,8641.0,newMWI_CN 27명 추가,9577263.0,김오심,82.0,CNM26,...,0.255111,0.742859,0.117688,0.454969,0.303533,1.391899,0.123960,1.251832,0.069831,0.113590
203,Yes,13탈락3-4,NaMCI,MWI_CN70,8641.0,newMWI_CN 27명 추가,2202449.0,이청자,80.0,CNM27,...,0.318675,0.701914,0.085252,0.510614,0.299052,1.049790,0.120790,0.835080,0.157372,0.105387
204,Yes,탈락-infarction,NaMCI,MREPT2020AD10,NaN,NaN,8276845.0,조영자,73.0,CNM29,...,0.390007,1.055012,0.174523,0.819847,0.434248,1.437341,0.142681,1.168819,0.165392,0.167523
205,Yes,탈락-venous anomaly,NaMCI,MREPT2020AD27,NaN,NaN,577752.0,양정자,71.0,CNM30,...,0.461093,1.077470,0.170364,0.743374,0.505978,1.039392,0.112909,0.899538,0.134500,0.190815

In [35]:
mask = res['PID'].notna()
res.loc[mask, 'PID'] = (res.loc[mask, 'PID']
                          .astype(str)
                          .str.replace(r'\.0$', '', regex=True)   # 끝의 .0 제거
                          .str.extract(r'(\d+)', expand=False)     # 숫자만 추출
                          .str.zfill(8))                           # 8자리로 0 채움
res

,건대분석정보,인원,DDX,AD_MWI_Code,미수코드,논문사용,PID,Name,Age,ChiQSM,...,LT_Insula_CTX,RT_MiddleTemporal_CTX,RT_ParaHippocampal_CTX,RT_Precuneus_CTX,RT_Insula_CTX,LT_Lat_Ventricle,CSF,RT_Lat_Ventricle,LT_Entorhinal_CTX,RT_Entorhinal_CTX
0,NL(39),NaN,NaN,nan,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Yea,NaN,NL,EPT2022AD40,NaN,2022 상반기영상,09463703,유길종,74.0,CNL02,...,0.437793,1.012329,0.158690,0.708591,0.428610,1.165589,0.110753,0.980698,0.189083,0.167442
2,No,NaN,NL,EPT2023AD09,NaN,NaN,08787368,이송웅,81.0,CNL03,...,0.346210,0.778912,0.115093,0.610142,0.367369,1.740043,0.103345,1.501742,0.114483,0.142610
3,Yes,1,NL,MWI_CN01,8641.0,"HFC,LFC사용",00145616,강난희,70.0,CNL04,...,0.528590,1.153423,0.145693,0.949497,0.551550,1.369492,0.136431,1.042649,0.188636,0.152508
4,Yes,2,NL,MWI_CN04,8641.0,HFC 사용,02716077,송승숙,62.0,CNL05,...,0.506306,1.370355,0.198570,0.981591,0.529487,0.467099,0.083311,0.579552,0.237150,0.215680
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
201,Yes,9탈락3-2,NaMCI,MWI_CN66,8641.0,newMWI_CN 27명 추가,00766581,조수연,71.0,CNM25,...,0.450704,1.096321,0.185040,0.878919,0.487818,1.460113,0.137387,1.243020,0.195444,0.205491
202,Yes,10탈락3-3,NaMCI,MWI_CN67,8641.0,newMWI_CN 27명 추가,09577263,김오심,82.0,CNM26,...,0.255111,0.742859,0.117688,0.454969,0.303533,1.391899,0.123960,1.251832,0.069831,0.113590
203,Yes,13탈락3-4,NaMCI,MWI_CN70,8641.0,newMWI_CN 27명 추가,02202449,이청자,80.0,CNM27,...,0.318675,0.701914,0.085252,0.510614,0.299052,1.049790,0.120790,0.835080,0.157372,0.105387
204,Yes,탈락-infarction,NaMCI,MREPT2020AD10,NaN,NaN,08276845,조영자,73.0,CNM29,...,0.390007,1.055012,0.174523,0.819847,0.434248,1.437341,0.142681,1.168819,0.165392,0.167523
205,Yes,탈락-venous anomaly,NaMCI,MREPT2020AD27,NaN,NaN,00577752,양정자,71.0,CNM30,...,0.461093,1.077470,0.170364,0.743374,0.505978,1.039392,0.112909,0.899538,0.134500,0.190815

In [36]:
os.makedirs(out, exist_ok=True)
res.to_excel(os.path.join(out, 'Auto_ALPS_index_19-24_0805.xlsx'), index=False)