In [21]:
import os, shutil, glob, re
from tqdm import tqdm
import numpy as np
import pandas as pd

In [2]:
base = r"D:\JHAhn\8641_conductivity\DTI_ALPS"
dst_root = os.path.join(base, "CTI_ALPS")

def ensure_tree(dst_dir: str):
    """dst_dir/Results/{CTI,Stats} 생성"""
    os.makedirs(os.path.join(dst_dir, "Results", "CTI"), exist_ok=True)
    os.makedirs(os.path.join(dst_dir, "Results", "Stats"), exist_ok=True)

def list_dirs(src: str):
    """src 하위의 1-depth 폴더 목록만"""
    try:
        for name in os.listdir(src):
            p = os.path.join(src, name)
            if os.path.isdir(p):
                yield name
    except FileNotFoundError:
        print(f"[WARN] Not found: {src}")

def process_block(src: str, exclude=None, note=""):
    """src의 폴더들(필터 적용)의 동명 폴더를 dst_root에 만들고 하위 트리 구성"""
    if exclude is None:
        exclude = lambda n: False
    created = 0
    for name in list_dirs(src):
        if exclude(name):
            continue
        dst_dir = os.path.join(dst_root, name)
        ensure_tree(dst_dir)
        created += 1
    print(f"[OK] {note} from {src} → {dst_root}  (folders processed: {created})")

In [12]:
# [1]
process_block(
    src=os.path.join(base, r"1_8641_CN_MCI"),
    exclude=lambda n: (n == "Bin") or n.startswith("x_"),
    note="[1]"
)

# [2]
process_block(
    src=os.path.join(base, r"2_Dementia", r"DKI"),
    exclude=lambda n: (n == "Bin"),
    note="[2]"
)

# [3]
process_block(
    src=os.path.join(base, r"2_Dementia", r"EPT2019", r"prep"),
    exclude=None,
    note="[3]"
)

# [4]
process_block(
    src=os.path.join(base, r"2_Dementia", r"EPT2020"),
    exclude=lambda n: n.startswith("xEPI-"),
    note="[4]"
)

# [5]
process_block(
    src=os.path.join(base, r"2_Dementia", r"EPT2021"),
    exclude=None,
    note="[5]"
)

# [6]
process_block(
    src=os.path.join(base, r"2_Dementia", r"EPT2022"),
    exclude=None,
    note="[6]"
)

# [7]
process_block(
    src=os.path.join(base, r"2_Dementia", r"EPT2023"),
    exclude=lambda n: n.startswith("xEPI-"),
    note="[7]"
)

# [8]
process_block(
    src=os.path.join(base, r"2_Dementia", r"EPT2024"),
    exclude=None,
    note="[8]"
)

# [9]
process_block(
    src=os.path.join(base, r"8641_DKI"),
    exclude=None,
    note="[9]"
)

[OK] [1] from D:\JHAhn\8641_conductivity\DTI_ALPS\1_8641_CN_MCI → D:\JHAhn\8641_conductivity\DTI_ALPS\CTI_ALPS  (folders processed: 58)
[OK] [2] from D:\JHAhn\8641_conductivity\DTI_ALPS\2_Dementia\DKI → D:\JHAhn\8641_conductivity\DTI_ALPS\CTI_ALPS  (folders processed: 55)
[OK] [3] from D:\JHAhn\8641_conductivity\DTI_ALPS\2_Dementia\EPT2019\prep → D:\JHAhn\8641_conductivity\DTI_ALPS\CTI_ALPS  (folders processed: 70)
[OK] [4] from D:\JHAhn\8641_conductivity\DTI_ALPS\2_Dementia\EPT2020 → D:\JHAhn\8641_conductivity\DTI_ALPS\CTI_ALPS  (folders processed: 30)
[OK] [5] from D:\JHAhn\8641_conductivity\DTI_ALPS\2_Dementia\EPT2021 → D:\JHAhn\8641_conductivity\DTI_ALPS\CTI_ALPS  (folders processed: 2)
[OK] [6] from D:\JHAhn\8641_conductivity\DTI_ALPS\2_Dementia\EPT2022 → D:\JHAhn\8641_conductivity\DTI_ALPS\CTI_ALPS  (folders processed: 74)
[OK] [7] from D:\JHAhn\8641_conductivity\DTI_ALPS\2_Dementia\EPT2023 → D:\JHAhn\8641_conductivity\DTI_ALPS\CTI_ALPS  (folders processed: 22)
[OK] [8] from D:\JHAhn\8641_conductivity\DTI_ALPS\2_Dementia\EPT2024 → D:\JHAhn\8641_conductivity\DTI_ALPS\CTI_ALPS  (folders processed: 13)
[OK] [9] from D:\JHAhn\8641_conductivity\DTI_ALPS\8641_DKI → D:\JHAhn\8641_conductivity\DTI_ALPS\CTI_ALPS  (folders processed: 15)

In [13]:
cti_root    = os.path.join(base, "CTI_ALPS")
tensors_root= r"D:\JHAhn\8641_conductivity\8641_CDT_tensors"

MOVE_FILES = False  # True로 바꾸면 '복사' 대신 '이동'

def ensure_dir(p):
    os.makedirs(p, exist_ok=True)

def unique_rename(path, new_name):
    parent = os.path.dirname(path)
    cand   = os.path.join(parent, new_name)
    if not os.path.exists(cand):
        os.rename(path, cand);  return cand
    i = 1
    while True:
        cand_i = os.path.join(parent, f"{new_name}_{i}")
        if not os.path.exists(cand_i):
            os.rename(path, cand_i);  return cand_i
        i += 1

def copy_or_move(src, dst):
    if MOVE_FILES:
        shutil.move(src, dst)
    else:
        shutil.copy2(src, dst)

def process_one(name):
    dst_folder = os.path.join(cti_root, name)
    if not os.path.isdir(dst_folder):
        return

    src_folder = os.path.join(tensors_root, name)
    nii_files  = glob.glob(os.path.join(src_folder, "*.nii")) if os.path.isdir(src_folder) else []

    if nii_files:
        cti_dir = os.path.join(dst_folder, "Results", "CTI")
        ensure_dir(cti_dir)
        for f in tqdm(nii_files, desc=f"[{name}] copying", unit="file"):
            try:
                copy_or_move(f, os.path.join(cti_dir, os.path.basename(f)))
            except Exception as e:
                tqdm.write(f"[ERR] {name}: {os.path.basename(f)} -> {e}")
        tqdm.write(f"[OK] {name}: {len(nii_files)} file(s) {'moved' if MOVE_FILES else 'copied'}")
    else:
        if not name.startswith("x_"):
            new_path = unique_rename(dst_folder, "x_" + name)
            tqdm.write(f"[REN] {name} -> {os.path.basename(new_path)} (no matching .nii)")
        else:
            tqdm.write(f"[SKIP] {name}: already prefixed x_, no matching .nii")

def main():
    if not os.path.isdir(cti_root):
        print(f"[WARN] Not found: {cti_root}");  return
    names = [d for d in os.listdir(cti_root)
             if os.path.isdir(os.path.join(cti_root, d))]
    for name in tqdm(sorted(names), desc="Processing folders", unit="folder"):
        process_one(name)

if __name__ == "__main__":
    main()

Processing folders:   0%|                                                                  | 0/339 [00:00<?, ?folder/s]
[ADEPT01_YSJ_NODDI24] copying: 100%|███████████████████████████████████████████████████| 1/1 [00:00<00:00, 26.36file/s]
Processing folders:   0%|                                                                  | 0/339 [00:00<?, ?folder/s]

[OK] ADEPT01_YSJ_NODDI24: 1 file(s) copied

[ADEPT02_LKY_NODDI24] copying: 100%|███████████████████████████████████████████████████| 1/1 [00:00<00:00, 18.77file/s]
Processing folders:   0%|                                                                  | 0/339 [00:00<?, ?folder/s]

[OK] ADEPT02_LKY_NODDI24: 1 file(s) copied

[ADEPT03_YKJ_NODDI24] copying: 100%|███████████████████████████████████████████████████| 1/1 [00:00<00:00, 27.56file/s]
Processing folders:   1%|▌                                                         | 3/339 [00:00<00:17, 19.70folder/s]

[OK] ADEPT03_YKJ_NODDI24: 1 file(s) copied

[ADEPT04_JWS_NODDI24] copying: 100%|███████████████████████████████████████████████████| 1/1 [00:00<00:00, 27.56file/s]
Processing folders:   1%|▌                                                         | 3/339 [00:00<00:17, 19.70folder/s]

[OK] ADEPT04_JWS_NODDI24: 1 file(s) copied

[ADEPT05_CBK_NODDI24] copying: 100%|███████████████████████████████████████████████████| 1/1 [00:00<00:00, 16.39file/s]
Processing folders:   1%|▊                                                         | 5/339 [00:00<00:17, 18.81folder/s]

[OK] ADEPT05_CBK_NODDI24: 1 file(s) copied

[ADEPT06_PHJ_NODDI24] copying: 100%|███████████████████████████████████████████████████| 1/1 [00:00<00:00, 14.93file/s]
Processing folders:   1%|▊                                                         | 5/339 [00:00<00:17, 18.81folder/s]

[OK] ADEPT06_PHJ_NODDI24: 1 file(s) copied

[ADEPT07_JG_NODDI24] copying: 100%|████████████████████████████████████████████████████| 1/1 [00:00<00:00, 26.59file/s]
Processing folders:   2%|█▏                                                        | 7/339 [00:00<00:17, 18.65folder/s]

[OK] ADEPT07_JG_NODDI24: 1 file(s) copied

[ADEPT08_KMJ_NODDI24] copying: 100%|███████████████████████████████████████████████████| 1/1 [00:00<00:00, 17.23file/s]
Processing folders:   2%|█▏                                                        | 7/339 [00:00<00:17, 18.65folder/s]

[OK] ADEPT08_KMJ_NODDI24: 1 file(s) copied

[ADEPT09_JCJ_NODDI24] copying: 100%|███████████████████████████████████████████████████| 1/1 [00:00<00:00, 26.26file/s]
Processing folders:   3%|█▌                                                        | 9/339 [00:00<00:17, 19.00folder/s]

[OK] ADEPT09_JCJ_NODDI24: 1 file(s) copied

[ADEPT10_YPL_NODDI24] copying: 100%|███████████████████████████████████████████████████| 1/1 [00:00<00:00, 17.87file/s]
Processing folders:   3%|█▌                                                        | 9/339 [00:00<00:17, 19.00folder/s]

[OK] ADEPT10_YPL_NODDI24: 1 file(s) copied

[ADEPT16_LJS_NODDI24] copying: 100%|███████████████████████████████████████████████████| 1/1 [00:00<00:00, 24.76file/s]
Processing folders:   3%|█▊                                                       | 11/339 [00:00<00:17, 18.78folder/s]

[OK] ADEPT16_LJS_NODDI24: 1 file(s) copied

[ADEPT18_PST_NODDI24] copying: 100%|███████████████████████████████████████████████████| 1/1 [00:00<00:00, 16.51file/s]
Processing folders:   3%|█▊                                                       | 11/339 [00:00<00:17, 18.78folder/s]

[OK] ADEPT18_PST_NODDI24: 1 file(s) copied

[ADEPT21_CJM_NODDI24] copying: 100%|███████████████████████████████████████████████████| 1/1 [00:00<00:00, 24.61file/s]
Processing folders:   4%|██▏                                                      | 13/339 [00:00<00:17, 18.44folder/s]

[OK] ADEPT21_CJM_NODDI24: 1 file(s) copied

[ADEPT22_KBS_NODDI24] copying: 100%|███████████████████████████████████████████████████| 1/1 [00:00<00:00, 25.74file/s]
Processing folders:   4%|██▏                                                      | 13/339 [00:00<00:17, 18.44folder/s]

[OK] ADEPT22_KBS_NODDI24: 1 file(s) copied

[ADEPT23_PYS_NODDI24] copying: 100%|███████████████████████████████████████████████████| 1/1 [00:00<00:00, 20.68file/s]
Processing folders:   4%|██▏                                                      | 13/339 [00:00<00:17, 18.44folder/s]

[OK] ADEPT23_PYS_NODDI24: 1 file(s) copied

[ADEPT24_KJH_NODDI24] copying: 100%|███████████████████████████████████████████████████| 1/1 [00:00<00:00, 24.76file/s]
Processing folders:   5%|██▋                                                      | 16/339 [00:00<00:16, 19.67folder/s]

[OK] ADEPT24_KJH_NODDI24: 1 file(s) copied

[ADEPT25_JKR_NODDI24] copying: 100%|███████████████████████████████████████████████████| 1/1 [00:00<00:00, 27.06file/s]
Processing folders:   5%|██▋                                                      | 16/339 [00:00<00:16, 19.67folder/s]

[OK] ADEPT25_JKR_NODDI24: 1 file(s) copied

[ADEPT26_KYJ_NODDI24] copying: 100%|███████████████████████████████████████████████████| 1/1 [00:00<00:00, 18.65file/s]
Processing folders:   5%|███                                                      | 18/339 [00:00<00:16, 19.57folder/s]

[OK] ADEPT26_KYJ_NODDI24: 1 file(s) copied

[ADEPT27_KKS_NODDI24] copying: 100%|███████████████████████████████████████████████████| 1/1 [00:00<00:00, 16.80file/s]
Processing folders:   5%|███                                                      | 18/339 [00:01<00:16, 19.57folder/s]

[OK] ADEPT27_KKS_NODDI24: 1 file(s) copied

EPT28_MSH_NODDI24] copying:   0%|                                                           | 0/1 [00:00<?, ?file/s]
[ADEPT28_MSH_NODDI24] copying: 100%|███████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.99s/file]
Processing folders:   6%|███▎                                                     | 20/339 [00:03<01:46,  2.99folder/s]

[OK] ADEPT28_MSH_NODDI24: 1 file(s) copied

Processing folders:   6%|███▎                                                     | 20/339 [00:20<01:46,  2.99folder/s]
[ADEPT29_LBS_NODDI24] copying: 100%|███████████████████████████████████████████████████| 1/1 [00:29<00:00, 29.70s/file]
Processing folders:   6%|███▌                                                     | 21/339 [00:32<28:19,  5.34s/folder]

[OK] ADEPT29_LBS_NODDI24: 1 file(s) copied

EPT30_WJS_NODDI24] copying:   0%|                                                           | 0/1 [00:00<?, ?file/s]
[ADEPT30_WJS_NODDI24] copying: 100%|███████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.34s/file]
Processing folders:   6%|███▋                                                     | 22/339 [00:34<24:06,  4.56s/folder]

[OK] ADEPT30_WJS_NODDI24: 1 file(s) copied

EPT31_PTL_NODDI24] copying:   0%|                                                           | 0/1 [00:00<?, ?file/s]
[ADEPT31_PTL_NODDI24] copying: 100%|███████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.38s/file]
Processing folders:   7%|███▊                                                     | 23/339 [00:35<20:22,  3.87s/folder]

[OK] ADEPT31_PTL_NODDI24: 1 file(s) copied

EPT32_KSW_NODDI24] copying:   0%|                                                           | 0/1 [00:00<?, ?file/s]
[ADEPT32_KSW_NODDI24] copying: 100%|███████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.21s/file]
Processing folders:   7%|████                                                     | 24/339 [00:37<18:15,  3.48s/folder]

[OK] ADEPT32_KSW_NODDI24: 1 file(s) copied

EPT33_YCY_NODDI24] copying:   0%|                                                           | 0/1 [00:00<?, ?file/s]
[ADEPT33_YCY_NODDI24] copying: 100%|███████████████████████████████████████████████████| 1/1 [00:05<00:00,  5.48s/file]
Processing folders:   7%|████▏                                                    | 25/339 [00:43<20:52,  3.99s/folder]

[OK] ADEPT33_YCY_NODDI24: 1 file(s) copied

EPT34_PDY_NODDI24] copying:   0%|                                                           | 0/1 [00:00<?, ?file/s]
[ADEPT34_PDY_NODDI24] copying: 100%|███████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.68s/file]
Processing folders:   8%|████▎                                                    | 26/339 [00:44<17:36,  3.38s/folder]

[OK] ADEPT34_PDY_NODDI24: 1 file(s) copied

EPT36_JJS_NODDI24] copying:   0%|                                                           | 0/1 [00:00<?, ?file/s]
[ADEPT36_JJS_NODDI24] copying: 100%|███████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.83s/file]
Processing folders:   8%|████▌                                                    | 27/339 [00:46<15:21,  2.95s/folder]

[OK] ADEPT36_JJS_NODDI24: 1 file(s) copied

EPT37_KTY_NODDI24] copying:   0%|                                                           | 0/1 [00:00<?, ?file/s]
[ADEPT37_KTY_NODDI24] copying: 100%|███████████████████████████████████████████████████| 1/1 [00:04<00:00,  4.74s/file]
Processing folders:   8%|████▋                                                    | 28/339 [00:51<17:55,  3.46s/folder]

[OK] ADEPT37_KTY_NODDI24: 1 file(s) copied

EPT38_KWW_NODDI24] copying:   0%|                                                           | 0/1 [00:00<?, ?file/s]
[ADEPT38_KWW_NODDI24] copying: 100%|███████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.86s/file]
Processing folders:   9%|████▉                                                    | 29/339 [00:53<15:31,  3.00s/folder]

[OK] ADEPT38_KWW_NODDI24: 1 file(s) copied

EPT39_KKS_NODDI24] copying:   0%|                                                           | 0/1 [00:00<?, ?file/s]
[ADEPT39_KKS_NODDI24] copying: 100%|███████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.63s/file]
Processing folders:   9%|█████                                                    | 30/339 [00:55<14:55,  2.90s/folder]

[OK] ADEPT39_KKS_NODDI24: 1 file(s) copied

EPT40_JOS_NODDI24] copying:   0%|                                                           | 0/1 [00:00<?, ?file/s]
[ADEPT40_JOS_NODDI24] copying: 100%|███████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.07s/file]
Processing folders:   9%|█████▏                                                   | 31/339 [00:57<12:07,  2.36s/folder]

[OK] ADEPT40_JOS_NODDI24: 1 file(s) copied

EPT41_YBO_NODDI24] copying:   0%|                                                           | 0/1 [00:00<?, ?file/s]
[ADEPT41_YBO_NODDI24] copying: 100%|███████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.44s/file]
Processing folders:   9%|█████▍                                                   | 32/339 [00:58<10:42,  2.09s/folder]

[OK] ADEPT41_YBO_NODDI24: 1 file(s) copied

EPT42_PSJ_NODDI24] copying:   0%|                                                           | 0/1 [00:00<?, ?file/s]
[ADEPT42_PSJ_NODDI24] copying: 100%|███████████████████████████████████████████████████| 1/1 [00:03<00:00,  3.36s/file]
Processing folders:  10%|█████▌                                                   | 33/339 [01:01<12:35,  2.47s/folder]

[OK] ADEPT42_PSJ_NODDI24: 1 file(s) copied

EPT43_SSY_NODDI24] copying:   0%|                                                           | 0/1 [00:00<?, ?file/s]
[ADEPT43_SSY_NODDI24] copying: 100%|███████████████████████████████████████████████████| 1/1 [00:06<00:00,  6.40s/file]
Processing folders:  10%|█████▋                                                   | 34/339 [01:08<18:31,  3.64s/folder]

[OK] ADEPT43_SSY_NODDI24: 1 file(s) copied

EPT44_WDS_NODDI24] copying:   0%|                                                           | 0/1 [00:00<?, ?file/s]
[ADEPT44_WDS_NODDI24] copying: 100%|███████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.37s/file]
Processing folders:  10%|█████▉                                                   | 35/339 [01:10<16:32,  3.27s/folder]

[OK] ADEPT44_WDS_NODDI24: 1 file(s) copied

EPT45_KKJ_NODDI24] copying:   0%|                                                           | 0/1 [00:00<?, ?file/s]
[ADEPT45_KKJ_NODDI24] copying: 100%|███████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.56s/file]
Processing folders:  11%|██████                                                   | 36/339 [01:12<13:56,  2.76s/folder]

[OK] ADEPT45_KKJ_NODDI24: 1 file(s) copied

EPT46_LJB_NODDI24] copying:   0%|                                                           | 0/1 [00:00<?, ?file/s]
[ADEPT46_LJB_NODDI24] copying: 100%|███████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.51s/file]
Processing folders:  11%|██████▏                                                  | 37/339 [01:13<12:01,  2.39s/folder]

[OK] ADEPT46_LJB_NODDI24: 1 file(s) copied

EPT47_SJH_NODDI24] copying:   0%|                                                           | 0/1 [00:00<?, ?file/s]
[ADEPT47_SJH_NODDI24] copying: 100%|███████████████████████████████████████████████████| 1/1 [00:05<00:00,  5.64s/file]
Processing folders:  11%|██████▍                                                  | 38/339 [01:19<16:52,  3.36s/folder]

[OK] ADEPT47_SJH_NODDI24: 1 file(s) copied

EPT48_CJK_NODDI24] copying:   0%|                                                           | 0/1 [00:00<?, ?file/s]
[ADEPT48_CJK_NODDI24] copying: 100%|███████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.96s/file]
Processing folders:  12%|██████▌                                                  | 39/339 [01:21<14:43,  2.95s/folder]

[OK] ADEPT48_CJK_NODDI24: 1 file(s) copied

EPT49_LKJ_NODDI24] copying:   0%|                                                           | 0/1 [00:00<?, ?file/s]
[ADEPT49_LKJ_NODDI24] copying: 100%|███████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.64s/file]
Processing folders:  12%|██████▋                                                  | 40/339 [01:22<12:44,  2.56s/folder]

[OK] ADEPT49_LKJ_NODDI24: 1 file(s) copied

EPT50_LJK_NODDI24] copying:   0%|                                                           | 0/1 [00:00<?, ?file/s]
[ADEPT50_LJK_NODDI24] copying: 100%|███████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.80s/file]
Processing folders:  12%|██████▉                                                  | 41/339 [01:24<11:35,  2.33s/folder]

[OK] ADEPT50_LJK_NODDI24: 1 file(s) copied

EPT51_HBH_NODDI24] copying:   0%|                                                           | 0/1 [00:00<?, ?file/s]
[ADEPT51_HBH_NODDI24] copying: 100%|███████████████████████████████████████████████████| 1/1 [00:03<00:00,  3.85s/file]
Processing folders:  12%|███████                                                  | 42/339 [01:28<13:49,  2.79s/folder]

[OK] ADEPT51_HBH_NODDI24: 1 file(s) copied

EPT52_YCW_NODDI24] copying:   0%|                                                           | 0/1 [00:00<?, ?file/s]
[ADEPT52_YCW_NODDI24] copying: 100%|███████████████████████████████████████████████████| 1/1 [00:05<00:00,  5.59s/file]
Processing folders:  13%|███████▏                                                 | 43/339 [01:34<17:54,  3.63s/folder]

[OK] ADEPT52_YCW_NODDI24: 1 file(s) copied

EPT53_PDL_NODDI24] copying:   0%|                                                           | 0/1 [00:00<?, ?file/s]
[ADEPT53_PDL_NODDI24] copying: 100%|███████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.59s/file]
Processing folders:  13%|███████▍                                                 | 44/339 [01:35<14:51,  3.02s/folder]

[OK] ADEPT53_PDL_NODDI24: 1 file(s) copied

EPT54_HCS_NODDI24] copying:   0%|                                                           | 0/1 [00:00<?, ?file/s]
[ADEPT54_HCS_NODDI24] copying: 100%|███████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.85s/file]
Processing folders:  13%|███████▌                                                 | 45/339 [01:37<13:05,  2.67s/folder]

[OK] ADEPT54_HCS_NODDI24: 1 file(s) copied

EPT55_HJS_NODDI24] copying:   0%|                                                           | 0/1 [00:00<?, ?file/s]
[ADEPT55_HJS_NODDI24] copying: 100%|███████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.25s/file]
Processing folders:  14%|███████▋                                                 | 46/339 [01:39<12:26,  2.55s/folder]

[OK] ADEPT55_HJS_NODDI24: 1 file(s) copied

EPT56_CKJ_NODDI24] copying:   0%|                                                           | 0/1 [00:00<?, ?file/s]
[ADEPT56_CKJ_NODDI24] copying: 100%|███████████████████████████████████████████████████| 1/1 [00:04<00:00,  4.72s/file]
Processing folders:  14%|███████▉                                                 | 47/339 [01:44<15:35,  3.20s/folder]

[OK] ADEPT56_CKJ_NODDI24: 1 file(s) copied

EPT57_LHS_NODDI24] copying:   0%|                                                           | 0/1 [00:00<?, ?file/s]
[ADEPT57_LHS_NODDI24] copying: 100%|███████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.38s/file]
Processing folders:  14%|████████                                                 | 48/339 [01:46<12:53,  2.66s/folder]

[OK] ADEPT57_LHS_NODDI24: 1 file(s) copied

EPT58_PJR_NODDI24] copying:   0%|                                                           | 0/1 [00:00<?, ?file/s]
[ADEPT58_PJR_NODDI24] copying: 100%|███████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.76s/file]
Processing folders:  14%|████████▏                                                | 49/339 [01:47<11:33,  2.39s/folder]

[OK] ADEPT58_PJR_NODDI24: 1 file(s) copied

EPT59_KJS_NODDI24] copying:   0%|                                                           | 0/1 [00:00<?, ?file/s]
[ADEPT59_KJS_NODDI24] copying: 100%|███████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.24s/file]
Processing folders:  15%|████████▍                                                | 50/339 [01:50<11:18,  2.35s/folder]

[OK] ADEPT59_KJS_NODDI24: 1 file(s) copied

EPT60_PNS_NODDI24] copying:   0%|                                                           | 0/1 [00:00<?, ?file/s]
[ADEPT60_PNS_NODDI24] copying: 100%|███████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.58s/file]
Processing folders:  15%|████████▌                                                | 51/339 [01:51<10:11,  2.12s/folder]

[OK] ADEPT60_PNS_NODDI24: 1 file(s) copied

EPT61_YJS_NODDI24] copying:   0%|                                                           | 0/1 [00:00<?, ?file/s]
[ADEPT61_YJS_NODDI24] copying: 100%|███████████████████████████████████████████████████| 1/1 [00:06<00:00,  6.69s/file]
Processing folders:  15%|████████▋                                                | 52/339 [01:58<16:42,  3.49s/folder]

[OK] ADEPT61_YJS_NODDI24: 1 file(s) copied

EPT62_HSO_NODDI24] copying:   0%|                                                           | 0/1 [00:00<?, ?file/s]
[ADEPT62_HSO_NODDI24] copying: 100%|███████████████████████████████████████████████████| 1/1 [00:03<00:00,  3.63s/file]
Processing folders:  16%|████████▉                                                | 53/339 [02:02<16:51,  3.54s/folder]

[OK] ADEPT62_HSO_NODDI24: 1 file(s) copied

EPT63_JMS_NODDI24] copying:   0%|                                                           | 0/1 [00:00<?, ?file/s]
[ADEPT63_JMS_NODDI24] copying: 100%|███████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.03s/file]
Processing folders:  16%|█████████                                                | 54/339 [02:03<13:14,  2.79s/folder]

[OK] ADEPT63_JMS_NODDI24: 1 file(s) copied

EPT64_PMS_NODDI24] copying:   0%|                                                           | 0/1 [00:00<?, ?file/s]
[ADEPT64_PMS_NODDI24] copying: 100%|███████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.87s/file]
Processing folders:  16%|█████████▏                                               | 55/339 [02:04<11:53,  2.51s/folder]

[OK] ADEPT64_PMS_NODDI24: 1 file(s) copied

EPT65_CMR_NODDI24] copying:   0%|                                                           | 0/1 [00:00<?, ?file/s]
[ADEPT65_CMR_NODDI24] copying: 100%|███████████████████████████████████████████████████| 1/1 [00:04<00:00,  4.94s/file]
Processing folders:  17%|█████████▍                                               | 56/339 [02:09<15:18,  3.25s/folder]

[OK] ADEPT65_CMR_NODDI24: 1 file(s) copied

EPT66_LDS_NODDI24] copying:   0%|                                                           | 0/1 [00:00<?, ?file/s]
[ADEPT66_LDS_NODDI24] copying: 100%|███████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.39s/file]
Processing folders:  17%|█████████▌                                               | 57/339 [02:11<12:39,  2.69s/folder]

[OK] ADEPT66_LDS_NODDI24: 1 file(s) copied

EPT67_JKJ_NODDI24] copying:   0%|                                                           | 0/1 [00:00<?, ?file/s]
[ADEPT67_JKJ_NODDI24] copying: 100%|███████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.71s/file]
Processing folders:  17%|█████████▊                                               | 58/339 [02:14<12:38,  2.70s/folder]

[OK] ADEPT67_JKJ_NODDI24: 1 file(s) copied

T2022AD01_KDKM_NODDI32] copying:   0%|                                                      | 0/1 [00:00<?, ?file/s]
[EPT2022AD01_KDKM_NODDI32] copying: 100%|██████████████████████████████████████████████| 1/1 [00:02<00:00,  2.67s/file]
Processing folders:  17%|█████████▉                                               | 59/339 [02:16<12:34,  2.70s/folder]

[OK] EPT2022AD01_KDKM_NODDI32: 1 file(s) copied

T2022AD02_SKM_NODDI32] copying:   0%|                                                       | 0/1 [00:00<?, ?file/s]
[EPT2022AD02_SKM_NODDI32] copying: 100%|███████████████████████████████████████████████| 1/1 [00:01<00:00,  1.83s/file]
Processing folders:  18%|██████████                                               | 60/339 [02:18<11:20,  2.44s/folder]

[OK] EPT2022AD02_SKM_NODDI32: 1 file(s) copied

T2022AD03_KKS_NODDI32] copying:   0%|                                                       | 0/1 [00:00<?, ?file/s]
[EPT2022AD03_KKS_NODDI32] copying: 100%|███████████████████████████████████████████████| 1/1 [00:02<00:00,  2.67s/file]
Processing folders:  18%|██████████▎                                              | 61/339 [02:21<11:38,  2.51s/folder]

[OK] EPT2022AD03_KKS_NODDI32: 1 file(s) copied
[REN] EPT2022AD04_KSS_NODDI32 -> x_EPT2022AD04_KSS_NODDI32 (no matching .nii)

T2022AD05_KIJD_NODDI32] copying:   0%|                                                      | 0/1 [00:00<?, ?file/s]
[EPT2022AD05_KIJD_NODDI32] copying: 100%|██████████████████████████████████████████████| 1/1 [00:04<00:00,  4.27s/file]
Processing folders:  19%|██████████▌                                              | 63/339 [02:25<10:46,  2.34s/folder]

[OK] EPT2022AD05_KIJD_NODDI32: 1 file(s) copied

T2022AD063_BPB_NODDI32] copying:   0%|                                                      | 0/1 [00:00<?, ?file/s]
[EPT2022AD063_BPB_NODDI32] copying: 100%|██████████████████████████████████████████████| 1/1 [00:02<00:00,  2.23s/file]
Processing folders:  19%|██████████▊                                              | 64/339 [02:27<10:36,  2.31s/folder]

[OK] EPT2022AD063_BPB_NODDI32: 1 file(s) copied

T2022AD064_LYS_NODDI32] copying:   0%|                                                      | 0/1 [00:00<?, ?file/s]
[EPT2022AD064_LYS_NODDI32] copying: 100%|██████████████████████████████████████████████| 1/1 [00:01<00:00,  1.78s/file]
Processing folders:  19%|██████████▉                                              | 65/339 [02:29<09:56,  2.18s/folder]

[OK] EPT2022AD064_LYS_NODDI32: 1 file(s) copied

T2022AD065_CGS_NODDI32] copying:   0%|                                                      | 0/1 [00:00<?, ?file/s]
[EPT2022AD065_CGS_NODDI32] copying: 100%|██████████████████████████████████████████████| 1/1 [00:02<00:00,  2.50s/file]
Processing folders:  19%|███████████                                              | 66/339 [02:32<10:18,  2.27s/folder]

[OK] EPT2022AD065_CGS_NODDI32: 1 file(s) copied

T2022AD066_AIS_NODDI32] copying:   0%|                                                      | 0/1 [00:00<?, ?file/s]
[EPT2022AD066_AIS_NODDI32] copying: 100%|██████████████████████████████████████████████| 1/1 [00:05<00:00,  5.12s/file]
Processing folders:  20%|███████████▎                                             | 67/339 [02:37<13:54,  3.07s/folder]

[OK] EPT2022AD066_AIS_NODDI32: 1 file(s) copied

T2022AD067_JSO_NODDI32] copying:   0%|                                                      | 0/1 [00:00<?, ?file/s]
[EPT2022AD067_JSO_NODDI32] copying: 100%|██████████████████████████████████████████████| 1/1 [00:01<00:00,  1.55s/file]
Processing folders:  20%|███████████▍                                             | 68/339 [02:38<11:54,  2.64s/folder]

[OK] EPT2022AD067_JSO_NODDI32: 1 file(s) copied

T2022AD068_NSE_NODDI32] copying:   0%|                                                      | 0/1 [00:00<?, ?file/s]
[EPT2022AD068_NSE_NODDI32] copying: 100%|██████████████████████████████████████████████| 1/1 [00:03<00:00,  3.80s/file]
Processing folders:  20%|███████████▌                                             | 69/339 [02:42<13:24,  2.98s/folder]

[OK] EPT2022AD068_NSE_NODDI32: 1 file(s) copied

T2022AD069_LBD_NODDI32] copying:   0%|                                                      | 0/1 [00:00<?, ?file/s]
[EPT2022AD069_LBD_NODDI32] copying: 100%|██████████████████████████████████████████████| 1/1 [00:02<00:00,  2.43s/file]
Processing folders:  21%|███████████▊                                             | 70/339 [02:44<12:38,  2.82s/folder]

[OK] EPT2022AD069_LBD_NODDI32: 1 file(s) copied

T2022AD06_JOJ_NODDI32] copying:   0%|                                                       | 0/1 [00:00<?, ?file/s]
[EPT2022AD06_JOJ_NODDI32] copying: 100%|███████████████████████████████████████████████| 1/1 [00:01<00:00,  1.30s/file]
Processing folders:  21%|███████████▉                                             | 71/339 [02:46<10:36,  2.38s/folder]

[OK] EPT2022AD06_JOJ_NODDI32: 1 file(s) copied

T2022AD070_KSH_NODDI32] copying:   0%|                                                      | 0/1 [00:00<?, ?file/s]
[EPT2022AD070_KSH_NODDI32] copying: 100%|██████████████████████████████████████████████| 1/1 [00:01<00:00,  1.72s/file]
Processing folders:  21%|████████████                                             | 72/339 [02:48<09:43,  2.19s/folder]

[OK] EPT2022AD070_KSH_NODDI32: 1 file(s) copied

T2022AD071_KSJ_NODDI32] copying:   0%|                                                      | 0/1 [00:00<?, ?file/s]
[EPT2022AD071_KSJ_NODDI32] copying: 100%|██████████████████████████████████████████████| 1/1 [00:01<00:00,  1.35s/file]
Processing folders:  22%|████████████▎                                            | 73/339 [02:49<08:35,  1.94s/folder]

[OK] EPT2022AD071_KSJ_NODDI32: 1 file(s) copied

T2022AD072_SDY_NODDI32] copying:   0%|                                                      | 0/1 [00:00<?, ?file/s]
[EPT2022AD072_SDY_NODDI32] copying: 100%|██████████████████████████████████████████████| 1/1 [00:05<00:00,  5.31s/file]
Processing folders:  22%|████████████▍                                            | 74/339 [02:54<13:01,  2.95s/folder]

[OK] EPT2022AD072_SDY_NODDI32: 1 file(s) copied

T2022AD073_KHR_NODDI32] copying:   0%|                                                      | 0/1 [00:00<?, ?file/s]
[EPT2022AD073_KHR_NODDI32] copying: 100%|██████████████████████████████████████████████| 1/1 [00:05<00:00,  5.01s/file]
Processing folders:  22%|████████████▌                                            | 75/339 [02:59<15:41,  3.57s/folder]

[OK] EPT2022AD073_KHR_NODDI32: 1 file(s) copied

T2022AD074_LGR_NODDI32] copying:   0%|                                                      | 0/1 [00:00<?, ?file/s]
[EPT2022AD074_LGR_NODDI32] copying: 100%|██████████████████████████████████████████████| 1/1 [00:00<00:00,  1.16file/s]
Processing folders:  22%|████████████▊                                            | 76/339 [03:00<12:05,  2.76s/folder]

[OK] EPT2022AD074_LGR_NODDI32: 1 file(s) copied

T2022AD07_YMY_NODDI32] copying:   0%|                                                       | 0/1 [00:00<?, ?file/s]
[EPT2022AD07_YMY_NODDI32] copying: 100%|███████████████████████████████████████████████| 1/1 [00:02<00:00,  2.37s/file]
Processing folders:  23%|████████████▉                                            | 77/339 [03:02<11:33,  2.65s/folder]

[OK] EPT2022AD07_YMY_NODDI32: 1 file(s) copied

T2022AD08_JIL_NODDI32] copying:   0%|                                                       | 0/1 [00:00<?, ?file/s]
[EPT2022AD08_JIL_NODDI32] copying: 100%|███████████████████████████████████████████████| 1/1 [00:04<00:00,  4.37s/file]
Processing folders:  23%|█████████████                                            | 78/339 [03:07<13:45,  3.16s/folder]

[OK] EPT2022AD08_JIL_NODDI32: 1 file(s) copied

T2022AD09_JYS_NODDI32] copying:   0%|                                                       | 0/1 [00:00<?, ?file/s]
[EPT2022AD09_JYS_NODDI32] copying: 100%|███████████████████████████████████████████████| 1/1 [00:01<00:00,  1.15s/file]
Processing folders:  23%|█████████████▎                                           | 79/339 [03:08<11:06,  2.56s/folder]

[OK] EPT2022AD09_JYS_NODDI32: 1 file(s) copied

T2022AD10_HSY_NODDI32] copying:   0%|                                                       | 0/1 [00:00<?, ?file/s]
[EPT2022AD10_HSY_NODDI32] copying: 100%|███████████████████████████████████████████████| 1/1 [00:02<00:00,  2.21s/file]
Processing folders:  24%|█████████████▍                                           | 80/339 [03:10<10:37,  2.46s/folder]

[OK] EPT2022AD10_HSY_NODDI32: 1 file(s) copied

T2022AD11_PSI_NODDI32] copying:   0%|                                                       | 0/1 [00:00<?, ?file/s]
[EPT2022AD11_PSI_NODDI32] copying: 100%|███████████████████████████████████████████████| 1/1 [00:03<00:00,  3.35s/file]
Processing folders:  24%|█████████████▌                                           | 81/339 [03:14<11:44,  2.73s/folder]

[OK] EPT2022AD11_PSI_NODDI32: 1 file(s) copied

T2022AD12_SYS_NODDI32] copying:   0%|                                                       | 0/1 [00:00<?, ?file/s]
[EPT2022AD12_SYS_NODDI32] copying: 100%|███████████████████████████████████████████████| 1/1 [00:02<00:00,  2.53s/file]
Processing folders:  24%|█████████████▊                                           | 82/339 [03:16<11:26,  2.67s/folder]

[OK] EPT2022AD12_SYS_NODDI32: 1 file(s) copied

T2022AD13_SYJ_NODDI32] copying:   0%|                                                       | 0/1 [00:00<?, ?file/s]
[EPT2022AD13_SYJ_NODDI32] copying: 100%|███████████████████████████████████████████████| 1/1 [00:02<00:00,  2.90s/file]
Processing folders:  24%|█████████████▉                                           | 83/339 [03:19<11:41,  2.74s/folder]

[OK] EPT2022AD13_SYJ_NODDI32: 1 file(s) copied

T2022AD14_PYS_NODDI32] copying:   0%|                                                       | 0/1 [00:00<?, ?file/s]
[EPT2022AD14_PYS_NODDI32] copying: 100%|███████████████████████████████████████████████| 1/1 [00:02<00:00,  2.36s/file]
Processing folders:  25%|██████████████                                           | 84/339 [03:21<11:10,  2.63s/folder]

[OK] EPT2022AD14_PYS_NODDI32: 1 file(s) copied

T2022AD15_YSH_NODDI32] copying:   0%|                                                       | 0/1 [00:00<?, ?file/s]
[EPT2022AD15_YSH_NODDI32] copying: 100%|███████████████████████████████████████████████| 1/1 [00:02<00:00,  2.73s/file]
Processing folders:  25%|██████████████▎                                          | 85/339 [03:24<11:16,  2.66s/folder]

[OK] EPT2022AD15_YSH_NODDI32: 1 file(s) copied

T2022AD16_CKJ_NODDI32] copying:   0%|                                                       | 0/1 [00:00<?, ?file/s]
[EPT2022AD16_CKJ_NODDI32] copying: 100%|███████████████████████████████████████████████| 1/1 [00:01<00:00,  1.59s/file]
Processing folders:  25%|██████████████▍                                          | 86/339 [03:26<09:53,  2.35s/folder]

[OK] EPT2022AD16_CKJ_NODDI32: 1 file(s) copied

T2022AD17_KHS_NODDI32] copying:   0%|                                                       | 0/1 [00:00<?, ?file/s]
[EPT2022AD17_KHS_NODDI32] copying: 100%|███████████████████████████████████████████████| 1/1 [00:02<00:00,  2.45s/file]
Processing folders:  26%|██████████████▋                                          | 87/339 [03:28<09:59,  2.38s/folder]

[OK] EPT2022AD17_KHS_NODDI32: 1 file(s) copied

T2022AD18_PKW_NODDI32] copying:   0%|                                                       | 0/1 [00:00<?, ?file/s]
[EPT2022AD18_PKW_NODDI32] copying: 100%|███████████████████████████████████████████████| 1/1 [00:04<00:00,  4.82s/file]
Processing folders:  26%|██████████████▊                                          | 88/339 [03:33<13:01,  3.12s/folder]

[OK] EPT2022AD18_PKW_NODDI32: 1 file(s) copied

T2022AD19_YJH_NODDI32] copying:   0%|                                                       | 0/1 [00:00<?, ?file/s]
[EPT2022AD19_YJH_NODDI32] copying: 100%|███████████████████████████████████████████████| 1/1 [00:01<00:00,  1.76s/file]
Processing folders:  26%|██████████████▉                                          | 89/339 [03:35<11:18,  2.71s/folder]

[OK] EPT2022AD19_YJH_NODDI32: 1 file(s) copied

T2022AD20_KYS_NODDI32] copying:   0%|                                                       | 0/1 [00:00<?, ?file/s]
[EPT2022AD20_KYS_NODDI32] copying: 100%|███████████████████████████████████████████████| 1/1 [00:02<00:00,  2.80s/file]
Processing folders:  27%|███████████████▏                                         | 90/339 [03:38<11:22,  2.74s/folder]

[OK] EPT2022AD20_KYS_NODDI32: 1 file(s) copied

T2022AD21_KOJ_NODDI32] copying:   0%|                                                       | 0/1 [00:00<?, ?file/s]
[EPT2022AD21_KOJ_NODDI32] copying: 100%|███████████████████████████████████████████████| 1/1 [00:02<00:00,  2.28s/file]
Processing folders:  27%|███████████████▎                                         | 91/339 [03:40<10:46,  2.61s/folder]

[OK] EPT2022AD21_KOJ_NODDI32: 1 file(s) copied

T2022AD22_NSC_NODDI32] copying:   0%|                                                       | 0/1 [00:00<?, ?file/s]
[EPT2022AD22_NSC_NODDI32] copying: 100%|███████████████████████████████████████████████| 1/1 [00:02<00:00,  2.70s/file]
Processing folders:  27%|███████████████▍                                         | 92/339 [03:43<10:51,  2.64s/folder]

[OK] EPT2022AD22_NSC_NODDI32: 1 file(s) copied

T2022AD23_SKSH_NODDI32] copying:   0%|                                                      | 0/1 [00:00<?, ?file/s]
[EPT2022AD23_SKSH_NODDI32] copying: 100%|██████████████████████████████████████████████| 1/1 [00:03<00:00,  3.75s/file]
Processing folders:  27%|███████████████▋                                         | 93/339 [03:46<12:11,  2.97s/folder]

[OK] EPT2022AD23_SKSH_NODDI32: 1 file(s) copied

T2022AD24_KJS_NODDI32] copying:   0%|                                                       | 0/1 [00:00<?, ?file/s]
[EPT2022AD24_KJS_NODDI32] copying: 100%|███████████████████████████████████████████████| 1/1 [00:04<00:00,  4.36s/file]
Processing folders:  28%|███████████████▊                                         | 94/339 [03:51<13:51,  3.39s/folder]

[OK] EPT2022AD24_KJS_NODDI32: 1 file(s) copied

T2022AD25_KMS_NODDI32] copying:   0%|                                                       | 0/1 [00:00<?, ?file/s]
[EPT2022AD25_KMS_NODDI32] copying: 100%|███████████████████████████████████████████████| 1/1 [00:01<00:00,  1.15s/file]
Processing folders:  28%|███████████████▉                                         | 95/339 [03:52<11:04,  2.72s/folder]

[OK] EPT2022AD25_KMS_NODDI32: 1 file(s) copied

T2022AD26_PSO_NODDI32] copying:   0%|                                                       | 0/1 [00:00<?, ?file/s]
[EPT2022AD26_PSO_NODDI32] copying: 100%|███████████████████████████████████████████████| 1/1 [00:01<00:00,  1.17s/file]
Processing folders:  28%|████████████████▏                                        | 96/339 [03:53<09:09,  2.26s/folder]

[OK] EPT2022AD26_PSO_NODDI32: 1 file(s) copied

T2022AD27_KDS_NODDI32] copying:   0%|                                                       | 0/1 [00:00<?, ?file/s]
[EPT2022AD27_KDS_NODDI32] copying: 100%|███████████████████████████████████████████████| 1/1 [00:02<00:00,  2.72s/file]
Processing folders:  29%|████████████████▎                                        | 97/339 [03:56<09:40,  2.40s/folder]

[OK] EPT2022AD27_KDS_NODDI32: 1 file(s) copied
[REN] EPT2022AD28_GMS_NODDI32v -> x_EPT2022AD28_GMS_NODDI32v (no matching .nii)

T2022AD29_LKH_NODDI32] copying:   0%|                                                       | 0/1 [00:00<?, ?file/s]
[EPT2022AD29_LKH_NODDI32] copying: 100%|███████████████████████████████████████████████| 1/1 [00:01<00:00,  1.90s/file]
Processing folders:  29%|████████████████▋                                        | 99/339 [03:58<06:56,  1.73s/folder]

[OK] EPT2022AD29_LKH_NODDI32: 1 file(s) copied

T2022AD30_NNO_NODDI32] copying:   0%|                                                       | 0/1 [00:00<?, ?file/s]
[EPT2022AD30_NNO_NODDI32] copying: 100%|███████████████████████████████████████████████| 1/1 [00:02<00:00,  2.19s/file]
Processing folders:  29%|████████████████▌                                       | 100/339 [04:00<07:21,  1.85s/folder]

[OK] EPT2022AD30_NNO_NODDI32: 1 file(s) copied

T2022AD31_HSB_NODDI32] copying:   0%|                                                       | 0/1 [00:00<?, ?file/s]
[EPT2022AD31_HSB_NODDI32] copying: 100%|███████████████████████████████████████████████| 1/1 [00:05<00:00,  5.86s/file]
Processing folders:  30%|████████████████▋                                       | 101/339 [04:06<11:30,  2.90s/folder]

[OK] EPT2022AD31_HSB_NODDI32: 1 file(s) copied

T2022AD32_CDR_NODDI32] copying:   0%|                                                       | 0/1 [00:00<?, ?file/s]
[EPT2022AD32_CDR_NODDI32] copying: 100%|███████████████████████████████████████████████| 1/1 [00:00<00:00,  1.00file/s]
Processing folders:  30%|████████████████▊                                       | 102/339 [04:07<09:25,  2.39s/folder]

[OK] EPT2022AD32_CDR_NODDI32: 1 file(s) copied

T2022AD33_KTY_NODDI32] copying:   0%|                                                       | 0/1 [00:00<?, ?file/s]
[EPT2022AD33_KTY_NODDI32] copying: 100%|███████████████████████████████████████████████| 1/1 [00:01<00:00,  1.25s/file]
Processing folders:  30%|█████████████████                                       | 103/339 [04:08<08:08,  2.07s/folder]

[OK] EPT2022AD33_KTY_NODDI32: 1 file(s) copied

T2022AD34_KMB_NODDI32] copying:   0%|                                                       | 0/1 [00:00<?, ?file/s]
[EPT2022AD34_KMB_NODDI32] copying: 100%|███████████████████████████████████████████████| 1/1 [00:02<00:00,  2.28s/file]
Processing folders:  31%|█████████████████▏                                      | 104/339 [04:10<08:21,  2.13s/folder]

[OK] EPT2022AD34_KMB_NODDI32: 1 file(s) copied

T2022AD35_HHS_NODDI32] copying:   0%|                                                       | 0/1 [00:00<?, ?file/s]
[EPT2022AD35_HHS_NODDI32] copying: 100%|███████████████████████████████████████████████| 1/1 [00:04<00:00,  4.22s/file]
Processing folders:  31%|█████████████████▎                                      | 105/339 [04:15<10:41,  2.74s/folder]

[OK] EPT2022AD35_HHS_NODDI32: 1 file(s) copied

T2022AD36_JYS_NODDI32] copying:   0%|                                                       | 0/1 [00:00<?, ?file/s]
[EPT2022AD36_JYS_NODDI32] copying: 100%|███████████████████████████████████████████████| 1/1 [00:05<00:00,  5.12s/file]
Processing folders:  31%|█████████████████▌                                      | 106/339 [04:20<13:21,  3.44s/folder]

[OK] EPT2022AD36_JYS_NODDI32: 1 file(s) copied

T2022AD37_CEH_NODDI32] copying:   0%|                                                       | 0/1 [00:00<?, ?file/s]
[EPT2022AD37_CEH_NODDI32] copying: 100%|███████████████████████████████████████████████| 1/1 [00:01<00:00,  1.27s/file]
Processing folders:  32%|█████████████████▋                                      | 107/339 [04:21<10:50,  2.80s/folder]

[OK] EPT2022AD37_CEH_NODDI32: 1 file(s) copied

T2022AD38_YYS_NODDI32] copying:   0%|                                                       | 0/1 [00:00<?, ?file/s]
[EPT2022AD38_YYS_NODDI32] copying: 100%|███████████████████████████████████████████████| 1/1 [00:01<00:00,  1.61s/file]
Processing folders:  32%|█████████████████▊                                      | 108/339 [04:23<09:26,  2.45s/folder]

[OK] EPT2022AD38_YYS_NODDI32: 1 file(s) copied

T2022AD39_LJS_NODDI32] copying:   0%|                                                       | 0/1 [00:00<?, ?file/s]
[EPT2022AD39_LJS_NODDI32] copying: 100%|███████████████████████████████████████████████| 1/1 [00:01<00:00,  1.62s/file]
Processing folders:  32%|██████████████████                                      | 109/339 [04:24<08:27,  2.21s/folder]

[OK] EPT2022AD39_LJS_NODDI32: 1 file(s) copied

T2022AD40_RKJ_NODDI32] copying:   0%|                                                       | 0/1 [00:00<?, ?file/s]
[EPT2022AD40_RKJ_NODDI32] copying: 100%|███████████████████████████████████████████████| 1/1 [00:04<00:00,  4.83s/file]
Processing folders:  32%|██████████████████▏                                     | 110/339 [04:29<11:24,  2.99s/folder]

[OK] EPT2022AD40_RKJ_NODDI32: 1 file(s) copied

T2022AD41_SIJ_NODDI32] copying:   0%|                                                       | 0/1 [00:00<?, ?file/s]
[EPT2022AD41_SIJ_NODDI32] copying: 100%|███████████████████████████████████████████████| 1/1 [00:02<00:00,  2.75s/file]
Processing folders:  33%|██████████████████▎                                     | 111/339 [04:32<11:05,  2.92s/folder]

[OK] EPT2022AD41_SIJ_NODDI32: 1 file(s) copied

T2022AD42_HPB_NODDI32] copying:   0%|                                                       | 0/1 [00:00<?, ?file/s]
[EPT2022AD42_HPB_NODDI32] copying: 100%|███████████████████████████████████████████████| 1/1 [00:01<00:00,  1.40s/file]
Processing folders:  33%|██████████████████▌                                     | 112/339 [04:33<09:20,  2.47s/folder]

[OK] EPT2022AD42_HPB_NODDI32: 1 file(s) copied

T2022AD43_CDH_NODDI32] copying:   0%|                                                       | 0/1 [00:00<?, ?file/s]
[EPT2022AD43_CDH_NODDI32] copying: 100%|███████████████████████████████████████████████| 1/1 [00:01<00:00,  1.99s/file]
Processing folders:  33%|██████████████████▋                                     | 113/339 [04:35<08:46,  2.33s/folder]

[OK] EPT2022AD43_CDH_NODDI32: 1 file(s) copied

T2022AD44_LKJ_NODDI32] copying:   0%|                                                       | 0/1 [00:00<?, ?file/s]
[EPT2022AD44_LKJ_NODDI32] copying: 100%|███████████████████████████████████████████████| 1/1 [00:05<00:00,  5.12s/file]
Processing folders:  34%|██████████████████▊                                     | 114/339 [04:40<11:52,  3.17s/folder]

[OK] EPT2022AD44_LKJ_NODDI32: 1 file(s) copied

T2022AD45_CHS_NODDI32] copying:   0%|                                                       | 0/1 [00:00<?, ?file/s]
[EPT2022AD45_CHS_NODDI32] copying: 100%|███████████████████████████████████████████████| 1/1 [00:02<00:00,  2.02s/file]
Processing folders:  34%|██████████████████▉                                     | 115/339 [04:42<10:33,  2.83s/folder]

[OK] EPT2022AD45_CHS_NODDI32: 1 file(s) copied

T2022AD46_KOS_NODDI32] copying:   0%|                                                       | 0/1 [00:00<?, ?file/s]
[EPT2022AD46_KOS_NODDI32] copying: 100%|███████████████████████████████████████████████| 1/1 [00:01<00:00,  1.55s/file]
Processing folders:  34%|███████████████████▏                                    | 116/339 [04:44<09:05,  2.45s/folder]

[OK] EPT2022AD46_KOS_NODDI32: 1 file(s) copied

T2022AD47_KPK_NODDI32] copying:   0%|                                                       | 0/1 [00:00<?, ?file/s]
[EPT2022AD47_KPK_NODDI32] copying: 100%|███████████████████████████████████████████████| 1/1 [00:01<00:00,  1.84s/file]
Processing folders:  35%|███████████████████▎                                    | 117/339 [04:46<08:23,  2.27s/folder]

[OK] EPT2022AD47_KPK_NODDI32: 1 file(s) copied

T2022AD48_HJJ_NODDI32] copying:   0%|                                                       | 0/1 [00:00<?, ?file/s]
[EPT2022AD48_HJJ_NODDI32] copying: 100%|███████████████████████████████████████████████| 1/1 [00:02<00:00,  2.60s/file]
Processing folders:  35%|███████████████████▍                                    | 118/339 [04:48<08:44,  2.37s/folder]

[OK] EPT2022AD48_HJJ_NODDI32: 1 file(s) copied

T2022AD49_PCS_NODDI32] copying:   0%|                                                       | 0/1 [00:00<?, ?file/s]
[EPT2022AD49_PCS_NODDI32] copying: 100%|███████████████████████████████████████████████| 1/1 [00:05<00:00,  5.24s/file]
Processing folders:  35%|███████████████████▋                                    | 119/339 [04:54<11:51,  3.23s/folder]

[OK] EPT2022AD49_PCS_NODDI32: 1 file(s) copied

T2022AD50_YYH_NODDI32] copying:   0%|                                                       | 0/1 [00:00<?, ?file/s]
[EPT2022AD50_YYH_NODDI32] copying: 100%|███████████████████████████████████████████████| 1/1 [00:01<00:00,  1.58s/file]
Processing folders:  35%|███████████████████▊                                    | 120/339 [04:55<09:59,  2.74s/folder]

[OK] EPT2022AD50_YYH_NODDI32: 1 file(s) copied

T2022AD51_KBS_NODDI32] copying:   0%|                                                       | 0/1 [00:00<?, ?file/s]
[EPT2022AD51_KBS_NODDI32] copying: 100%|███████████████████████████████████████████████| 1/1 [00:02<00:00,  2.02s/file]
Processing folders:  36%|███████████████████▉                                    | 121/339 [04:57<09:10,  2.52s/folder]

[OK] EPT2022AD51_KBS_NODDI32: 1 file(s) copied

T2022AD52_POA_NODDI32] copying:   0%|                                                       | 0/1 [00:00<?, ?file/s]
[EPT2022AD52_POA_NODDI32] copying: 100%|███████████████████████████████████████████████| 1/1 [00:03<00:00,  3.25s/file]
Processing folders:  36%|████████████████████▏                                   | 122/339 [05:01<09:55,  2.74s/folder]

[OK] EPT2022AD52_POA_NODDI32: 1 file(s) copied

T2022AD53_KJD_NODDI32] copying:   0%|                                                       | 0/1 [00:00<?, ?file/s]
[EPT2022AD53_KJD_NODDI32] copying: 100%|███████████████████████████████████████████████| 1/1 [00:02<00:00,  2.04s/file]
Processing folders:  36%|████████████████████▎                                   | 123/339 [05:03<09:07,  2.53s/folder]

[OK] EPT2022AD53_KJD_NODDI32: 1 file(s) copied

T2022AD54_GJJ_NODDI32] copying:   0%|                                                       | 0/1 [00:00<?, ?file/s]
[EPT2022AD54_GJJ_NODDI32] copying: 100%|███████████████████████████████████████████████| 1/1 [00:03<00:00,  3.11s/file]
Processing folders:  37%|████████████████████▍                                   | 124/339 [05:06<09:42,  2.71s/folder]

[OK] EPT2022AD54_GJJ_NODDI32: 1 file(s) copied

T2022AD55_SSB_NODDI32] copying:   0%|                                                       | 0/1 [00:00<?, ?file/s]
[EPT2022AD55_SSB_NODDI32] copying: 100%|███████████████████████████████████████████████| 1/1 [00:01<00:00,  1.97s/file]
Processing folders:  37%|████████████████████▋                                   | 125/339 [05:08<08:53,  2.49s/folder]

[OK] EPT2022AD55_SSB_NODDI32: 1 file(s) copied

T2022AD56_SKS_NODDI32] copying:   0%|                                                       | 0/1 [00:00<?, ?file/s]
[EPT2022AD56_SKS_NODDI32] copying: 100%|███████████████████████████████████████████████| 1/1 [00:02<00:00,  2.23s/file]
Processing folders:  37%|████████████████████▊                                   | 126/339 [05:10<08:35,  2.42s/folder]

[OK] EPT2022AD56_SKS_NODDI32: 1 file(s) copied

T2022AD57_KYS_NODDI32] copying:   0%|                                                       | 0/1 [00:00<?, ?file/s]
[EPT2022AD57_KYS_NODDI32] copying: 100%|███████████████████████████████████████████████| 1/1 [00:01<00:00,  1.40s/file]
Processing folders:  37%|████████████████████▉                                   | 127/339 [05:11<07:28,  2.12s/folder]

[OK] EPT2022AD57_KYS_NODDI32: 1 file(s) copied

T2022AD58_PYR_NODDI32] copying:   0%|                                                       | 0/1 [00:00<?, ?file/s]
[EPT2022AD58_PYR_NODDI32] copying: 100%|███████████████████████████████████████████████| 1/1 [00:07<00:00,  7.01s/file]
Processing folders:  38%|█████████████████████▏                                  | 128/339 [05:18<12:36,  3.58s/folder]

[OK] EPT2022AD58_PYR_NODDI32: 1 file(s) copied

T2022AD59_SNO_NODDI32] copying:   0%|                                                       | 0/1 [00:00<?, ?file/s]
[EPT2022AD59_SNO_NODDI32] copying: 100%|███████████████████████████████████████████████| 1/1 [00:01<00:00,  1.96s/file]
Processing folders:  38%|█████████████████████▎                                  | 129/339 [05:20<10:50,  3.10s/folder]

[OK] EPT2022AD59_SNO_NODDI32: 1 file(s) copied

T2022AD60_KYD_NODDI32] copying:   0%|                                                       | 0/1 [00:00<?, ?file/s]
[EPT2022AD60_KYD_NODDI32] copying: 100%|███████████████████████████████████████████████| 1/1 [00:02<00:00,  2.38s/file]
Processing folders:  38%|█████████████████████▍                                  | 130/339 [05:23<10:02,  2.88s/folder]

[OK] EPT2022AD60_KYD_NODDI32: 1 file(s) copied

T2022AD61_KYJ_NODDI32] copying:   0%|                                                       | 0/1 [00:00<?, ?file/s]
[EPT2022AD61_KYJ_NODDI32] copying: 100%|███████████████████████████████████████████████| 1/1 [00:02<00:00,  2.39s/file]
Processing folders:  39%|█████████████████████▋                                  | 131/339 [05:25<09:30,  2.74s/folder]

[OK] EPT2022AD61_KYJ_NODDI32: 1 file(s) copied

T2022AD62_LHJ_NODDI32] copying:   0%|                                                       | 0/1 [00:00<?, ?file/s]
[EPT2022AD62_LHJ_NODDI32] copying: 100%|███████████████████████████████████████████████| 1/1 [00:05<00:00,  5.36s/file]
Processing folders:  39%|█████████████████████▊                                  | 132/339 [05:30<12:10,  3.53s/folder]

[OK] EPT2022AD62_LHJ_NODDI32: 1 file(s) copied

T2023AD01_KMH_NODDI32] copying:   0%|                                                       | 0/1 [00:00<?, ?file/s]
[EPT2023AD01_KMH_NODDI32] copying: 100%|███████████████████████████████████████████████| 1/1 [00:01<00:00,  1.47s/file]
Processing folders:  39%|█████████████████████▉                                  | 133/339 [05:32<09:59,  2.91s/folder]

[OK] EPT2023AD01_KMH_NODDI32: 1 file(s) copied

T2023AD02_HUI_NODDI32] copying:   0%|                                                       | 0/1 [00:00<?, ?file/s]
[EPT2023AD02_HUI_NODDI32] copying: 100%|███████████████████████████████████████████████| 1/1 [00:02<00:00,  2.08s/file]
Processing folders:  40%|██████████████████████▏                                 | 134/339 [05:34<09:06,  2.66s/folder]

[OK] EPT2023AD02_HUI_NODDI32: 1 file(s) copied

T2023AD03_MSJ_NODDI32] copying:   0%|                                                       | 0/1 [00:00<?, ?file/s]
[EPT2023AD03_MSJ_NODDI32] copying: 100%|███████████████████████████████████████████████| 1/1 [00:01<00:00,  1.17s/file]
Processing folders:  40%|██████████████████████▎                                 | 135/339 [05:35<07:32,  2.22s/folder]

[OK] EPT2023AD03_MSJ_NODDI32: 1 file(s) copied

T2023AD04_KJU_NODDI32] copying:   0%|                                                       | 0/1 [00:00<?, ?file/s]
[EPT2023AD04_KJU_NODDI32] copying: 100%|███████████████████████████████████████████████| 1/1 [00:02<00:00,  2.19s/file]
Processing folders:  40%|██████████████████████▍                                 | 136/339 [05:37<07:29,  2.21s/folder]

[OK] EPT2023AD04_KJU_NODDI32: 1 file(s) copied

T2023AD05_JIS_NODDI32] copying:   0%|                                                       | 0/1 [00:00<?, ?file/s]
[EPT2023AD05_JIS_NODDI32] copying: 100%|███████████████████████████████████████████████| 1/1 [00:01<00:00,  1.75s/file]
Processing folders:  40%|██████████████████████▋                                 | 137/339 [05:39<06:59,  2.08s/folder]

[OK] EPT2023AD05_JIS_NODDI32: 1 file(s) copied

T2023AD06_LSJ_NODDI32] copying:   0%|                                                       | 0/1 [00:00<?, ?file/s]
[EPT2023AD06_LSJ_NODDI32] copying: 100%|███████████████████████████████████████████████| 1/1 [00:06<00:00,  6.22s/file]
Processing folders:  41%|██████████████████████▊                                 | 138/339 [05:45<11:07,  3.32s/folder]

[OK] EPT2023AD06_LSJ_NODDI32: 1 file(s) copied

T2023AD07_WGJ_NODDI32] copying:   0%|                                                       | 0/1 [00:00<?, ?file/s]
[EPT2023AD07_WGJ_NODDI32] copying: 100%|███████████████████████████████████████████████| 1/1 [00:01<00:00,  1.22s/file]
Processing folders:  41%|██████████████████████▉                                 | 139/339 [05:47<08:59,  2.70s/folder]

[OK] EPT2023AD07_WGJ_NODDI32: 1 file(s) copied

T2023AD08_KMS_NODDI32] copying:   0%|                                                       | 0/1 [00:00<?, ?file/s]
[EPT2023AD08_KMS_NODDI32] copying: 100%|███████████████████████████████████████████████| 1/1 [00:03<00:00,  3.64s/file]
Processing folders:  41%|███████████████████████▏                                | 140/339 [05:50<09:53,  2.98s/folder]

[OK] EPT2023AD08_KMS_NODDI32: 1 file(s) copied

T2023AD09_LSU_NODDI32] copying:   0%|                                                       | 0/1 [00:00<?, ?file/s]
[EPT2023AD09_LSU_NODDI32] copying: 100%|███████████████████████████████████████████████| 1/1 [00:02<00:00,  2.46s/file]
Processing folders:  42%|███████████████████████▎                                | 141/339 [05:53<09:20,  2.83s/folder]

[OK] EPT2023AD09_LSU_NODDI32: 1 file(s) copied

T2023AD10_JBY_NODDI32] copying:   0%|                                                       | 0/1 [00:00<?, ?file/s]
[EPT2023AD10_JBY_NODDI32] copying: 100%|███████████████████████████████████████████████| 1/1 [00:03<00:00,  3.84s/file]
Processing folders:  42%|███████████████████████▍                                | 142/339 [05:57<10:17,  3.14s/folder]

[OK] EPT2023AD10_JBY_NODDI32: 1 file(s) copied

T2023AD11_HSY_NODDI32] copying:   0%|                                                       | 0/1 [00:00<?, ?file/s]
[EPT2023AD11_HSY_NODDI32] copying: 100%|███████████████████████████████████████████████| 1/1 [00:01<00:00,  1.08s/file]
Processing folders:  42%|███████████████████████▌                                | 143/339 [05:58<08:14,  2.52s/folder]

[OK] EPT2023AD11_HSY_NODDI32: 1 file(s) copied

T2023AD12_YJS_NODDI32] copying:   0%|                                                       | 0/1 [00:00<?, ?file/s]
[EPT2023AD12_YJS_NODDI32] copying: 100%|███████████████████████████████████████████████| 1/1 [00:02<00:00,  2.13s/file]
Processing folders:  42%|███████████████████████▊                                | 144/339 [06:00<07:49,  2.41s/folder]

[OK] EPT2023AD12_YJS_NODDI32: 1 file(s) copied

T2023AD13_WOB_NODDI32] copying:   0%|                                                       | 0/1 [00:00<?, ?file/s]
[EPT2023AD13_WOB_NODDI32] copying: 100%|███████████████████████████████████████████████| 1/1 [00:02<00:00,  2.48s/file]
Processing folders:  43%|███████████████████████▉                                | 145/339 [06:02<07:51,  2.43s/folder]

[OK] EPT2023AD13_WOB_NODDI32: 1 file(s) copied

T2023AD14_LMS_NODDI32] copying:   0%|                                                       | 0/1 [00:00<?, ?file/s]
[EPT2023AD14_LMS_NODDI32] copying: 100%|███████████████████████████████████████████████| 1/1 [00:06<00:00,  6.50s/file]
Processing folders:  43%|████████████████████████                                | 146/339 [06:09<11:44,  3.65s/folder]

[OK] EPT2023AD14_LMS_NODDI32: 1 file(s) copied

T2023AD15_LSJ_NODDI32] copying:   0%|                                                       | 0/1 [00:00<?, ?file/s]
[EPT2023AD15_LSJ_NODDI32] copying: 100%|███████████████████████████████████████████████| 1/1 [00:01<00:00,  1.89s/file]
Processing folders:  43%|████████████████████████▎                               | 147/339 [06:11<10:00,  3.13s/folder]

[OK] EPT2023AD15_LSJ_NODDI32: 1 file(s) copied

T2023AD16_JHG_NODDI32] copying:   0%|                                                       | 0/1 [00:00<?, ?file/s]
[EPT2023AD16_JHG_NODDI32] copying: 100%|███████████████████████████████████████████████| 1/1 [00:02<00:00,  2.57s/file]
Processing folders:  44%|████████████████████████▍                               | 148/339 [06:13<09:26,  2.96s/folder]

[OK] EPT2023AD16_JHG_NODDI32: 1 file(s) copied

T2023AD17_LHG_NODDI32] copying:   0%|                                                       | 0/1 [00:00<?, ?file/s]
[EPT2023AD17_LHG_NODDI32] copying: 100%|███████████████████████████████████████████████| 1/1 [00:01<00:00,  2.00s/file]
Processing folders:  44%|████████████████████████▌                               | 149/339 [06:15<08:28,  2.68s/folder]

[OK] EPT2023AD17_LHG_NODDI32: 1 file(s) copied

T2023AD18_LMS_NODDI32] copying:   0%|                                                       | 0/1 [00:00<?, ?file/s]
[EPT2023AD18_LMS_NODDI32] copying: 100%|███████████████████████████████████████████████| 1/1 [00:02<00:00,  2.69s/file]
Processing folders:  44%|████████████████████████▊                               | 150/339 [06:18<08:27,  2.68s/folder]

[OK] EPT2023AD18_LMS_NODDI32: 1 file(s) copied

T2023AD19_KTG_NODDI32] copying:   0%|                                                       | 0/1 [00:00<?, ?file/s]
[EPT2023AD19_KTG_NODDI32] copying: 100%|███████████████████████████████████████████████| 1/1 [00:02<00:00,  2.22s/file]
Processing folders:  45%|████████████████████████▉                               | 151/339 [06:20<07:58,  2.54s/folder]

[OK] EPT2023AD19_KTG_NODDI32: 1 file(s) copied

T2023AD20_CGJ_NODDI32] copying:   0%|                                                       | 0/1 [00:00<?, ?file/s]
[EPT2023AD20_CGJ_NODDI32] copying: 100%|███████████████████████████████████████████████| 1/1 [00:01<00:00,  1.86s/file]
Processing folders:  45%|█████████████████████████                               | 152/339 [06:22<07:17,  2.34s/folder]

[OK] EPT2023AD20_CGJ_NODDI32: 1 file(s) copied

T2023AD21_PDB_NODDI32] copying:   0%|                                                       | 0/1 [00:00<?, ?file/s]
[EPT2023AD21_PDB_NODDI32] copying: 100%|███████████████████████████████████████████████| 1/1 [00:05<00:00,  5.24s/file]
Processing folders:  45%|█████████████████████████▎                              | 153/339 [06:27<09:57,  3.21s/folder]

[OK] EPT2023AD21_PDB_NODDI32: 1 file(s) copied

T2023AD22_KID_NODDI32] copying:   0%|                                                       | 0/1 [00:00<?, ?file/s]
[EPT2023AD22_KID_NODDI32] copying: 100%|███████████████████████████████████████████████| 1/1 [00:01<00:00,  1.18s/file]
Processing folders:  45%|█████████████████████████▍                              | 154/339 [06:29<08:02,  2.61s/folder]

[OK] EPT2023AD22_KID_NODDI32: 1 file(s) copied

T2024AD01_KJI_NODDI32] copying:   0%|                                                       | 0/1 [00:00<?, ?file/s]
[EPT2024AD01_KJI_NODDI32] copying: 100%|███████████████████████████████████████████████| 1/1 [00:02<00:00,  2.06s/file]
Processing folders:  46%|█████████████████████████▌                              | 155/339 [06:31<07:29,  2.45s/folder]

[OK] EPT2024AD01_KJI_NODDI32: 1 file(s) copied

T2024AD02_HUY_NODDI32] copying:   0%|                                                       | 0/1 [00:00<?, ?file/s]
[EPT2024AD02_HUY_NODDI32] copying: 100%|███████████████████████████████████████████████| 1/1 [00:01<00:00,  1.88s/file]
Processing folders:  46%|█████████████████████████▊                              | 156/339 [06:32<06:57,  2.28s/folder]

[OK] EPT2024AD02_HUY_NODDI32: 1 file(s) copied

T2024AD03_NGS_NODDI32] copying:   0%|                                                       | 0/1 [00:00<?, ?file/s]
[EPT2024AD03_NGS_NODDI32] copying: 100%|███████████████████████████████████████████████| 1/1 [00:02<00:00,  2.76s/file]
Processing folders:  46%|█████████████████████████▉                              | 157/339 [06:35<07:21,  2.43s/folder]

[OK] EPT2024AD03_NGS_NODDI32: 1 file(s) copied

T2024AD04_LDS_NODDI32] copying:   0%|                                                       | 0/1 [00:00<?, ?file/s]
[EPT2024AD04_LDS_NODDI32] copying: 100%|███████████████████████████████████████████████| 1/1 [00:04<00:00,  4.48s/file]
Processing folders:  47%|██████████████████████████                              | 158/339 [06:40<09:11,  3.05s/folder]

[OK] EPT2024AD04_LDS_NODDI32: 1 file(s) copied

T2024AD05_KEJ_NODDI32] copying:   0%|                                                       | 0/1 [00:00<?, ?file/s]
[EPT2024AD05_KEJ_NODDI32] copying: 100%|███████████████████████████████████████████████| 1/1 [00:02<00:00,  2.40s/file]
Processing folders:  47%|██████████████████████████▎                             | 159/339 [06:42<08:34,  2.86s/folder]

[OK] EPT2024AD05_KEJ_NODDI32: 1 file(s) copied

T2024AD06_PYG_NODDI32] copying:   0%|                                                       | 0/1 [00:00<?, ?file/s]
[EPT2024AD06_PYG_NODDI32] copying: 100%|███████████████████████████████████████████████| 1/1 [00:02<00:00,  2.01s/file]
Processing folders:  47%|██████████████████████████▍                             | 160/339 [06:44<07:46,  2.60s/folder]

[OK] EPT2024AD06_PYG_NODDI32: 1 file(s) copied

T2024AD07_JGJ_NODDI32] copying:   0%|                                                       | 0/1 [00:00<?, ?file/s]
[EPT2024AD07_JGJ_NODDI32] copying: 100%|███████████████████████████████████████████████| 1/1 [00:01<00:00,  1.25s/file]
Processing folders:  47%|██████████████████████████▌                             | 161/339 [06:45<06:31,  2.20s/folder]

[OK] EPT2024AD07_JGJ_NODDI32: 1 file(s) copied

T2024AD08_LMS_NODDI32] copying:   0%|                                                       | 0/1 [00:00<?, ?file/s]
[EPT2024AD08_LMS_NODDI32] copying: 100%|███████████████████████████████████████████████| 1/1 [00:01<00:00,  1.50s/file]
Processing folders:  48%|██████████████████████████▊                             | 162/339 [06:47<05:52,  1.99s/folder]

[OK] EPT2024AD08_LMS_NODDI32: 1 file(s) copied

T2024AD09_CSO_NODDI32] copying:   0%|                                                       | 0/1 [00:00<?, ?file/s]
[EPT2024AD09_CSO_NODDI32] copying: 100%|███████████████████████████████████████████████| 1/1 [00:06<00:00,  6.12s/file]
Processing folders:  48%|██████████████████████████▉                             | 163/339 [06:53<09:29,  3.23s/folder]

[OK] EPT2024AD09_CSO_NODDI32: 1 file(s) copied

T2024AD10_KCJ_NODDI32] copying:   0%|                                                       | 0/1 [00:00<?, ?file/s]
[EPT2024AD10_KCJ_NODDI32] copying: 100%|███████████████████████████████████████████████| 1/1 [00:02<00:00,  2.03s/file]
Processing folders:  48%|███████████████████████████                             | 164/339 [06:55<08:22,  2.87s/folder]

[OK] EPT2024AD10_KCJ_NODDI32: 1 file(s) copied

T2024AD11_KHJ_NODDI32] copying:   0%|                                                       | 0/1 [00:00<?, ?file/s]
[EPT2024AD11_KHJ_NODDI32] copying: 100%|███████████████████████████████████████████████| 1/1 [00:01<00:00,  1.67s/file]
Processing folders:  49%|███████████████████████████▎                            | 165/339 [06:57<07:17,  2.51s/folder]

[OK] EPT2024AD11_KHJ_NODDI32: 1 file(s) copied

T2024AD12_LDS_NODDI32] copying:   0%|                                                       | 0/1 [00:00<?, ?file/s]
[EPT2024AD12_LDS_NODDI32] copying: 100%|███████████████████████████████████████████████| 1/1 [00:01<00:00,  1.79s/file]
Processing folders:  49%|███████████████████████████▍                            | 166/339 [06:59<06:37,  2.30s/folder]

[OK] EPT2024AD12_LDS_NODDI32: 1 file(s) copied

T2024AD13_LTO_NODDI32] copying:   0%|                                                       | 0/1 [00:00<?, ?file/s]
[EPT2024AD13_LTO_NODDI32] copying: 100%|███████████████████████████████████████████████| 1/1 [00:02<00:00,  2.55s/file]
Processing folders:  49%|███████████████████████████▌                            | 167/339 [07:01<06:49,  2.38s/folder]

[OK] EPT2024AD13_LTO_NODDI32: 1 file(s) copied
[REN] HFC2020AD01_KYM_NODDI32 -> x_HFC2020AD01_KYM_NODDI32 (no matching .nii)

C2020AD02_KS_NODDI32] copying:   0%|                                                        | 0/1 [00:00<?, ?file/s]
[HFC2020AD02_KS_NODDI32] copying: 100%|████████████████████████████████████████████████| 1/1 [00:06<00:00,  6.42s/file]
Processing folders:  50%|███████████████████████████▉                            | 169/339 [07:08<07:50,  2.77s/folder]

[OK] HFC2020AD02_KS_NODDI32: 1 file(s) copied

C2021AD01_YMB_NODDI32] copying:   0%|                                                       | 0/1 [00:00<?, ?file/s]
[HFC2021AD01_YMB_NODDI32] copying: 100%|███████████████████████████████████████████████| 1/1 [00:01<00:00,  1.46s/file]
Processing folders:  50%|████████████████████████████                            | 170/339 [07:09<06:53,  2.45s/folder]

[OK] HFC2021AD01_YMB_NODDI32: 1 file(s) copied

C2021AD02_SHS_NODDI32] copying:   0%|                                                       | 0/1 [00:00<?, ?file/s]
[HFC2021AD02_SHS_NODDI32] copying: 100%|███████████████████████████████████████████████| 1/1 [00:01<00:00,  1.32s/file]
Processing folders:  64%|███████████████████████████████████▋                    | 216/339 [07:11<00:15,  8.06folder/s]

[OK] HFC2021AD02_SHS_NODDI32: 1 file(s) copied
[REN] HFC2021AD03_LHY_DKI -> x_HFC2021AD03_LHY_DKI (no matching .nii)
[REN] HFC2021AD04_HKS_DKI -> x_HFC2021AD04_HKS_DKI (no matching .nii)
[REN] HFC2021AD05_KSM_DKI -> x_HFC2021AD05_KSM_DKI (no matching .nii)
[REN] HFC2021AD06_KKO_DKI -> x_HFC2021AD06_KKO_DKI (no matching .nii)
[REN] HFC2021AD07_HJY_DKI -> x_HFC2021AD07_HJY_DKI (no matching .nii)
[REN] HFC2021AD08_NHN_DKI -> x_HFC2021AD08_NHN_DKI (no matching .nii)
[REN] HFC2021AD09_KID_DKI -> x_HFC2021AD09_KID_DKI (no matching .nii)
[REN] HFC2021AD10_KSY_DKI -> x_HFC2021AD10_KSY_DKI (no matching .nii)
[REN] HFC2021AD11_KJB_DKI -> x_HFC2021AD11_KJB_DKI (no matching .nii)
[REN] HFC2021AD12_LGH_DKI -> x_HFC2021AD12_LGH_DKI (no matching .nii)
[REN] HFC2021AD13_KYI_DKI -> x_HFC2021AD13_KYI_DKI (no matching .nii)
[REN] HFC2021AD14_PGJ_DKI -> x_HFC2021AD14_PGJ_DKI (no matching .nii)
[REN] HFC2021AD15_YOH_DKI -> x_HFC2021AD15_YOH_DKI (no matching .nii)
[REN] HFC2021AD16_OGY_DKI -> x_HFC2021AD16_OGY_DKI (no matching .nii)
[REN] HFC2021AD17_KJS_DKI -> x_HFC2021AD17_KJS_DKI (no matching .nii)
[REN] HFC2021AD18_WJC_DKI -> x_HFC2021AD18_WJC_DKI (no matching .nii)
[REN] HFC2021AD19_KDH_DKI -> x_HFC2021AD19_KDH_DKI (no matching .nii)
[REN] HFC2021AD20_YSJ_DKI -> x_HFC2021AD20_YSJ_DKI (no matching .nii)
[REN] HFC2021AD21_CYS_DKI -> x_HFC2021AD21_CYS_DKI (no matching .nii)
[REN] HFC2021AD22_LUB_DKI -> x_HFC2021AD22_LUB_DKI (no matching .nii)
[REN] HFC2021AD23_OSD_DKI -> x_HFC2021AD23_OSD_DKI (no matching .nii)
[REN] HFC2021AD24_LSM_DKI -> x_HFC2021AD24_LSM_DKI (no matching .nii)
[REN] HFC2021AD25_SHS_DKI -> x_HFC2021AD25_SHS_DKI (no matching .nii)
[REN] HFC2021AD26_YJI_DKI -> x_HFC2021AD26_YJI_DKI (no matching .nii)
[REN] HFC2021AD27_LSH_DKI -> x_HFC2021AD27_LSH_DKI (no matching .nii)
[REN] HFC2021AD28_CYA_DKI -> x_HFC2021AD28_CYA_DKI (no matching .nii)
[REN] HFC2021AD29_LBD_DKI -> x_HFC2021AD29_LBD_DKI (no matching .nii)
[REN] HFC2021AD30_HGS_DKI -> x_HFC2021AD30_HGS_DKI (no matching .nii)
[REN] HFC2021AD31_LJB_DKI -> x_HFC2021AD31_LJB_DKI (no matching .nii)
[REN] HFC2021AD32_CPY_DKI -> x_HFC2021AD32_CPY_DKI (no matching .nii)
[REN] HFC2021AD33_YEO_DKI -> x_HFC2021AD33_YEO_DKI (no matching .nii)
[REN] HFC2021AD34_PBY_DKI -> x_HFC2021AD34_PBY_DKI (no matching .nii)
[REN] HFC2021AD35_KSS_DKI -> x_HFC2021AD35_KSS_DKI (no matching .nii)
[REN] HFC2021AD36_LGS_DKI -> x_HFC2021AD36_LGS_DKI (no matching .nii)
[REN] HFC2021AD37_SYH_DKI -> x_HFC2021AD37_SYH_DKI (no matching .nii)
[REN] HFC2021AD38_BMR_DKI -> x_HFC2021AD38_BMR_DKI (no matching .nii)
[REN] HFC2021AD39_YTG_DKI -> x_HFC2021AD39_YTG_DKI (no matching .nii)
[REN] HFC2021AD40_KMS_DKI -> x_HFC2021AD40_KMS_DKI (no matching .nii)
[REN] HFC2021AD41_MBS_DKI -> x_HFC2021AD41_MBS_DKI (no matching .nii)
[REN] HFC2021AD42_KED_DKI -> x_HFC2021AD42_KED_DKI (no matching .nii)
[REN] HFC2021AD43_NSD_DKI -> x_HFC2021AD43_NSD_DKI (no matching .nii)
[REN] HFC2021AD44_YCJ_DKI -> x_HFC2021AD44_YCJ_DKI (no matching .nii)
[REN] HFC2021AD45_OIS_DKI -> x_HFC2021AD45_OIS_DKI (no matching .nii)
[REN] HFC2021AD46_KYJ_DKI -> x_HFC2021AD46_KYJ_DKI (no matching .nii)
[REN] HFC2021AD47_LHS_DKI -> x_HFC2021AD47_LHS_DKI (no matching .nii)
[REN] HFC2021AD48_KJM_DKI -> x_HFC2021AD48_KJM_DKI (no matching .nii)
[REN] HFC2021AD49_LJS_DKI -> x_HFC2021AD49_LJS_DKI (no matching .nii)
[REN] HFC2021AD50_DGY_DKI -> x_HFC2021AD50_DGY_DKI (no matching .nii)
[REN] HFC2021AD51_NEH_DKI -> x_HFC2021AD51_NEH_DKI (no matching .nii)
[REN] HFC2021AD52_KSS_DKI -> x_HFC2021AD52_KSS_DKI (no matching .nii)
[REN] HFC2021AD53_LSD_DKI -> x_HFC2021AD53_LSD_DKI (no matching .nii)
[REN] HFC2021AD54_KGI_DKI -> x_HFC2021AD54_KGI_DKI (no matching .nii)
[REN] HFC2021AD55_LGE_DKI -> x_HFC2021AD55_LGE_DKI (no matching .nii)
[REN] HFC2021AD56_SEY_DKI -> x_HFC2021AD56_SEY_DKI (no matching .nii)
[REN] HFC2021AD57_PGJ_DKI -> x_HFC2021AD57_PGJ_DKI (no matching .nii)

EPT2019AD01_KMO_NODDI32] copying:   0%|                                                     | 0/1 [00:00<?, ?file/s]
[MREPT2019AD01_KMO_NODDI32] copying: 100%|█████████████████████████████████████████████| 1/1 [00:01<00:00,  1.56s/file]
Processing folders:  67%|█████████████████████████████████████▍                  | 227/339 [07:12<00:14,  7.75folder/s]

[OK] MREPT2019AD01_KMO_NODDI32: 1 file(s) copied

EPT2019AD02_JSJ_NODDI32] copying:   0%|                                                     | 0/1 [00:00<?, ?file/s]
[MREPT2019AD02_JSJ_NODDI32] copying: 100%|█████████████████████████████████████████████| 1/1 [00:01<00:00,  1.73s/file]
Processing folders:  67%|█████████████████████████████████████▍                  | 227/339 [07:14<00:14,  7.75folder/s]

[OK] MREPT2019AD02_JSJ_NODDI32: 1 file(s) copied

EPT2019AD03_OHS_NODDI32] copying:   0%|                                                     | 0/1 [00:00<?, ?file/s]
[MREPT2019AD03_OHS_NODDI32] copying: 100%|█████████████████████████████████████████████| 1/1 [00:03<00:00,  3.69s/file]
Processing folders:  67%|█████████████████████████████████████▍                  | 227/339 [07:18<00:14,  7.75folder/s]

[OK] MREPT2019AD03_OHS_NODDI32: 1 file(s) copied

EPT2019AD04_CSY_NODDI32] copying:   0%|                                                     | 0/1 [00:00<?, ?file/s]
[MREPT2019AD04_CSY_NODDI32] copying: 100%|█████████████████████████████████████████████| 1/1 [00:03<00:00,  3.95s/file]
Processing folders:  67%|█████████████████████████████████████▍                  | 227/339 [07:22<00:14,  7.75folder/s]

[OK] MREPT2019AD04_CSY_NODDI32: 1 file(s) copied

EPT2019AD05_KJI_NODDI32] copying:   0%|                                                     | 0/1 [00:00<?, ?file/s]
[MREPT2019AD05_KJI_NODDI32] copying: 100%|█████████████████████████████████████████████| 1/1 [00:01<00:00,  1.78s/file]
Processing folders:  67%|█████████████████████████████████████▍                  | 227/339 [07:23<00:14,  7.75folder/s]

[OK] MREPT2019AD05_KJI_NODDI32: 1 file(s) copied

EPT2019AD06_CKJ_NODDI32] copying:   0%|                                                     | 0/1 [00:00<?, ?file/s]
[MREPT2019AD06_CKJ_NODDI32] copying: 100%|█████████████████████████████████████████████| 1/1 [00:03<00:00,  3.33s/file]
Processing folders:  67%|█████████████████████████████████████▍                  | 227/339 [07:27<00:14,  7.75folder/s]

[OK] MREPT2019AD06_CKJ_NODDI32: 1 file(s) copied

EPT2019AD07_LJH_NODDI32] copying:   0%|                                                     | 0/1 [00:00<?, ?file/s]
[MREPT2019AD07_LJH_NODDI32] copying: 100%|█████████████████████████████████████████████| 1/1 [00:02<00:00,  2.39s/file]
Processing folders:  67%|█████████████████████████████████████▍                  | 227/339 [07:29<00:14,  7.75folder/s]

[OK] MREPT2019AD07_LJH_NODDI32: 1 file(s) copied

Processing folders:  67%|█████████████████████████████████████▍                  | 227/339 [07:30<00:14,  7.75folder/s]
[MREPT2019AD09_LKS_NODDI32] copying: 100%|█████████████████████████████████████████████| 1/1 [00:02<00:00,  2.10s/file]
Processing folders:  69%|██████████████████████████████████████▋                 | 234/339 [07:31<01:03,  1.65folder/s]

[OK] MREPT2019AD09_LKS_NODDI32: 1 file(s) copied

EPT2019AD10_KJL_NODDI32] copying:   0%|                                                     | 0/1 [00:00<?, ?file/s]
[MREPT2019AD10_KJL_NODDI32] copying: 100%|█████████████████████████████████████████████| 1/1 [00:04<00:00,  4.87s/file]
Processing folders:  69%|██████████████████████████████████████▊                 | 235/339 [07:36<01:19,  1.32folder/s]

[OK] MREPT2019AD10_KJL_NODDI32: 1 file(s) copied

EPT2019AD11_CKS_NODDI32] copying:   0%|                                                     | 0/1 [00:00<?, ?file/s]
[MREPT2019AD11_CKS_NODDI32] copying: 100%|█████████████████████████████████████████████| 1/1 [00:01<00:00,  1.87s/file]
Processing folders:  69%|██████████████████████████████████████▊                 | 235/339 [07:38<01:19,  1.32folder/s]

[OK] MREPT2019AD11_CKS_NODDI32: 1 file(s) copied

EPT2019AD13_KHS_NODDI32] copying:   0%|                                                     | 0/1 [00:00<?, ?file/s]
[MREPT2019AD13_KHS_NODDI32] copying: 100%|█████████████████████████████████████████████| 1/1 [00:01<00:00,  1.18s/file]
Processing folders:  69%|██████████████████████████████████████▊                 | 235/339 [07:39<01:19,  1.32folder/s]

[OK] MREPT2019AD13_KHS_NODDI32: 1 file(s) copied

EPT2019AD14_CMJ_NODDI32] copying:   0%|                                                     | 0/1 [00:00<?, ?file/s]
[MREPT2019AD14_CMJ_NODDI32] copying: 100%|█████████████████████████████████████████████| 1/1 [00:02<00:00,  2.62s/file]
Processing folders:  69%|██████████████████████████████████████▊                 | 235/339 [07:42<01:19,  1.32folder/s]

[OK] MREPT2019AD14_CMJ_NODDI32: 1 file(s) copied

EPT2020AD01_CGS_NODDI32] copying:   0%|                                                     | 0/1 [00:00<?, ?file/s]
[MREPT2020AD01_CGS_NODDI32] copying: 100%|█████████████████████████████████████████████| 1/1 [00:05<00:00,  5.91s/file]
Processing folders:  69%|██████████████████████████████████████▊                 | 235/339 [07:48<01:19,  1.32folder/s]

[OK] MREPT2020AD01_CGS_NODDI32: 1 file(s) copied

EPT2020AD02_HMJ_NODDI32] copying:   0%|                                                     | 0/1 [00:00<?, ?file/s]
[MREPT2020AD02_HMJ_NODDI32] copying: 100%|█████████████████████████████████████████████| 1/1 [00:01<00:00,  1.42s/file]
Processing folders:  71%|███████████████████████████████████████▋                | 240/339 [07:49<01:52,  1.14s/folder]

[OK] MREPT2020AD02_HMJ_NODDI32: 1 file(s) copied

EPT2020AD03_KJH_NODDI32] copying:   0%|                                                     | 0/1 [00:00<?, ?file/s]
[MREPT2020AD03_KJH_NODDI32] copying: 100%|█████████████████████████████████████████████| 1/1 [00:02<00:00,  2.22s/file]
Processing folders:  71%|███████████████████████████████████████▊                | 241/339 [07:51<01:57,  1.20s/folder]

[OK] MREPT2020AD03_KJH_NODDI32: 1 file(s) copied

EPT2020AD04_NGR_NODDI32] copying:   0%|                                                     | 0/1 [00:00<?, ?file/s]
[MREPT2020AD04_NGR_NODDI32] copying: 100%|█████████████████████████████████████████████| 1/1 [00:01<00:00,  1.36s/file]
Processing folders:  71%|███████████████████████████████████████▊                | 241/339 [07:53<01:57,  1.20s/folder]

[OK] MREPT2020AD04_NGR_NODDI32: 1 file(s) copied

EPT2020AD05_PJE_NODDI32] copying:   0%|                                                     | 0/1 [00:00<?, ?file/s]
[MREPT2020AD05_PJE_NODDI32] copying: 100%|█████████████████████████████████████████████| 1/1 [00:02<00:00,  2.61s/file]
Processing folders:  71%|███████████████████████████████████████▊                | 241/339 [07:55<01:57,  1.20s/folder]

[OK] MREPT2020AD05_PJE_NODDI32: 1 file(s) copied

EPT2020AD06_JHK_NODDI32] copying:   0%|                                                     | 0/1 [00:00<?, ?file/s]
[MREPT2020AD06_JHK_NODDI32] copying: 100%|█████████████████████████████████████████████| 1/1 [00:05<00:00,  5.81s/file]
Processing folders:  71%|███████████████████████████████████████▊                | 241/339 [08:01<01:57,  1.20s/folder]

[OK] MREPT2020AD06_JHK_NODDI32: 1 file(s) copied

EPT2020AD07_KYG_NODDI32] copying:   0%|                                                     | 0/1 [00:00<?, ?file/s]
[MREPT2020AD07_KYG_NODDI32] copying: 100%|█████████████████████████████████████████████| 1/1 [00:01<00:00,  1.20s/file]
Processing folders:  72%|████████████████████████████████████████▍               | 245/339 [08:02<02:27,  1.57s/folder]

[OK] MREPT2020AD07_KYG_NODDI32: 1 file(s) copied

EPT2020AD08_CYS_NODDI32] copying:   0%|                                                     | 0/1 [00:00<?, ?file/s]
[MREPT2020AD08_CYS_NODDI32] copying: 100%|█████████████████████████████████████████████| 1/1 [00:01<00:00,  1.91s/file]
Processing folders:  73%|████████████████████████████████████████▋               | 246/339 [08:04<02:28,  1.60s/folder]

[OK] MREPT2020AD08_CYS_NODDI32: 1 file(s) copied
[REN] MREPT2020AD09_PJJ_NODDI32 -> x_MREPT2020AD09_PJJ_NODDI32 (no matching .nii)

EPT2020AD10_CYJ_NODDI32] copying:   0%|                                                     | 0/1 [00:00<?, ?file/s]
[MREPT2020AD10_CYJ_NODDI32] copying: 100%|█████████████████████████████████████████████| 1/1 [00:01<00:00,  1.39s/file]
Processing folders:  73%|████████████████████████████████████████▋               | 246/339 [08:06<02:28,  1.60s/folder]

[OK] MREPT2020AD10_CYJ_NODDI32: 1 file(s) copied

EPT2020AD11_KHJ_NODDI32] copying:   0%|                                                     | 0/1 [00:00<?, ?file/s]
[MREPT2020AD11_KHJ_NODDI32] copying: 100%|█████████████████████████████████████████████| 1/1 [00:03<00:00,  3.28s/file]
Processing folders:  73%|█████████████████████████████████████████▏              | 249/339 [08:09<02:23,  1.59s/folder]

[OK] MREPT2020AD11_KHJ_NODDI32: 1 file(s) copied

EPT2020AD12_KOB_NODDI32] copying:   0%|                                                     | 0/1 [00:00<?, ?file/s]
[MREPT2020AD12_KOB_NODDI32] copying: 100%|█████████████████████████████████████████████| 1/1 [00:04<00:00,  4.96s/file]
Processing folders:  73%|█████████████████████████████████████████▏              | 249/339 [08:14<02:23,  1.59s/folder]

[OK] MREPT2020AD12_KOB_NODDI32: 1 file(s) copied

EPT2020AD13_SBS_NODDI32] copying:   0%|                                                     | 0/1 [00:00<?, ?file/s]
[MREPT2020AD13_SBS_NODDI32] copying: 100%|█████████████████████████████████████████████| 1/1 [00:01<00:00,  1.73s/file]
Processing folders:  74%|█████████████████████████████████████████▍              | 251/339 [08:16<02:50,  1.93s/folder]

[OK] MREPT2020AD13_SBS_NODDI32: 1 file(s) copied

EPT2020AD14_CIL_NODDI32] copying:   0%|                                                     | 0/1 [00:00<?, ?file/s]
[MREPT2020AD14_CIL_NODDI32] copying: 100%|█████████████████████████████████████████████| 1/1 [00:02<00:00,  2.00s/file]
Processing folders:  74%|█████████████████████████████████████████▍              | 251/339 [08:18<02:50,  1.93s/folder]

[OK] MREPT2020AD14_CIL_NODDI32: 1 file(s) copied

EPT2020AD15_LHS_NODDI32] copying:   0%|                                                     | 0/1 [00:00<?, ?file/s]
[MREPT2020AD15_LHS_NODDI32] copying: 100%|█████████████████████████████████████████████| 1/1 [00:02<00:00,  2.16s/file]
Processing folders:  75%|█████████████████████████████████████████▊              | 253/339 [08:20<02:49,  1.97s/folder]

[OK] MREPT2020AD15_LHS_NODDI32: 1 file(s) copied
[REN] MREPT2020AD16_CKL_NODDI32 -> x_MREPT2020AD16_CKL_NODDI32 (no matching .nii)
[REN] MREPT2020AD17_LSH_NODDI32 -> x_MREPT2020AD17_LSH_NODDI32 (no matching .nii)

EPT2020AD18_YHS_NODDI32] copying:   0%|                                                     | 0/1 [00:00<?, ?file/s]
[MREPT2020AD18_YHS_NODDI32] copying: 100%|█████████████████████████████████████████████| 1/1 [00:02<00:00,  2.76s/file]
Processing folders:  76%|██████████████████████████████████████████▎             | 256/339 [08:23<02:15,  1.64s/folder]

[OK] MREPT2020AD18_YHS_NODDI32: 1 file(s) copied

EPT2020AD19_PKS_NODDI32] copying:   0%|                                                     | 0/1 [00:00<?, ?file/s]
[MREPT2020AD19_PKS_NODDI32] copying: 100%|█████████████████████████████████████████████| 1/1 [00:01<00:00,  1.64s/file]
Processing folders:  76%|██████████████████████████████████████████▍             | 257/339 [08:24<02:14,  1.64s/folder]

[OK] MREPT2020AD19_PKS_NODDI32: 1 file(s) copied

EPT2020AD20_LSK_NODDI32] copying:   0%|                                                     | 0/1 [00:00<?, ?file/s]
[MREPT2020AD20_LSK_NODDI32] copying: 100%|█████████████████████████████████████████████| 1/1 [00:02<00:00,  2.49s/file]
Processing folders:  76%|██████████████████████████████████████████▌             | 258/339 [08:27<02:23,  1.77s/folder]

[OK] MREPT2020AD20_LSK_NODDI32: 1 file(s) copied
[REN] MREPT2020AD21_CBS_NODDI32 -> x_MREPT2020AD21_CBS_NODDI32 (no matching .nii)

EPT2020AD22_KYH_NODDI32] copying:   0%|                                                     | 0/1 [00:00<?, ?file/s]
[MREPT2020AD22_KYH_NODDI32] copying: 100%|█████████████████████████████████████████████| 1/1 [00:03<00:00,  3.71s/file]
Processing folders:  77%|██████████████████████████████████████████▉             | 260/339 [08:30<02:22,  1.80s/folder]

[OK] MREPT2020AD22_KYH_NODDI32: 1 file(s) copied

EPT2020AD23_LSH_NODDI32] copying:   0%|                                                     | 0/1 [00:00<?, ?file/s]
[MREPT2020AD23_LSH_NODDI32] copying: 100%|█████████████████████████████████████████████| 1/1 [00:04<00:00,  4.77s/file]
Processing folders:  77%|███████████████████████████████████████████             | 261/339 [08:35<03:02,  2.34s/folder]

[OK] MREPT2020AD23_LSH_NODDI32: 1 file(s) copied

EPT2020AD24_YYS_NODDI32] copying:   0%|                                                     | 0/1 [00:00<?, ?file/s]
[MREPT2020AD24_YYS_NODDI32] copying: 100%|█████████████████████████████████████████████| 1/1 [00:01<00:00,  1.75s/file]
Processing folders:  77%|███████████████████████████████████████████▎            | 262/339 [08:37<02:51,  2.22s/folder]

[OK] MREPT2020AD24_YYS_NODDI32: 1 file(s) copied

EPT2020AD25_YSJ_NODDI32] copying:   0%|                                                     | 0/1 [00:00<?, ?file/s]
[MREPT2020AD25_YSJ_NODDI32] copying: 100%|█████████████████████████████████████████████| 1/1 [00:01<00:00,  1.89s/file]
Processing folders:  78%|███████████████████████████████████████████▍            | 263/339 [08:39<02:43,  2.15s/folder]

[OK] MREPT2020AD25_YSJ_NODDI32: 1 file(s) copied

EPT2020AD26_HMH_NODDI32] copying:   0%|                                                     | 0/1 [00:00<?, ?file/s]
[MREPT2020AD26_HMH_NODDI32] copying: 100%|█████████████████████████████████████████████| 1/1 [00:01<00:00,  1.52s/file]
Processing folders:  78%|███████████████████████████████████████████▌            | 264/339 [08:40<02:29,  2.00s/folder]

[OK] MREPT2020AD26_HMH_NODDI32: 1 file(s) copied

EPT2020AD27_YJJ_NODDI32] copying:   0%|                                                     | 0/1 [00:00<?, ?file/s]
[MREPT2020AD27_YJJ_NODDI32] copying: 100%|█████████████████████████████████████████████| 1/1 [00:02<00:00,  2.24s/file]
Processing folders:  78%|███████████████████████████████████████████▊            | 265/339 [08:43<02:32,  2.06s/folder]

[OK] MREPT2020AD27_YJJ_NODDI32: 1 file(s) copied

EPT2020AD28_YYL_NODDI32] copying:   0%|                                                     | 0/1 [00:00<?, ?file/s]
[MREPT2020AD28_YYL_NODDI32] copying: 100%|█████████████████████████████████████████████| 1/1 [00:01<00:00,  1.90s/file]
Processing folders:  78%|███████████████████████████████████████████▉            | 266/339 [08:45<02:27,  2.02s/folder]

[OK] MREPT2020AD28_YYL_NODDI32: 1 file(s) copied

I_CN01_KNH_NODDI32] copying:   0%|                                                          | 0/1 [00:00<?, ?file/s]
[MWI_CN01_KNH_NODDI32] copying: 100%|██████████████████████████████████████████████████| 1/1 [00:05<00:00,  5.89s/file]
Processing folders:  79%|████████████████████████████████████████████            | 267/339 [08:50<03:43,  3.10s/folder]

[OK] MWI_CN01_KNH_NODDI32: 1 file(s) copied

I_CN04_SSS_NODDI32] copying:   0%|                                                          | 0/1 [00:00<?, ?file/s]
[MWI_CN04_SSS_NODDI32] copying: 100%|██████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.62s/file]
Processing folders:  79%|████████████████████████████████████████████▎           | 268/339 [08:53<03:30,  2.97s/folder]

[OK] MWI_CN04_SSS_NODDI32: 1 file(s) copied

I_CN05_LSS_NODDI32] copying:   0%|                                                          | 0/1 [00:00<?, ?file/s]
[MWI_CN05_LSS_NODDI32] copying: 100%|██████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.77s/file]
Processing folders:  79%|████████████████████████████████████████████▍           | 269/339 [08:55<03:03,  2.62s/folder]

[OK] MWI_CN05_LSS_NODDI32: 1 file(s) copied

I_CN06_KDS_NODDI32] copying:   0%|                                                          | 0/1 [00:00<?, ?file/s]
[MWI_CN06_KDS_NODDI32] copying: 100%|██████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.59s/file]
Processing folders:  80%|████████████████████████████████████████████▌           | 270/339 [08:56<02:40,  2.32s/folder]

[OK] MWI_CN06_KDS_NODDI32: 1 file(s) copied

I_CN07_KSB_NODDI32] copying:   0%|                                                          | 0/1 [00:00<?, ?file/s]
[MWI_CN07_KSB_NODDI32] copying: 100%|██████████████████████████████████████████████████| 1/1 [00:03<00:00,  3.00s/file]
Processing folders:  80%|████████████████████████████████████████████▊           | 271/339 [08:59<02:51,  2.52s/folder]

[OK] MWI_CN07_KSB_NODDI32: 1 file(s) copied

I_CN09_YKJ_NODDI32] copying:   0%|                                                          | 0/1 [00:00<?, ?file/s]
[MWI_CN09_YKJ_NODDI32] copying: 100%|██████████████████████████████████████████████████| 1/1 [00:04<00:00,  4.65s/file]
Processing folders:  80%|████████████████████████████████████████████▉           | 272/339 [09:04<03:31,  3.16s/folder]

[OK] MWI_CN09_YKJ_NODDI32: 1 file(s) copied

I_CN10_CJS_NODDI32] copying:   0%|                                                          | 0/1 [00:00<?, ?file/s]
[MWI_CN10_CJS_NODDI32] copying: 100%|██████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.98s/file]
Processing folders:  81%|█████████████████████████████████████████████           | 273/339 [09:06<03:05,  2.81s/folder]

[OK] MWI_CN10_CJS_NODDI32: 1 file(s) copied

I_CN12_LJK_NODDI32] copying:   0%|                                                          | 0/1 [00:00<?, ?file/s]
[MWI_CN12_LJK_NODDI32] copying: 100%|██████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.77s/file]
Processing folders:  81%|█████████████████████████████████████████████▎          | 274/339 [09:08<02:42,  2.50s/folder]

[OK] MWI_CN12_LJK_NODDI32: 1 file(s) copied

I_CN13_KH_NODDI32] copying:   0%|                                                           | 0/1 [00:00<?, ?file/s]
[MWI_CN13_KH_NODDI32] copying: 100%|███████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.47s/file]
Processing folders:  81%|█████████████████████████████████████████████▍          | 275/339 [09:09<02:20,  2.20s/folder]

[OK] MWI_CN13_KH_NODDI32: 1 file(s) copied

I_CN14_PYJ_NODDI32] copying:   0%|                                                          | 0/1 [00:00<?, ?file/s]
[MWI_CN14_PYJ_NODDI32] copying: 100%|██████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.78s/file]
Processing folders:  81%|█████████████████████████████████████████████▌          | 276/339 [09:12<02:29,  2.37s/folder]

[OK] MWI_CN14_PYJ_NODDI32: 1 file(s) copied

I_CN15_YCJ_NODDI32] copying:   0%|                                                          | 0/1 [00:00<?, ?file/s]
[MWI_CN15_YCJ_NODDI32] copying: 100%|██████████████████████████████████████████████████| 1/1 [00:04<00:00,  4.55s/file]
Processing folders:  82%|█████████████████████████████████████████████▊          | 277/339 [09:17<03:07,  3.03s/folder]

[OK] MWI_CN15_YCJ_NODDI32: 1 file(s) copied

I_CN16_LCS_NODDI32] copying:   0%|                                                          | 0/1 [00:00<?, ?file/s]
[MWI_CN16_LCS_NODDI32] copying: 100%|██████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.02s/file]
Processing folders:  82%|█████████████████████████████████████████████▉          | 278/339 [09:18<02:28,  2.43s/folder]

[OK] MWI_CN16_LCS_NODDI32: 1 file(s) copied

I_CN17_LPS_NODDI32] copying:   0%|                                                          | 0/1 [00:00<?, ?file/s]
[MWI_CN17_LPS_NODDI32] copying: 100%|██████████████████████████████████████████████████| 1/1 [00:04<00:00,  4.86s/file]
Processing folders:  82%|██████████████████████████████████████████████          | 279/339 [09:23<03:09,  3.16s/folder]

[OK] MWI_CN17_LPS_NODDI32: 1 file(s) copied

I_CN18_HCS_NODDI32] copying:   0%|                                                          | 0/1 [00:00<?, ?file/s]
[MWI_CN18_HCS_NODDI32] copying: 100%|██████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.28s/file]
Processing folders:  83%|██████████████████████████████████████████████▎         | 280/339 [09:24<02:33,  2.60s/folder]

[OK] MWI_CN18_HCS_NODDI32: 1 file(s) copied

I_CN19_CSO_NODDI32] copying:   0%|                                                          | 0/1 [00:00<?, ?file/s]
[MWI_CN19_CSO_NODDI32] copying: 100%|██████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.18s/file]
Processing folders:  83%|██████████████████████████████████████████████▍         | 281/339 [09:26<02:23,  2.48s/folder]

[OK] MWI_CN19_CSO_NODDI32: 1 file(s) copied

I_CN20_PYJ_NODDI32] copying:   0%|                                                          | 0/1 [00:00<?, ?file/s]
[MWI_CN20_PYJ_NODDI32] copying: 100%|██████████████████████████████████████████████████| 1/1 [00:03<00:00,  3.57s/file]
Processing folders:  83%|██████████████████████████████████████████████▌         | 282/339 [09:30<02:40,  2.81s/folder]

[OK] MWI_CN20_PYJ_NODDI32: 1 file(s) copied

I_CN21_PYB_NODDI32] copying:   0%|                                                          | 0/1 [00:00<?, ?file/s]
[MWI_CN21_PYB_NODDI32] copying: 100%|██████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.64s/file]
Processing folders:  83%|██████████████████████████████████████████████▋         | 283/339 [09:32<02:34,  2.76s/folder]

[OK] MWI_CN21_PYB_NODDI32: 1 file(s) copied

I_CN22_YYJ_NODDI32] copying:   0%|                                                          | 0/1 [00:00<?, ?file/s]
[MWI_CN22_YYJ_NODDI32] copying: 100%|██████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.07s/file]
Processing folders:  84%|██████████████████████████████████████████████▉         | 284/339 [09:34<02:20,  2.55s/folder]

[OK] MWI_CN22_YYJ_NODDI32: 1 file(s) copied

I_CN23_HJL_NODDI32] copying:   0%|                                                          | 0/1 [00:00<?, ?file/s]
[MWI_CN23_HJL_NODDI32] copying: 100%|██████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.10s/file]
Processing folders:  84%|███████████████████████████████████████████████         | 285/339 [09:37<02:10,  2.42s/folder]

[OK] MWI_CN23_HJL_NODDI32: 1 file(s) copied

I_CN24_PKJ_NODDI32] copying:   0%|                                                          | 0/1 [00:00<?, ?file/s]
[MWI_CN24_PKJ_NODDI32] copying: 100%|██████████████████████████████████████████████████| 1/1 [00:03<00:00,  3.39s/file]
Processing folders:  84%|███████████████████████████████████████████████▏        | 286/339 [09:40<02:23,  2.71s/folder]

[OK] MWI_CN24_PKJ_NODDI32: 1 file(s) copied

I_CN25_NKJ_NODDI32] copying:   0%|                                                          | 0/1 [00:00<?, ?file/s]
[MWI_CN25_NKJ_NODDI32] copying: 100%|██████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.80s/file]
Processing folders:  85%|███████████████████████████████████████████████▍        | 287/339 [09:43<02:22,  2.74s/folder]

[OK] MWI_CN25_NKJ_NODDI32: 1 file(s) copied

I_CN26_LSR_NODDI32] copying:   0%|                                                          | 0/1 [00:00<?, ?file/s]
[MWI_CN26_LSR_NODDI32] copying: 100%|██████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.39s/file]
Processing folders:  85%|███████████████████████████████████████████████▌        | 288/339 [09:45<02:14,  2.64s/folder]

[OK] MWI_CN26_LSR_NODDI32: 1 file(s) copied

I_CN27_LSJ_NODDI32] copying:   0%|                                                          | 0/1 [00:00<?, ?file/s]
[MWI_CN27_LSJ_NODDI32] copying: 100%|██████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.67s/file]
Processing folders:  85%|███████████████████████████████████████████████▋        | 289/339 [09:48<02:12,  2.65s/folder]

[OK] MWI_CN27_LSJ_NODDI32: 1 file(s) copied

I_CN28_KOS_NODDI32] copying:   0%|                                                          | 0/1 [00:00<?, ?file/s]
[MWI_CN28_KOS_NODDI32] copying: 100%|██████████████████████████████████████████████████| 1/1 [00:04<00:00,  4.08s/file]
Processing folders:  86%|███████████████████████████████████████████████▉        | 290/339 [09:52<02:30,  3.08s/folder]

[OK] MWI_CN28_KOS_NODDI32: 1 file(s) copied

I_CN29_KSH_NODDI32] copying:   0%|                                                          | 0/1 [00:00<?, ?file/s]
[MWI_CN29_KSH_NODDI32] copying: 100%|██████████████████████████████████████████████████| 1/1 [00:03<00:00,  3.31s/file]
Processing folders:  86%|████████████████████████████████████████████████        | 291/339 [09:55<02:31,  3.15s/folder]

[OK] MWI_CN29_KSH_NODDI32: 1 file(s) copied

I_CN30_PYS_NODDI32] copying:   0%|                                                          | 0/1 [00:00<?, ?file/s]
[MWI_CN30_PYS_NODDI32] copying: 100%|██████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.33s/file]
Processing folders:  86%|████████████████████████████████████████████████▏       | 292/339 [09:57<02:02,  2.61s/folder]

[OK] MWI_CN30_PYS_NODDI32: 1 file(s) copied

I_CN31_LOH_NODDI32] copying:   0%|                                                          | 0/1 [00:00<?, ?file/s]
[MWI_CN31_LOH_NODDI32] copying: 100%|██████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.43s/file]
Processing folders:  86%|████████████████████████████████████████████████▍       | 293/339 [09:59<01:57,  2.56s/folder]

[OK] MWI_CN31_LOH_NODDI32: 1 file(s) copied

I_CN32_KYH_NODDI32] copying:   0%|                                                          | 0/1 [00:00<?, ?file/s]
[MWI_CN32_KYH_NODDI32] copying: 100%|██████████████████████████████████████████████████| 1/1 [00:04<00:00,  4.85s/file]
Processing folders:  87%|████████████████████████████████████████████████▌       | 294/339 [10:04<02:26,  3.25s/folder]

[OK] MWI_CN32_KYH_NODDI32: 1 file(s) copied

I_CN33_LSH_NODDI32] copying:   0%|                                                          | 0/1 [00:00<?, ?file/s]
[MWI_CN33_LSH_NODDI32] copying: 100%|██████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.54s/file]
Processing folders:  87%|████████████████████████████████████████████████▋       | 295/339 [10:06<02:13,  3.04s/folder]

[OK] MWI_CN33_LSH_NODDI32: 1 file(s) copied

I_CN34_OJS_NODDI32] copying:   0%|                                                          | 0/1 [00:00<?, ?file/s]
[MWI_CN34_OJS_NODDI32] copying: 100%|██████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.26s/file]
Processing folders:  87%|████████████████████████████████████████████████▉       | 296/339 [10:08<01:47,  2.51s/folder]

[OK] MWI_CN34_OJS_NODDI32: 1 file(s) copied

I_CN35_LES_NODDI32] copying:   0%|                                                          | 0/1 [00:00<?, ?file/s]
[MWI_CN35_LES_NODDI32] copying: 100%|██████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.99s/file]
Processing folders:  88%|█████████████████████████████████████████████████       | 297/339 [10:10<01:38,  2.35s/folder]

[OK] MWI_CN35_LES_NODDI32: 1 file(s) copied

I_CN36_KER_NODDI32] copying:   0%|                                                          | 0/1 [00:00<?, ?file/s]
[MWI_CN36_KER_NODDI32] copying: 100%|██████████████████████████████████████████████████| 1/1 [00:04<00:00,  4.36s/file]
Processing folders:  88%|█████████████████████████████████████████████████▏      | 298/339 [10:14<02:01,  2.96s/folder]

[OK] MWI_CN36_KER_NODDI32: 1 file(s) copied

I_CN37_KJR_NODDI32] copying:   0%|                                                          | 0/1 [00:00<?, ?file/s]
[MWI_CN37_KJR_NODDI32] copying: 100%|██████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.19s/file]
Processing folders:  88%|█████████████████████████████████████████████████▍      | 299/339 [10:15<01:37,  2.43s/folder]

[OK] MWI_CN37_KJR_NODDI32: 1 file(s) copied

I_CN38_JJB_NODDI32] copying:   0%|                                                          | 0/1 [00:00<?, ?file/s]
[MWI_CN38_JJB_NODDI32] copying: 100%|██████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.34s/file]
Processing folders:  88%|█████████████████████████████████████████████████▌      | 300/339 [10:17<01:22,  2.11s/folder]

[OK] MWI_CN38_JJB_NODDI32: 1 file(s) copied

I_CN39_LTS_NODDI32] copying:   0%|                                                          | 0/1 [00:00<?, ?file/s]
[MWI_CN39_LTS_NODDI32] copying: 100%|██████████████████████████████████████████████████| 1/1 [00:04<00:00,  4.08s/file]
Processing folders:  89%|█████████████████████████████████████████████████▋      | 301/339 [10:21<01:42,  2.70s/folder]

[OK] MWI_CN39_LTS_NODDI32: 1 file(s) copied

I_CN40_LDS_NODDI32] copying:   0%|                                                          | 0/1 [00:00<?, ?file/s]
[MWI_CN40_LDS_NODDI32] copying: 100%|██████████████████████████████████████████████████| 1/1 [00:03<00:00,  3.51s/file]
Processing folders:  89%|█████████████████████████████████████████████████▉      | 302/339 [10:24<01:49,  2.95s/folder]

[OK] MWI_CN40_LDS_NODDI32: 1 file(s) copied

I_CN41_JHL_NODDI32] copying:   0%|                                                          | 0/1 [00:00<?, ?file/s]
[MWI_CN41_JHL_NODDI32] copying: 100%|██████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.84s/file]
Processing folders:  89%|██████████████████████████████████████████████████      | 303/339 [10:27<01:45,  2.92s/folder]

[OK] MWI_CN41_JHL_NODDI32: 1 file(s) copied
[REN] MWI_CN42_KKD_DKI -> x_MWI_CN42_KKD_DKI (no matching .nii)
[REN] MWI_CN43_LSL_DKI -> x_MWI_CN43_LSL_DKI (no matching .nii)
[REN] MWI_CN44_OKS_DKI -> x_MWI_CN44_OKS_DKI (no matching .nii)
[REN] MWI_CN45_KTJ_DKI -> x_MWI_CN45_KTJ_DKI (no matching .nii)
[REN] MWI_CN46_KCS_DKI -> x_MWI_CN46_KCS_DKI (no matching .nii)
[REN] MWI_CN47_YKS_DKI -> x_MWI_CN47_YKS_DKI (no matching .nii)
[REN] MWI_CN48_WHJ_DKI -> x_MWI_CN48_WHJ_DKI (no matching .nii)
[REN] MWI_CN49_CBW_DKI -> x_MWI_CN49_CBW_DKI (no matching .nii)
[REN] MWI_CN50_PMJ_DKI -> x_MWI_CN50_PMJ_DKI (no matching .nii)
[REN] MWI_CN51_POS_DKI -> x_MWI_CN51_POS_DKI (no matching .nii)
[REN] MWI_CN52_SJS_DKI -> x_MWI_CN52_SJS_DKI (no matching .nii)
[REN] MWI_CN53_YMS_DKI -> x_MWI_CN53_YMS_DKI (no matching .nii)
[REN] MWI_CN54_KHS_DKI -> x_MWI_CN54_KHS_DKI (no matching .nii)
[REN] MWI_CN55_JMS_DKI -> x_MWI_CN55_JMS_DKI (no matching .nii)
[REN] MWI_CN56_KYO_DKI -> x_MWI_CN56_KYO_DKI (no matching .nii)

I_CN57_YHY_NODDI32] copying:   0%|                                                          | 0/1 [00:00<?, ?file/s]
[MWI_CN57_YHY_NODDI32] copying: 100%|██████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.82s/file]
Processing folders:  94%|████████████████████████████████████████████████████▋   | 319/339 [10:29<00:09,  2.11folder/s]

[OK] MWI_CN57_YHY_NODDI32: 1 file(s) copied

I_CN58_LSB_NODDI32] copying:   0%|                                                          | 0/1 [00:00<?, ?file/s]
[MWI_CN58_LSB_NODDI32] copying: 100%|██████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.99s/file]
Processing folders:  94%|████████████████████████████████████████████████████▊   | 320/339 [10:31<00:11,  1.71folder/s]

[OK] MWI_CN58_LSB_NODDI32: 1 file(s) copied

I_CN61_CHS_NODDI32] copying:   0%|                                                          | 0/1 [00:00<?, ?file/s]
[MWI_CN61_CHS_NODDI32] copying: 100%|██████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.25s/file]
Processing folders:  95%|█████████████████████████████████████████████████████   | 321/339 [10:33<00:13,  1.35folder/s]

[OK] MWI_CN61_CHS_NODDI32: 1 file(s) copied

I_CN65_PYS_NODDI32] copying:   0%|                                                          | 0/1 [00:00<?, ?file/s]
[MWI_CN65_PYS_NODDI32] copying: 100%|██████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.64s/file]
Processing folders:  95%|█████████████████████████████████████████████████████▏  | 322/339 [10:35<00:14,  1.18folder/s]

[OK] MWI_CN65_PYS_NODDI32: 1 file(s) copied

I_CN66_CSY_NODDI32] copying:   0%|                                                          | 0/1 [00:00<?, ?file/s]
[MWI_CN66_CSY_NODDI32] copying: 100%|██████████████████████████████████████████████████| 1/1 [00:03<00:00,  3.49s/file]
Processing folders:  95%|█████████████████████████████████████████████████████▎  | 323/339 [10:38<00:19,  1.23s/folder]

[OK] MWI_CN66_CSY_NODDI32: 1 file(s) copied

I_CN67_KOS_NODDI32] copying:   0%|                                                          | 0/1 [00:00<?, ?file/s]
[MWI_CN67_KOS_NODDI32] copying: 100%|██████████████████████████████████████████████████| 1/1 [00:05<00:00,  5.19s/file]
Processing folders:  96%|█████████████████████████████████████████████████████▌  | 324/339 [10:43<00:28,  1.91s/folder]

[OK] MWI_CN67_KOS_NODDI32: 1 file(s) copied

I_CN68_CDL_NODDI32] copying:   0%|                                                          | 0/1 [00:00<?, ?file/s]
[MWI_CN68_CDL_NODDI32] copying: 100%|██████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.97s/file]
Processing folders:  96%|█████████████████████████████████████████████████████▋  | 325/339 [10:45<00:26,  1.92s/folder]

[OK] MWI_CN68_CDL_NODDI32: 1 file(s) copied

I_CN69_LSL_NODDI32] copying:   0%|                                                          | 0/1 [00:00<?, ?file/s]
[MWI_CN69_LSL_NODDI32] copying: 100%|██████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.83s/file]
Processing folders:  96%|█████████████████████████████████████████████████████▊  | 326/339 [10:47<00:24,  1.90s/folder]

[OK] MWI_CN69_LSL_NODDI32: 1 file(s) copied

I_CN70_LCJ_NODDI32] copying:   0%|                                                          | 0/1 [00:00<?, ?file/s]
[MWI_CN70_LCJ_NODDI32] copying: 100%|██████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.24s/file]
Processing folders:  96%|██████████████████████████████████████████████████████  | 327/339 [10:50<00:23,  1.99s/folder]

[OK] MWI_CN70_LCJ_NODDI32: 1 file(s) copied

I_CN71_LSH_NODDI32] copying:   0%|                                                          | 0/1 [00:00<?, ?file/s]
[MWI_CN71_LSH_NODDI32] copying: 100%|██████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.49s/file]
Processing folders:  97%|██████████████████████████████████████████████████████▏ | 328/339 [10:52<00:23,  2.12s/folder]

[OK] MWI_CN71_LSH_NODDI32: 1 file(s) copied

I_CN73_GIS_NODDI32] copying:   0%|                                                          | 0/1 [00:00<?, ?file/s]
[MWI_CN73_GIS_NODDI32] copying: 100%|██████████████████████████████████████████████████| 1/1 [00:03<00:00,  3.15s/file]
Processing folders:  97%|██████████████████████████████████████████████████████▎ | 329/339 [10:55<00:23,  2.40s/folder]

[OK] MWI_CN73_GIS_NODDI32: 1 file(s) copied

I_CN74_LKY_NODDI32] copying:   0%|                                                          | 0/1 [00:00<?, ?file/s]
[MWI_CN74_LKY_NODDI32] copying: 100%|██████████████████████████████████████████████████| 1/1 [00:05<00:00,  5.06s/file]
Processing folders:  97%|██████████████████████████████████████████████████████▌ | 330/339 [11:00<00:28,  3.13s/folder]

[OK] MWI_CN74_LKY_NODDI32: 1 file(s) copied

I_CN75_KKS_NODDI32] copying:   0%|                                                          | 0/1 [00:00<?, ?file/s]
[MWI_CN75_KKS_NODDI32] copying: 100%|██████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.48s/file]
Processing folders:  98%|██████████████████████████████████████████████████████▋ | 331/339 [11:02<00:21,  2.67s/folder]

[OK] MWI_CN75_KKS_NODDI32: 1 file(s) copied

I_CN76_PHJ_NODDI32] copying:   0%|                                                          | 0/1 [00:00<?, ?file/s]
[MWI_CN76_PHJ_NODDI32] copying: 100%|██████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.08s/file]
Processing folders:  98%|██████████████████████████████████████████████████████▊ | 332/339 [11:04<00:17,  2.50s/folder]

[OK] MWI_CN76_PHJ_NODDI32: 1 file(s) copied

I_CN77_PJC_NODDI32] copying:   0%|                                                          | 0/1 [00:00<?, ?file/s]
[MWI_CN77_PJC_NODDI32] copying: 100%|██████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.73s/file]
Processing folders:  98%|███████████████████████████████████████████████████████ | 333/339 [11:06<00:13,  2.28s/folder]

[OK] MWI_CN77_PJC_NODDI32: 1 file(s) copied

I_CN79_CYE_NODDI32] copying:   0%|                                                          | 0/1 [00:00<?, ?file/s]
[MWI_CN79_CYE_NODDI32] copying: 100%|██████████████████████████████████████████████████| 1/1 [00:03<00:00,  3.62s/file]
Processing folders:  99%|███████████████████████████████████████████████████████▏| 334/339 [11:09<00:13,  2.67s/folder]

[OK] MWI_CN79_CYE_NODDI32: 1 file(s) copied

I_CN80_LSR_NODDI32] copying:   0%|                                                          | 0/1 [00:00<?, ?file/s]
[MWI_CN80_LSR_NODDI32] copying: 100%|██████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.96s/file]
Processing folders:  99%|███████████████████████████████████████████████████████▎| 335/339 [11:12<00:11,  2.76s/folder]

[OK] MWI_CN80_LSR_NODDI32: 1 file(s) copied

I_CN81_CSH_NODDI32] copying:   0%|                                                          | 0/1 [00:00<?, ?file/s]
[MWI_CN81_CSH_NODDI32] copying: 100%|██████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.81s/file]
Processing folders:  99%|███████████████████████████████████████████████████████▌| 336/339 [11:14<00:07,  2.48s/folder]

[OK] MWI_CN81_CSH_NODDI32: 1 file(s) copied

I_CN82_LMR_NODDI32] copying:   0%|                                                          | 0/1 [00:00<?, ?file/s]
[MWI_CN82_LMR_NODDI32] copying: 100%|██████████████████████████████████████████████████| 1/1 [00:03<00:00,  3.18s/file]
Processing folders:  99%|███████████████████████████████████████████████████████▋| 337/339 [11:17<00:05,  2.69s/folder]

[OK] MWI_CN82_LMR_NODDI32: 1 file(s) copied

I_CN83_LYS_NODDI32] copying:   0%|                                                          | 0/1 [00:00<?, ?file/s]
[MWI_CN83_LYS_NODDI32] copying: 100%|██████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.87s/file]
Processing folders: 100%|███████████████████████████████████████████████████████▊| 338/339 [11:19<00:02,  2.45s/folder]

[OK] MWI_CN83_LYS_NODDI32: 1 file(s) copied

I_CN84_LHS_NODDI32] copying:   0%|                                                          | 0/1 [00:00<?, ?file/s]
[MWI_CN84_LHS_NODDI32] copying: 100%|██████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.28s/file]
Processing folders: 100%|████████████████████████████████████████████████████████| 339/339 [11:21<00:00,  2.01s/folder]

[OK] MWI_CN84_LHS_NODDI32: 1 file(s) copied

In [3]:
cti_root = os.path.join(base, "CTI_ALPS")

# === 대상 경로 블록 정의 ===
blocks = [
    # [1]
    (os.path.join(base, r"1_8641_CN_MCI"),
     lambda n: (n == "Bin") or n.startswith("x_"), "[1]"),
    # [2]
    (os.path.join(base, r"2_Dementia", r"DKI"),
     lambda n: (n == "Bin"), "[2]"),
    # [3]
    (os.path.join(base, r"2_Dementia", r"EPT2019", r"prep"),
     None, "[3]"),
    # [4]
    (os.path.join(base, r"2_Dementia", r"EPT2020"),
     lambda n: n.startswith("xEPI-"), "[4]"),
    # [5]
    (os.path.join(base, r"2_Dementia", r"EPT2021"),
     None, "[5]"),
    # [6]
    (os.path.join(base, r"2_Dementia", r"EPT2022"),
     None, "[6]"),
    # [7]
    (os.path.join(base, r"2_Dementia", r"EPT2023"),
     lambda n: n.startswith("xEPI-"), "[7]"),
    # [8]
    (os.path.join(base, r"2_Dementia", r"EPT2024"),
     None, "[8]"),
    # [9]
    (os.path.join(base, r"8641_DKI"),
     None, "[9]"),
]

In [ ]:
OVERWRITE = True   # True면 같은 파일명은 덮어씀, False면 이미 있으면 건너뜀
DRY_RUN   = False  # True면 실제 복사/생성 안 하고 로그만

def list_dirs(path):
    try:
        for n in os.listdir(path):
            p = os.path.join(path, n)
            if os.path.isdir(p):
                yield n
    except FileNotFoundError:
        return

def find_match(name):
    """블록 우선순위([1]→[9])대로 동명 폴더를 찾아 경로 반환(필터 제외 적용). 없으면 None."""
    for root, exclude, _note in blocks:
        if not os.path.isdir(root):
            continue
        if exclude and exclude(name):
            continue
        cand = os.path.join(root, name)
        if os.path.isdir(cand):
            return cand, _note
    return None, None

def ensure_dir(p):
    if DRY_RUN: return
    os.makedirs(p, exist_ok=True)

def copytree_merge(src_dir, dst_dir, pbar=None):
    """src_dir 내용을 dst_dir로 병합 복사."""
    for root, dirs, files in os.walk(src_dir):
        rel = os.path.relpath(root, src_dir)
        target_root = dst_dir if rel == "." else os.path.join(dst_dir, rel)
        if not DRY_RUN:
            os.makedirs(target_root, exist_ok=True)
        for f in files:
            src_f = os.path.join(root, f)
            dst_f = os.path.join(target_root, f)
            if os.path.exists(dst_f) and not OVERWRITE:
                if pbar: pbar.write(f"[SKIP] {os.path.relpath(dst_f, dst_dir)} (exists)")
                continue
            if not DRY_RUN:
                shutil.copy2(src_f, dst_f)
            if pbar: pbar.update(1)

def count_files(src_dir):
    total = 0
    for _, _, files in os.walk(src_dir):
        total += len(files)
    return total

def main():
    if not os.path.isdir(cti_root):
        print(f"[ERR] CTI root not found: {cti_root}")
        return

    cti_names = [d for d in os.listdir(cti_root)
                 if os.path.isdir(os.path.join(cti_root, d))]
    cti_names.sort()

    outer = tqdm(cti_names, desc="CTI_ALPS folders", unit="folder")
    for name in outer:
        if name.startswith("x_"):
            outer.write(f"[SKIP] {name}: prefixed x_")
            continue

        cti_src = os.path.join(cti_root, name, "Results", "CTI")
        if not os.path.isdir(cti_src):
            outer.write(f"[MISS] {name}: CTI source missing → {cti_src}")
            continue

        dest_person, note = find_match(name)
        if not dest_person:
            outer.write(f"[NOMATCH] {name}: no matching person in target blocks")
            continue

        results_dir = os.path.join(dest_person, "Results")
        dest_cti    = os.path.join(results_dir, "CTI")
        ensure_dir(results_dir)
        ensure_dir(dest_cti)

        # 파일 개수 세고 tqdm 바
        n_files = count_files(cti_src)
        if n_files == 0:
            outer.write(f"[EMPTY] {name}: CTI has no files")
            continue

        desc = f"[{note} {name}] → Results\\CTI"
        with tqdm(total=n_files, desc=desc, unit="file", leave=False) as pbar:
            copytree_merge(cti_src, dest_cti, pbar=pbar)

        outer.write(f"[OK] {name}: copied {n_files} file(s) to {dest_cti}")

if __name__ == "__main__":
    main()

CTI_ALPS folders:   0%|                                                                    | 0/262 [00:00<?, ?folder/s]
] ADEPT01_YSJ_NODDI24] → Results\CTI:   0%|                                                 | 0/4 [00:00<?, ?file/s]
] ADEPT01_YSJ_NODDI24] → Results\CTI:  25%|██████████▎                              | 1/4 [00:01<00:03,  1.01s/file]
] ADEPT01_YSJ_NODDI24] → Results\CTI:  50%|████████████████████▌                    | 2/4 [00:01<00:01,  1.47file/s]
] ADEPT01_YSJ_NODDI24] → Results\CTI:  75%|██████████████████████████████▊          | 3/4 [00:01<00:00,  2.03file/s]
] ADEPT01_YSJ_NODDI24] → Results\CTI: 100%|█████████████████████████████████████████| 4/4 [00:02<00:00,  1.32file/s]
CTI_ALPS folders:   0%|▏                                                           | 1/262 [00:02<12:39,  2.91s/folder]

[OK] ADEPT01_YSJ_NODDI24: copied 4 file(s) to D:\JHAhn\8641_conductivity\DTI_ALPS\2_Dementia\EPT2019\prep\ADEPT01_YSJ_NODDI24\Results\CTI

] ADEPT02_LKY_NODDI24] → Results\CTI:   0%|                                                 | 0/1 [00:00<?, ?file/s]
] ADEPT02_LKY_NODDI24] → Results\CTI: 100%|█████████████████████████████████████████| 1/1 [00:01<00:00,  1.34s/file]
CTI_ALPS folders:   1%|▍                                                           | 2/262 [00:04<08:37,  1.99s/folder]

[OK] ADEPT02_LKY_NODDI24: copied 1 file(s) to D:\JHAhn\8641_conductivity\DTI_ALPS\2_Dementia\EPT2019\prep\ADEPT02_LKY_NODDI24\Results\CTI

] ADEPT03_YKJ_NODDI24] → Results\CTI:   0%|                                                 | 0/1 [00:00<?, ?file/s]
] ADEPT03_YKJ_NODDI24] → Results\CTI: 100%|█████████████████████████████████████████| 1/1 [00:01<00:00,  1.56s/file]
CTI_ALPS folders:   1%|▋                                                           | 3/262 [00:05<07:45,  1.80s/folder]

[OK] ADEPT03_YKJ_NODDI24: copied 1 file(s) to D:\JHAhn\8641_conductivity\DTI_ALPS\2_Dementia\EPT2019\prep\ADEPT03_YKJ_NODDI24\Results\CTI

] ADEPT04_JWS_NODDI24] → Results\CTI:   0%|                                                 | 0/1 [00:00<?, ?file/s]
] ADEPT04_JWS_NODDI24] → Results\CTI: 100%|█████████████████████████████████████████| 1/1 [00:03<00:00,  3.59s/file]
CTI_ALPS folders:   2%|▉                                                           | 4/262 [00:09<10:47,  2.51s/folder]

[OK] ADEPT04_JWS_NODDI24: copied 1 file(s) to D:\JHAhn\8641_conductivity\DTI_ALPS\2_Dementia\EPT2019\prep\ADEPT04_JWS_NODDI24\Results\CTI

] ADEPT05_CBK_NODDI24] → Results\CTI:   0%|                                                 | 0/1 [00:00<?, ?file/s]
] ADEPT05_CBK_NODDI24] → Results\CTI: 100%|█████████████████████████████████████████| 1/1 [00:04<00:00,  4.07s/file]
CTI_ALPS folders:   2%|█▏                                                          | 5/262 [00:13<13:11,  3.08s/folder]

[OK] ADEPT05_CBK_NODDI24: copied 1 file(s) to D:\JHAhn\8641_conductivity\DTI_ALPS\2_Dementia\EPT2019\prep\ADEPT05_CBK_NODDI24\Results\CTI

] ADEPT06_PHJ_NODDI24] → Results\CTI:   0%|                                                 | 0/1 [00:00<?, ?file/s]
] ADEPT06_PHJ_NODDI24] → Results\CTI: 100%|█████████████████████████████████████████| 1/1 [00:01<00:00,  1.30s/file]
CTI_ALPS folders:   2%|█▎                                                          | 6/262 [00:14<10:35,  2.48s/folder]

[OK] ADEPT06_PHJ_NODDI24: copied 1 file(s) to D:\JHAhn\8641_conductivity\DTI_ALPS\2_Dementia\EPT2019\prep\ADEPT06_PHJ_NODDI24\Results\CTI

] ADEPT07_JG_NODDI24] → Results\CTI:   0%|                                                  | 0/1 [00:00<?, ?file/s]
] ADEPT07_JG_NODDI24] → Results\CTI: 100%|██████████████████████████████████████████| 1/1 [00:01<00:00,  1.54s/file]
CTI_ALPS folders:   3%|█▌                                                          | 7/262 [00:16<09:15,  2.18s/folder]

[OK] ADEPT07_JG_NODDI24: copied 1 file(s) to D:\JHAhn\8641_conductivity\DTI_ALPS\2_Dementia\EPT2019\prep\ADEPT07_JG_NODDI24\Results\CTI

] ADEPT08_KMJ_NODDI24] → Results\CTI:   0%|                                                 | 0/1 [00:00<?, ?file/s]
] ADEPT08_KMJ_NODDI24] → Results\CTI: 100%|█████████████████████████████████████████| 1/1 [00:02<00:00,  2.97s/file]
CTI_ALPS folders:   3%|█▊                                                          | 8/262 [00:19<10:19,  2.44s/folder]

[OK] ADEPT08_KMJ_NODDI24: copied 1 file(s) to D:\JHAhn\8641_conductivity\DTI_ALPS\2_Dementia\EPT2019\prep\ADEPT08_KMJ_NODDI24\Results\CTI

] ADEPT09_JCJ_NODDI24] → Results\CTI:   0%|                                                 | 0/1 [00:00<?, ?file/s]
] ADEPT09_JCJ_NODDI24] → Results\CTI: 100%|█████████████████████████████████████████| 1/1 [00:05<00:00,  5.15s/file]
CTI_ALPS folders:   3%|██                                                          | 9/262 [00:24<13:53,  3.29s/folder]

[OK] ADEPT09_JCJ_NODDI24: copied 1 file(s) to D:\JHAhn\8641_conductivity\DTI_ALPS\2_Dementia\EPT2019\prep\ADEPT09_JCJ_NODDI24\Results\CTI

] ADEPT10_YPL_NODDI24] → Results\CTI:   0%|                                                 | 0/1 [00:00<?, ?file/s]
] ADEPT10_YPL_NODDI24] → Results\CTI: 100%|█████████████████████████████████████████| 1/1 [00:01<00:00,  1.45s/file]
CTI_ALPS folders:   4%|██▎                                                        | 10/262 [00:26<11:27,  2.73s/folder]

[OK] ADEPT10_YPL_NODDI24: copied 1 file(s) to D:\JHAhn\8641_conductivity\DTI_ALPS\2_Dementia\EPT2019\prep\ADEPT10_YPL_NODDI24\Results\CTI

] ADEPT16_LJS_NODDI24] → Results\CTI:   0%|                                                 | 0/1 [00:00<?, ?file/s]
] ADEPT16_LJS_NODDI24] → Results\CTI: 100%|█████████████████████████████████████████| 1/1 [00:01<00:00,  1.20s/file]
CTI_ALPS folders:   4%|██▍                                                        | 11/262 [00:27<09:27,  2.26s/folder]

[OK] ADEPT16_LJS_NODDI24: copied 1 file(s) to D:\JHAhn\8641_conductivity\DTI_ALPS\2_Dementia\EPT2019\prep\ADEPT16_LJS_NODDI24\Results\CTI

] ADEPT18_PST_NODDI24] → Results\CTI:   0%|                                                 | 0/1 [00:00<?, ?file/s]
] ADEPT18_PST_NODDI24] → Results\CTI: 100%|█████████████████████████████████████████| 1/1 [00:02<00:00,  2.01s/file]
CTI_ALPS folders:   5%|██▋                                                        | 12/262 [00:29<09:08,  2.19s/folder]

[OK] ADEPT18_PST_NODDI24: copied 1 file(s) to D:\JHAhn\8641_conductivity\DTI_ALPS\2_Dementia\EPT2019\prep\ADEPT18_PST_NODDI24\Results\CTI

] ADEPT21_CJM_NODDI24] → Results\CTI:   0%|                                                 | 0/1 [00:00<?, ?file/s]
] ADEPT21_CJM_NODDI24] → Results\CTI: 100%|█████████████████████████████████████████| 1/1 [00:02<00:00,  2.76s/file]
CTI_ALPS folders:   5%|██▉                                                        | 13/262 [00:32<09:49,  2.37s/folder]

[OK] ADEPT21_CJM_NODDI24: copied 1 file(s) to D:\JHAhn\8641_conductivity\DTI_ALPS\2_Dementia\EPT2019\prep\ADEPT21_CJM_NODDI24\Results\CTI

] ADEPT22_KBS_NODDI24] → Results\CTI:   0%|                                                 | 0/1 [00:00<?, ?file/s]
] ADEPT22_KBS_NODDI24] → Results\CTI: 100%|█████████████████████████████████████████| 1/1 [00:05<00:00,  5.77s/file]
CTI_ALPS folders:   5%|███▏                                                       | 14/262 [00:37<14:03,  3.40s/folder]

[OK] ADEPT22_KBS_NODDI24: copied 1 file(s) to D:\JHAhn\8641_conductivity\DTI_ALPS\2_Dementia\EPT2019\prep\ADEPT22_KBS_NODDI24\Results\CTI

] ADEPT23_PYS_NODDI24] → Results\CTI:   0%|                                                 | 0/1 [00:00<?, ?file/s]
] ADEPT23_PYS_NODDI24] → Results\CTI: 100%|█████████████████████████████████████████| 1/1 [00:02<00:00,  2.75s/file]
CTI_ALPS folders:   6%|███▍                                                       | 15/262 [00:40<13:13,  3.21s/folder]

[OK] ADEPT23_PYS_NODDI24: copied 1 file(s) to D:\JHAhn\8641_conductivity\DTI_ALPS\2_Dementia\EPT2019\prep\ADEPT23_PYS_NODDI24\Results\CTI

] ADEPT24_KJH_NODDI24] → Results\CTI:   0%|                                                 | 0/1 [00:00<?, ?file/s]
] ADEPT24_KJH_NODDI24] → Results\CTI: 100%|█████████████████████████████████████████| 1/1 [00:02<00:00,  2.07s/file]
CTI_ALPS folders:   6%|███▌                                                       | 16/262 [00:42<11:47,  2.88s/folder]

[OK] ADEPT24_KJH_NODDI24: copied 1 file(s) to D:\JHAhn\8641_conductivity\DTI_ALPS\2_Dementia\EPT2019\prep\ADEPT24_KJH_NODDI24\Results\CTI

] ADEPT25_JKR_NODDI24] → Results\CTI:   0%|                                                 | 0/1 [00:00<?, ?file/s]
] ADEPT25_JKR_NODDI24] → Results\CTI: 100%|█████████████████████████████████████████| 1/1 [00:02<00:00,  2.00s/file]
CTI_ALPS folders:   6%|███▊                                                       | 17/262 [00:44<10:41,  2.62s/folder]

[OK] ADEPT25_JKR_NODDI24: copied 1 file(s) to D:\JHAhn\8641_conductivity\DTI_ALPS\2_Dementia\EPT2019\prep\ADEPT25_JKR_NODDI24\Results\CTI

] ADEPT26_KYJ_NODDI24] → Results\CTI:   0%|                                                 | 0/1 [00:00<?, ?file/s]
] ADEPT26_KYJ_NODDI24] → Results\CTI: 100%|█████████████████████████████████████████| 1/1 [00:04<00:00,  4.97s/file]
CTI_ALPS folders:   7%|████                                                       | 18/262 [00:49<13:32,  3.33s/folder]

[OK] ADEPT26_KYJ_NODDI24: copied 1 file(s) to D:\JHAhn\8641_conductivity\DTI_ALPS\2_Dementia\EPT2019\prep\ADEPT26_KYJ_NODDI24\Results\CTI

] ADEPT27_KKS_NODDI24] → Results\CTI:   0%|                                                 | 0/1 [00:00<?, ?file/s]
] ADEPT27_KKS_NODDI24] → Results\CTI: 100%|█████████████████████████████████████████| 1/1 [00:01<00:00,  1.26s/file]
CTI_ALPS folders:   7%|████▎                                                      | 19/262 [00:50<10:59,  2.71s/folder]

[OK] ADEPT27_KKS_NODDI24: copied 1 file(s) to D:\JHAhn\8641_conductivity\DTI_ALPS\2_Dementia\EPT2019\prep\ADEPT27_KKS_NODDI24\Results\CTI

] ADEPT28_MSH_NODDI24] → Results\CTI:   0%|                                                 | 0/1 [00:00<?, ?file/s]
] ADEPT28_MSH_NODDI24] → Results\CTI: 100%|█████████████████████████████████████████| 1/1 [00:02<00:00,  2.27s/file]
CTI_ALPS folders:   8%|████▌                                                      | 20/262 [00:53<10:25,  2.58s/folder]

[OK] ADEPT28_MSH_NODDI24: copied 1 file(s) to D:\JHAhn\8641_conductivity\DTI_ALPS\2_Dementia\EPT2019\prep\ADEPT28_MSH_NODDI24\Results\CTI

] ADEPT29_LBS_NODDI24] → Results\CTI:   0%|                                                 | 0/1 [00:00<?, ?file/s]
] ADEPT29_LBS_NODDI24] → Results\CTI: 100%|█████████████████████████████████████████| 1/1 [00:01<00:00,  1.46s/file]
CTI_ALPS folders:   8%|████▋                                                      | 21/262 [00:54<09:03,  2.25s/folder]

[OK] ADEPT29_LBS_NODDI24: copied 1 file(s) to D:\JHAhn\8641_conductivity\DTI_ALPS\2_Dementia\EPT2019\prep\ADEPT29_LBS_NODDI24\Results\CTI

] ADEPT30_WJS_NODDI24] → Results\CTI:   0%|                                                 | 0/1 [00:00<?, ?file/s]
] ADEPT30_WJS_NODDI24] → Results\CTI: 100%|█████████████████████████████████████████| 1/1 [00:04<00:00,  4.72s/file]
CTI_ALPS folders:   8%|████▉                                                      | 22/262 [00:59<11:59,  3.00s/folder]

[OK] ADEPT30_WJS_NODDI24: copied 1 file(s) to D:\JHAhn\8641_conductivity\DTI_ALPS\2_Dementia\EPT2019\prep\ADEPT30_WJS_NODDI24\Results\CTI

] ADEPT31_PTL_NODDI24] → Results\CTI:   0%|                                                 | 0/1 [00:00<?, ?file/s]
] ADEPT31_PTL_NODDI24] → Results\CTI: 100%|█████████████████████████████████████████| 1/1 [00:03<00:00,  3.79s/file]
CTI_ALPS folders:   9%|█████▏                                                     | 23/262 [01:03<12:54,  3.24s/folder]

[OK] ADEPT31_PTL_NODDI24: copied 1 file(s) to D:\JHAhn\8641_conductivity\DTI_ALPS\2_Dementia\EPT2019\prep\ADEPT31_PTL_NODDI24\Results\CTI

] ADEPT32_KSW_NODDI24] → Results\CTI:   0%|                                                 | 0/1 [00:00<?, ?file/s]
] ADEPT32_KSW_NODDI24] → Results\CTI: 100%|█████████████████████████████████████████| 1/1 [00:01<00:00,  1.18s/file]
CTI_ALPS folders:   9%|█████▍                                                     | 24/262 [01:04<10:25,  2.63s/folder]

[OK] ADEPT32_KSW_NODDI24: copied 1 file(s) to D:\JHAhn\8641_conductivity\DTI_ALPS\2_Dementia\EPT2019\prep\ADEPT32_KSW_NODDI24\Results\CTI

] ADEPT33_YCY_NODDI24] → Results\CTI:   0%|                                                 | 0/1 [00:00<?, ?file/s]
] ADEPT33_YCY_NODDI24] → Results\CTI: 100%|█████████████████████████████████████████| 1/1 [00:02<00:00,  2.25s/file]
CTI_ALPS folders:  10%|█████▋                                                     | 25/262 [01:06<09:56,  2.52s/folder]

[OK] ADEPT33_YCY_NODDI24: copied 1 file(s) to D:\JHAhn\8641_conductivity\DTI_ALPS\2_Dementia\EPT2019\prep\ADEPT33_YCY_NODDI24\Results\CTI

] ADEPT34_PDY_NODDI24] → Results\CTI:   0%|                                                 | 0/1 [00:00<?, ?file/s]
] ADEPT34_PDY_NODDI24] → Results\CTI: 100%|█████████████████████████████████████████| 1/1 [00:03<00:00,  3.06s/file]
CTI_ALPS folders:  10%|█████▊                                                     | 26/262 [01:09<10:33,  2.68s/folder]

[OK] ADEPT34_PDY_NODDI24: copied 1 file(s) to D:\JHAhn\8641_conductivity\DTI_ALPS\2_Dementia\EPT2019\prep\ADEPT34_PDY_NODDI24\Results\CTI

] ADEPT36_JJS_NODDI24] → Results\CTI:   0%|                                                 | 0/1 [00:00<?, ?file/s]
] ADEPT36_JJS_NODDI24] → Results\CTI: 100%|█████████████████████████████████████████| 1/1 [00:03<00:00,  3.85s/file]
CTI_ALPS folders:  10%|██████                                                     | 27/262 [01:13<11:53,  3.04s/folder]

[OK] ADEPT36_JJS_NODDI24: copied 1 file(s) to D:\JHAhn\8641_conductivity\DTI_ALPS\2_Dementia\EPT2019\prep\ADEPT36_JJS_NODDI24\Results\CTI

] ADEPT37_KTY_NODDI24] → Results\CTI:   0%|                                                 | 0/1 [00:00<?, ?file/s]
] ADEPT37_KTY_NODDI24] → Results\CTI: 100%|█████████████████████████████████████████| 1/1 [00:02<00:00,  2.56s/file]
CTI_ALPS folders:  11%|██████▎                                                    | 28/262 [01:16<11:17,  2.90s/folder]

[OK] ADEPT37_KTY_NODDI24: copied 1 file(s) to D:\JHAhn\8641_conductivity\DTI_ALPS\2_Dementia\EPT2019\prep\ADEPT37_KTY_NODDI24\Results\CTI

] ADEPT38_KWW_NODDI24] → Results\CTI:   0%|                                                 | 0/1 [00:00<?, ?file/s]
] ADEPT38_KWW_NODDI24] → Results\CTI: 100%|█████████████████████████████████████████| 1/1 [00:01<00:00,  1.56s/file]
CTI_ALPS folders:  11%|██████▌                                                    | 29/262 [01:17<09:41,  2.50s/folder]

[OK] ADEPT38_KWW_NODDI24: copied 1 file(s) to D:\JHAhn\8641_conductivity\DTI_ALPS\2_Dementia\EPT2019\prep\ADEPT38_KWW_NODDI24\Results\CTI

] ADEPT39_KKS_NODDI24] → Results\CTI:   0%|                                                 | 0/1 [00:00<?, ?file/s]
] ADEPT39_KKS_NODDI24] → Results\CTI: 100%|█████████████████████████████████████████| 1/1 [00:02<00:00,  2.81s/file]
CTI_ALPS folders:  11%|██████▊                                                    | 30/262 [01:20<10:01,  2.59s/folder]

[OK] ADEPT39_KKS_NODDI24: copied 1 file(s) to D:\JHAhn\8641_conductivity\DTI_ALPS\2_Dementia\EPT2019\prep\ADEPT39_KKS_NODDI24\Results\CTI

] ADEPT40_JOS_NODDI24] → Results\CTI:   0%|                                                 | 0/1 [00:00<?, ?file/s]
] ADEPT40_JOS_NODDI24] → Results\CTI: 100%|█████████████████████████████████████████| 1/1 [00:03<00:00,  3.91s/file]
CTI_ALPS folders:  12%|██████▉                                                    | 31/262 [01:24<11:32,  3.00s/folder]

[OK] ADEPT40_JOS_NODDI24: copied 1 file(s) to D:\JHAhn\8641_conductivity\DTI_ALPS\2_Dementia\EPT2019\prep\ADEPT40_JOS_NODDI24\Results\CTI

] ADEPT41_YBO_NODDI24] → Results\CTI:   0%|                                                 | 0/1 [00:00<?, ?file/s]
] ADEPT41_YBO_NODDI24] → Results\CTI: 100%|█████████████████████████████████████████| 1/1 [00:01<00:00,  1.83s/file]
CTI_ALPS folders:  12%|███████▏                                                   | 32/262 [01:26<10:10,  2.65s/folder]

[OK] ADEPT41_YBO_NODDI24: copied 1 file(s) to D:\JHAhn\8641_conductivity\DTI_ALPS\2_Dementia\EPT2019\prep\ADEPT41_YBO_NODDI24\Results\CTI

] ADEPT42_PSJ_NODDI24] → Results\CTI:   0%|                                                 | 0/1 [00:00<?, ?file/s]
] ADEPT42_PSJ_NODDI24] → Results\CTI: 100%|█████████████████████████████████████████| 1/1 [00:01<00:00,  1.75s/file]
CTI_ALPS folders:  13%|███████▍                                                   | 33/262 [01:28<09:06,  2.39s/folder]

[OK] ADEPT42_PSJ_NODDI24: copied 1 file(s) to D:\JHAhn\8641_conductivity\DTI_ALPS\2_Dementia\EPT2019\prep\ADEPT42_PSJ_NODDI24\Results\CTI

] ADEPT43_SSY_NODDI24] → Results\CTI:   0%|                                                 | 0/1 [00:00<?, ?file/s]
] ADEPT43_SSY_NODDI24] → Results\CTI: 100%|█████████████████████████████████████████| 1/1 [00:01<00:00,  1.50s/file]
CTI_ALPS folders:  13%|███████▋                                                   | 34/262 [01:29<08:04,  2.13s/folder]

[OK] ADEPT43_SSY_NODDI24: copied 1 file(s) to D:\JHAhn\8641_conductivity\DTI_ALPS\2_Dementia\EPT2019\prep\ADEPT43_SSY_NODDI24\Results\CTI

] ADEPT44_WDS_NODDI24] → Results\CTI:   0%|                                                 | 0/1 [00:00<?, ?file/s]
] ADEPT44_WDS_NODDI24] → Results\CTI: 100%|█████████████████████████████████████████| 1/1 [00:02<00:00,  2.78s/file]
CTI_ALPS folders:  13%|███████▉                                                   | 35/262 [01:32<08:48,  2.33s/folder]

[OK] ADEPT44_WDS_NODDI24: copied 1 file(s) to D:\JHAhn\8641_conductivity\DTI_ALPS\2_Dementia\EPT2019\prep\ADEPT44_WDS_NODDI24\Results\CTI

] ADEPT45_KKJ_NODDI24] → Results\CTI:   0%|                                                 | 0/1 [00:00<?, ?file/s]
] ADEPT45_KKJ_NODDI24] → Results\CTI: 100%|█████████████████████████████████████████| 1/1 [00:05<00:00,  5.15s/file]
CTI_ALPS folders:  14%|████████                                                   | 36/262 [01:37<12:00,  3.19s/folder]

[OK] ADEPT45_KKJ_NODDI24: copied 1 file(s) to D:\JHAhn\8641_conductivity\DTI_ALPS\2_Dementia\EPT2019\prep\ADEPT45_KKJ_NODDI24\Results\CTI

] ADEPT46_LJB_NODDI24] → Results\CTI:   0%|                                                 | 0/1 [00:00<?, ?file/s]
] ADEPT46_LJB_NODDI24] → Results\CTI: 100%|█████████████████████████████████████████| 1/1 [00:03<00:00,  3.30s/file]
CTI_ALPS folders:  14%|████████▎                                                  | 37/262 [01:41<12:06,  3.23s/folder]

[OK] ADEPT46_LJB_NODDI24: copied 1 file(s) to D:\JHAhn\8641_conductivity\DTI_ALPS\2_Dementia\EPT2019\prep\ADEPT46_LJB_NODDI24\Results\CTI

] ADEPT47_SJH_NODDI24] → Results\CTI:   0%|                                                 | 0/1 [00:00<?, ?file/s]
] ADEPT47_SJH_NODDI24] → Results\CTI: 100%|█████████████████████████████████████████| 1/1 [00:02<00:00,  2.02s/file]
CTI_ALPS folders:  15%|████████▌                                                  | 38/262 [01:43<10:41,  2.87s/folder]

[OK] ADEPT47_SJH_NODDI24: copied 1 file(s) to D:\JHAhn\8641_conductivity\DTI_ALPS\2_Dementia\EPT2019\prep\ADEPT47_SJH_NODDI24\Results\CTI

] ADEPT48_CJK_NODDI24] → Results\CTI:   0%|                                                 | 0/1 [00:00<?, ?file/s]
] ADEPT48_CJK_NODDI24] → Results\CTI: 100%|█████████████████████████████████████████| 1/1 [00:02<00:00,  2.83s/file]
CTI_ALPS folders:  15%|████████▊                                                  | 39/262 [01:45<10:38,  2.86s/folder]

[OK] ADEPT48_CJK_NODDI24: copied 1 file(s) to D:\JHAhn\8641_conductivity\DTI_ALPS\2_Dementia\EPT2019\prep\ADEPT48_CJK_NODDI24\Results\CTI

] ADEPT49_LKJ_NODDI24] → Results\CTI:   0%|                                                 | 0/1 [00:00<?, ?file/s]
] ADEPT49_LKJ_NODDI24] → Results\CTI: 100%|█████████████████████████████████████████| 1/1 [00:01<00:00,  1.70s/file]
CTI_ALPS folders:  15%|█████████                                                  | 40/262 [01:47<09:19,  2.52s/folder]

[OK] ADEPT49_LKJ_NODDI24: copied 1 file(s) to D:\JHAhn\8641_conductivity\DTI_ALPS\2_Dementia\EPT2019\prep\ADEPT49_LKJ_NODDI24\Results\CTI

] ADEPT50_LJK_NODDI24] → Results\CTI:   0%|                                                 | 0/1 [00:00<?, ?file/s]
] ADEPT50_LJK_NODDI24] → Results\CTI: 100%|█████████████████████████████████████████| 1/1 [00:01<00:00,  1.62s/file]
CTI_ALPS folders:  16%|█████████▏                                                 | 41/262 [01:49<08:18,  2.26s/folder]

[OK] ADEPT50_LJK_NODDI24: copied 1 file(s) to D:\JHAhn\8641_conductivity\DTI_ALPS\2_Dementia\EPT2019\prep\ADEPT50_LJK_NODDI24\Results\CTI

] ADEPT51_HBH_NODDI24] → Results\CTI:   0%|                                                 | 0/1 [00:00<?, ?file/s]
] ADEPT51_HBH_NODDI24] → Results\CTI: 100%|█████████████████████████████████████████| 1/1 [00:02<00:00,  2.04s/file]
CTI_ALPS folders:  16%|█████████▍                                                 | 42/262 [01:51<08:03,  2.20s/folder]

[OK] ADEPT51_HBH_NODDI24: copied 1 file(s) to D:\JHAhn\8641_conductivity\DTI_ALPS\2_Dementia\EPT2019\prep\ADEPT51_HBH_NODDI24\Results\CTI

] ADEPT52_YCW_NODDI24] → Results\CTI:   0%|                                                 | 0/1 [00:00<?, ?file/s]
] ADEPT52_YCW_NODDI24] → Results\CTI: 100%|█████████████████████████████████████████| 1/1 [00:03<00:00,  3.15s/file]
CTI_ALPS folders:  16%|█████████▋                                                 | 43/262 [01:54<09:04,  2.48s/folder]

[OK] ADEPT52_YCW_NODDI24: copied 1 file(s) to D:\JHAhn\8641_conductivity\DTI_ALPS\2_Dementia\EPT2019\prep\ADEPT52_YCW_NODDI24\Results\CTI

] ADEPT53_PDL_NODDI24] → Results\CTI:   0%|                                                 | 0/1 [00:00<?, ?file/s]
] ADEPT53_PDL_NODDI24] → Results\CTI: 100%|█████████████████████████████████████████| 1/1 [00:05<00:00,  5.07s/file]
CTI_ALPS folders:  17%|█████████▉                                                 | 44/262 [01:59<11:51,  3.27s/folder]

[OK] ADEPT53_PDL_NODDI24: copied 1 file(s) to D:\JHAhn\8641_conductivity\DTI_ALPS\2_Dementia\EPT2019\prep\ADEPT53_PDL_NODDI24\Results\CTI

] ADEPT54_HCS_NODDI24] → Results\CTI:   0%|                                                 | 0/1 [00:00<?, ?file/s]
] ADEPT54_HCS_NODDI24] → Results\CTI: 100%|█████████████████████████████████████████| 1/1 [00:01<00:00,  1.27s/file]
CTI_ALPS folders:  17%|██████████▏                                                | 45/262 [02:00<09:39,  2.67s/folder]

[OK] ADEPT54_HCS_NODDI24: copied 1 file(s) to D:\JHAhn\8641_conductivity\DTI_ALPS\2_Dementia\EPT2019\prep\ADEPT54_HCS_NODDI24\Results\CTI

] ADEPT55_HJS_NODDI24] → Results\CTI:   0%|                                                 | 0/1 [00:00<?, ?file/s]
] ADEPT55_HJS_NODDI24] → Results\CTI: 100%|█████████████████████████████████████████| 1/1 [00:02<00:00,  2.09s/file]
CTI_ALPS folders:  18%|██████████▎                                                | 46/262 [02:02<09:00,  2.50s/folder]

[OK] ADEPT55_HJS_NODDI24: copied 1 file(s) to D:\JHAhn\8641_conductivity\DTI_ALPS\2_Dementia\EPT2019\prep\ADEPT55_HJS_NODDI24\Results\CTI

] ADEPT56_CKJ_NODDI24] → Results\CTI:   0%|                                                 | 0/1 [00:00<?, ?file/s]
] ADEPT56_CKJ_NODDI24] → Results\CTI: 100%|█████████████████████████████████████████| 1/1 [00:02<00:00,  2.15s/file]
CTI_ALPS folders:  18%|██████████▌                                                | 47/262 [02:05<08:36,  2.40s/folder]

[OK] ADEPT56_CKJ_NODDI24: copied 1 file(s) to D:\JHAhn\8641_conductivity\DTI_ALPS\2_Dementia\EPT2019\prep\ADEPT56_CKJ_NODDI24\Results\CTI

] ADEPT57_LHS_NODDI24] → Results\CTI:   0%|                                                 | 0/1 [00:00<?, ?file/s]
] ADEPT57_LHS_NODDI24] → Results\CTI: 100%|█████████████████████████████████████████| 1/1 [00:04<00:00,  4.35s/file]
CTI_ALPS folders:  18%|██████████▊                                                | 48/262 [02:09<10:39,  2.99s/folder]

[OK] ADEPT57_LHS_NODDI24: copied 1 file(s) to D:\JHAhn\8641_conductivity\DTI_ALPS\2_Dementia\EPT2019\prep\ADEPT57_LHS_NODDI24\Results\CTI

] ADEPT58_PJR_NODDI24] → Results\CTI:   0%|                                                 | 0/1 [00:00<?, ?file/s]
] ADEPT58_PJR_NODDI24] → Results\CTI: 100%|█████████████████████████████████████████| 1/1 [00:04<00:00,  4.36s/file]
CTI_ALPS folders:  19%|███████████                                                | 49/262 [02:13<12:06,  3.41s/folder]

[OK] ADEPT58_PJR_NODDI24: copied 1 file(s) to D:\JHAhn\8641_conductivity\DTI_ALPS\2_Dementia\EPT2019\prep\ADEPT58_PJR_NODDI24\Results\CTI

] ADEPT59_KJS_NODDI24] → Results\CTI:   0%|                                                 | 0/1 [00:00<?, ?file/s]
] ADEPT59_KJS_NODDI24] → Results\CTI: 100%|█████████████████████████████████████████| 1/1 [00:01<00:00,  1.24s/file]
CTI_ALPS folders:  19%|███████████▎                                               | 50/262 [02:15<09:47,  2.77s/folder]

[OK] ADEPT59_KJS_NODDI24: copied 1 file(s) to D:\JHAhn\8641_conductivity\DTI_ALPS\2_Dementia\EPT2019\prep\ADEPT59_KJS_NODDI24\Results\CTI

] ADEPT60_PNS_NODDI24] → Results\CTI:   0%|                                                 | 0/1 [00:00<?, ?file/s]
] ADEPT60_PNS_NODDI24] → Results\CTI: 100%|█████████████████████████████████████████| 1/1 [00:02<00:00,  2.10s/file]
CTI_ALPS folders:  19%|███████████▍                                               | 51/262 [02:17<09:04,  2.58s/folder]

[OK] ADEPT60_PNS_NODDI24: copied 1 file(s) to D:\JHAhn\8641_conductivity\DTI_ALPS\2_Dementia\EPT2019\prep\ADEPT60_PNS_NODDI24\Results\CTI

] ADEPT61_YJS_NODDI24] → Results\CTI:   0%|                                                 | 0/1 [00:00<?, ?file/s]
] ADEPT61_YJS_NODDI24] → Results\CTI: 100%|█████████████████████████████████████████| 1/1 [00:03<00:00,  3.50s/file]
CTI_ALPS folders:  20%|███████████▋                                               | 52/262 [02:20<10:00,  2.86s/folder]

[OK] ADEPT61_YJS_NODDI24: copied 1 file(s) to D:\JHAhn\8641_conductivity\DTI_ALPS\2_Dementia\EPT2019\prep\ADEPT61_YJS_NODDI24\Results\CTI

] ADEPT62_HSO_NODDI24] → Results\CTI:   0%|                                                 | 0/1 [00:00<?, ?file/s]
] ADEPT62_HSO_NODDI24] → Results\CTI: 100%|█████████████████████████████████████████| 1/1 [00:01<00:00,  1.94s/file]
CTI_ALPS folders:  20%|███████████▉                                               | 53/262 [02:22<09:01,  2.59s/folder]

[OK] ADEPT62_HSO_NODDI24: copied 1 file(s) to D:\JHAhn\8641_conductivity\DTI_ALPS\2_Dementia\EPT2019\prep\ADEPT62_HSO_NODDI24\Results\CTI

] ADEPT63_JMS_NODDI24] → Results\CTI:   0%|                                                 | 0/1 [00:00<?, ?file/s]
] ADEPT63_JMS_NODDI24] → Results\CTI: 100%|█████████████████████████████████████████| 1/1 [00:01<00:00,  1.47s/file]
CTI_ALPS folders:  21%|████████████▏                                              | 54/262 [02:24<07:50,  2.26s/folder]

[OK] ADEPT63_JMS_NODDI24: copied 1 file(s) to D:\JHAhn\8641_conductivity\DTI_ALPS\2_Dementia\EPT2019\prep\ADEPT63_JMS_NODDI24\Results\CTI

] ADEPT64_PMS_NODDI24] → Results\CTI:   0%|                                                 | 0/1 [00:00<?, ?file/s]
] ADEPT64_PMS_NODDI24] → Results\CTI: 100%|█████████████████████████████████████████| 1/1 [00:03<00:00,  3.06s/file]
CTI_ALPS folders:  21%|████████████▍                                              | 55/262 [02:27<08:38,  2.51s/folder]

[OK] ADEPT64_PMS_NODDI24: copied 1 file(s) to D:\JHAhn\8641_conductivity\DTI_ALPS\2_Dementia\EPT2019\prep\ADEPT64_PMS_NODDI24\Results\CTI

] ADEPT65_CMR_NODDI24] → Results\CTI:   0%|                                                 | 0/1 [00:00<?, ?file/s]
] ADEPT65_CMR_NODDI24] → Results\CTI: 100%|█████████████████████████████████████████| 1/1 [00:04<00:00,  4.07s/file]
CTI_ALPS folders:  21%|████████████▌                                              | 56/262 [02:31<10:14,  2.98s/folder]

[OK] ADEPT65_CMR_NODDI24: copied 1 file(s) to D:\JHAhn\8641_conductivity\DTI_ALPS\2_Dementia\EPT2019\prep\ADEPT65_CMR_NODDI24\Results\CTI

] ADEPT66_LDS_NODDI24] → Results\CTI:   0%|                                                 | 0/1 [00:00<?, ?file/s]
] ADEPT66_LDS_NODDI24] → Results\CTI: 100%|█████████████████████████████████████████| 1/1 [00:02<00:00,  2.27s/file]
CTI_ALPS folders:  22%|████████████▊                                              | 57/262 [02:33<09:27,  2.77s/folder]

[OK] ADEPT66_LDS_NODDI24: copied 1 file(s) to D:\JHAhn\8641_conductivity\DTI_ALPS\2_Dementia\EPT2019\prep\ADEPT66_LDS_NODDI24\Results\CTI

] ADEPT67_JKJ_NODDI24] → Results\CTI:   0%|                                                 | 0/1 [00:00<?, ?file/s]
] ADEPT67_JKJ_NODDI24] → Results\CTI: 100%|█████████████████████████████████████████| 1/1 [00:01<00:00,  1.47s/file]
CTI_ALPS folders:  22%|█████████████                                              | 58/262 [02:35<08:06,  2.39s/folder]

[OK] ADEPT67_JKJ_NODDI24: copied 1 file(s) to D:\JHAhn\8641_conductivity\DTI_ALPS\2_Dementia\EPT2019\prep\ADEPT67_JKJ_NODDI24\Results\CTI

] EPT2022AD01_KDKM_NODDI32] → Results\CTI:   0%|                                            | 0/1 [00:00<?, ?file/s]
] EPT2022AD01_KDKM_NODDI32] → Results\CTI: 100%|████████████████████████████████████| 1/1 [00:02<00:00,  2.43s/file]
CTI_ALPS folders:  23%|█████████████▎                                             | 59/262 [02:37<08:10,  2.42s/folder]

[OK] EPT2022AD01_KDKM_NODDI32: copied 1 file(s) to D:\JHAhn\8641_conductivity\DTI_ALPS\2_Dementia\EPT2022\EPT2022AD01_KDKM_NODDI32\Results\CTI

] EPT2022AD02_SKM_NODDI32] → Results\CTI:   0%|                                             | 0/1 [00:00<?, ?file/s]
] EPT2022AD02_SKM_NODDI32] → Results\CTI: 100%|█████████████████████████████████████| 1/1 [00:02<00:00,  2.44s/file]
CTI_ALPS folders:  23%|█████████████▌                                             | 60/262 [02:40<08:56,  2.65s/folder]

[OK] EPT2022AD02_SKM_NODDI32: copied 1 file(s) to D:\JHAhn\8641_conductivity\DTI_ALPS\2_Dementia\EPT2022\EPT2022AD02_SKM_NODDI32\Results\CTI

] EPT2022AD03_KKS_NODDI32] → Results\CTI:   0%|                                             | 0/1 [00:00<?, ?file/s]
] EPT2022AD03_KKS_NODDI32] → Results\CTI: 100%|█████████████████████████████████████| 1/1 [00:03<00:00,  3.55s/file]
CTI_ALPS folders:  23%|█████████████▋                                             | 61/262 [02:44<09:59,  2.98s/folder]

[OK] EPT2022AD03_KKS_NODDI32: copied 1 file(s) to D:\JHAhn\8641_conductivity\DTI_ALPS\2_Dementia\EPT2022\EPT2022AD03_KKS_NODDI32\Results\CTI

] EPT2022AD05_KIJD_NODDI32] → Results\CTI:   0%|                                            | 0/1 [00:00<?, ?file/s]
] EPT2022AD05_KIJD_NODDI32] → Results\CTI: 100%|████████████████████████████████████| 1/1 [00:01<00:00,  1.70s/file]
CTI_ALPS folders:  24%|█████████████▉                                             | 62/262 [02:46<08:42,  2.61s/folder]

[OK] EPT2022AD05_KIJD_NODDI32: copied 1 file(s) to D:\JHAhn\8641_conductivity\DTI_ALPS\2_Dementia\EPT2022\EPT2022AD05_KIJD_NODDI32\Results\CTI

] EPT2022AD063_BPB_NODDI32] → Results\CTI:   0%|                                            | 0/1 [00:00<?, ?file/s]
] EPT2022AD063_BPB_NODDI32] → Results\CTI: 100%|████████████████████████████████████| 1/1 [00:01<00:00,  1.17s/file]
CTI_ALPS folders:  24%|██████████████▏                                            | 63/262 [02:47<07:17,  2.20s/folder]

[OK] EPT2022AD063_BPB_NODDI32: copied 1 file(s) to D:\JHAhn\8641_conductivity\DTI_ALPS\2_Dementia\EPT2022\EPT2022AD063_BPB_NODDI32\Results\CTI

] EPT2022AD064_LYS_NODDI32] → Results\CTI:   0%|                                            | 0/1 [00:00<?, ?file/s]
] EPT2022AD064_LYS_NODDI32] → Results\CTI: 100%|████████████████████████████████████| 1/1 [00:02<00:00,  2.71s/file]
CTI_ALPS folders:  24%|██████████████▍                                            | 64/262 [02:50<07:53,  2.39s/folder]

[OK] EPT2022AD064_LYS_NODDI32: copied 1 file(s) to D:\JHAhn\8641_conductivity\DTI_ALPS\2_Dementia\EPT2022\EPT2022AD064_LYS_NODDI32\Results\CTI

] EPT2022AD065_CGS_NODDI32] → Results\CTI:   0%|                                            | 0/1 [00:00<?, ?file/s]
] EPT2022AD065_CGS_NODDI32] → Results\CTI: 100%|████████████████████████████████████| 1/1 [00:02<00:00,  2.42s/file]
CTI_ALPS folders:  25%|██████████████▋                                            | 65/262 [02:52<07:58,  2.43s/folder]

[OK] EPT2022AD065_CGS_NODDI32: copied 1 file(s) to D:\JHAhn\8641_conductivity\DTI_ALPS\2_Dementia\EPT2022\EPT2022AD065_CGS_NODDI32\Results\CTI

] EPT2022AD066_AIS_NODDI32] → Results\CTI:   0%|                                            | 0/1 [00:00<?, ?file/s]
] EPT2022AD066_AIS_NODDI32] → Results\CTI: 100%|████████████████████████████████████| 1/1 [00:04<00:00,  4.55s/file]
CTI_ALPS folders:  25%|██████████████▊                                            | 66/262 [02:57<10:03,  3.08s/folder]

[OK] EPT2022AD066_AIS_NODDI32: copied 1 file(s) to D:\JHAhn\8641_conductivity\DTI_ALPS\2_Dementia\EPT2022\EPT2022AD066_AIS_NODDI32\Results\CTI

] EPT2022AD067_JSO_NODDI32] → Results\CTI:   0%|                                            | 0/1 [00:00<?, ?file/s]
] EPT2022AD067_JSO_NODDI32] → Results\CTI: 100%|████████████████████████████████████| 1/1 [00:01<00:00,  1.56s/file]
CTI_ALPS folders:  26%|███████████████                                            | 67/262 [02:59<08:37,  2.65s/folder]

[OK] EPT2022AD067_JSO_NODDI32: copied 1 file(s) to D:\JHAhn\8641_conductivity\DTI_ALPS\2_Dementia\EPT2022\EPT2022AD067_JSO_NODDI32\Results\CTI

] EPT2022AD068_NSE_NODDI32] → Results\CTI:   0%|                                            | 0/1 [00:00<?, ?file/s]
] EPT2022AD068_NSE_NODDI32] → Results\CTI: 100%|████████████████████████████████████| 1/1 [00:01<00:00,  1.37s/file]
CTI_ALPS folders:  26%|███████████████▎                                           | 68/262 [03:00<07:24,  2.29s/folder]

[OK] EPT2022AD068_NSE_NODDI32: copied 1 file(s) to D:\JHAhn\8641_conductivity\DTI_ALPS\2_Dementia\EPT2022\EPT2022AD068_NSE_NODDI32\Results\CTI

] EPT2022AD069_LBD_NODDI32] → Results\CTI:   0%|                                            | 0/1 [00:00<?, ?file/s]
] EPT2022AD069_LBD_NODDI32] → Results\CTI: 100%|████████████████████████████████████| 1/1 [00:01<00:00,  1.94s/file]
CTI_ALPS folders:  26%|███████████████▌                                           | 69/262 [03:02<07:06,  2.21s/folder]

[OK] EPT2022AD069_LBD_NODDI32: copied 1 file(s) to D:\JHAhn\8641_conductivity\DTI_ALPS\2_Dementia\EPT2022\EPT2022AD069_LBD_NODDI32\Results\CTI

] EPT2022AD06_JOJ_NODDI32] → Results\CTI:   0%|                                             | 0/1 [00:00<?, ?file/s]
] EPT2022AD06_JOJ_NODDI32] → Results\CTI: 100%|█████████████████████████████████████| 1/1 [00:03<00:00,  3.13s/file]
CTI_ALPS folders:  27%|███████████████▊                                           | 70/262 [03:05<08:06,  2.54s/folder]

[OK] EPT2022AD06_JOJ_NODDI32: copied 1 file(s) to D:\JHAhn\8641_conductivity\DTI_ALPS\2_Dementia\EPT2022\EPT2022AD06_JOJ_NODDI32\Results\CTI

] EPT2022AD070_KSH_NODDI32] → Results\CTI:   0%|                                            | 0/1 [00:00<?, ?file/s]
] EPT2022AD070_KSH_NODDI32] → Results\CTI: 100%|████████████████████████████████████| 1/1 [00:04<00:00,  4.61s/file]
CTI_ALPS folders:  27%|███████████████▉                                           | 71/262 [03:10<10:12,  3.20s/folder]

[OK] EPT2022AD070_KSH_NODDI32: copied 1 file(s) to D:\JHAhn\8641_conductivity\DTI_ALPS\2_Dementia\EPT2022\EPT2022AD070_KSH_NODDI32\Results\CTI

] EPT2022AD071_KSJ_NODDI32] → Results\CTI:   0%|                                            | 0/1 [00:00<?, ?file/s]
] EPT2022AD071_KSJ_NODDI32] → Results\CTI: 100%|████████████████████████████████████| 1/1 [00:02<00:00,  2.14s/file]
CTI_ALPS folders:  27%|████████████████▏                                          | 72/262 [03:13<09:19,  2.94s/folder]

[OK] EPT2022AD071_KSJ_NODDI32: copied 1 file(s) to D:\JHAhn\8641_conductivity\DTI_ALPS\2_Dementia\EPT2022\EPT2022AD071_KSJ_NODDI32\Results\CTI

] EPT2022AD072_SDY_NODDI32] → Results\CTI:   0%|                                            | 0/1 [00:00<?, ?file/s]
] EPT2022AD072_SDY_NODDI32] → Results\CTI: 100%|████████████████████████████████████| 1/1 [00:01<00:00,  1.62s/file]
CTI_ALPS folders:  28%|████████████████▍                                          | 73/262 [03:14<08:11,  2.60s/folder]

[OK] EPT2022AD072_SDY_NODDI32: copied 1 file(s) to D:\JHAhn\8641_conductivity\DTI_ALPS\2_Dementia\EPT2022\EPT2022AD072_SDY_NODDI32\Results\CTI

] EPT2022AD073_KHR_NODDI32] → Results\CTI:   0%|                                            | 0/1 [00:00<?, ?file/s]
] EPT2022AD073_KHR_NODDI32] → Results\CTI: 100%|████████████████████████████████████| 1/1 [00:01<00:00,  1.73s/file]
CTI_ALPS folders:  28%|████████████████▋                                          | 74/262 [03:16<07:33,  2.41s/folder]

[OK] EPT2022AD073_KHR_NODDI32: copied 1 file(s) to D:\JHAhn\8641_conductivity\DTI_ALPS\2_Dementia\EPT2022\EPT2022AD073_KHR_NODDI32\Results\CTI

] EPT2022AD074_LGR_NODDI32] → Results\CTI:   0%|                                            | 0/1 [00:00<?, ?file/s]
] EPT2022AD074_LGR_NODDI32] → Results\CTI: 100%|████████████████████████████████████| 1/1 [00:02<00:00,  2.73s/file]
CTI_ALPS folders:  29%|████████████████▉                                          | 75/262 [03:19<08:00,  2.57s/folder]

[OK] EPT2022AD074_LGR_NODDI32: copied 1 file(s) to D:\JHAhn\8641_conductivity\DTI_ALPS\2_Dementia\EPT2022\EPT2022AD074_LGR_NODDI32\Results\CTI

] EPT2022AD07_YMY_NODDI32] → Results\CTI:   0%|                                             | 0/1 [00:00<?, ?file/s]
] EPT2022AD07_YMY_NODDI32] → Results\CTI: 100%|█████████████████████████████████████| 1/1 [00:04<00:00,  4.40s/file]
CTI_ALPS folders:  29%|█████████████████                                          | 76/262 [03:24<09:43,  3.14s/folder]

[OK] EPT2022AD07_YMY_NODDI32: copied 1 file(s) to D:\JHAhn\8641_conductivity\DTI_ALPS\2_Dementia\EPT2022\EPT2022AD07_YMY_NODDI32\Results\CTI

] EPT2022AD08_JIL_NODDI32] → Results\CTI:   0%|                                             | 0/1 [00:00<?, ?file/s]
] EPT2022AD08_JIL_NODDI32] → Results\CTI: 100%|█████████████████████████████████████| 1/1 [00:01<00:00,  1.29s/file]
CTI_ALPS folders:  29%|█████████████████▎                                         | 77/262 [03:25<08:06,  2.63s/folder]

[OK] EPT2022AD08_JIL_NODDI32: copied 1 file(s) to D:\JHAhn\8641_conductivity\DTI_ALPS\2_Dementia\EPT2022\EPT2022AD08_JIL_NODDI32\Results\CTI

] EPT2022AD09_JYS_NODDI32] → Results\CTI:   0%|                                             | 0/1 [00:00<?, ?file/s]
] EPT2022AD09_JYS_NODDI32] → Results\CTI: 100%|█████████████████████████████████████| 1/1 [00:02<00:00,  2.24s/file]
CTI_ALPS folders:  30%|█████████████████▌                                         | 78/262 [03:27<07:45,  2.53s/folder]

[OK] EPT2022AD09_JYS_NODDI32: copied 1 file(s) to D:\JHAhn\8641_conductivity\DTI_ALPS\2_Dementia\EPT2022\EPT2022AD09_JYS_NODDI32\Results\CTI

] EPT2022AD10_HSY_NODDI32] → Results\CTI:   0%|                                             | 0/1 [00:00<?, ?file/s]
] EPT2022AD10_HSY_NODDI32] → Results\CTI: 100%|█████████████████████████████████████| 1/1 [00:03<00:00,  3.42s/file]
CTI_ALPS folders:  30%|█████████████████▊                                         | 79/262 [03:31<08:40,  2.85s/folder]

[OK] EPT2022AD10_HSY_NODDI32: copied 1 file(s) to D:\JHAhn\8641_conductivity\DTI_ALPS\2_Dementia\EPT2022\EPT2022AD10_HSY_NODDI32\Results\CTI

] EPT2022AD11_PSI_NODDI32] → Results\CTI:   0%|                                             | 0/1 [00:00<?, ?file/s]
] EPT2022AD11_PSI_NODDI32] → Results\CTI: 100%|█████████████████████████████████████| 1/1 [00:02<00:00,  2.32s/file]
CTI_ALPS folders:  31%|██████████████████                                         | 80/262 [03:34<08:23,  2.77s/folder]

[OK] EPT2022AD11_PSI_NODDI32: copied 1 file(s) to D:\JHAhn\8641_conductivity\DTI_ALPS\2_Dementia\EPT2022\EPT2022AD11_PSI_NODDI32\Results\CTI

] EPT2022AD12_SYS_NODDI32] → Results\CTI:   0%|                                             | 0/1 [00:00<?, ?file/s]
] EPT2022AD12_SYS_NODDI32] → Results\CTI: 100%|█████████████████████████████████████| 1/1 [00:01<00:00,  1.81s/file]
CTI_ALPS folders:  31%|██████████████████▏                                        | 81/262 [03:35<07:30,  2.49s/folder]

[OK] EPT2022AD12_SYS_NODDI32: copied 1 file(s) to D:\JHAhn\8641_conductivity\DTI_ALPS\2_Dementia\EPT2022\EPT2022AD12_SYS_NODDI32\Results\CTI

] EPT2022AD13_SYJ_NODDI32] → Results\CTI:   0%|                                             | 0/1 [00:00<?, ?file/s]
] EPT2022AD13_SYJ_NODDI32] → Results\CTI: 100%|█████████████████████████████████████| 1/1 [00:01<00:00,  1.37s/file]
CTI_ALPS folders:  31%|██████████████████▍                                        | 82/262 [03:37<06:50,  2.28s/folder]

[OK] EPT2022AD13_SYJ_NODDI32: copied 1 file(s) to D:\JHAhn\8641_conductivity\DTI_ALPS\2_Dementia\EPT2022\EPT2022AD13_SYJ_NODDI32\Results\CTI

] EPT2022AD14_PYS_NODDI32] → Results\CTI:   0%|                                             | 0/1 [00:00<?, ?file/s]
] EPT2022AD14_PYS_NODDI32] → Results\CTI: 100%|█████████████████████████████████████| 1/1 [00:02<00:00,  2.68s/file]
CTI_ALPS folders:  32%|██████████████████▋                                        | 83/262 [03:40<07:17,  2.44s/folder]

[OK] EPT2022AD14_PYS_NODDI32: copied 1 file(s) to D:\JHAhn\8641_conductivity\DTI_ALPS\2_Dementia\EPT2022\EPT2022AD14_PYS_NODDI32\Results\CTI

] EPT2022AD15_YSH_NODDI32] → Results\CTI:   0%|                                             | 0/1 [00:00<?, ?file/s]
] EPT2022AD15_YSH_NODDI32] → Results\CTI: 100%|█████████████████████████████████████| 1/1 [00:04<00:00,  4.80s/file]
CTI_ALPS folders:  32%|██████████████████▉                                        | 84/262 [03:45<09:29,  3.20s/folder]

[OK] EPT2022AD15_YSH_NODDI32: copied 1 file(s) to D:\JHAhn\8641_conductivity\DTI_ALPS\2_Dementia\EPT2022\EPT2022AD15_YSH_NODDI32\Results\CTI

] EPT2022AD16_CKJ_NODDI32] → Results\CTI:   0%|                                             | 0/1 [00:00<?, ?file/s]
] EPT2022AD16_CKJ_NODDI32] → Results\CTI: 100%|█████████████████████████████████████| 1/1 [00:02<00:00,  2.35s/file]
CTI_ALPS folders:  32%|███████████████████▏                                       | 85/262 [03:48<08:52,  3.01s/folder]

[OK] EPT2022AD16_CKJ_NODDI32: copied 1 file(s) to D:\JHAhn\8641_conductivity\DTI_ALPS\2_Dementia\EPT2022\EPT2022AD16_CKJ_NODDI32\Results\CTI

] EPT2022AD17_KHS_NODDI32] → Results\CTI:   0%|                                             | 0/1 [00:00<?, ?file/s]
] EPT2022AD17_KHS_NODDI32] → Results\CTI: 100%|█████████████████████████████████████| 1/1 [00:01<00:00,  1.37s/file]
CTI_ALPS folders:  33%|███████████████████▎                                       | 86/262 [03:49<07:29,  2.55s/folder]

[OK] EPT2022AD17_KHS_NODDI32: copied 1 file(s) to D:\JHAhn\8641_conductivity\DTI_ALPS\2_Dementia\EPT2022\EPT2022AD17_KHS_NODDI32\Results\CTI

] EPT2022AD18_PKW_NODDI32] → Results\CTI:   0%|                                             | 0/1 [00:00<?, ?file/s]
] EPT2022AD18_PKW_NODDI32] → Results\CTI: 100%|█████████████████████████████████████| 1/1 [00:03<00:00,  3.90s/file]
CTI_ALPS folders:  33%|███████████████████▌                                       | 87/262 [03:53<08:56,  3.07s/folder]

[OK] EPT2022AD18_PKW_NODDI32: copied 1 file(s) to D:\JHAhn\8641_conductivity\DTI_ALPS\2_Dementia\EPT2022\EPT2022AD18_PKW_NODDI32\Results\CTI

] EPT2022AD19_YJH_NODDI32] → Results\CTI:   0%|                                             | 0/1 [00:00<?, ?file/s]
] EPT2022AD19_YJH_NODDI32] → Results\CTI: 100%|█████████████████████████████████████| 1/1 [00:01<00:00,  1.37s/file]
CTI_ALPS folders:  34%|███████████████████▊                                       | 88/262 [03:55<07:42,  2.66s/folder]

[OK] EPT2022AD19_YJH_NODDI32: copied 1 file(s) to D:\JHAhn\8641_conductivity\DTI_ALPS\2_Dementia\EPT2022\EPT2022AD19_YJH_NODDI32\Results\CTI

] EPT2022AD20_KYS_NODDI32] → Results\CTI:   0%|                                             | 0/1 [00:00<?, ?file/s]
] EPT2022AD20_KYS_NODDI32] → Results\CTI: 100%|█████████████████████████████████████| 1/1 [00:02<00:00,  2.22s/file]
CTI_ALPS folders:  34%|████████████████████                                       | 89/262 [03:57<07:25,  2.58s/folder]

[OK] EPT2022AD20_KYS_NODDI32: copied 1 file(s) to D:\JHAhn\8641_conductivity\DTI_ALPS\2_Dementia\EPT2022\EPT2022AD20_KYS_NODDI32\Results\CTI

] EPT2022AD21_KOJ_NODDI32] → Results\CTI:   0%|                                             | 0/1 [00:00<?, ?file/s]
] EPT2022AD21_KOJ_NODDI32] → Results\CTI: 100%|█████████████████████████████████████| 1/1 [00:01<00:00,  1.81s/file]
CTI_ALPS folders:  34%|████████████████████▎                                      | 90/262 [03:59<06:50,  2.38s/folder]

[OK] EPT2022AD21_KOJ_NODDI32: copied 1 file(s) to D:\JHAhn\8641_conductivity\DTI_ALPS\2_Dementia\EPT2022\EPT2022AD21_KOJ_NODDI32\Results\CTI

] EPT2022AD22_NSC_NODDI32] → Results\CTI:   0%|                                             | 0/1 [00:00<?, ?file/s]
] EPT2022AD22_NSC_NODDI32] → Results\CTI: 100%|█████████████████████████████████████| 1/1 [00:02<00:00,  2.89s/file]
CTI_ALPS folders:  35%|████████████████████▍                                      | 91/262 [04:02<07:17,  2.56s/folder]

[OK] EPT2022AD22_NSC_NODDI32: copied 1 file(s) to D:\JHAhn\8641_conductivity\DTI_ALPS\2_Dementia\EPT2022\EPT2022AD22_NSC_NODDI32\Results\CTI

] EPT2022AD23_SKSH_NODDI32] → Results\CTI:   0%|                                            | 0/1 [00:00<?, ?file/s]
] EPT2022AD23_SKSH_NODDI32] → Results\CTI: 100%|████████████████████████████████████| 1/1 [00:04<00:00,  4.90s/file]
CTI_ALPS folders:  35%|████████████████████▋                                      | 92/262 [04:07<09:22,  3.31s/folder]

[OK] EPT2022AD23_SKSH_NODDI32: copied 1 file(s) to D:\JHAhn\8641_conductivity\DTI_ALPS\2_Dementia\EPT2022\EPT2022AD23_SKSH_NODDI32\Results\CTI

] EPT2022AD24_KJS_NODDI32] → Results\CTI:   0%|                                             | 0/1 [00:00<?, ?file/s]
] EPT2022AD24_KJS_NODDI32] → Results\CTI: 100%|█████████████████████████████████████| 1/1 [00:01<00:00,  1.53s/file]
CTI_ALPS folders:  35%|████████████████████▉                                      | 93/262 [04:09<07:54,  2.81s/folder]

[OK] EPT2022AD24_KJS_NODDI32: copied 1 file(s) to D:\JHAhn\8641_conductivity\DTI_ALPS\2_Dementia\EPT2022\EPT2022AD24_KJS_NODDI32\Results\CTI

] EPT2022AD25_KMS_NODDI32] → Results\CTI:   0%|                                             | 0/1 [00:00<?, ?file/s]
] EPT2022AD25_KMS_NODDI32] → Results\CTI: 100%|█████████████████████████████████████| 1/1 [00:01<00:00,  1.81s/file]
CTI_ALPS folders:  36%|█████████████████████▏                                     | 94/262 [04:11<07:04,  2.53s/folder]

[OK] EPT2022AD25_KMS_NODDI32: copied 1 file(s) to D:\JHAhn\8641_conductivity\DTI_ALPS\2_Dementia\EPT2022\EPT2022AD25_KMS_NODDI32\Results\CTI

] EPT2022AD26_PSO_NODDI32] → Results\CTI:   0%|                                             | 0/1 [00:00<?, ?file/s]
] EPT2022AD26_PSO_NODDI32] → Results\CTI: 100%|█████████████████████████████████████| 1/1 [00:01<00:00,  1.60s/file]
CTI_ALPS folders:  36%|█████████████████████▍                                     | 95/262 [04:13<06:22,  2.29s/folder]

[OK] EPT2022AD26_PSO_NODDI32: copied 1 file(s) to D:\JHAhn\8641_conductivity\DTI_ALPS\2_Dementia\EPT2022\EPT2022AD26_PSO_NODDI32\Results\CTI

] EPT2022AD27_KDS_NODDI32] → Results\CTI:   0%|                                             | 0/1 [00:00<?, ?file/s]
] EPT2022AD27_KDS_NODDI32] → Results\CTI: 100%|█████████████████████████████████████| 1/1 [00:03<00:00,  3.86s/file]
CTI_ALPS folders:  37%|█████████████████████▌                                     | 96/262 [04:17<07:43,  2.79s/folder]

[OK] EPT2022AD27_KDS_NODDI32: copied 1 file(s) to D:\JHAhn\8641_conductivity\DTI_ALPS\2_Dementia\EPT2022\EPT2022AD27_KDS_NODDI32\Results\CTI

] EPT2022AD29_LKH_NODDI32] → Results\CTI:   0%|                                             | 0/1 [00:00<?, ?file/s]
] EPT2022AD29_LKH_NODDI32] → Results\CTI: 100%|█████████████████████████████████████| 1/1 [00:03<00:00,  3.87s/file]
CTI_ALPS folders:  37%|█████████████████████▊                                     | 97/262 [04:21<08:45,  3.18s/folder]

[OK] EPT2022AD29_LKH_NODDI32: copied 1 file(s) to D:\JHAhn\8641_conductivity\DTI_ALPS\2_Dementia\EPT2022\EPT2022AD29_LKH_NODDI32\Results\CTI

] EPT2022AD30_NNO_NODDI32] → Results\CTI:   0%|                                             | 0/1 [00:00<?, ?file/s]
] EPT2022AD30_NNO_NODDI32] → Results\CTI: 100%|█████████████████████████████████████| 1/1 [00:01<00:00,  1.18s/file]
CTI_ALPS folders:  37%|██████████████████████                                     | 98/262 [04:22<07:13,  2.64s/folder]

[OK] EPT2022AD30_NNO_NODDI32: copied 1 file(s) to D:\JHAhn\8641_conductivity\DTI_ALPS\2_Dementia\EPT2022\EPT2022AD30_NNO_NODDI32\Results\CTI

] EPT2022AD31_HSB_NODDI32] → Results\CTI:   0%|                                             | 0/1 [00:00<?, ?file/s]
] EPT2022AD31_HSB_NODDI32] → Results\CTI: 100%|█████████████████████████████████████| 1/1 [00:02<00:00,  2.20s/file]
CTI_ALPS folders:  38%|██████████████████████▎                                    | 99/262 [04:24<06:51,  2.52s/folder]

[OK] EPT2022AD31_HSB_NODDI32: copied 1 file(s) to D:\JHAhn\8641_conductivity\DTI_ALPS\2_Dementia\EPT2022\EPT2022AD31_HSB_NODDI32\Results\CTI

] EPT2022AD32_CDR_NODDI32] → Results\CTI:   0%|                                             | 0/1 [00:00<?, ?file/s]
] EPT2022AD32_CDR_NODDI32] → Results\CTI: 100%|█████████████████████████████████████| 1/1 [00:03<00:00,  3.97s/file]
CTI_ALPS folders:  38%|██████████████████████▏                                   | 100/262 [04:29<08:16,  3.06s/folder]

[OK] EPT2022AD32_CDR_NODDI32: copied 1 file(s) to D:\JHAhn\8641_conductivity\DTI_ALPS\2_Dementia\EPT2022\EPT2022AD32_CDR_NODDI32\Results\CTI

] EPT2022AD33_KTY_NODDI32] → Results\CTI:   0%|                                             | 0/1 [00:00<?, ?file/s]
] EPT2022AD33_KTY_NODDI32] → Results\CTI: 100%|█████████████████████████████████████| 1/1 [00:01<00:00,  1.27s/file]
CTI_ALPS folders:  39%|██████████████████████▎                                   | 101/262 [04:30<07:01,  2.62s/folder]

[OK] EPT2022AD33_KTY_NODDI32: copied 1 file(s) to D:\JHAhn\8641_conductivity\DTI_ALPS\2_Dementia\EPT2022\EPT2022AD33_KTY_NODDI32\Results\CTI

] EPT2022AD34_KMB_NODDI32] → Results\CTI:   0%|                                             | 0/1 [00:00<?, ?file/s]
] EPT2022AD34_KMB_NODDI32] → Results\CTI: 100%|█████████████████████████████████████| 1/1 [00:02<00:00,  2.25s/file]
CTI_ALPS folders:  39%|██████████████████████▌                                   | 102/262 [04:33<06:43,  2.52s/folder]

[OK] EPT2022AD34_KMB_NODDI32: copied 1 file(s) to D:\JHAhn\8641_conductivity\DTI_ALPS\2_Dementia\EPT2022\EPT2022AD34_KMB_NODDI32\Results\CTI

] EPT2022AD35_HHS_NODDI32] → Results\CTI:   0%|                                             | 0/1 [00:00<?, ?file/s]
] EPT2022AD35_HHS_NODDI32] → Results\CTI: 100%|█████████████████████████████████████| 1/1 [00:01<00:00,  1.91s/file]
CTI_ALPS folders:  39%|██████████████████████▊                                   | 103/262 [04:35<06:13,  2.35s/folder]

[OK] EPT2022AD35_HHS_NODDI32: copied 1 file(s) to D:\JHAhn\8641_conductivity\DTI_ALPS\2_Dementia\EPT2022\EPT2022AD35_HHS_NODDI32\Results\CTI

] EPT2022AD36_JYS_NODDI32] → Results\CTI:   0%|                                             | 0/1 [00:00<?, ?file/s]
] EPT2022AD36_JYS_NODDI32] → Results\CTI: 100%|█████████████████████████████████████| 1/1 [00:04<00:00,  4.98s/file]
CTI_ALPS folders:  40%|███████████████████████                                   | 104/262 [04:40<08:23,  3.18s/folder]

[OK] EPT2022AD36_JYS_NODDI32: copied 1 file(s) to D:\JHAhn\8641_conductivity\DTI_ALPS\2_Dementia\EPT2022\EPT2022AD36_JYS_NODDI32\Results\CTI

] EPT2022AD37_CEH_NODDI32] → Results\CTI:   0%|                                             | 0/1 [00:00<?, ?file/s]
] EPT2022AD37_CEH_NODDI32] → Results\CTI: 100%|█████████████████████████████████████| 1/1 [00:02<00:00,  2.13s/file]
CTI_ALPS folders:  40%|███████████████████████▏                                  | 105/262 [04:42<07:38,  2.92s/folder]

[OK] EPT2022AD37_CEH_NODDI32: copied 1 file(s) to D:\JHAhn\8641_conductivity\DTI_ALPS\2_Dementia\EPT2022\EPT2022AD37_CEH_NODDI32\Results\CTI

] EPT2022AD38_YYS_NODDI32] → Results\CTI:   0%|                                             | 0/1 [00:00<?, ?file/s]
] EPT2022AD38_YYS_NODDI32] → Results\CTI: 100%|█████████████████████████████████████| 1/1 [00:01<00:00,  1.94s/file]
CTI_ALPS folders:  40%|███████████████████████▍                                  | 106/262 [04:44<06:55,  2.66s/folder]

[OK] EPT2022AD38_YYS_NODDI32: copied 1 file(s) to D:\JHAhn\8641_conductivity\DTI_ALPS\2_Dementia\EPT2022\EPT2022AD38_YYS_NODDI32\Results\CTI

] EPT2022AD39_LJS_NODDI32] → Results\CTI:   0%|                                             | 0/1 [00:00<?, ?file/s]
] EPT2022AD39_LJS_NODDI32] → Results\CTI: 100%|█████████████████████████████████████| 1/1 [00:02<00:00,  2.03s/file]
CTI_ALPS folders:  41%|███████████████████████▋                                  | 107/262 [04:46<06:25,  2.49s/folder]

[OK] EPT2022AD39_LJS_NODDI32: copied 1 file(s) to D:\JHAhn\8641_conductivity\DTI_ALPS\2_Dementia\EPT2022\EPT2022AD39_LJS_NODDI32\Results\CTI

] EPT2022AD40_RKJ_NODDI32] → Results\CTI:   0%|                                             | 0/1 [00:00<?, ?file/s]
] EPT2022AD40_RKJ_NODDI32] → Results\CTI: 100%|█████████████████████████████████████| 1/1 [00:04<00:00,  4.39s/file]
CTI_ALPS folders:  41%|███████████████████████▉                                  | 108/262 [04:51<07:56,  3.10s/folder]

[OK] EPT2022AD40_RKJ_NODDI32: copied 1 file(s) to D:\JHAhn\8641_conductivity\DTI_ALPS\2_Dementia\EPT2022\EPT2022AD40_RKJ_NODDI32\Results\CTI

] EPT2022AD41_SIJ_NODDI32] → Results\CTI:   0%|                                             | 0/1 [00:00<?, ?file/s]
] EPT2022AD41_SIJ_NODDI32] → Results\CTI: 100%|█████████████████████████████████████| 1/1 [00:02<00:00,  2.97s/file]
CTI_ALPS folders:  42%|████████████████████████▏                                 | 109/262 [04:54<07:54,  3.10s/folder]

[OK] EPT2022AD41_SIJ_NODDI32: copied 1 file(s) to D:\JHAhn\8641_conductivity\DTI_ALPS\2_Dementia\EPT2022\EPT2022AD41_SIJ_NODDI32\Results\CTI

] EPT2022AD42_HPB_NODDI32] → Results\CTI:   0%|                                             | 0/1 [00:00<?, ?file/s]
] EPT2022AD42_HPB_NODDI32] → Results\CTI: 100%|█████████████████████████████████████| 1/1 [00:01<00:00,  1.23s/file]
CTI_ALPS folders:  42%|████████████████████████▎                                 | 110/262 [04:55<06:28,  2.56s/folder]

[OK] EPT2022AD42_HPB_NODDI32: copied 1 file(s) to D:\JHAhn\8641_conductivity\DTI_ALPS\2_Dementia\EPT2022\EPT2022AD42_HPB_NODDI32\Results\CTI

] EPT2022AD43_CDH_NODDI32] → Results\CTI:   0%|                                             | 0/1 [00:00<?, ?file/s]
] EPT2022AD43_CDH_NODDI32] → Results\CTI: 100%|█████████████████████████████████████| 1/1 [00:01<00:00,  1.56s/file]
CTI_ALPS folders:  42%|████████████████████████▌                                 | 111/262 [04:57<05:44,  2.28s/folder]

[OK] EPT2022AD43_CDH_NODDI32: copied 1 file(s) to D:\JHAhn\8641_conductivity\DTI_ALPS\2_Dementia\EPT2022\EPT2022AD43_CDH_NODDI32\Results\CTI

] EPT2022AD44_LKJ_NODDI32] → Results\CTI:   0%|                                             | 0/1 [00:00<?, ?file/s]
] EPT2022AD44_LKJ_NODDI32] → Results\CTI: 100%|█████████████████████████████████████| 1/1 [00:02<00:00,  2.58s/file]
CTI_ALPS folders:  43%|████████████████████████▊                                 | 112/262 [05:00<06:07,  2.45s/folder]

[OK] EPT2022AD44_LKJ_NODDI32: copied 1 file(s) to D:\JHAhn\8641_conductivity\DTI_ALPS\2_Dementia\EPT2022\EPT2022AD44_LKJ_NODDI32\Results\CTI

] EPT2022AD45_CHS_NODDI32] → Results\CTI:   0%|                                             | 0/1 [00:00<?, ?file/s]
] EPT2022AD45_CHS_NODDI32] → Results\CTI: 100%|█████████████████████████████████████| 1/1 [00:01<00:00,  1.51s/file]
CTI_ALPS folders:  43%|█████████████████████████                                 | 113/262 [05:01<05:30,  2.22s/folder]

[OK] EPT2022AD45_CHS_NODDI32: copied 1 file(s) to D:\JHAhn\8641_conductivity\DTI_ALPS\2_Dementia\EPT2022\EPT2022AD45_CHS_NODDI32\Results\CTI

] EPT2022AD46_KOS_NODDI32] → Results\CTI:   0%|                                             | 0/1 [00:00<?, ?file/s]
] EPT2022AD46_KOS_NODDI32] → Results\CTI: 100%|█████████████████████████████████████| 1/1 [00:04<00:00,  4.44s/file]
CTI_ALPS folders:  44%|█████████████████████████▏                                | 114/262 [05:06<07:19,  2.97s/folder]

[OK] EPT2022AD46_KOS_NODDI32: copied 1 file(s) to D:\JHAhn\8641_conductivity\DTI_ALPS\2_Dementia\EPT2022\EPT2022AD46_KOS_NODDI32\Results\CTI

] EPT2022AD47_KPK_NODDI32] → Results\CTI:   0%|                                             | 0/1 [00:00<?, ?file/s]
] EPT2022AD47_KPK_NODDI32] → Results\CTI: 100%|█████████████████████████████████████| 1/1 [00:03<00:00,  3.36s/file]
CTI_ALPS folders:  44%|█████████████████████████▍                                | 115/262 [05:10<07:48,  3.18s/folder]

[OK] EPT2022AD47_KPK_NODDI32: copied 1 file(s) to D:\JHAhn\8641_conductivity\DTI_ALPS\2_Dementia\EPT2022\EPT2022AD47_KPK_NODDI32\Results\CTI

] EPT2022AD48_HJJ_NODDI32] → Results\CTI:   0%|                                             | 0/1 [00:00<?, ?file/s]
] EPT2022AD48_HJJ_NODDI32] → Results\CTI: 100%|█████████████████████████████████████| 1/1 [00:01<00:00,  1.76s/file]
CTI_ALPS folders:  44%|█████████████████████████▋                                | 116/262 [05:11<06:45,  2.78s/folder]

[OK] EPT2022AD48_HJJ_NODDI32: copied 1 file(s) to D:\JHAhn\8641_conductivity\DTI_ALPS\2_Dementia\EPT2022\EPT2022AD48_HJJ_NODDI32\Results\CTI

] EPT2022AD49_PCS_NODDI32] → Results\CTI:   0%|                                             | 0/1 [00:00<?, ?file/s]
] EPT2022AD49_PCS_NODDI32] → Results\CTI: 100%|█████████████████████████████████████| 1/1 [00:01<00:00,  1.11s/file]
CTI_ALPS folders:  45%|█████████████████████████▉                                | 117/262 [05:13<05:31,  2.29s/folder]

[OK] EPT2022AD49_PCS_NODDI32: copied 1 file(s) to D:\JHAhn\8641_conductivity\DTI_ALPS\2_Dementia\EPT2022\EPT2022AD49_PCS_NODDI32\Results\CTI

] EPT2022AD50_YYH_NODDI32] → Results\CTI:   0%|                                             | 0/1 [00:00<?, ?file/s]
] EPT2022AD50_YYH_NODDI32] → Results\CTI: 100%|█████████████████████████████████████| 1/1 [00:03<00:00,  3.74s/file]
CTI_ALPS folders:  45%|██████████████████████████                                | 118/262 [05:17<06:40,  2.78s/folder]

[OK] EPT2022AD50_YYH_NODDI32: copied 1 file(s) to D:\JHAhn\8641_conductivity\DTI_ALPS\2_Dementia\EPT2022\EPT2022AD50_YYH_NODDI32\Results\CTI

] EPT2022AD51_KBS_NODDI32] → Results\CTI:   0%|                                             | 0/1 [00:00<?, ?file/s]
] EPT2022AD51_KBS_NODDI32] → Results\CTI: 100%|█████████████████████████████████████| 1/1 [00:01<00:00,  1.41s/file]
CTI_ALPS folders:  45%|██████████████████████████▎                               | 119/262 [05:18<05:45,  2.42s/folder]

[OK] EPT2022AD51_KBS_NODDI32: copied 1 file(s) to D:\JHAhn\8641_conductivity\DTI_ALPS\2_Dementia\EPT2022\EPT2022AD51_KBS_NODDI32\Results\CTI

] EPT2022AD52_POA_NODDI32] → Results\CTI:   0%|                                             | 0/1 [00:00<?, ?file/s]
] EPT2022AD52_POA_NODDI32] → Results\CTI: 100%|█████████████████████████████████████| 1/1 [00:01<00:00,  1.67s/file]
CTI_ALPS folders:  46%|██████████████████████████▌                               | 120/262 [05:20<05:18,  2.24s/folder]

[OK] EPT2022AD52_POA_NODDI32: copied 1 file(s) to D:\JHAhn\8641_conductivity\DTI_ALPS\2_Dementia\EPT2022\EPT2022AD52_POA_NODDI32\Results\CTI

] EPT2022AD53_KJD_NODDI32] → Results\CTI:   0%|                                             | 0/1 [00:00<?, ?file/s]
] EPT2022AD53_KJD_NODDI32] → Results\CTI: 100%|█████████████████████████████████████| 1/1 [00:02<00:00,  2.41s/file]
CTI_ALPS folders:  46%|██████████████████████████▊                               | 121/262 [05:23<05:36,  2.39s/folder]

[OK] EPT2022AD53_KJD_NODDI32: copied 1 file(s) to D:\JHAhn\8641_conductivity\DTI_ALPS\2_Dementia\EPT2022\EPT2022AD53_KJD_NODDI32\Results\CTI

] EPT2022AD54_GJJ_NODDI32] → Results\CTI:   0%|                                             | 0/1 [00:00<?, ?file/s]
] EPT2022AD54_GJJ_NODDI32] → Results\CTI: 100%|█████████████████████████████████████| 1/1 [00:04<00:00,  4.87s/file]
CTI_ALPS folders:  47%|███████████████████████████                               | 122/262 [05:28<07:21,  3.16s/folder]

[OK] EPT2022AD54_GJJ_NODDI32: copied 1 file(s) to D:\JHAhn\8641_conductivity\DTI_ALPS\2_Dementia\EPT2022\EPT2022AD54_GJJ_NODDI32\Results\CTI

] EPT2022AD55_SSB_NODDI32] → Results\CTI:   0%|                                             | 0/1 [00:00<?, ?file/s]
] EPT2022AD55_SSB_NODDI32] → Results\CTI: 100%|█████████████████████████████████████| 1/1 [00:01<00:00,  1.19s/file]
CTI_ALPS folders:  47%|███████████████████████████▏                              | 123/262 [05:29<06:25,  2.77s/folder]

[OK] EPT2022AD55_SSB_NODDI32: copied 1 file(s) to D:\JHAhn\8641_conductivity\DTI_ALPS\2_Dementia\EPT2022\EPT2022AD55_SSB_NODDI32\Results\CTI

] EPT2022AD56_SKS_NODDI32] → Results\CTI:   0%|                                             | 0/1 [00:00<?, ?file/s]
] EPT2022AD56_SKS_NODDI32] → Results\CTI: 100%|█████████████████████████████████████| 1/1 [00:02<00:00,  2.30s/file]
CTI_ALPS folders:  47%|███████████████████████████▍                              | 124/262 [05:32<06:13,  2.70s/folder]

[OK] EPT2022AD56_SKS_NODDI32: copied 1 file(s) to D:\JHAhn\8641_conductivity\DTI_ALPS\2_Dementia\EPT2022\EPT2022AD56_SKS_NODDI32\Results\CTI

] EPT2022AD57_KYS_NODDI32] → Results\CTI:   0%|                                             | 0/1 [00:00<?, ?file/s]
] EPT2022AD57_KYS_NODDI32] → Results\CTI: 100%|█████████████████████████████████████| 1/1 [00:01<00:00,  1.81s/file]
CTI_ALPS folders:  48%|███████████████████████████▋                              | 125/262 [05:34<05:37,  2.46s/folder]

[OK] EPT2022AD57_KYS_NODDI32: copied 1 file(s) to D:\JHAhn\8641_conductivity\DTI_ALPS\2_Dementia\EPT2022\EPT2022AD57_KYS_NODDI32\Results\CTI

] EPT2022AD58_PYR_NODDI32] → Results\CTI:   0%|                                             | 0/1 [00:00<?, ?file/s]
] EPT2022AD58_PYR_NODDI32] → Results\CTI: 100%|█████████████████████████████████████| 1/1 [00:03<00:00,  3.74s/file]
CTI_ALPS folders:  48%|███████████████████████████▉                              | 126/262 [05:38<06:35,  2.91s/folder]

[OK] EPT2022AD58_PYR_NODDI32: copied 1 file(s) to D:\JHAhn\8641_conductivity\DTI_ALPS\2_Dementia\EPT2022\EPT2022AD58_PYR_NODDI32\Results\CTI

] EPT2022AD59_SNO_NODDI32] → Results\CTI:   0%|                                             | 0/1 [00:00<?, ?file/s]
] EPT2022AD59_SNO_NODDI32] → Results\CTI: 100%|█████████████████████████████████████| 1/1 [00:02<00:00,  2.85s/file]
CTI_ALPS folders:  48%|████████████████████████████                              | 127/262 [05:41<06:41,  2.98s/folder]

[OK] EPT2022AD59_SNO_NODDI32: copied 1 file(s) to D:\JHAhn\8641_conductivity\DTI_ALPS\2_Dementia\EPT2022\EPT2022AD59_SNO_NODDI32\Results\CTI

] EPT2022AD60_KYD_NODDI32] → Results\CTI:   0%|                                             | 0/1 [00:00<?, ?file/s]
] EPT2022AD60_KYD_NODDI32] → Results\CTI: 100%|█████████████████████████████████████| 1/1 [00:01<00:00,  1.55s/file]
CTI_ALPS folders:  49%|████████████████████████████▎                             | 128/262 [05:43<05:43,  2.56s/folder]

[OK] EPT2022AD60_KYD_NODDI32: copied 1 file(s) to D:\JHAhn\8641_conductivity\DTI_ALPS\2_Dementia\EPT2022\EPT2022AD60_KYD_NODDI32\Results\CTI

] EPT2022AD61_KYJ_NODDI32] → Results\CTI:   0%|                                             | 0/1 [00:00<?, ?file/s]
] EPT2022AD61_KYJ_NODDI32] → Results\CTI: 100%|█████████████████████████████████████| 1/1 [00:01<00:00,  1.41s/file]
CTI_ALPS folders:  49%|████████████████████████████▌                             | 129/262 [05:44<04:56,  2.23s/folder]

[OK] EPT2022AD61_KYJ_NODDI32: copied 1 file(s) to D:\JHAhn\8641_conductivity\DTI_ALPS\2_Dementia\EPT2022\EPT2022AD61_KYJ_NODDI32\Results\CTI

] EPT2022AD62_LHJ_NODDI32] → Results\CTI:   0%|                                             | 0/1 [00:00<?, ?file/s]
] EPT2022AD62_LHJ_NODDI32] → Results\CTI: 100%|█████████████████████████████████████| 1/1 [00:02<00:00,  2.80s/file]
CTI_ALPS folders:  50%|████████████████████████████▊                             | 130/262 [05:47<05:22,  2.44s/folder]

[OK] EPT2022AD62_LHJ_NODDI32: copied 1 file(s) to D:\JHAhn\8641_conductivity\DTI_ALPS\2_Dementia\EPT2022\EPT2022AD62_LHJ_NODDI32\Results\CTI

] EPT2023AD01_KMH_NODDI32] → Results\CTI:   0%|                                             | 0/1 [00:00<?, ?file/s]
] EPT2023AD01_KMH_NODDI32] → Results\CTI: 100%|█████████████████████████████████████| 1/1 [00:04<00:00,  4.23s/file]
CTI_ALPS folders:  50%|█████████████████████████████                             | 131/262 [05:51<06:30,  2.98s/folder]

[OK] EPT2023AD01_KMH_NODDI32: copied 1 file(s) to D:\JHAhn\8641_conductivity\DTI_ALPS\2_Dementia\EPT2023\EPT2023AD01_KMH_NODDI32\Results\CTI

] EPT2023AD02_HUI_NODDI32] → Results\CTI:   0%|                                             | 0/1 [00:00<?, ?file/s]
] EPT2023AD02_HUI_NODDI32] → Results\CTI: 100%|█████████████████████████████████████| 1/1 [00:02<00:00,  2.22s/file]
CTI_ALPS folders:  50%|█████████████████████████████▏                            | 132/262 [05:53<05:58,  2.76s/folder]

[OK] EPT2023AD02_HUI_NODDI32: copied 1 file(s) to D:\JHAhn\8641_conductivity\DTI_ALPS\2_Dementia\EPT2023\EPT2023AD02_HUI_NODDI32\Results\CTI

] EPT2023AD03_MSJ_NODDI32] → Results\CTI:   0%|                                             | 0/1 [00:00<?, ?file/s]
] EPT2023AD03_MSJ_NODDI32] → Results\CTI: 100%|█████████████████████████████████████| 1/1 [00:01<00:00,  1.96s/file]
CTI_ALPS folders:  51%|█████████████████████████████▍                            | 133/262 [05:55<05:25,  2.52s/folder]

[OK] EPT2023AD03_MSJ_NODDI32: copied 1 file(s) to D:\JHAhn\8641_conductivity\DTI_ALPS\2_Dementia\EPT2023\EPT2023AD03_MSJ_NODDI32\Results\CTI

] EPT2023AD04_KJU_NODDI32] → Results\CTI:   0%|                                             | 0/1 [00:00<?, ?file/s]
] EPT2023AD04_KJU_NODDI32] → Results\CTI: 100%|█████████████████████████████████████| 1/1 [00:02<00:00,  2.36s/file]
CTI_ALPS folders:  51%|█████████████████████████████▋                            | 134/262 [05:58<05:16,  2.48s/folder]

[OK] EPT2023AD04_KJU_NODDI32: copied 1 file(s) to D:\JHAhn\8641_conductivity\DTI_ALPS\2_Dementia\EPT2023\EPT2023AD04_KJU_NODDI32\Results\CTI

] EPT2023AD05_JIS_NODDI32] → Results\CTI:   0%|                                             | 0/1 [00:00<?, ?file/s]
] EPT2023AD05_JIS_NODDI32] → Results\CTI: 100%|█████████████████████████████████████| 1/1 [00:03<00:00,  3.72s/file]
CTI_ALPS folders:  52%|█████████████████████████████▉                            | 135/262 [06:02<06:02,  2.85s/folder]

[OK] EPT2023AD05_JIS_NODDI32: copied 1 file(s) to D:\JHAhn\8641_conductivity\DTI_ALPS\2_Dementia\EPT2023\EPT2023AD05_JIS_NODDI32\Results\CTI

] EPT2023AD06_LSJ_NODDI32] → Results\CTI:   0%|                                             | 0/1 [00:00<?, ?file/s]
] EPT2023AD06_LSJ_NODDI32] → Results\CTI: 100%|█████████████████████████████████████| 1/1 [00:02<00:00,  2.71s/file]
CTI_ALPS folders:  52%|██████████████████████████████                            | 136/262 [06:04<05:54,  2.81s/folder]

[OK] EPT2023AD06_LSJ_NODDI32: copied 1 file(s) to D:\JHAhn\8641_conductivity\DTI_ALPS\2_Dementia\EPT2023\EPT2023AD06_LSJ_NODDI32\Results\CTI

] EPT2023AD07_WGJ_NODDI32] → Results\CTI:   0%|                                             | 0/1 [00:00<?, ?file/s]
] EPT2023AD07_WGJ_NODDI32] → Results\CTI: 100%|█████████████████████████████████████| 1/1 [00:01<00:00,  1.57s/file]
CTI_ALPS folders:  52%|██████████████████████████████▎                           | 137/262 [06:06<05:05,  2.44s/folder]

[OK] EPT2023AD07_WGJ_NODDI32: copied 1 file(s) to D:\JHAhn\8641_conductivity\DTI_ALPS\2_Dementia\EPT2023\EPT2023AD07_WGJ_NODDI32\Results\CTI

] EPT2023AD08_KMS_NODDI32] → Results\CTI:   0%|                                             | 0/1 [00:00<?, ?file/s]
] EPT2023AD08_KMS_NODDI32] → Results\CTI: 100%|█████████████████████████████████████| 1/1 [00:02<00:00,  2.16s/file]
CTI_ALPS folders:  53%|██████████████████████████████▌                           | 138/262 [06:08<04:53,  2.37s/folder]

[OK] EPT2023AD08_KMS_NODDI32: copied 1 file(s) to D:\JHAhn\8641_conductivity\DTI_ALPS\2_Dementia\EPT2023\EPT2023AD08_KMS_NODDI32\Results\CTI

] EPT2023AD09_LSU_NODDI32] → Results\CTI:   0%|                                             | 0/1 [00:00<?, ?file/s]
] EPT2023AD09_LSU_NODDI32] → Results\CTI: 100%|█████████████████████████████████████| 1/1 [00:02<00:00,  2.05s/file]
CTI_ALPS folders:  53%|██████████████████████████████▊                           | 139/262 [06:10<04:39,  2.27s/folder]

[OK] EPT2023AD09_LSU_NODDI32: copied 1 file(s) to D:\JHAhn\8641_conductivity\DTI_ALPS\2_Dementia\EPT2023\EPT2023AD09_LSU_NODDI32\Results\CTI

] EPT2023AD10_JBY_NODDI32] → Results\CTI:   0%|                                             | 0/1 [00:00<?, ?file/s]
] EPT2023AD10_JBY_NODDI32] → Results\CTI: 100%|█████████████████████████████████████| 1/1 [00:05<00:00,  5.38s/file]
CTI_ALPS folders:  53%|██████████████████████████████▉                           | 140/262 [06:15<06:32,  3.21s/folder]

[OK] EPT2023AD10_JBY_NODDI32: copied 1 file(s) to D:\JHAhn\8641_conductivity\DTI_ALPS\2_Dementia\EPT2023\EPT2023AD10_JBY_NODDI32\Results\CTI

] EPT2023AD11_HSY_NODDI32] → Results\CTI:   0%|                                             | 0/1 [00:00<?, ?file/s]
] EPT2023AD11_HSY_NODDI32] → Results\CTI: 100%|█████████████████████████████████████| 1/1 [00:01<00:00,  1.44s/file]
CTI_ALPS folders:  54%|███████████████████████████████▏                          | 141/262 [06:17<05:25,  2.69s/folder]

[OK] EPT2023AD11_HSY_NODDI32: copied 1 file(s) to D:\JHAhn\8641_conductivity\DTI_ALPS\2_Dementia\EPT2023\EPT2023AD11_HSY_NODDI32\Results\CTI

] EPT2023AD12_YJS_NODDI32] → Results\CTI:   0%|                                             | 0/1 [00:00<?, ?file/s]
] EPT2023AD12_YJS_NODDI32] → Results\CTI: 100%|█████████████████████████████████████| 1/1 [00:01<00:00,  1.89s/file]
CTI_ALPS folders:  54%|███████████████████████████████▍                          | 142/262 [06:19<04:54,  2.46s/folder]

[OK] EPT2023AD12_YJS_NODDI32: copied 1 file(s) to D:\JHAhn\8641_conductivity\DTI_ALPS\2_Dementia\EPT2023\EPT2023AD12_YJS_NODDI32\Results\CTI

] EPT2023AD13_WOB_NODDI32] → Results\CTI:   0%|                                             | 0/1 [00:00<?, ?file/s]
] EPT2023AD13_WOB_NODDI32] → Results\CTI: 100%|█████████████████████████████████████| 1/1 [00:01<00:00,  1.72s/file]
CTI_ALPS folders:  55%|███████████████████████████████▋                          | 143/262 [06:21<04:26,  2.24s/folder]

[OK] EPT2023AD13_WOB_NODDI32: copied 1 file(s) to D:\JHAhn\8641_conductivity\DTI_ALPS\2_Dementia\EPT2023\EPT2023AD13_WOB_NODDI32\Results\CTI

] EPT2023AD14_LMS_NODDI32] → Results\CTI:   0%|                                             | 0/1 [00:00<?, ?file/s]
] EPT2023AD14_LMS_NODDI32] → Results\CTI: 100%|█████████████████████████████████████| 1/1 [00:04<00:00,  4.04s/file]
CTI_ALPS folders:  55%|███████████████████████████████▉                          | 144/262 [06:25<05:30,  2.80s/folder]

[OK] EPT2023AD14_LMS_NODDI32: copied 1 file(s) to D:\JHAhn\8641_conductivity\DTI_ALPS\2_Dementia\EPT2023\EPT2023AD14_LMS_NODDI32\Results\CTI

] EPT2023AD15_LSJ_NODDI32] → Results\CTI:   0%|                                             | 0/1 [00:00<?, ?file/s]
] EPT2023AD15_LSJ_NODDI32] → Results\CTI: 100%|█████████████████████████████████████| 1/1 [00:03<00:00,  3.26s/file]
CTI_ALPS folders:  55%|████████████████████████████████                          | 145/262 [06:28<05:44,  2.95s/folder]

[OK] EPT2023AD15_LSJ_NODDI32: copied 1 file(s) to D:\JHAhn\8641_conductivity\DTI_ALPS\2_Dementia\EPT2023\EPT2023AD15_LSJ_NODDI32\Results\CTI

] EPT2023AD16_JHG_NODDI32] → Results\CTI:   0%|                                             | 0/1 [00:00<?, ?file/s]
] EPT2023AD16_JHG_NODDI32] → Results\CTI: 100%|█████████████████████████████████████| 1/1 [00:02<00:00,  2.08s/file]
CTI_ALPS folders:  56%|████████████████████████████████▎                         | 146/262 [06:30<05:11,  2.69s/folder]

[OK] EPT2023AD16_JHG_NODDI32: copied 1 file(s) to D:\JHAhn\8641_conductivity\DTI_ALPS\2_Dementia\EPT2023\EPT2023AD16_JHG_NODDI32\Results\CTI

] EPT2023AD17_LHG_NODDI32] → Results\CTI:   0%|                                             | 0/1 [00:00<?, ?file/s]
] EPT2023AD17_LHG_NODDI32] → Results\CTI: 100%|█████████████████████████████████████| 1/1 [00:01<00:00,  1.57s/file]
CTI_ALPS folders:  56%|████████████████████████████████▌                         | 147/262 [06:32<04:30,  2.36s/folder]

[OK] EPT2023AD17_LHG_NODDI32: copied 1 file(s) to D:\JHAhn\8641_conductivity\DTI_ALPS\2_Dementia\EPT2023\EPT2023AD17_LHG_NODDI32\Results\CTI

] EPT2023AD18_LMS_NODDI32] → Results\CTI:   0%|                                             | 0/1 [00:00<?, ?file/s]
] EPT2023AD18_LMS_NODDI32] → Results\CTI: 100%|█████████████████████████████████████| 1/1 [00:02<00:00,  2.39s/file]
CTI_ALPS folders:  56%|████████████████████████████████▊                         | 148/262 [06:34<04:30,  2.37s/folder]

[OK] EPT2023AD18_LMS_NODDI32: copied 1 file(s) to D:\JHAhn\8641_conductivity\DTI_ALPS\2_Dementia\EPT2023\EPT2023AD18_LMS_NODDI32\Results\CTI

] EPT2023AD19_KTG_NODDI32] → Results\CTI:   0%|                                             | 0/1 [00:00<?, ?file/s]
] EPT2023AD19_KTG_NODDI32] → Results\CTI: 100%|█████████████████████████████████████| 1/1 [00:04<00:00,  4.51s/file]
CTI_ALPS folders:  57%|████████████████████████████████▉                         | 149/262 [06:39<05:41,  3.02s/folder]

[OK] EPT2023AD19_KTG_NODDI32: copied 1 file(s) to D:\JHAhn\8641_conductivity\DTI_ALPS\2_Dementia\EPT2023\EPT2023AD19_KTG_NODDI32\Results\CTI

] EPT2023AD20_CGJ_NODDI32] → Results\CTI:   0%|                                             | 0/1 [00:00<?, ?file/s]
] EPT2023AD20_CGJ_NODDI32] → Results\CTI: 100%|█████████████████████████████████████| 1/1 [00:02<00:00,  2.81s/file]
CTI_ALPS folders:  57%|█████████████████████████████████▏                        | 150/262 [06:41<05:31,  2.96s/folder]

[OK] EPT2023AD20_CGJ_NODDI32: copied 1 file(s) to D:\JHAhn\8641_conductivity\DTI_ALPS\2_Dementia\EPT2023\EPT2023AD20_CGJ_NODDI32\Results\CTI

] EPT2023AD21_PDB_NODDI32] → Results\CTI:   0%|                                             | 0/1 [00:00<?, ?file/s]
] EPT2023AD21_PDB_NODDI32] → Results\CTI: 100%|█████████████████████████████████████| 1/1 [00:01<00:00,  1.23s/file]
CTI_ALPS folders:  58%|█████████████████████████████████▍                        | 151/262 [06:43<04:30,  2.44s/folder]

[OK] EPT2023AD21_PDB_NODDI32: copied 1 file(s) to D:\JHAhn\8641_conductivity\DTI_ALPS\2_Dementia\EPT2023\EPT2023AD21_PDB_NODDI32\Results\CTI

] EPT2023AD22_KID_NODDI32] → Results\CTI:   0%|                                             | 0/1 [00:00<?, ?file/s]
] EPT2023AD22_KID_NODDI32] → Results\CTI: 100%|█████████████████████████████████████| 1/1 [00:02<00:00,  2.40s/file]
CTI_ALPS folders:  58%|█████████████████████████████████▋                        | 152/262 [06:45<04:27,  2.43s/folder]

[OK] EPT2023AD22_KID_NODDI32: copied 1 file(s) to D:\JHAhn\8641_conductivity\DTI_ALPS\2_Dementia\EPT2023\EPT2023AD22_KID_NODDI32\Results\CTI

] EPT2024AD01_KJI_NODDI32] → Results\CTI:   0%|                                             | 0/1 [00:00<?, ?file/s]
] EPT2024AD01_KJI_NODDI32] → Results\CTI: 100%|█████████████████████████████████████| 1/1 [00:04<00:00,  4.02s/file]
CTI_ALPS folders:  58%|█████████████████████████████████▊                        | 153/262 [06:49<05:23,  2.97s/folder]

[OK] EPT2024AD01_KJI_NODDI32: copied 1 file(s) to D:\JHAhn\8641_conductivity\DTI_ALPS\2_Dementia\EPT2024\EPT2024AD01_KJI_NODDI32\Results\CTI

] EPT2024AD02_HUY_NODDI32] → Results\CTI:   0%|                                             | 0/1 [00:00<?, ?file/s]
] EPT2024AD02_HUY_NODDI32] → Results\CTI: 100%|█████████████████████████████████████| 1/1 [00:01<00:00,  1.36s/file]
CTI_ALPS folders:  59%|██████████████████████████████████                        | 154/262 [06:51<04:30,  2.50s/folder]

[OK] EPT2024AD02_HUY_NODDI32: copied 1 file(s) to D:\JHAhn\8641_conductivity\DTI_ALPS\2_Dementia\EPT2024\EPT2024AD02_HUY_NODDI32\Results\CTI

] EPT2024AD03_NGS_NODDI32] → Results\CTI:   0%|                                             | 0/1 [00:00<?, ?file/s]
] EPT2024AD03_NGS_NODDI32] → Results\CTI: 100%|█████████████████████████████████████| 1/1 [00:01<00:00,  1.89s/file]
CTI_ALPS folders:  59%|██████████████████████████████████▎                       | 155/262 [06:53<04:09,  2.33s/folder]

[OK] EPT2024AD03_NGS_NODDI32: copied 1 file(s) to D:\JHAhn\8641_conductivity\DTI_ALPS\2_Dementia\EPT2024\EPT2024AD03_NGS_NODDI32\Results\CTI

] EPT2024AD04_LDS_NODDI32] → Results\CTI:   0%|                                             | 0/1 [00:00<?, ?file/s]
] EPT2024AD04_LDS_NODDI32] → Results\CTI: 100%|█████████████████████████████████████| 1/1 [00:01<00:00,  1.38s/file]
CTI_ALPS folders:  60%|██████████████████████████████████▌                       | 156/262 [06:54<03:40,  2.08s/folder]

[OK] EPT2024AD04_LDS_NODDI32: copied 1 file(s) to D:\JHAhn\8641_conductivity\DTI_ALPS\2_Dementia\EPT2024\EPT2024AD04_LDS_NODDI32\Results\CTI

] EPT2024AD05_KEJ_NODDI32] → Results\CTI:   0%|                                             | 0/1 [00:00<?, ?file/s]
] EPT2024AD05_KEJ_NODDI32] → Results\CTI: 100%|█████████████████████████████████████| 1/1 [00:02<00:00,  2.57s/file]
CTI_ALPS folders:  60%|██████████████████████████████████▊                       | 157/262 [06:57<03:58,  2.27s/folder]

[OK] EPT2024AD05_KEJ_NODDI32: copied 1 file(s) to D:\JHAhn\8641_conductivity\DTI_ALPS\2_Dementia\EPT2024\EPT2024AD05_KEJ_NODDI32\Results\CTI

] EPT2024AD06_PYG_NODDI32] → Results\CTI:   0%|                                             | 0/1 [00:00<?, ?file/s]
] EPT2024AD06_PYG_NODDI32] → Results\CTI: 100%|█████████████████████████████████████| 1/1 [00:04<00:00,  4.46s/file]
CTI_ALPS folders:  60%|██████████████████████████████████▉                       | 158/262 [07:01<05:09,  2.98s/folder]

[OK] EPT2024AD06_PYG_NODDI32: copied 1 file(s) to D:\JHAhn\8641_conductivity\DTI_ALPS\2_Dementia\EPT2024\EPT2024AD06_PYG_NODDI32\Results\CTI

] EPT2024AD07_JGJ_NODDI32] → Results\CTI:   0%|                                             | 0/1 [00:00<?, ?file/s]
] EPT2024AD07_JGJ_NODDI32] → Results\CTI: 100%|█████████████████████████████████████| 1/1 [00:02<00:00,  2.85s/file]
CTI_ALPS folders:  61%|███████████████████████████████████▏                      | 159/262 [07:04<05:08,  3.00s/folder]

[OK] EPT2024AD07_JGJ_NODDI32: copied 1 file(s) to D:\JHAhn\8641_conductivity\DTI_ALPS\2_Dementia\EPT2024\EPT2024AD07_JGJ_NODDI32\Results\CTI

] EPT2024AD08_LMS_NODDI32] → Results\CTI:   0%|                                             | 0/1 [00:00<?, ?file/s]
] EPT2024AD08_LMS_NODDI32] → Results\CTI: 100%|█████████████████████████████████████| 1/1 [00:01<00:00,  1.12s/file]
CTI_ALPS folders:  61%|███████████████████████████████████▍                      | 160/262 [07:06<04:09,  2.44s/folder]

[OK] EPT2024AD08_LMS_NODDI32: copied 1 file(s) to D:\JHAhn\8641_conductivity\DTI_ALPS\2_Dementia\EPT2024\EPT2024AD08_LMS_NODDI32\Results\CTI

] EPT2024AD09_CSO_NODDI32] → Results\CTI:   0%|                                             | 0/1 [00:00<?, ?file/s]
] EPT2024AD09_CSO_NODDI32] → Results\CTI: 100%|█████████████████████████████████████| 1/1 [00:01<00:00,  1.43s/file]
CTI_ALPS folders:  61%|███████████████████████████████████▋                      | 161/262 [07:07<03:37,  2.16s/folder]

[OK] EPT2024AD09_CSO_NODDI32: copied 1 file(s) to D:\JHAhn\8641_conductivity\DTI_ALPS\2_Dementia\EPT2024\EPT2024AD09_CSO_NODDI32\Results\CTI

] EPT2024AD10_KCJ_NODDI32] → Results\CTI:   0%|                                             | 0/1 [00:00<?, ?file/s]
] EPT2024AD10_KCJ_NODDI32] → Results\CTI: 100%|█████████████████████████████████████| 1/1 [00:03<00:00,  3.80s/file]
CTI_ALPS folders:  62%|███████████████████████████████████▊                      | 162/262 [07:11<04:31,  2.72s/folder]

[OK] EPT2024AD10_KCJ_NODDI32: copied 1 file(s) to D:\JHAhn\8641_conductivity\DTI_ALPS\2_Dementia\EPT2024\EPT2024AD10_KCJ_NODDI32\Results\CTI

] EPT2024AD11_KHJ_NODDI32] → Results\CTI:   0%|                                             | 0/1 [00:00<?, ?file/s]
] EPT2024AD11_KHJ_NODDI32] → Results\CTI: 100%|█████████████████████████████████████| 1/1 [00:03<00:00,  3.95s/file]
CTI_ALPS folders:  62%|████████████████████████████████████                      | 163/262 [07:15<05:11,  3.15s/folder]

[OK] EPT2024AD11_KHJ_NODDI32: copied 1 file(s) to D:\JHAhn\8641_conductivity\DTI_ALPS\2_Dementia\EPT2024\EPT2024AD11_KHJ_NODDI32\Results\CTI

] EPT2024AD12_LDS_NODDI32] → Results\CTI:   0%|                                             | 0/1 [00:00<?, ?file/s]
] EPT2024AD12_LDS_NODDI32] → Results\CTI: 100%|█████████████████████████████████████| 1/1 [00:01<00:00,  1.29s/file]
CTI_ALPS folders:  63%|████████████████████████████████████▎                     | 164/262 [07:17<04:15,  2.61s/folder]

[OK] EPT2024AD12_LDS_NODDI32: copied 1 file(s) to D:\JHAhn\8641_conductivity\DTI_ALPS\2_Dementia\EPT2024\EPT2024AD12_LDS_NODDI32\Results\CTI

] EPT2024AD13_LTO_NODDI32] → Results\CTI:   0%|                                             | 0/1 [00:00<?, ?file/s]
] EPT2024AD13_LTO_NODDI32] → Results\CTI: 100%|█████████████████████████████████████| 1/1 [00:02<00:00,  2.57s/file]
CTI_ALPS folders:  63%|████████████████████████████████████▌                     | 165/262 [07:19<04:13,  2.62s/folder]

[OK] EPT2024AD13_LTO_NODDI32: copied 1 file(s) to D:\JHAhn\8641_conductivity\DTI_ALPS\2_Dementia\EPT2024\EPT2024AD13_LTO_NODDI32\Results\CTI

] HFC2020AD02_KS_NODDI32] → Results\CTI:   0%|                                              | 0/1 [00:00<?, ?file/s]
] HFC2020AD02_KS_NODDI32] → Results\CTI: 100%|██████████████████████████████████████| 1/1 [00:03<00:00,  3.73s/file]
CTI_ALPS folders:  63%|████████████████████████████████████▋                     | 166/262 [07:23<04:43,  2.95s/folder]

[OK] HFC2020AD02_KS_NODDI32: copied 1 file(s) to D:\JHAhn\8641_conductivity\DTI_ALPS\2_Dementia\EPT2020\HFC2020AD02_KS_NODDI32\Results\CTI

] HFC2021AD01_YMB_NODDI32] → Results\CTI:   0%|                                             | 0/1 [00:00<?, ?file/s]
] HFC2021AD01_YMB_NODDI32] → Results\CTI: 100%|█████████████████████████████████████| 1/1 [00:01<00:00,  1.53s/file]
CTI_ALPS folders:  64%|████████████████████████████████████▉                     | 167/262 [07:25<04:02,  2.55s/folder]

[OK] HFC2021AD01_YMB_NODDI32: copied 1 file(s) to D:\JHAhn\8641_conductivity\DTI_ALPS\2_Dementia\EPT2021\HFC2021AD01_YMB_NODDI32\Results\CTI

] HFC2021AD02_SHS_NODDI32] → Results\CTI:   0%|                                             | 0/1 [00:00<?, ?file/s]
] HFC2021AD02_SHS_NODDI32] → Results\CTI: 100%|█████████████████████████████████████| 1/1 [00:02<00:00,  2.19s/file]
CTI_ALPS folders:  64%|█████████████████████████████████████▏                    | 168/262 [07:27<03:51,  2.46s/folder]

[OK] HFC2021AD02_SHS_NODDI32: copied 1 file(s) to D:\JHAhn\8641_conductivity\DTI_ALPS\2_Dementia\EPT2021\HFC2021AD02_SHS_NODDI32\Results\CTI

] MREPT2019AD01_KMO_NODDI32] → Results\CTI:   0%|                                           | 0/1 [00:00<?, ?file/s]
] MREPT2019AD01_KMO_NODDI32] → Results\CTI: 100%|███████████████████████████████████| 1/1 [00:01<00:00,  1.90s/file]
CTI_ALPS folders:  65%|█████████████████████████████████████▍                    | 169/262 [07:29<03:33,  2.30s/folder]

[OK] MREPT2019AD01_KMO_NODDI32: copied 1 file(s) to D:\JHAhn\8641_conductivity\DTI_ALPS\2_Dementia\EPT2019\prep\MREPT2019AD01_KMO_NODDI32\Results\CTI

] MREPT2019AD02_JSJ_NODDI32] → Results\CTI:   0%|                                           | 0/1 [00:00<?, ?file/s]
] MREPT2019AD02_JSJ_NODDI32] → Results\CTI: 100%|███████████████████████████████████| 1/1 [00:02<00:00,  2.69s/file]
CTI_ALPS folders:  65%|█████████████████████████████████████▋                    | 170/262 [07:31<03:42,  2.42s/folder]

[OK] MREPT2019AD02_JSJ_NODDI32: copied 1 file(s) to D:\JHAhn\8641_conductivity\DTI_ALPS\2_Dementia\EPT2019\prep\MREPT2019AD02_JSJ_NODDI32\Results\CTI

] MREPT2019AD03_OHS_NODDI32] → Results\CTI:   0%|                                           | 0/1 [00:00<?, ?file/s]
] MREPT2019AD03_OHS_NODDI32] → Results\CTI: 100%|███████████████████████████████████| 1/1 [00:05<00:00,  5.04s/file]
CTI_ALPS folders:  65%|█████████████████████████████████████▊                    | 171/262 [07:37<04:52,  3.21s/folder]

[OK] MREPT2019AD03_OHS_NODDI32: copied 1 file(s) to D:\JHAhn\8641_conductivity\DTI_ALPS\2_Dementia\EPT2019\prep\MREPT2019AD03_OHS_NODDI32\Results\CTI

] MREPT2019AD04_CSY_NODDI32] → Results\CTI:   0%|                                           | 0/1 [00:00<?, ?file/s]
] MREPT2019AD04_CSY_NODDI32] → Results\CTI: 100%|███████████████████████████████████| 1/1 [00:02<00:00,  2.23s/file]
CTI_ALPS folders:  66%|██████████████████████████████████████                    | 172/262 [07:39<04:22,  2.92s/folder]

[OK] MREPT2019AD04_CSY_NODDI32: copied 1 file(s) to D:\JHAhn\8641_conductivity\DTI_ALPS\2_Dementia\EPT2019\prep\MREPT2019AD04_CSY_NODDI32\Results\CTI

] MREPT2019AD05_KJI_NODDI32] → Results\CTI:   0%|                                           | 0/1 [00:00<?, ?file/s]
] MREPT2019AD05_KJI_NODDI32] → Results\CTI: 100%|███████████████████████████████████| 1/1 [00:01<00:00,  1.06s/file]
CTI_ALPS folders:  66%|██████████████████████████████████████▎                   | 173/262 [07:40<03:30,  2.36s/folder]

[OK] MREPT2019AD05_KJI_NODDI32: copied 1 file(s) to D:\JHAhn\8641_conductivity\DTI_ALPS\2_Dementia\EPT2019\prep\MREPT2019AD05_KJI_NODDI32\Results\CTI

] MREPT2019AD06_CKJ_NODDI32] → Results\CTI:   0%|                                           | 0/1 [00:00<?, ?file/s]
] MREPT2019AD06_CKJ_NODDI32] → Results\CTI: 100%|███████████████████████████████████| 1/1 [00:02<00:00,  2.36s/file]
CTI_ALPS folders:  66%|██████████████████████████████████████▌                   | 174/262 [07:42<03:28,  2.37s/folder]

[OK] MREPT2019AD06_CKJ_NODDI32: copied 1 file(s) to D:\JHAhn\8641_conductivity\DTI_ALPS\2_Dementia\EPT2019\prep\MREPT2019AD06_CKJ_NODDI32\Results\CTI

] MREPT2019AD07_LJH_NODDI32] → Results\CTI:   0%|                                           | 0/1 [00:00<?, ?file/s]
] MREPT2019AD07_LJH_NODDI32] → Results\CTI: 100%|███████████████████████████████████| 1/1 [00:04<00:00,  4.16s/file]
CTI_ALPS folders:  67%|██████████████████████████████████████▋                   | 175/262 [07:46<04:13,  2.91s/folder]

[OK] MREPT2019AD07_LJH_NODDI32: copied 1 file(s) to D:\JHAhn\8641_conductivity\DTI_ALPS\2_Dementia\EPT2019\prep\MREPT2019AD07_LJH_NODDI32\Results\CTI

] MREPT2019AD09_LKS_NODDI32] → Results\CTI:   0%|                                           | 0/1 [00:00<?, ?file/s]
] MREPT2019AD09_LKS_NODDI32] → Results\CTI: 100%|███████████████████████████████████| 1/1 [00:03<00:00,  3.44s/file]
CTI_ALPS folders:  67%|██████████████████████████████████████▉                   | 176/262 [07:50<04:24,  3.07s/folder]

[OK] MREPT2019AD09_LKS_NODDI32: copied 1 file(s) to D:\JHAhn\8641_conductivity\DTI_ALPS\2_Dementia\EPT2019\prep\MREPT2019AD09_LKS_NODDI32\Results\CTI

] MREPT2019AD10_KJL_NODDI32] → Results\CTI:   0%|                                           | 0/1 [00:00<?, ?file/s]
] MREPT2019AD10_KJL_NODDI32] → Results\CTI: 100%|███████████████████████████████████| 1/1 [00:01<00:00,  1.13s/file]
CTI_ALPS folders:  68%|███████████████████████████████████████▏                  | 177/262 [07:51<03:32,  2.50s/folder]

[OK] MREPT2019AD10_KJL_NODDI32: copied 1 file(s) to D:\JHAhn\8641_conductivity\DTI_ALPS\2_Dementia\EPT2019\prep\MREPT2019AD10_KJL_NODDI32\Results\CTI

] MREPT2019AD11_CKS_NODDI32] → Results\CTI:   0%|                                           | 0/1 [00:00<?, ?file/s]
] MREPT2019AD11_CKS_NODDI32] → Results\CTI: 100%|███████████████████████████████████| 1/1 [00:01<00:00,  1.26s/file]
CTI_ALPS folders:  68%|███████████████████████████████████████▍                  | 178/262 [07:52<02:59,  2.13s/folder]

[OK] MREPT2019AD11_CKS_NODDI32: copied 1 file(s) to D:\JHAhn\8641_conductivity\DTI_ALPS\2_Dementia\EPT2019\prep\MREPT2019AD11_CKS_NODDI32\Results\CTI

] MREPT2019AD13_KHS_NODDI32] → Results\CTI:   0%|                                           | 0/1 [00:00<?, ?file/s]
] MREPT2019AD13_KHS_NODDI32] → Results\CTI: 100%|███████████████████████████████████| 1/1 [00:02<00:00,  2.60s/file]
CTI_ALPS folders:  68%|███████████████████████████████████████▋                  | 179/262 [07:55<03:08,  2.28s/folder]

[OK] MREPT2019AD13_KHS_NODDI32: copied 1 file(s) to D:\JHAhn\8641_conductivity\DTI_ALPS\2_Dementia\EPT2019\prep\MREPT2019AD13_KHS_NODDI32\Results\CTI

] MREPT2019AD14_CMJ_NODDI32] → Results\CTI:   0%|                                           | 0/1 [00:00<?, ?file/s]
] MREPT2019AD14_CMJ_NODDI32] → Results\CTI: 100%|███████████████████████████████████| 1/1 [00:01<00:00,  1.66s/file]
CTI_ALPS folders:  69%|███████████████████████████████████████▊                  | 180/262 [07:57<02:52,  2.10s/folder]

[OK] MREPT2019AD14_CMJ_NODDI32: copied 1 file(s) to D:\JHAhn\8641_conductivity\DTI_ALPS\2_Dementia\EPT2019\prep\MREPT2019AD14_CMJ_NODDI32\Results\CTI

] MREPT2020AD01_CGS_NODDI32] → Results\CTI:   0%|                                           | 0/1 [00:00<?, ?file/s]
] MREPT2020AD01_CGS_NODDI32] → Results\CTI: 100%|███████████████████████████████████| 1/1 [00:03<00:00,  3.57s/file]
CTI_ALPS folders:  69%|████████████████████████████████████████                  | 181/262 [08:00<03:26,  2.54s/folder]

[OK] MREPT2020AD01_CGS_NODDI32: copied 1 file(s) to D:\JHAhn\8641_conductivity\DTI_ALPS\2_Dementia\EPT2020\MREPT2020AD01_CGS_NODDI32\Results\CTI

] MREPT2020AD02_HMJ_NODDI32] → Results\CTI:   0%|                                           | 0/1 [00:00<?, ?file/s]
] MREPT2020AD02_HMJ_NODDI32] → Results\CTI: 100%|███████████████████████████████████| 1/1 [00:05<00:00,  5.18s/file]
CTI_ALPS folders:  69%|████████████████████████████████████████▎                 | 182/262 [08:05<04:27,  3.34s/folder]

[OK] MREPT2020AD02_HMJ_NODDI32: copied 1 file(s) to D:\JHAhn\8641_conductivity\DTI_ALPS\2_Dementia\EPT2020\MREPT2020AD02_HMJ_NODDI32\Results\CTI

] MREPT2020AD03_KJH_NODDI32] → Results\CTI:   0%|                                           | 0/1 [00:00<?, ?file/s]
] MREPT2020AD03_KJH_NODDI32] → Results\CTI: 100%|███████████████████████████████████| 1/1 [00:02<00:00,  2.14s/file]
CTI_ALPS folders:  70%|████████████████████████████████████████▌                 | 183/262 [08:08<03:55,  2.98s/folder]

[OK] MREPT2020AD03_KJH_NODDI32: copied 1 file(s) to D:\JHAhn\8641_conductivity\DTI_ALPS\2_Dementia\EPT2020\MREPT2020AD03_KJH_NODDI32\Results\CTI

] MREPT2020AD04_NGR_NODDI32] → Results\CTI:   0%|                                           | 0/1 [00:00<?, ?file/s]
] MREPT2020AD04_NGR_NODDI32] → Results\CTI: 100%|███████████████████████████████████| 1/1 [00:02<00:00,  2.57s/file]
CTI_ALPS folders:  70%|████████████████████████████████████████▋                 | 184/262 [08:10<03:43,  2.87s/folder]

[OK] MREPT2020AD04_NGR_NODDI32: copied 1 file(s) to D:\JHAhn\8641_conductivity\DTI_ALPS\2_Dementia\EPT2020\MREPT2020AD04_NGR_NODDI32\Results\CTI

] MREPT2020AD05_PJE_NODDI32] → Results\CTI:   0%|                                           | 0/1 [00:00<?, ?file/s]
] MREPT2020AD05_PJE_NODDI32] → Results\CTI: 100%|███████████████████████████████████| 1/1 [00:01<00:00,  1.75s/file]
CTI_ALPS folders:  71%|████████████████████████████████████████▉                 | 185/262 [08:12<03:15,  2.54s/folder]

[OK] MREPT2020AD05_PJE_NODDI32: copied 1 file(s) to D:\JHAhn\8641_conductivity\DTI_ALPS\2_Dementia\EPT2020\MREPT2020AD05_PJE_NODDI32\Results\CTI

] MREPT2020AD06_JHK_NODDI32] → Results\CTI:   0%|                                           | 0/1 [00:00<?, ?file/s]
] MREPT2020AD06_JHK_NODDI32] → Results\CTI: 100%|███████████████████████████████████| 1/1 [00:01<00:00,  1.65s/file]
CTI_ALPS folders:  71%|█████████████████████████████████████████▏                | 186/262 [08:14<02:52,  2.28s/folder]

[OK] MREPT2020AD06_JHK_NODDI32: copied 1 file(s) to D:\JHAhn\8641_conductivity\DTI_ALPS\2_Dementia\EPT2020\MREPT2020AD06_JHK_NODDI32\Results\CTI

] MREPT2020AD07_KYG_NODDI32] → Results\CTI:   0%|                                           | 0/1 [00:00<?, ?file/s]
] MREPT2020AD07_KYG_NODDI32] → Results\CTI: 100%|███████████████████████████████████| 1/1 [00:04<00:00,  4.73s/file]
CTI_ALPS folders:  71%|█████████████████████████████████████████▍                | 187/262 [08:18<03:46,  3.02s/folder]

[OK] MREPT2020AD07_KYG_NODDI32: copied 1 file(s) to D:\JHAhn\8641_conductivity\DTI_ALPS\2_Dementia\EPT2020\MREPT2020AD07_KYG_NODDI32\Results\CTI

] MREPT2020AD08_CYS_NODDI32] → Results\CTI:   0%|                                           | 0/1 [00:00<?, ?file/s]
] MREPT2020AD08_CYS_NODDI32] → Results\CTI: 100%|███████████████████████████████████| 1/1 [00:04<00:00,  4.85s/file]
CTI_ALPS folders:  72%|█████████████████████████████████████████▌                | 188/262 [08:23<04:24,  3.57s/folder]

[OK] MREPT2020AD08_CYS_NODDI32: copied 1 file(s) to D:\JHAhn\8641_conductivity\DTI_ALPS\2_Dementia\EPT2020\MREPT2020AD08_CYS_NODDI32\Results\CTI

] MREPT2020AD10_CYJ_NODDI32] → Results\CTI:   0%|                                           | 0/1 [00:00<?, ?file/s]
] MREPT2020AD10_CYJ_NODDI32] → Results\CTI: 100%|███████████████████████████████████| 1/1 [00:01<00:00,  1.38s/file]
CTI_ALPS folders:  72%|█████████████████████████████████████████▊                | 189/262 [08:25<03:33,  2.92s/folder]

[OK] MREPT2020AD10_CYJ_NODDI32: copied 1 file(s) to D:\JHAhn\8641_conductivity\DTI_ALPS\2_Dementia\EPT2020\MREPT2020AD10_CYJ_NODDI32\Results\CTI

] MREPT2020AD11_KHJ_NODDI32] → Results\CTI:   0%|                                           | 0/1 [00:00<?, ?file/s]
] MREPT2020AD11_KHJ_NODDI32] → Results\CTI: 100%|███████████████████████████████████| 1/1 [00:01<00:00,  1.38s/file]
CTI_ALPS folders:  73%|██████████████████████████████████████████                | 190/262 [08:26<02:57,  2.46s/folder]

[OK] MREPT2020AD11_KHJ_NODDI32: copied 1 file(s) to D:\JHAhn\8641_conductivity\DTI_ALPS\2_Dementia\EPT2020\MREPT2020AD11_KHJ_NODDI32\Results\CTI

] MREPT2020AD12_KOB_NODDI32] → Results\CTI:   0%|                                           | 0/1 [00:00<?, ?file/s]
] MREPT2020AD12_KOB_NODDI32] → Results\CTI: 100%|███████████████████████████████████| 1/1 [00:01<00:00,  1.48s/file]
CTI_ALPS folders:  73%|██████████████████████████████████████████▎               | 191/262 [08:27<02:34,  2.17s/folder]

[OK] MREPT2020AD12_KOB_NODDI32: copied 1 file(s) to D:\JHAhn\8641_conductivity\DTI_ALPS\2_Dementia\EPT2020\MREPT2020AD12_KOB_NODDI32\Results\CTI

] MREPT2020AD13_SBS_NODDI32] → Results\CTI:   0%|                                           | 0/1 [00:00<?, ?file/s]
] MREPT2020AD13_SBS_NODDI32] → Results\CTI: 100%|███████████████████████████████████| 1/1 [00:03<00:00,  3.13s/file]
CTI_ALPS folders:  73%|██████████████████████████████████████████▌               | 192/262 [08:31<02:52,  2.47s/folder]

[OK] MREPT2020AD13_SBS_NODDI32: copied 1 file(s) to D:\JHAhn\8641_conductivity\DTI_ALPS\2_Dementia\EPT2020\MREPT2020AD13_SBS_NODDI32\Results\CTI

] MREPT2020AD14_CIL_NODDI32] → Results\CTI:   0%|                                           | 0/1 [00:00<?, ?file/s]
] MREPT2020AD14_CIL_NODDI32] → Results\CTI: 100%|███████████████████████████████████| 1/1 [00:04<00:00,  4.50s/file]
CTI_ALPS folders:  74%|██████████████████████████████████████████▋               | 193/262 [08:35<03:32,  3.08s/folder]

[OK] MREPT2020AD14_CIL_NODDI32: copied 1 file(s) to D:\JHAhn\8641_conductivity\DTI_ALPS\2_Dementia\EPT2020\MREPT2020AD14_CIL_NODDI32\Results\CTI

] MREPT2020AD15_LHS_NODDI32] → Results\CTI:   0%|                                           | 0/1 [00:00<?, ?file/s]
] MREPT2020AD15_LHS_NODDI32] → Results\CTI: 100%|███████████████████████████████████| 1/1 [00:01<00:00,  1.12s/file]
CTI_ALPS folders:  74%|██████████████████████████████████████████▉               | 194/262 [08:36<02:50,  2.50s/folder]

[OK] MREPT2020AD15_LHS_NODDI32: copied 1 file(s) to D:\JHAhn\8641_conductivity\DTI_ALPS\2_Dementia\EPT2020\MREPT2020AD15_LHS_NODDI32\Results\CTI

] MREPT2020AD18_YHS_NODDI32] → Results\CTI:   0%|                                           | 0/1 [00:00<?, ?file/s]
] MREPT2020AD18_YHS_NODDI32] → Results\CTI: 100%|███████████████████████████████████| 1/1 [00:01<00:00,  1.53s/file]
CTI_ALPS folders:  74%|███████████████████████████████████████████▏              | 195/262 [08:38<02:28,  2.21s/folder]

[OK] MREPT2020AD18_YHS_NODDI32: copied 1 file(s) to D:\JHAhn\8641_conductivity\DTI_ALPS\2_Dementia\EPT2020\MREPT2020AD18_YHS_NODDI32\Results\CTI

] MREPT2020AD19_PKS_NODDI32] → Results\CTI:   0%|                                           | 0/1 [00:00<?, ?file/s]
] MREPT2020AD19_PKS_NODDI32] → Results\CTI: 100%|███████████████████████████████████| 1/1 [00:02<00:00,  2.52s/file]
CTI_ALPS folders:  75%|███████████████████████████████████████████▍              | 196/262 [08:40<02:32,  2.31s/folder]

[OK] MREPT2020AD19_PKS_NODDI32: copied 1 file(s) to D:\JHAhn\8641_conductivity\DTI_ALPS\2_Dementia\EPT2020\MREPT2020AD19_PKS_NODDI32\Results\CTI

] MREPT2020AD20_LSK_NODDI32] → Results\CTI:   0%|                                           | 0/1 [00:00<?, ?file/s]
] MREPT2020AD20_LSK_NODDI32] → Results\CTI: 100%|███████████████████████████████████| 1/1 [00:04<00:00,  4.44s/file]
CTI_ALPS folders:  75%|███████████████████████████████████████████▌              | 197/262 [08:45<03:12,  2.95s/folder]

[OK] MREPT2020AD20_LSK_NODDI32: copied 1 file(s) to D:\JHAhn\8641_conductivity\DTI_ALPS\2_Dementia\EPT2020\MREPT2020AD20_LSK_NODDI32\Results\CTI

] MREPT2020AD22_KYH_NODDI32] → Results\CTI:   0%|                                           | 0/1 [00:00<?, ?file/s]
] MREPT2020AD22_KYH_NODDI32] → Results\CTI: 100%|███████████████████████████████████| 1/1 [00:02<00:00,  2.37s/file]
CTI_ALPS folders:  76%|███████████████████████████████████████████▊              | 198/262 [08:47<02:58,  2.79s/folder]

[OK] MREPT2020AD22_KYH_NODDI32: copied 1 file(s) to D:\JHAhn\8641_conductivity\DTI_ALPS\2_Dementia\EPT2020\MREPT2020AD22_KYH_NODDI32\Results\CTI

] MREPT2020AD23_LSH_NODDI32] → Results\CTI:   0%|                                           | 0/1 [00:00<?, ?file/s]
] MREPT2020AD23_LSH_NODDI32] → Results\CTI: 100%|███████████████████████████████████| 1/1 [00:01<00:00,  1.23s/file]
CTI_ALPS folders:  76%|████████████████████████████████████████████              | 199/262 [08:48<02:26,  2.32s/folder]

[OK] MREPT2020AD23_LSH_NODDI32: copied 1 file(s) to D:\JHAhn\8641_conductivity\DTI_ALPS\2_Dementia\EPT2020\MREPT2020AD23_LSH_NODDI32\Results\CTI

] MREPT2020AD24_YYS_NODDI32] → Results\CTI:   0%|                                           | 0/1 [00:00<?, ?file/s]
] MREPT2020AD24_YYS_NODDI32] → Results\CTI: 100%|███████████████████████████████████| 1/1 [00:02<00:00,  2.08s/file]
CTI_ALPS folders:  76%|████████████████████████████████████████████▎             | 200/262 [08:51<02:19,  2.26s/folder]

[OK] MREPT2020AD24_YYS_NODDI32: copied 1 file(s) to D:\JHAhn\8641_conductivity\DTI_ALPS\2_Dementia\EPT2020\MREPT2020AD24_YYS_NODDI32\Results\CTI

] MREPT2020AD25_YSJ_NODDI32] → Results\CTI:   0%|                                           | 0/1 [00:00<?, ?file/s]
] MREPT2020AD25_YSJ_NODDI32] → Results\CTI: 100%|███████████████████████████████████| 1/1 [00:01<00:00,  1.73s/file]
CTI_ALPS folders:  77%|████████████████████████████████████████████▍             | 201/262 [08:52<02:08,  2.10s/folder]

[OK] MREPT2020AD25_YSJ_NODDI32: copied 1 file(s) to D:\JHAhn\8641_conductivity\DTI_ALPS\2_Dementia\EPT2020\MREPT2020AD25_YSJ_NODDI32\Results\CTI

] MREPT2020AD26_HMH_NODDI32] → Results\CTI:   0%|                                           | 0/1 [00:00<?, ?file/s]
] MREPT2020AD26_HMH_NODDI32] → Results\CTI: 100%|███████████████████████████████████| 1/1 [00:03<00:00,  3.66s/file]
CTI_ALPS folders:  77%|████████████████████████████████████████████▋             | 202/262 [08:56<02:34,  2.58s/folder]

[OK] MREPT2020AD26_HMH_NODDI32: copied 1 file(s) to D:\JHAhn\8641_conductivity\DTI_ALPS\2_Dementia\EPT2020\MREPT2020AD26_HMH_NODDI32\Results\CTI

] MREPT2020AD27_YJJ_NODDI32] → Results\CTI:   0%|                                           | 0/1 [00:00<?, ?file/s]
] MREPT2020AD27_YJJ_NODDI32] → Results\CTI: 100%|███████████████████████████████████| 1/1 [00:05<00:00,  5.37s/file]
CTI_ALPS folders:  77%|████████████████████████████████████████████▉             | 203/262 [09:01<03:21,  3.42s/folder]

[OK] MREPT2020AD27_YJJ_NODDI32: copied 1 file(s) to D:\JHAhn\8641_conductivity\DTI_ALPS\2_Dementia\EPT2020\MREPT2020AD27_YJJ_NODDI32\Results\CTI

] MREPT2020AD28_YYL_NODDI32] → Results\CTI:   0%|                                           | 0/1 [00:00<?, ?file/s]
] MREPT2020AD28_YYL_NODDI32] → Results\CTI: 100%|███████████████████████████████████| 1/1 [00:02<00:00,  2.64s/file]
CTI_ALPS folders:  78%|█████████████████████████████████████████████▏            | 204/262 [09:04<03:05,  3.19s/folder]

[OK] MREPT2020AD28_YYL_NODDI32: copied 1 file(s) to D:\JHAhn\8641_conductivity\DTI_ALPS\2_Dementia\EPT2020\MREPT2020AD28_YYL_NODDI32\Results\CTI

] MWI_CN01_KNH_NODDI32] → Results\CTI:   0%|                                                | 0/1 [00:00<?, ?file/s]
] MWI_CN01_KNH_NODDI32] → Results\CTI: 100%|████████████████████████████████████████| 1/1 [00:01<00:00,  1.42s/file]
CTI_ALPS folders:  78%|█████████████████████████████████████████████▍            | 205/262 [09:05<02:31,  2.66s/folder]

[OK] MWI_CN01_KNH_NODDI32: copied 1 file(s) to D:\JHAhn\8641_conductivity\DTI_ALPS\1_8641_CN_MCI\MWI_CN01_KNH_NODDI32\Results\CTI

] MWI_CN04_SSS_NODDI32] → Results\CTI:   0%|                                                | 0/4 [00:00<?, ?file/s]
] MWI_CN04_SSS_NODDI32] → Results\CTI:  25%|██████████                              | 1/4 [00:00<00:01,  2.12file/s]
] MWI_CN04_SSS_NODDI32] → Results\CTI:  50%|████████████████████                    | 2/4 [00:01<00:01,  1.43file/s]
] MWI_CN04_SSS_NODDI32] → Results\CTI:  75%|██████████████████████████████          | 3/4 [00:02<00:00,  1.45file/s]
] MWI_CN04_SSS_NODDI32] → Results\CTI: 100%|████████████████████████████████████████| 4/4 [00:03<00:00,  1.15s/file]
CTI_ALPS folders:  79%|█████████████████████████████████████████████▌            | 206/262 [09:09<02:49,  3.03s/folder]

[OK] MWI_CN04_SSS_NODDI32: copied 4 file(s) to D:\JHAhn\8641_conductivity\DTI_ALPS\1_8641_CN_MCI\MWI_CN04_SSS_NODDI32\Results\CTI

] MWI_CN05_LSS_NODDI32] → Results\CTI:   0%|                                                | 0/1 [00:00<?, ?file/s]
] MWI_CN05_LSS_NODDI32] → Results\CTI: 100%|████████████████████████████████████████| 1/1 [00:01<00:00,  1.43s/file]
CTI_ALPS folders:  79%|█████████████████████████████████████████████▊            | 207/262 [09:11<02:20,  2.55s/folder]

[OK] MWI_CN05_LSS_NODDI32: copied 1 file(s) to D:\JHAhn\8641_conductivity\DTI_ALPS\1_8641_CN_MCI\MWI_CN05_LSS_NODDI32\Results\CTI

] MWI_CN06_KDS_NODDI32] → Results\CTI:   0%|                                                | 0/1 [00:00<?, ?file/s]
] MWI_CN06_KDS_NODDI32] → Results\CTI: 100%|████████████████████████████████████████| 1/1 [00:02<00:00,  2.42s/file]
CTI_ALPS folders:  79%|██████████████████████████████████████████████            | 208/262 [09:13<02:15,  2.52s/folder]

[OK] MWI_CN06_KDS_NODDI32: copied 1 file(s) to D:\JHAhn\8641_conductivity\DTI_ALPS\1_8641_CN_MCI\MWI_CN06_KDS_NODDI32\Results\CTI

] MWI_CN07_KSB_NODDI32] → Results\CTI:   0%|                                                | 0/1 [00:00<?, ?file/s]
] MWI_CN07_KSB_NODDI32] → Results\CTI: 100%|████████████████████████████████████████| 1/1 [00:04<00:00,  4.80s/file]
CTI_ALPS folders:  80%|██████████████████████████████████████████████▎           | 209/262 [09:18<02:49,  3.20s/folder]

[OK] MWI_CN07_KSB_NODDI32: copied 1 file(s) to D:\JHAhn\8641_conductivity\DTI_ALPS\1_8641_CN_MCI\MWI_CN07_KSB_NODDI32\Results\CTI

] MWI_CN09_YKJ_NODDI32] → Results\CTI:   0%|                                                | 0/1 [00:00<?, ?file/s]
] MWI_CN09_YKJ_NODDI32] → Results\CTI: 100%|████████████████████████████████████████| 1/1 [00:01<00:00,  1.08s/file]
CTI_ALPS folders:  80%|██████████████████████████████████████████████▍           | 210/262 [09:19<02:13,  2.57s/folder]

[OK] MWI_CN09_YKJ_NODDI32: copied 1 file(s) to D:\JHAhn\8641_conductivity\DTI_ALPS\1_8641_CN_MCI\MWI_CN09_YKJ_NODDI32\Results\CTI

] MWI_CN10_CJS_NODDI32] → Results\CTI:   0%|                                                | 0/1 [00:00<?, ?file/s]
] MWI_CN10_CJS_NODDI32] → Results\CTI: 100%|████████████████████████████████████████| 1/1 [00:02<00:00,  2.17s/file]
CTI_ALPS folders:  81%|██████████████████████████████████████████████▋           | 211/262 [09:21<02:05,  2.46s/folder]

[OK] MWI_CN10_CJS_NODDI32: copied 1 file(s) to D:\JHAhn\8641_conductivity\DTI_ALPS\1_8641_CN_MCI\MWI_CN10_CJS_NODDI32\Results\CTI

] MWI_CN12_LJK_NODDI32] → Results\CTI:   0%|                                                | 0/1 [00:00<?, ?file/s]
] MWI_CN12_LJK_NODDI32] → Results\CTI: 100%|████████████████████████████████████████| 1/1 [00:02<00:00,  2.91s/file]
CTI_ALPS folders:  81%|██████████████████████████████████████████████▉           | 212/262 [09:24<02:09,  2.60s/folder]

[OK] MWI_CN12_LJK_NODDI32: copied 1 file(s) to D:\JHAhn\8641_conductivity\DTI_ALPS\1_8641_CN_MCI\MWI_CN12_LJK_NODDI32\Results\CTI

] MWI_CN13_KH_NODDI32] → Results\CTI:   0%|                                                 | 0/1 [00:00<?, ?file/s]
] MWI_CN13_KH_NODDI32] → Results\CTI: 100%|█████████████████████████████████████████| 1/1 [00:04<00:00,  4.22s/file]
CTI_ALPS folders:  81%|███████████████████████████████████████████████▏          | 213/262 [09:28<02:31,  3.09s/folder]

[OK] MWI_CN13_KH_NODDI32: copied 1 file(s) to D:\JHAhn\8641_conductivity\DTI_ALPS\1_8641_CN_MCI\MWI_CN13_KH_NODDI32\Results\CTI

] MWI_CN14_PYJ_NODDI32] → Results\CTI:   0%|                                                | 0/1 [00:00<?, ?file/s]
] MWI_CN14_PYJ_NODDI32] → Results\CTI: 100%|████████████████████████████████████████| 1/1 [00:02<00:00,  2.27s/file]
CTI_ALPS folders:  82%|███████████████████████████████████████████████▎          | 214/262 [09:31<02:16,  2.85s/folder]

[OK] MWI_CN14_PYJ_NODDI32: copied 1 file(s) to D:\JHAhn\8641_conductivity\DTI_ALPS\1_8641_CN_MCI\MWI_CN14_PYJ_NODDI32\Results\CTI

] MWI_CN15_YCJ_NODDI32] → Results\CTI:   0%|                                                | 0/1 [00:00<?, ?file/s]
] MWI_CN15_YCJ_NODDI32] → Results\CTI: 100%|████████████████████████████████████████| 1/1 [00:01<00:00,  1.66s/file]
CTI_ALPS folders:  82%|███████████████████████████████████████████████▌          | 215/262 [09:32<01:57,  2.49s/folder]

[OK] MWI_CN15_YCJ_NODDI32: copied 1 file(s) to D:\JHAhn\8641_conductivity\DTI_ALPS\1_8641_CN_MCI\MWI_CN15_YCJ_NODDI32\Results\CTI

] MWI_CN16_LCS_NODDI32] → Results\CTI:   0%|                                                | 0/1 [00:00<?, ?file/s]
] MWI_CN16_LCS_NODDI32] → Results\CTI: 100%|████████████████████████████████████████| 1/1 [00:01<00:00,  1.35s/file]
CTI_ALPS folders:  82%|███████████████████████████████████████████████▊          | 216/262 [09:34<01:39,  2.16s/folder]

[OK] MWI_CN16_LCS_NODDI32: copied 1 file(s) to D:\JHAhn\8641_conductivity\DTI_ALPS\1_8641_CN_MCI\MWI_CN16_LCS_NODDI32\Results\CTI

] MWI_CN17_LPS_NODDI32] → Results\CTI:   0%|                                                | 0/1 [00:00<?, ?file/s]
] MWI_CN17_LPS_NODDI32] → Results\CTI: 100%|████████████████████████████████████████| 1/1 [00:02<00:00,  2.95s/file]
CTI_ALPS folders:  83%|████████████████████████████████████████████████          | 217/262 [09:37<01:48,  2.40s/folder]

[OK] MWI_CN17_LPS_NODDI32: copied 1 file(s) to D:\JHAhn\8641_conductivity\DTI_ALPS\1_8641_CN_MCI\MWI_CN17_LPS_NODDI32\Results\CTI

] MWI_CN18_HCS_NODDI32] → Results\CTI:   0%|                                                | 0/1 [00:00<?, ?file/s]
] MWI_CN18_HCS_NODDI32] → Results\CTI: 100%|████████████████████████████████████████| 1/1 [00:04<00:00,  4.73s/file]
CTI_ALPS folders:  83%|████████████████████████████████████████████████▎         | 218/262 [09:42<02:16,  3.11s/folder]

[OK] MWI_CN18_HCS_NODDI32: copied 1 file(s) to D:\JHAhn\8641_conductivity\DTI_ALPS\1_8641_CN_MCI\MWI_CN18_HCS_NODDI32\Results\CTI

] MWI_CN19_CSO_NODDI32] → Results\CTI:   0%|                                                | 0/1 [00:00<?, ?file/s]
] MWI_CN19_CSO_NODDI32] → Results\CTI: 100%|████████████████████████████████████████| 1/1 [00:02<00:00,  2.29s/file]
CTI_ALPS folders:  84%|████████████████████████████████████████████████▍         | 219/262 [09:44<02:03,  2.87s/folder]

[OK] MWI_CN19_CSO_NODDI32: copied 1 file(s) to D:\JHAhn\8641_conductivity\DTI_ALPS\1_8641_CN_MCI\MWI_CN19_CSO_NODDI32\Results\CTI

] MWI_CN20_PYJ_NODDI32] → Results\CTI:   0%|                                                | 0/1 [00:00<?, ?file/s]
] MWI_CN20_PYJ_NODDI32] → Results\CTI: 100%|████████████████████████████████████████| 1/1 [00:01<00:00,  1.04s/file]
CTI_ALPS folders:  84%|████████████████████████████████████████████████▋         | 220/262 [09:45<01:37,  2.32s/folder]

[OK] MWI_CN20_PYJ_NODDI32: copied 1 file(s) to D:\JHAhn\8641_conductivity\DTI_ALPS\1_8641_CN_MCI\MWI_CN20_PYJ_NODDI32\Results\CTI

] MWI_CN21_PYB_NODDI32] → Results\CTI:   0%|                                                | 0/1 [00:00<?, ?file/s]
] MWI_CN21_PYB_NODDI32] → Results\CTI: 100%|████████████████████████████████████████| 1/1 [00:01<00:00,  1.20s/file]
CTI_ALPS folders:  84%|████████████████████████████████████████████████▉         | 221/262 [09:46<01:21,  1.99s/folder]

[OK] MWI_CN21_PYB_NODDI32: copied 1 file(s) to D:\JHAhn\8641_conductivity\DTI_ALPS\1_8641_CN_MCI\MWI_CN21_PYB_NODDI32\Results\CTI

] MWI_CN22_YYJ_NODDI32] → Results\CTI:   0%|                                                | 0/1 [00:00<?, ?file/s]
] MWI_CN22_YYJ_NODDI32] → Results\CTI: 100%|████████████████████████████████████████| 1/1 [00:01<00:00,  1.94s/file]
CTI_ALPS folders:  85%|█████████████████████████████████████████████████▏        | 222/262 [09:48<01:19,  1.98s/folder]

[OK] MWI_CN22_YYJ_NODDI32: copied 1 file(s) to D:\JHAhn\8641_conductivity\DTI_ALPS\1_8641_CN_MCI\MWI_CN22_YYJ_NODDI32\Results\CTI

] MWI_CN23_HJL_NODDI32] → Results\CTI:   0%|                                                | 0/1 [00:00<?, ?file/s]
] MWI_CN23_HJL_NODDI32] → Results\CTI: 100%|████████████████████████████████████████| 1/1 [00:04<00:00,  4.82s/file]
CTI_ALPS folders:  85%|█████████████████████████████████████████████████▎        | 223/262 [09:53<01:50,  2.85s/folder]

[OK] MWI_CN23_HJL_NODDI32: copied 1 file(s) to D:\JHAhn\8641_conductivity\DTI_ALPS\1_8641_CN_MCI\MWI_CN23_HJL_NODDI32\Results\CTI

] MWI_CN24_PKJ_NODDI32] → Results\CTI:   0%|                                                | 0/1 [00:00<?, ?file/s]
] MWI_CN24_PKJ_NODDI32] → Results\CTI: 100%|████████████████████████████████████████| 1/1 [00:04<00:00,  4.26s/file]
CTI_ALPS folders:  85%|█████████████████████████████████████████████████▌        | 224/262 [09:57<02:04,  3.28s/folder]

[OK] MWI_CN24_PKJ_NODDI32: copied 1 file(s) to D:\JHAhn\8641_conductivity\DTI_ALPS\1_8641_CN_MCI\MWI_CN24_PKJ_NODDI32\Results\CTI

] MWI_CN25_NKJ_NODDI32] → Results\CTI:   0%|                                                | 0/1 [00:00<?, ?file/s]
] MWI_CN25_NKJ_NODDI32] → Results\CTI: 100%|████████████████████████████████████████| 1/1 [00:01<00:00,  1.08s/file]
CTI_ALPS folders:  86%|█████████████████████████████████████████████████▊        | 225/262 [09:58<01:36,  2.62s/folder]

[OK] MWI_CN25_NKJ_NODDI32: copied 1 file(s) to D:\JHAhn\8641_conductivity\DTI_ALPS\1_8641_CN_MCI\MWI_CN25_NKJ_NODDI32\Results\CTI

] MWI_CN26_LSR_NODDI32] → Results\CTI:   0%|                                                | 0/1 [00:00<?, ?file/s]
] MWI_CN26_LSR_NODDI32] → Results\CTI: 100%|████████████████████████████████████████| 1/1 [00:02<00:00,  2.65s/file]
CTI_ALPS folders:  86%|██████████████████████████████████████████████████        | 226/262 [10:01<01:34,  2.64s/folder]

[OK] MWI_CN26_LSR_NODDI32: copied 1 file(s) to D:\JHAhn\8641_conductivity\DTI_ALPS\1_8641_CN_MCI\MWI_CN26_LSR_NODDI32\Results\CTI

] MWI_CN27_LSJ_NODDI32] → Results\CTI:   0%|                                                | 0/1 [00:00<?, ?file/s]
] MWI_CN27_LSJ_NODDI32] → Results\CTI: 100%|████████████████████████████████████████| 1/1 [00:03<00:00,  3.32s/file]
CTI_ALPS folders:  87%|██████████████████████████████████████████████████▎       | 227/262 [10:04<01:39,  2.84s/folder]

[OK] MWI_CN27_LSJ_NODDI32: copied 1 file(s) to D:\JHAhn\8641_conductivity\DTI_ALPS\1_8641_CN_MCI\MWI_CN27_LSJ_NODDI32\Results\CTI

] MWI_CN28_KOS_NODDI32] → Results\CTI:   0%|                                                | 0/1 [00:00<?, ?file/s]
] MWI_CN28_KOS_NODDI32] → Results\CTI: 100%|████████████████████████████████████████| 1/1 [00:01<00:00,  1.41s/file]
CTI_ALPS folders:  87%|██████████████████████████████████████████████████▍       | 228/262 [10:06<01:22,  2.42s/folder]

[OK] MWI_CN28_KOS_NODDI32: copied 1 file(s) to D:\JHAhn\8641_conductivity\DTI_ALPS\1_8641_CN_MCI\MWI_CN28_KOS_NODDI32\Results\CTI

] MWI_CN29_KSH_NODDI32] → Results\CTI:   0%|                                                | 0/1 [00:00<?, ?file/s]
] MWI_CN29_KSH_NODDI32] → Results\CTI: 100%|████████████████████████████████████████| 1/1 [00:01<00:00,  1.69s/file]
CTI_ALPS folders:  87%|██████████████████████████████████████████████████▋       | 229/262 [10:07<01:12,  2.21s/folder]

[OK] MWI_CN29_KSH_NODDI32: copied 1 file(s) to D:\JHAhn\8641_conductivity\DTI_ALPS\1_8641_CN_MCI\MWI_CN29_KSH_NODDI32\Results\CTI

] MWI_CN30_PYS_NODDI32] → Results\CTI:   0%|                                                | 0/1 [00:00<?, ?file/s]
] MWI_CN30_PYS_NODDI32] → Results\CTI: 100%|████████████████████████████████████████| 1/1 [00:02<00:00,  2.19s/file]
CTI_ALPS folders:  88%|██████████████████████████████████████████████████▉       | 230/262 [10:10<01:10,  2.21s/folder]

[OK] MWI_CN30_PYS_NODDI32: copied 1 file(s) to D:\JHAhn\8641_conductivity\DTI_ALPS\1_8641_CN_MCI\MWI_CN30_PYS_NODDI32\Results\CTI

] MWI_CN31_LOH_NODDI32] → Results\CTI:   0%|                                                | 0/1 [00:00<?, ?file/s]
] MWI_CN31_LOH_NODDI32] → Results\CTI: 100%|████████████████████████████████████████| 1/1 [00:02<00:00,  2.68s/file]
CTI_ALPS folders:  88%|███████████████████████████████████████████████████▏      | 231/262 [10:12<01:13,  2.36s/folder]

[OK] MWI_CN31_LOH_NODDI32: copied 1 file(s) to D:\JHAhn\8641_conductivity\DTI_ALPS\1_8641_CN_MCI\MWI_CN31_LOH_NODDI32\Results\CTI

] MWI_CN32_KYH_NODDI32] → Results\CTI:   0%|                                                | 0/1 [00:00<?, ?file/s]
] MWI_CN32_KYH_NODDI32] → Results\CTI: 100%|████████████████████████████████████████| 1/1 [00:04<00:00,  4.78s/file]
CTI_ALPS folders:  89%|███████████████████████████████████████████████████▎      | 232/262 [10:17<01:32,  3.09s/folder]

[OK] MWI_CN32_KYH_NODDI32: copied 1 file(s) to D:\JHAhn\8641_conductivity\DTI_ALPS\1_8641_CN_MCI\MWI_CN32_KYH_NODDI32\Results\CTI

] MWI_CN33_LSH_NODDI32] → Results\CTI:   0%|                                                | 0/1 [00:00<?, ?file/s]
] MWI_CN33_LSH_NODDI32] → Results\CTI: 100%|████████████████████████████████████████| 1/1 [00:01<00:00,  1.17s/file]
CTI_ALPS folders:  89%|███████████████████████████████████████████████████▌      | 233/262 [10:18<01:13,  2.52s/folder]

[OK] MWI_CN33_LSH_NODDI32: copied 1 file(s) to D:\JHAhn\8641_conductivity\DTI_ALPS\1_8641_CN_MCI\MWI_CN33_LSH_NODDI32\Results\CTI

] MWI_CN34_OJS_NODDI32] → Results\CTI:   0%|                                                | 0/1 [00:00<?, ?file/s]
] MWI_CN34_OJS_NODDI32] → Results\CTI: 100%|████████████████████████████████████████| 1/1 [00:00<00:00,  1.00file/s]
CTI_ALPS folders:  89%|███████████████████████████████████████████████████▊      | 234/262 [10:19<00:57,  2.07s/folder]

[OK] MWI_CN34_OJS_NODDI32: copied 1 file(s) to D:\JHAhn\8641_conductivity\DTI_ALPS\1_8641_CN_MCI\MWI_CN34_OJS_NODDI32\Results\CTI

] MWI_CN35_LES_NODDI32] → Results\CTI:   0%|                                                | 0/1 [00:00<?, ?file/s]
] MWI_CN35_LES_NODDI32] → Results\CTI: 100%|████████████████████████████████████████| 1/1 [00:01<00:00,  1.64s/file]
CTI_ALPS folders:  90%|████████████████████████████████████████████████████      | 235/262 [10:21<00:52,  1.94s/folder]

[OK] MWI_CN35_LES_NODDI32: copied 1 file(s) to D:\JHAhn\8641_conductivity\DTI_ALPS\1_8641_CN_MCI\MWI_CN35_LES_NODDI32\Results\CTI

] MWI_CN36_KER_NODDI32] → Results\CTI:   0%|                                                | 0/1 [00:00<?, ?file/s]
] MWI_CN36_KER_NODDI32] → Results\CTI: 100%|████████████████████████████████████████| 1/1 [00:02<00:00,  2.61s/file]
CTI_ALPS folders:  90%|████████████████████████████████████████████████████▏     | 236/262 [10:24<00:55,  2.15s/folder]

[OK] MWI_CN36_KER_NODDI32: copied 1 file(s) to D:\JHAhn\8641_conductivity\DTI_ALPS\1_8641_CN_MCI\MWI_CN36_KER_NODDI32\Results\CTI

] MWI_CN37_KJR_NODDI32] → Results\CTI:   0%|                                                | 0/1 [00:00<?, ?file/s]
] MWI_CN37_KJR_NODDI32] → Results\CTI: 100%|████████████████████████████████████████| 1/1 [00:05<00:00,  5.28s/file]
CTI_ALPS folders:  90%|████████████████████████████████████████████████████▍     | 237/262 [10:29<01:17,  3.09s/folder]

[OK] MWI_CN37_KJR_NODDI32: copied 1 file(s) to D:\JHAhn\8641_conductivity\DTI_ALPS\1_8641_CN_MCI\MWI_CN37_KJR_NODDI32\Results\CTI

] MWI_CN38_JJB_NODDI32] → Results\CTI:   0%|                                                | 0/1 [00:00<?, ?file/s]
] MWI_CN38_JJB_NODDI32] → Results\CTI: 100%|████████████████████████████████████████| 1/1 [00:03<00:00,  3.05s/file]
CTI_ALPS folders:  91%|████████████████████████████████████████████████████▋     | 238/262 [10:32<01:14,  3.09s/folder]

[OK] MWI_CN38_JJB_NODDI32: copied 1 file(s) to D:\JHAhn\8641_conductivity\DTI_ALPS\1_8641_CN_MCI\MWI_CN38_JJB_NODDI32\Results\CTI

] MWI_CN39_LTS_NODDI32] → Results\CTI:   0%|                                                | 0/1 [00:00<?, ?file/s]
] MWI_CN39_LTS_NODDI32] → Results\CTI: 100%|████████████████████████████████████████| 1/1 [00:01<00:00,  1.66s/file]
CTI_ALPS folders:  91%|████████████████████████████████████████████████████▉     | 239/262 [10:34<01:01,  2.66s/folder]

[OK] MWI_CN39_LTS_NODDI32: copied 1 file(s) to D:\JHAhn\8641_conductivity\DTI_ALPS\1_8641_CN_MCI\MWI_CN39_LTS_NODDI32\Results\CTI

] MWI_CN40_LDS_NODDI32] → Results\CTI:   0%|                                                | 0/1 [00:00<?, ?file/s]
] MWI_CN40_LDS_NODDI32] → Results\CTI: 100%|████████████████████████████████████████| 1/1 [00:01<00:00,  1.11s/file]
CTI_ALPS folders:  92%|█████████████████████████████████████████████████████▏    | 240/262 [10:35<00:48,  2.20s/folder]

[OK] MWI_CN40_LDS_NODDI32: copied 1 file(s) to D:\JHAhn\8641_conductivity\DTI_ALPS\1_8641_CN_MCI\MWI_CN40_LDS_NODDI32\Results\CTI

] MWI_CN41_JHL_NODDI32] → Results\CTI:   0%|                                                | 0/1 [00:00<?, ?file/s]
] MWI_CN41_JHL_NODDI32] → Results\CTI: 100%|████████████████████████████████████████| 1/1 [00:01<00:00,  1.25s/file]
CTI_ALPS folders:  92%|█████████████████████████████████████████████████████▎    | 241/262 [10:36<00:40,  1.92s/folder]

[OK] MWI_CN41_JHL_NODDI32: copied 1 file(s) to D:\JHAhn\8641_conductivity\DTI_ALPS\1_8641_CN_MCI\MWI_CN41_JHL_NODDI32\Results\CTI

] MWI_CN57_YHY_NODDI32] → Results\CTI:   0%|                                                | 0/1 [00:00<?, ?file/s]
] MWI_CN57_YHY_NODDI32] → Results\CTI: 100%|████████████████████████████████████████| 1/1 [00:02<00:00,  2.94s/file]
CTI_ALPS folders:  92%|█████████████████████████████████████████████████████▌    | 242/262 [10:39<00:44,  2.23s/folder]

[OK] MWI_CN57_YHY_NODDI32: copied 1 file(s) to D:\JHAhn\8641_conductivity\DTI_ALPS\1_8641_CN_MCI\MWI_CN57_YHY_NODDI32\Results\CTI

] MWI_CN58_LSB_NODDI32] → Results\CTI:   0%|                                                | 0/1 [00:00<?, ?file/s]
] MWI_CN58_LSB_NODDI32] → Results\CTI: 100%|████████████████████████████████████████| 1/1 [00:03<00:00,  3.09s/file]
CTI_ALPS folders:  93%|█████████████████████████████████████████████████████▊    | 243/262 [10:42<00:47,  2.49s/folder]

[OK] MWI_CN58_LSB_NODDI32: copied 1 file(s) to D:\JHAhn\8641_conductivity\DTI_ALPS\1_8641_CN_MCI\MWI_CN58_LSB_NODDI32\Results\CTI

] MWI_CN61_CHS_NODDI32] → Results\CTI:   0%|                                                | 0/1 [00:00<?, ?file/s]
] MWI_CN61_CHS_NODDI32] → Results\CTI: 100%|████████████████████████████████████████| 1/1 [00:03<00:00,  3.02s/file]
CTI_ALPS folders:  93%|██████████████████████████████████████████████████████    | 244/262 [10:45<00:47,  2.65s/folder]

[OK] MWI_CN61_CHS_NODDI32: copied 1 file(s) to D:\JHAhn\8641_conductivity\DTI_ALPS\1_8641_CN_MCI\MWI_CN61_CHS_NODDI32\Results\CTI

] MWI_CN65_PYS_NODDI32] → Results\CTI:   0%|                                                | 0/1 [00:00<?, ?file/s]
] MWI_CN65_PYS_NODDI32] → Results\CTI: 100%|████████████████████████████████████████| 1/1 [00:00<00:00,  1.10file/s]
CTI_ALPS folders:  94%|██████████████████████████████████████████████████████▏   | 245/262 [10:46<00:36,  2.14s/folder]

[OK] MWI_CN65_PYS_NODDI32: copied 1 file(s) to D:\JHAhn\8641_conductivity\DTI_ALPS\1_8641_CN_MCI\MWI_CN65_PYS_NODDI32\Results\CTI

] MWI_CN66_CSY_NODDI32] → Results\CTI:   0%|                                                | 0/1 [00:00<?, ?file/s]
] MWI_CN66_CSY_NODDI32] → Results\CTI: 100%|████████████████████████████████████████| 1/1 [00:01<00:00,  1.73s/file]
CTI_ALPS folders:  94%|██████████████████████████████████████████████████████▍   | 246/262 [10:48<00:32,  2.02s/folder]

[OK] MWI_CN66_CSY_NODDI32: copied 1 file(s) to D:\JHAhn\8641_conductivity\DTI_ALPS\1_8641_CN_MCI\MWI_CN66_CSY_NODDI32\Results\CTI

] MWI_CN67_KOS_NODDI32] → Results\CTI:   0%|                                                | 0/1 [00:00<?, ?file/s]
] MWI_CN67_KOS_NODDI32] → Results\CTI: 100%|████████████████████████████████████████| 1/1 [00:01<00:00,  1.73s/file]
CTI_ALPS folders:  94%|██████████████████████████████████████████████████████▋   | 247/262 [10:50<00:29,  1.94s/folder]

[OK] MWI_CN67_KOS_NODDI32: copied 1 file(s) to D:\JHAhn\8641_conductivity\DTI_ALPS\1_8641_CN_MCI\MWI_CN67_KOS_NODDI32\Results\CTI

] MWI_CN68_CDL_NODDI32] → Results\CTI:   0%|                                                | 0/1 [00:00<?, ?file/s]
] MWI_CN68_CDL_NODDI32] → Results\CTI: 100%|████████████████████████████████████████| 1/1 [00:02<00:00,  2.79s/file]
CTI_ALPS folders:  95%|██████████████████████████████████████████████████████▉   | 248/262 [10:52<00:30,  2.20s/folder]

[OK] MWI_CN68_CDL_NODDI32: copied 1 file(s) to D:\JHAhn\8641_conductivity\DTI_ALPS\1_8641_CN_MCI\MWI_CN68_CDL_NODDI32\Results\CTI

] MWI_CN69_LSL_NODDI32] → Results\CTI:   0%|                                                | 0/1 [00:00<?, ?file/s]
] MWI_CN69_LSL_NODDI32] → Results\CTI: 100%|████████████████████████████████████████| 1/1 [00:04<00:00,  4.70s/file]
CTI_ALPS folders:  95%|███████████████████████████████████████████████████████   | 249/262 [10:57<00:38,  2.96s/folder]

[OK] MWI_CN69_LSL_NODDI32: copied 1 file(s) to D:\JHAhn\8641_conductivity\DTI_ALPS\1_8641_CN_MCI\MWI_CN69_LSL_NODDI32\Results\CTI

] MWI_CN70_LCJ_NODDI32] → Results\CTI:   0%|                                                | 0/1 [00:00<?, ?file/s]
] MWI_CN70_LCJ_NODDI32] → Results\CTI: 100%|████████████████████████████████████████| 1/1 [00:03<00:00,  3.36s/file]
CTI_ALPS folders:  95%|███████████████████████████████████████████████████████▎  | 250/262 [11:00<00:36,  3.08s/folder]

[OK] MWI_CN70_LCJ_NODDI32: copied 1 file(s) to D:\JHAhn\8641_conductivity\DTI_ALPS\1_8641_CN_MCI\MWI_CN70_LCJ_NODDI32\Results\CTI

] MWI_CN71_LSH_NODDI32] → Results\CTI:   0%|                                                | 0/1 [00:00<?, ?file/s]
] MWI_CN71_LSH_NODDI32] → Results\CTI: 100%|████████████████████████████████████████| 1/1 [00:02<00:00,  2.22s/file]
CTI_ALPS folders:  96%|███████████████████████████████████████████████████████▌  | 251/262 [11:03<00:31,  2.83s/folder]

[OK] MWI_CN71_LSH_NODDI32: copied 1 file(s) to D:\JHAhn\8641_conductivity\DTI_ALPS\1_8641_CN_MCI\MWI_CN71_LSH_NODDI32\Results\CTI

] MWI_CN73_GIS_NODDI32] → Results\CTI:   0%|                                                | 0/1 [00:00<?, ?file/s]
] MWI_CN73_GIS_NODDI32] → Results\CTI: 100%|████████████████████████████████████████| 1/1 [00:03<00:00,  3.11s/file]
CTI_ALPS folders:  96%|███████████████████████████████████████████████████████▊  | 252/262 [11:06<00:29,  2.92s/folder]

[OK] MWI_CN73_GIS_NODDI32: copied 1 file(s) to D:\JHAhn\8641_conductivity\DTI_ALPS\1_8641_CN_MCI\MWI_CN73_GIS_NODDI32\Results\CTI

] MWI_CN74_LKY_NODDI32] → Results\CTI:   0%|                                                | 0/1 [00:00<?, ?file/s]
] MWI_CN74_LKY_NODDI32] → Results\CTI: 100%|████████████████████████████████████████| 1/1 [00:01<00:00,  1.81s/file]
CTI_ALPS folders:  97%|████████████████████████████████████████████████████████  | 253/262 [11:08<00:23,  2.59s/folder]

[OK] MWI_CN74_LKY_NODDI32: copied 1 file(s) to D:\JHAhn\8641_conductivity\DTI_ALPS\1_8641_CN_MCI\MWI_CN74_LKY_NODDI32\Results\CTI

] MWI_CN75_KKS_NODDI32] → Results\CTI:   0%|                                                | 0/1 [00:00<?, ?file/s]
] MWI_CN75_KKS_NODDI32] → Results\CTI: 100%|████████████████████████████████████████| 1/1 [00:01<00:00,  1.03s/file]
CTI_ALPS folders:  97%|████████████████████████████████████████████████████████▏ | 254/262 [11:09<00:17,  2.13s/folder]

[OK] MWI_CN75_KKS_NODDI32: copied 1 file(s) to D:\JHAhn\8641_conductivity\DTI_ALPS\1_8641_CN_MCI\MWI_CN75_KKS_NODDI32\Results\CTI

] MWI_CN76_PHJ_NODDI32] → Results\CTI:   0%|                                                | 0/1 [00:00<?, ?file/s]
] MWI_CN76_PHJ_NODDI32] → Results\CTI: 100%|████████████████████████████████████████| 1/1 [00:01<00:00,  1.44s/file]
CTI_ALPS folders:  97%|████████████████████████████████████████████████████████▍ | 255/262 [11:10<00:13,  1.93s/folder]

[OK] MWI_CN76_PHJ_NODDI32: copied 1 file(s) to D:\JHAhn\8641_conductivity\DTI_ALPS\1_8641_CN_MCI\MWI_CN76_PHJ_NODDI32\Results\CTI

] MWI_CN77_PJC_NODDI32] → Results\CTI:   0%|                                                | 0/1 [00:00<?, ?file/s]
] MWI_CN77_PJC_NODDI32] → Results\CTI: 100%|████████████████████████████████████████| 1/1 [00:02<00:00,  2.06s/file]
CTI_ALPS folders:  98%|████████████████████████████████████████████████████████▋ | 256/262 [11:12<00:11,  1.97s/folder]

[OK] MWI_CN77_PJC_NODDI32: copied 1 file(s) to D:\JHAhn\8641_conductivity\DTI_ALPS\1_8641_CN_MCI\MWI_CN77_PJC_NODDI32\Results\CTI

] MWI_CN79_CYE_NODDI32] → Results\CTI:   0%|                                                | 0/1 [00:00<?, ?file/s]
] MWI_CN79_CYE_NODDI32] → Results\CTI: 100%|████████████████████████████████████████| 1/1 [00:04<00:00,  4.93s/file]
CTI_ALPS folders:  98%|████████████████████████████████████████████████████████▉ | 257/262 [11:17<00:14,  2.87s/folder]

[OK] MWI_CN79_CYE_NODDI32: copied 1 file(s) to D:\JHAhn\8641_conductivity\DTI_ALPS\1_8641_CN_MCI\MWI_CN79_CYE_NODDI32\Results\CTI

] MWI_CN80_LSR_NODDI32] → Results\CTI:   0%|                                                | 0/1 [00:00<?, ?file/s]
] MWI_CN80_LSR_NODDI32] → Results\CTI: 100%|████████████████████████████████████████| 1/1 [00:03<00:00,  3.52s/file]
CTI_ALPS folders:  98%|█████████████████████████████████████████████████████████ | 258/262 [11:21<00:12,  3.07s/folder]

[OK] MWI_CN80_LSR_NODDI32: copied 1 file(s) to D:\JHAhn\8641_conductivity\DTI_ALPS\1_8641_CN_MCI\MWI_CN80_LSR_NODDI32\Results\CTI

] MWI_CN81_CSH_NODDI32] → Results\CTI:   0%|                                                | 0/1 [00:00<?, ?file/s]
] MWI_CN81_CSH_NODDI32] → Results\CTI: 100%|████████████████████████████████████████| 1/1 [00:01<00:00,  1.38s/file]
CTI_ALPS folders:  99%|█████████████████████████████████████████████████████████▎| 259/262 [11:22<00:07,  2.56s/folder]

[OK] MWI_CN81_CSH_NODDI32: copied 1 file(s) to D:\JHAhn\8641_conductivity\DTI_ALPS\1_8641_CN_MCI\MWI_CN81_CSH_NODDI32\Results\CTI

] MWI_CN82_LMR_NODDI32] → Results\CTI:   0%|                                                | 0/1 [00:00<?, ?file/s]
] MWI_CN82_LMR_NODDI32] → Results\CTI: 100%|████████████████████████████████████████| 1/1 [00:01<00:00,  1.34s/file]
CTI_ALPS folders:  99%|█████████████████████████████████████████████████████████▌| 260/262 [11:23<00:04,  2.20s/folder]

[OK] MWI_CN82_LMR_NODDI32: copied 1 file(s) to D:\JHAhn\8641_conductivity\DTI_ALPS\1_8641_CN_MCI\MWI_CN82_LMR_NODDI32\Results\CTI

] MWI_CN83_LYS_NODDI32] → Results\CTI:   0%|                                                | 0/1 [00:00<?, ?file/s]
] MWI_CN83_LYS_NODDI32] → Results\CTI: 100%|████████████████████████████████████████| 1/1 [00:02<00:00,  2.18s/file]
CTI_ALPS folders: 100%|█████████████████████████████████████████████████████████▊| 261/262 [11:26<00:02,  2.20s/folder]

[OK] MWI_CN83_LYS_NODDI32: copied 1 file(s) to D:\JHAhn\8641_conductivity\DTI_ALPS\1_8641_CN_MCI\MWI_CN83_LYS_NODDI32\Results\CTI

] MWI_CN84_LHS_NODDI32] → Results\CTI:   0%|                                                | 0/1 [00:00<?, ?file/s]
] MWI_CN84_LHS_NODDI32] → Results\CTI: 100%|████████████████████████████████████████| 1/1 [00:04<00:00,  4.06s/file]
CTI_ALPS folders: 100%|██████████████████████████████████████████████████████████| 262/262 [11:30<00:00,  2.63s/folder]

[OK] MWI_CN84_LHS_NODDI32: copied 1 file(s) to D:\JHAhn\8641_conductivity\DTI_ALPS\1_8641_CN_MCI\MWI_CN84_LHS_NODDI32\Results\CTI

In [ ]:
## CTI-ALPS data merging

In [5]:
LT_COLS = ["LT_Proj_Dxx","LT_Proj_Dyy","LT_Proj_Dzz",
           "LT_Assoc_Dxx","LT_Assoc_Dyy","LT_Assoc_Dzz",
           "LT_CTI-ALPS index"]
RT_COLS = ["RT_Proj_Dxx","RT_Proj_Dyy","RT_Proj_Dzz",
           "RT_Assoc_Dxx","RT_Assoc_Dyy","RT_Assoc_Dzz",
           "RT_CTI-ALPS index"]
FINAL_COLS = ["PDI"] + LT_COLS + RT_COLS

def get_blocks(base):
    """9개 대상 경로(필터 포함) 구성"""
    return [
        (os.path.join(base, r"1_8641_CN_MCI"),                   lambda n: (n == "Bin") or n.startswith("x_")),
        (os.path.join(base, r"2_Dementia", r"DKI"),              lambda n: (n == "Bin")),
        (os.path.join(base, r"2_Dementia", r"EPT2019", r"prep"), None),
        (os.path.join(base, r"2_Dementia", r"EPT2020"),          lambda n: n.startswith("xEPI-")),
        (os.path.join(base, r"2_Dementia", r"EPT2021"),          None),
        (os.path.join(base, r"2_Dementia", r"EPT2022"),          None),
        (os.path.join(base, r"2_Dementia", r"EPT2023"),          lambda n: n.startswith("xEPI-")),
        (os.path.join(base, r"2_Dementia", r"EPT2024"),          None),
        (os.path.join(base, r"8641_DKI"),                        None),
    ]

def _norm_cell(x):
    if pd.isna(x): return None
    s = str(x).strip().strip('"').strip()
    v = pd.to_numeric(s, errors="coerce")
    return v if v is not None and not pd.isna(v) else s

def read_stat_file(path):
    """한 행 파일 읽어 (pdi:str, 7개 float 리스트) 반환. 실패 시 None"""
    try:
        ext = os.path.splitext(path)[1].lower()
        if ext in (".xlsx", ".xls"):
            df = pd.read_excel(path, header=None)
        else:
            df = pd.read_csv(path, header=None, sep=None, engine="python")
        if df.empty: return None
        row = [_norm_cell(x) for x in df.iloc[0].tolist()]
        if len(row) < 8: return None
        pdi  = str(row[0]).strip().strip('"').strip()
        vals = [pd.to_numeric(v, errors="coerce") for v in row[1:8]]
        if any(pd.isna(v) for v in vals): return None
        return pdi, vals
    except Exception:
        return None

def find_person_roots(blocks):
    """블록 우선순위대로 사람 폴더 매핑(name -> abs_path)"""
    seen = {}
    for root, exclude in blocks:
        if not os.path.isdir(root): continue
        try:
            for name in os.listdir(root):
                p = os.path.join(root, name)
                if not os.path.isdir(p): continue
                if exclude and exclude(name): continue
                if name not in seen:
                    seen[name] = p
        except PermissionError:
            continue
    return seen

def find_stat_paths(person_dir):
    """person_dir/Results/Stats 에서 LH/RH 파일 경로"""
    stats_dir = os.path.join(person_dir, "Results", "Stats")
    if not os.path.isdir(stats_dir): return None, None
    c_lh = glob.glob(os.path.join(stats_dir, "Auto_CTI_ALPS_index_LH.*"))
    c_rh = glob.glob(os.path.join(stats_dir, "Auto_CTI_ALPS_index_RH.*"))
    return (c_lh[0] if c_lh else None), (c_rh[0] if c_rh else None)

def make_row(person_dir):
    """LH/RH 둘 다 있으면 1행 dict, 아니면 None"""
    lh_path, rh_path = find_stat_paths(person_dir)
    if not lh_path or not rh_path: return None
    lh = read_stat_file(lh_path)
    rh = read_stat_file(rh_path)
    if (lh is None) or (rh is None): return None

    pdi_lh, vals_lh = lh
    _pdi_rh, vals_rh = rh
    row = {"PDI": pdi_lh}
    keys = ["Proj_Dxx","Proj_Dyy","Proj_Dzz","Assoc_Dxx","Assoc_Dyy","Assoc_Dzz","CTI-ALPS index"]
    for k, v in zip(keys, vals_lh): row["LT_"+k] = float(v)
    for k, v in zip(keys, vals_rh): row["RT_"+k] = float(v)
    return row

def merge_cti_alps(base, show_progress=True):
    """
    반환: (df, info)
      - df: 최종 병합 DataFrame (PDI 1열 + LT/RT 7+7열)
      - info: {'total':N, 'written':M, 'skipped':K}
    """
    blocks_raw = get_blocks(base)
    # (root, exclude, note) → (root, exclude)만 사용
    blocks = [(r, ex) for (r, ex, *_) in [(b[0], b[1], None) if len(b)==2 else b for b in blocks_raw]]

    people = find_person_roots(blocks)
    names = sorted(people.keys())
    rows, skipped = [], 0

    iterator = tqdm(names, desc="Merging CTI-ALPS", unit="person") if show_progress else names
    for name in iterator:
        row = make_row(people[name])
        if row is None:
            skipped += 1
            if show_progress: tqdm.write(f"[SKIP] {name}: LH/RH 없음 또는 읽기 실패")
            continue
        rows.append(row)

    if not rows:
        empty = pd.DataFrame(columns=FINAL_COLS)
        return empty, {"total": len(names), "written": 0, "skipped": skipped}

    df = pd.DataFrame(rows)
    for c in FINAL_COLS:
        if c not in df.columns: df[c] = pd.NA
    df = df[FINAL_COLS]
    return df, {"total": len(names), "written": len(df), "skipped": skipped}

df, info = merge_cti_alps(base, show_progress=True)
print(info)
df

Merging CTI-ALPS:  28%|████████████████▍                                         | 96/340 [00:00<00:00, 474.71person/s]

[SKIP] Bin: LH/RH 없음 또는 읽기 실패
[SKIP] EPT2022AD04_KSS_NODDI32: LH/RH 없음 또는 읽기 실패
[SKIP] EPT2022AD28_GMS_NODDI32v: LH/RH 없음 또는 읽기 실패

Merging CTI-ALPS:  55%|███████████████████████████████▎                         | 187/340 [00:00<00:00, 403.77person/s]

[SKIP] HFC2020AD01_KYM_NODDI32: LH/RH 없음 또는 읽기 실패
[SKIP] HFC2021AD03_LHY_DKI: LH/RH 없음 또는 읽기 실패
[SKIP] HFC2021AD04_HKS_DKI: LH/RH 없음 또는 읽기 실패
[SKIP] HFC2021AD05_KSM_DKI: LH/RH 없음 또는 읽기 실패
[SKIP] HFC2021AD06_KKO_DKI: LH/RH 없음 또는 읽기 실패
[SKIP] HFC2021AD07_HJY_DKI: LH/RH 없음 또는 읽기 실패
[SKIP] HFC2021AD08_NHN_DKI: LH/RH 없음 또는 읽기 실패
[SKIP] HFC2021AD09_KID_DKI: LH/RH 없음 또는 읽기 실패
[SKIP] HFC2021AD10_KSY_DKI: LH/RH 없음 또는 읽기 실패
[SKIP] HFC2021AD11_KJB_DKI: LH/RH 없음 또는 읽기 실패
[SKIP] HFC2021AD12_LGH_DKI: LH/RH 없음 또는 읽기 실패
[SKIP] HFC2021AD13_KYI_DKI: LH/RH 없음 또는 읽기 실패
[SKIP] HFC2021AD14_PGJ_DKI: LH/RH 없음 또는 읽기 실패
[SKIP] HFC2021AD15_YOH_DKI: LH/RH 없음 또는 읽기 실패
[SKIP] HFC2021AD16_OGY_DKI: LH/RH 없음 또는 읽기 실패
[SKIP] HFC2021AD17_KJS_DKI: LH/RH 없음 또는 읽기 실패
[SKIP] HFC2021AD18_WJC_DKI: LH/RH 없음 또는 읽기 실패
[SKIP] HFC2021AD19_KDH_DKI: LH/RH 없음 또는 읽기 실패
[SKIP] HFC2021AD20_YSJ_DKI: LH/RH 없음 또는 읽기 실패
[SKIP] HFC2021AD21_CYS_DKI: LH/RH 없음 또는 읽기 실패
[SKIP] HFC2021AD22_LUB_DKI: LH/RH 없음 또는 읽기 실패
[SKIP] HFC2021AD23_OSD_DKI: LH/RH 없음 또는 읽기 실패
[SKIP] HFC2021AD24_LSM_DKI: LH/RH 없음 또는 읽기 실패
[SKIP] HFC2021AD25_SHS_DKI: LH/RH 없음 또는 읽기 실패
[SKIP] HFC2021AD26_YJI_DKI: LH/RH 없음 또는 읽기 실패
[SKIP] HFC2021AD27_LSH_DKI: LH/RH 없음 또는 읽기 실패
[SKIP] HFC2021AD28_CYA_DKI: LH/RH 없음 또는 읽기 실패
[SKIP] HFC2021AD29_LBD_DKI: LH/RH 없음 또는 읽기 실패
[SKIP] HFC2021AD30_HGS_DKI: LH/RH 없음 또는 읽기 실패
[SKIP] HFC2021AD31_LJB_DKI: LH/RH 없음 또는 읽기 실패
[SKIP] HFC2021AD32_CPY_DKI: LH/RH 없음 또는 읽기 실패
[SKIP] HFC2021AD33_YEO_DKI: LH/RH 없음 또는 읽기 실패
[SKIP] HFC2021AD34_PBY_DKI: LH/RH 없음 또는 읽기 실패
[SKIP] HFC2021AD35_KSS_DKI: LH/RH 없음 또는 읽기 실패
[SKIP] HFC2021AD36_LGS_DKI: LH/RH 없음 또는 읽기 실패
[SKIP] HFC2021AD37_SYH_DKI: LH/RH 없음 또는 읽기 실패
[SKIP] HFC2021AD38_BMR_DKI: LH/RH 없음 또는 읽기 실패
[SKIP] HFC2021AD39_YTG_DKI: LH/RH 없음 또는 읽기 실패
[SKIP] HFC2021AD40_KMS_DKI: LH/RH 없음 또는 읽기 실패
[SKIP] HFC2021AD41_MBS_DKI: LH/RH 없음 또는 읽기 실패
[SKIP] HFC2021AD42_KED_DKI: LH/RH 없음 또는 읽기 실패
[SKIP] HFC2021AD43_NSD_DKI: LH/RH 없음 또는 읽기 실패
[SKIP] HFC2021AD44_YCJ_DKI: LH/RH 없음 또는 읽기 실패
[SKIP] HFC2021AD45_OIS_DKI: LH/RH 없음 또는 읽기 실패
[SKIP] HFC2021AD46_KYJ_DKI: LH/RH 없음 또는 읽기 실패
[SKIP] HFC2021AD47_LHS_DKI: LH/RH 없음 또는 읽기 실패

Merging CTI-ALPS:  80%|█████████████████████████████████████████████▊           | 273/340 [00:00<00:00, 366.04person/s]

[SKIP] HFC2021AD48_KJM_DKI: LH/RH 없음 또는 읽기 실패
[SKIP] HFC2021AD49_LJS_DKI: LH/RH 없음 또는 읽기 실패
[SKIP] HFC2021AD50_DGY_DKI: LH/RH 없음 또는 읽기 실패
[SKIP] HFC2021AD51_NEH_DKI: LH/RH 없음 또는 읽기 실패
[SKIP] HFC2021AD52_KSS_DKI: LH/RH 없음 또는 읽기 실패
[SKIP] HFC2021AD53_LSD_DKI: LH/RH 없음 또는 읽기 실패
[SKIP] HFC2021AD54_KGI_DKI: LH/RH 없음 또는 읽기 실패
[SKIP] HFC2021AD55_LGE_DKI: LH/RH 없음 또는 읽기 실패
[SKIP] HFC2021AD56_SEY_DKI: LH/RH 없음 또는 읽기 실패
[SKIP] HFC2021AD57_PGJ_DKI: LH/RH 없음 또는 읽기 실패
[SKIP] MREPT2020AD09_PJJ_NODDI32: LH/RH 없음 또는 읽기 실패
[SKIP] MREPT2020AD16_CKL_NODDI32: LH/RH 없음 또는 읽기 실패
[SKIP] MREPT2020AD17_LSH_NODDI32: LH/RH 없음 또는 읽기 실패
[SKIP] MREPT2020AD21_CBS_NODDI32: LH/RH 없음 또는 읽기 실패

Merging CTI-ALPS: 100%|█████████████████████████████████████████████████████████| 340/340 [00:00<00:00, 385.78person/s]

[SKIP] MWI_CN42_KKD_DKI: LH/RH 없음 또는 읽기 실패
[SKIP] MWI_CN43_LSL_DKI: LH/RH 없음 또는 읽기 실패
[SKIP] MWI_CN44_OKS_DKI: LH/RH 없음 또는 읽기 실패
[SKIP] MWI_CN45_KTJ_DKI: LH/RH 없음 또는 읽기 실패
[SKIP] MWI_CN46_KCS_DKI: LH/RH 없음 또는 읽기 실패
[SKIP] MWI_CN47_YKS_DKI: LH/RH 없음 또는 읽기 실패
[SKIP] MWI_CN48_WHJ_DKI: LH/RH 없음 또는 읽기 실패
[SKIP] MWI_CN49_CBW_DKI: LH/RH 없음 또는 읽기 실패
[SKIP] MWI_CN50_PMJ_DKI: LH/RH 없음 또는 읽기 실패
[SKIP] MWI_CN51_POS_DKI: LH/RH 없음 또는 읽기 실패
[SKIP] MWI_CN52_SJS_DKI: LH/RH 없음 또는 읽기 실패
[SKIP] MWI_CN53_YMS_DKI: LH/RH 없음 또는 읽기 실패
[SKIP] MWI_CN54_KHS_DKI: LH/RH 없음 또는 읽기 실패
[SKIP] MWI_CN55_JMS_DKI: LH/RH 없음 또는 읽기 실패
[SKIP] MWI_CN56_KYO_DKI: LH/RH 없음 또는 읽기 실패
{'total': 340, 'written': 262, 'skipped': 78}

,PDI,LT_Proj_Dxx,LT_Proj_Dyy,LT_Proj_Dzz,LT_Assoc_Dxx,LT_Assoc_Dyy,LT_Assoc_Dzz,LT_CTI-ALPS index,RT_Proj_Dxx,RT_Proj_Dyy,RT_Proj_Dzz,RT_Assoc_Dxx,RT_Assoc_Dyy,RT_Assoc_Dzz,RT_CTI-ALPS index
0,ADEPT01_YSJ_NODDI24,0.154640,0.136547,0.372179,0.286533,0.394715,0.262895,1.104470,0.421284,0.419805,0.658573,0.393475,0.464674,0.372838,1.027901
1,ADEPT02_LKY_NODDI24,0.230889,0.213943,0.426038,0.247660,0.395434,0.240741,1.052484,0.206692,0.183261,0.478556,0.305591,0.433569,0.313158,1.031956
2,ADEPT03_YKJ_NODDI24,0.200499,0.209197,0.430680,0.340928,0.385080,0.309460,1.043901,0.370849,0.376692,0.702424,0.350790,0.394135,0.352442,0.989719
3,ADEPT04_JWS_NODDI24,0.331312,0.331995,0.598961,0.426246,0.447030,0.377781,1.067319,0.410472,0.408417,0.720397,0.390904,0.460661,0.391659,1.001624
4,ADEPT05_CBK_NODDI24,0.361086,0.332316,0.500665,0.263974,0.370518,0.238849,1.094361,0.440325,0.428100,0.646132,0.350006,0.462110,0.330923,1.041247
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
257,MWI_CN80_LSR_NODDI32,0.120455,0.116088,0.334192,0.272016,0.299302,0.205978,1.218601,0.095568,0.095638,0.362974,0.188456,0.319088,0.206177,0.941056
258,MWI_CN81_CSH_NODDI32,0.099054,0.085795,0.268894,0.225133,0.252498,0.184627,1.198815,0.128332,0.117998,0.345852,0.233705,0.350583,0.250176,0.983328
259,MWI_CN82_LMR_NODDI32,0.180362,0.149926,0.326837,0.200367,0.295091,0.177061,1.164355,0.202879,0.205939,0.485830,0.220892,0.379424,0.203464,1.035095
260,MWI_CN83_LYS_NODDI32,0.072631,0.057072,0.236033,0.205523,0.305449,0.174870,1.199239,0.099302,0.093738,0.271875,0.156811,0.200440,0.142957,1.082038
261,MWI_CN84_LHS_NODDI32,0.117327,0.108673,0.335294,0.324119,0.355334,0.281343,1.131866,0.134248,0.133475,0.430146,0.213679,0.295333,0.187398,1.084313

In [6]:
# Save to file
def save_cti_alps(df, out_path):
    os.makedirs(os.path.dirname(out_path), exist_ok=True)
    with pd.ExcelWriter(out_path, engine="openpyxl") as w:
        df.to_excel(w, sheet_name="CTI_ALPS_index", index=False)
    return out_path

save_cti_alps(df, os.path.join(base, "CTI_ALPS", "CTI_ALPS-index_Results.xlsx"))

'D:\\JHAhn\\8641_conductivity\\DTI_ALPS\\CTI_ALPS\\CTI_ALPS-index_Results.xlsx'

In [17]:
main = pd.read_excel(r"D:\JHAhn\files\Auto_ALPS_index_19-24_main.xlsx")
main["PID"] = (main["PID"].astype(str)
                          .str.strip()
                          .str.replace(r"\.0$", "", regex=True))
main["PID"] = main["PID"].mask(main["PID"].eq("") | main["PID"].str.lower().eq("nan"))
mask = main["PID"].notna()
main.loc[mask, "PID"] = main.loc[mask, "PID"].str.zfill(8)
# main = main.set_index("PID")
main

,PDI,PID,DDX,Group,Age,Sex_01,Sex,Education (Year),MMSE,CDR,...,R_LT_insulaIC-HippoVol,R_RT_insulaIC-HippoVol,R_LT_HippoHFC-HippoVol,R_RT_HippoHFC-HippoVol,R_LT_HippoEC-HippoVol,R_RT_HippoEC-HippoVol,R_LT_InsulaHFC-InsulaVol,R_RT_InsulaHFC-InsulaVol,R_LT_InsulaEC-InsulaVol,R_RT_InsulaEC-InsulaVol
0,ADEPT54_HCS_NODDI24,02459562,NL,0,82,1,F,6.0,27,0.0,...,0.305024,0.205650,2.696677,3.256284,2.444712,3.149281,1.794523,2.122095,1.687050,2.056645
1,EPT2022AD01_KDKM_NODDI32,00310282,AD,2,66,1,F,NaN,23,0.5,...,0.503716,0.338423,1.950329,2.288472,1.344138,1.474099,0.984815,1.160552,0.757258,1.013958
2,EPT2022AD02_SKM_NODDI32,00454439,AD,2,74,0,M,NaN,13,2.0,...,0.259266,0.242416,4.028479,3.885575,3.000292,3.186409,3.174278,3.362853,2.911189,3.385903
3,EPT2022AD03_KKS_NODDI32,00461257,SaMCI,1,74,1,F,12.0,27,0.5,...,0.590434,0.451437,4.347021,4.789124,3.108060,3.079740,1.929451,2.280834,1.681998,2.082624
4,EPT2022AD05_KIJD_NODDI32,00612238,AD,2,83,1,F,NaN,24,1.0,...,0.499354,0.355829,5.133861,3.923252,3.753946,2.823341,1.630049,1.702562,1.476418,1.624511
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
97,MWI_CN79_CYE_NODDI32,10412739,SaMCI,1,72,1,F,NaN,28,0.5,...,0.392295,0.329853,2.061915,2.584288,1.402835,1.590919,0.985638,1.137157,0.793481,1.013646
98,MWI_CN80_LSR_NODDI32,10474812,MaMCI,1,78,1,F,NaN,29,0.5,...,0.436719,0.321682,2.986758,3.788903,2.069485,2.511578,1.512010,1.565580,1.362344,1.507729
99,MWI_CN81_CSH_NODDI32,10482577,SaMCI,1,66,0,M,NaN,28,0.5,...,0.364005,0.253456,3.074656,3.210483,2.783346,2.181404,1.241762,1.372388,1.100934,1.277327
100,MWI_CN82_LMR_NODDI32,10412747,SaMCI,1,74,0,M,NaN,28,0.5,...,0.411900,0.321186,2.727216,3.716997,2.377508,2.466592,1.344976,1.582950,1.148864,1.442690
101,MWI_CN83_LYS_NODDI32,10474783,NL,0,74,1,F,NaN,29,0.0,...,0.497406,0.344000,2.398450,2.817386,1.586735,1.844147,1.405353,1.557870,1.145939,1.383068

In [18]:
if "PDI" not in main.columns:
    raise KeyError("No 'PDI' col in file 'main'")
if "PDI" not in df.columns:
    raise KeyError("No 'PDI' col in file 'df'")
main["PDI"] = (main["PDI"].astype(str).str.strip().str.strip('"').str.strip())
df["PDI"]   = (df["PDI"].astype(str).str.strip().str.strip('"').str.strip())
main["PDI"] = main["PDI"].mask(main["PDI"].eq("") | main["PDI"].str.lower().eq("nan"))
df["PDI"]   = df["PDI"].mask(df["PDI"].eq("")   | df["PDI"].str.lower().eq("nan"))

dup_main = main["PDI"].duplicated(keep=False).sum()
dup_df   = df["PDI"].duplicated(keep=False).sum()
if dup_main: print(f"[WARN] Duplicated PDIs in main: {dup_main} --> Use first PDI")
if dup_df:   print(f"[WARN] Duplicated PDIs in df {dup_df} --> Use first PDI")
main = main.drop_duplicates(subset=["PDI"], keep="first")
df   = df.drop_duplicates(subset=["PDI"], keep="first")

new_cols = [c for c in df.columns if c != "PDI"]
df = df.rename(columns={c: f"CTI_{c}" for c in new_cols})

merged = main.merge(df, on="PDI", how="left")

merged

,PDI,PID,DDX,Group,Age,Sex_01,Sex,Education (Year),MMSE,CDR,...,CTI_CTI_CTI_LT_Assoc_Dyy,CTI_CTI_CTI_LT_Assoc_Dzz,CTI_CTI_CTI_LT_CTI-ALPS index,CTI_CTI_CTI_RT_Proj_Dxx,CTI_CTI_CTI_RT_Proj_Dyy,CTI_CTI_CTI_RT_Proj_Dzz,CTI_CTI_CTI_RT_Assoc_Dxx,CTI_CTI_CTI_RT_Assoc_Dyy,CTI_CTI_CTI_RT_Assoc_Dzz,CTI_CTI_CTI_RT_CTI-ALPS index
0,ADEPT54_HCS_NODDI24,02459562,NL,0,82,1,F,6.0,27,0.0,...,0.472277,0.365113,1.109783,0.520848,0.521945,0.838614,0.467179,0.576006,0.492187,0.974257
1,EPT2022AD01_KDKM_NODDI32,00310282,AD,2,66,1,F,NaN,23,0.5,...,0.183024,0.106396,1.464138,0.065613,0.067988,0.281590,0.176224,0.300066,0.182062,0.967150
2,EPT2022AD02_SKM_NODDI32,00454439,AD,2,74,0,M,NaN,13,2.0,...,0.660463,0.603218,1.030054,0.572164,0.576388,0.822231,0.644952,0.752475,0.651444,0.991272
3,EPT2022AD03_KKS_NODDI32,00461257,SaMCI,1,74,1,F,12.0,27,0.5,...,0.237381,0.136555,1.267073,0.154561,0.157407,0.506764,0.192443,0.356904,0.196123,0.981540
4,EPT2022AD05_KIJD_NODDI32,00612238,AD,2,83,1,F,NaN,24,1.0,...,0.288539,0.223676,1.173859,0.304080,0.295770,0.657524,0.360456,0.467134,0.333783,1.055569
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
97,MWI_CN79_CYE_NODDI32,10412739,SaMCI,1,72,1,F,NaN,28,0.5,...,0.200644,0.137980,1.401680,0.060288,0.061287,0.217723,0.152784,0.181179,0.100257,1.318971
98,MWI_CN80_LSR_NODDI32,10474812,MaMCI,1,78,1,F,NaN,29,0.5,...,0.299302,0.205978,1.218601,0.095568,0.095638,0.362974,0.188456,0.319088,0.206177,0.941056
99,MWI_CN81_CSH_NODDI32,10482577,SaMCI,1,66,0,M,NaN,28,0.5,...,0.252498,0.184627,1.198815,0.128332,0.117998,0.345852,0.233705,0.350583,0.250176,0.983328
100,MWI_CN82_LMR_NODDI32,10412747,SaMCI,1,74,0,M,NaN,28,0.5,...,0.295091,0.177061,1.164355,0.202879,0.205939,0.485830,0.220892,0.379424,0.203464,1.035095
101,MWI_CN83_LYS_NODDI32,10474783,NL,0,74,1,F,NaN,29,0.0,...,0.305449,0.174870,1.199239,0.099302,0.093738,0.271875,0.156811,0.200440,0.142957,1.082038

In [20]:
merged.to_excel(r"D:\JHAhn\files\Auto_ALPS_index_19-24_main_+CTI.xlsx", index=False)

In [27]:
# for Repeated test
base = r'D:\JHAhn\CTI_repeatbility\Val'


def is_num(x):
    return isinstance(x, (int, float, np.integer, np.floating)) and not pd.isna(x)

def is_filled(v):
    if pd.isna(v):
        return False
    if isinstance(v, str) and v.strip() == "":
        return False
    return True

def to_float_safe(s):
    s = str(s).strip()
    if s == "":
        return None
    # ".123" -> "0.123", "-.123" -> "-0.123"
    if re.match(r'^-?\.\d+$', s):
        s = s.replace('.', '0.', 1)
    if re.match(r'^-?\d{1,3}(,\d{3})+(\.\d+)?$', s):
        s = s.replace(',', '')
    try:
        return float(s)
    except Exception:
        try:
            return float(s.replace(',', '.'))
        except Exception:
            return None

def read_first_row(path):
    """일반 CSV 첫 행(헤더 있는 형식) → Series. 실패/빈 파일은 None."""
    try:
        df = pd.read_csv(path)
    except Exception as e:
        print(f"[WARN] read_csv failed: {path} -> {e}")
        return None
    if df.empty:
        print(f"[WARN] empty CSV skipped: {path}")
        return None
    df = df.loc[:, ~df.columns.astype(str).str.match(r'^Unnamed')]
    df.columns = df.columns.map(lambda x: str(x).strip())
    s = df.iloc[0].copy()
    for c in s.index:
        try:
            s[c] = pd.to_numeric(s[c])
        except Exception:
            pass
    return s

def read_cti_singleline(path, side):
    """
    1-lined CTI CSV without Header:
      PDI, Dxx_proj, Dyy_proj, Dzz_proj, Dxx_assoc, Dyy_assoc, Dzz_assoc, ALPS index
    → {side}_CTI_* 표준 컬럼명으로 Series 반환.
    """
    try:
        raw = open(path, 'r', encoding='utf-8', errors='ignore').read().strip()
    except Exception as e:
        print(f"[WARN] read failed: {path} -> {e}")
        return None

    parts = [p.strip() for p in raw.split(',') if p.strip() != ""]
    if len(parts) < 8:
        parts = re.split(r'[,\t]+', raw)
        parts = [p.strip() for p in parts if p.strip() != ""]
    if len(parts) < 8:
        print(f"[WARN] CTI single-line format not matched: {path}")
        return None

    pdi_from_file = parts[0]
    nums = [to_float_safe(x) for x in parts[1:8]]
    if any(v is None for v in nums):
        print(f"[WARN] CTI single-line numeric parse failed: {path} -> {parts[1:8]}")
        return None

    proj_dxx, proj_dyy, proj_dzz, assoc_dxx, assoc_dyy, assoc_dzz, alps = nums
    ser = pd.Series({
        f"{side}_CTI_Proj_Dxx": proj_dxx,
        f"{side}_CTI_Proj_Dyy": proj_dyy,
        f"{side}_CTI_Proj_Dzz": proj_dzz,
        f"{side}_CTI_Assoc_Dxx": assoc_dxx,
        f"{side}_CTI_Assoc_Dyy": assoc_dyy,
        f"{side}_CTI_Assoc_Dzz": assoc_dzz,
        f"{side}_CTI-ALPS index": alps,
        # 참고용: 파일 안의 PDI (폴더명과 다르면 확인용)
        "PDI_from_file": pdi_from_file,
    })
    return ser

def find_file(stats_dir, filename):
    pats = glob.glob(os.path.join(stats_dir, '**', filename), recursive=True)
    return pats[0] if pats else None

# Schema targeted
dti_feats = ['Dxx_proj','Dyy_proj','Dzz_proj','Dxx_assoc','Dyy_assoc','Dzz_assoc','ALPS index']
dti_bands = ['ALL', 'b800', 'b2000']
sides     = ['LT', 'RT']
final_dti_cols = [f"{side}_{band}_{feat}" for side in sides for band in dti_bands for feat in dti_feats]

final_cti_lt = ['LT_CTI_Proj_Dxx','LT_CTI_Proj_Dyy','LT_CTI_Proj_Dzz',
                'LT_CTI_Assoc_Dxx','LT_CTI_Assoc_Dyy','LT_CTI_Assoc_Dzz','LT_CTI-ALPS index']
final_cti_rt = ['RT_CTI_Proj_Dxx','RT_CTI_Proj_Dyy','RT_CTI_Proj_Dzz',
                'RT_CTI_Assoc_Dxx','RT_CTI_Assoc_Dyy','RT_CTI_Assoc_Dzz','RT_CTI-ALPS index']

final_cols = ['PDI'] + final_dti_cols + final_cti_lt + final_cti_rt

# Mapping target names
dti_file_map = {
    ('LT','ALL'):   'Auto_ALPS_index_LH.csv',
    ('LT','b800'):  'Auto_ALPS_index_LH_maxbval800.csv',
    ('LT','b2000'): 'Auto_ALPS_index_LH_maxbval2000.csv',
    ('RT','ALL'):   'Auto_ALPS_index_RH.csv',
    ('RT','b800'):  'Auto_ALPS_index_RH_maxbval800.csv',
    ('RT','b2000'): 'Auto_ALPS_index_RH_maxbval2000.csv',
}
cti_file_map = {
    'LT': 'Auto_CTI_ALPS_index_LH.csv',
    'RT': 'Auto_CTI_ALPS_index_RH.csv',
}

# Remaning: DTI (line-by-line) → Target names
def rename_dti_series(s, side, band):
    out = {}
    for feat in dti_feats:
        candidates = [feat]
        if feat == 'ALPS index':
            candidates += ['ALPS_index','ALPS-index','ALPS','Index','ALPS  index']
        for cand in candidates:
            if cand in s.index and is_filled(s[cand]):
                out[f"{side}_{band}_{feat}"] = s[cand]
                break
    return pd.Series(out)

# Main loops
rows = []
subjects = sorted([d for d in os.listdir(base) if os.path.isdir(os.path.join(base, d))])

for pdi in tqdm(subjects, desc="Merging ALPS per subject", unit="subj", dynamic_ncols=True):
    stats_dir = os.path.join(base, pdi, 'Results', 'Stats')
    if not os.path.isdir(stats_dir):
        continue

    row = {'PDI': pdi}

    # DTI: LT/RT × ALL/b800/b2000
    for side in sides:
        for band in dti_bands:
            fp = find_file(stats_dir, dti_file_map[(side, band)])
            if not fp:
                continue
            s = read_first_row(fp)
            if s is None:
                continue
            s_renamed = rename_dti_series(s, side, band)
            for k, v in s_renamed.items():
                if is_filled(v):
                    row[k] = v

    # CTI: Parsing 1-line Without header CSV (Priority)
    for side in ['LT', 'RT']:
        fp = find_file(stats_dir, cti_file_map[side])
        if fp:
            s_cti = read_cti_singleline(fp, side)
            if s_cti is not None:
                # PDI correction test
                pf = s_cti.get('PDI_from_file')
                if isinstance(pf, str) and pf and pf != pdi:
                    print(f"[INFO] CTI PDI mismatch? folder={pdi} vs file={pf} @ {fp}")
                # Insert values
                for k, v in s_cti.items():
                    if k == 'PDI_from_file':
                        continue
                    if is_filled(v):
                        row[k] = v
                continue

        # CSV files with headers
        if fp:
            s_generic = read_first_row(fp)
            if s_generic is not None:
                def get_val(keys):
                    for k in keys:
                        if k in s_generic.index and is_filled(s_generic[k]):
                            return s_generic[k]
                    return None
                mapping = {
                    f"{side}_CTI_Proj_Dxx": get_val([f"{side}_CTI_Proj_Dxx", f"{side}_Proj_Dxx", "Proj_Dxx"]),
                    f"{side}_CTI_Proj_Dyy": get_val([f"{side}_CTI_Proj_Dyy", f"{side}_Proj_Dyy", "Proj_Dyy"]),
                    f"{side}_CTI_Proj_Dzz": get_val([f"{side}_CTI_Proj_Dzz", f"{side}_Proj_Dzz", "Proj_Dzz"]),
                    f"{side}_CTI_Assoc_Dxx": get_val([f"{side}_CTI_Assoc_Dxx", f"{side}_Assoc_Dxx", "Assoc_Dxx"]),
                    f"{side}_CTI_Assoc_Dyy": get_val([f"{side}_CTI_Assoc_Dyy", f"{side}_Assoc_Dyy", "Assoc_Dyy"]),
                    f"{side}_CTI_Assoc_Dzz": get_val([f"{side}_CTI_Assoc_Dzz", f"{side}_Assoc_Dzz", "Assoc_Dzz"]),
                    f"{side}_CTI-ALPS index": get_val([f"{side}_CTI-ALPS index", f"{side}_CTI_ALPS index", f"{side}_ALPS index", "CTI-ALPS index", "ALPS index"]),
                }
                for k, v in mapping.items():
                    if is_filled(v):
                        row[k] = v

    rows.append(row)

# Final DataFrame --> matching Column ORDERs
dti_feats = ['Dxx_proj','Dyy_proj','Dzz_proj','Dxx_assoc','Dyy_assoc','Dzz_assoc','ALPS index']
dti_bands = ['ALL', 'b800', 'b2000']
sides     = ['LT', 'RT']
final_dti_cols = [f"{side}_{band}_{feat}" for side in sides for band in dti_bands for feat in dti_feats]
final_cti_lt = ['LT_CTI_Proj_Dxx','LT_CTI_Proj_Dyy','LT_CTI_Proj_Dzz',
                'LT_CTI_Assoc_Dxx','LT_CTI_Assoc_Dyy','LT_CTI_Assoc_Dzz','LT_CTI-ALPS index']
final_cti_rt = ['RT_CTI_Proj_Dxx','RT_CTI_Proj_Dyy','RT_CTI_Proj_Dzz',
                'RT_CTI_Assoc_Dxx','RT_CTI_Assoc_Dyy','RT_CTI_Assoc_Dzz','RT_CTI-ALPS index']
final_cols = ['PDI'] + final_dti_cols + final_cti_lt + final_cti_rt

df_all = pd.DataFrame(rows).reindex(columns=final_cols)

# Numeric cols
for c in df_all.columns:
    if c != 'PDI':
        df_all[c] = pd.to_numeric(df_all[c], errors='coerce')

print("Shape:", df_all.shape)

df_all

Merging ALPS per subject:  69%|█████████████████████████████████████▏                | 11/16 [00:00<00:00, 97.38subj/s]

[WARN] CTI single-line format not matched: D:\JHAhn\CTI_repeatbility\Val\HYPEPT02_Post\Results\Stats\Auto_CTI_ALPS_index_LH.csv
[WARN] empty CSV skipped: D:\JHAhn\CTI_repeatbility\Val\HYPEPT02_Post\Results\Stats\Auto_CTI_ALPS_index_LH.csv
[WARN] CTI single-line format not matched: D:\JHAhn\CTI_repeatbility\Val\HYPEPT02_Post\Results\Stats\Auto_CTI_ALPS_index_RH.csv
[WARN] empty CSV skipped: D:\JHAhn\CTI_repeatbility\Val\HYPEPT02_Post\Results\Stats\Auto_CTI_ALPS_index_RH.csv
[WARN] CTI single-line format not matched: D:\JHAhn\CTI_repeatbility\Val\HYPEPT02_Pre\Results\Stats\Auto_CTI_ALPS_index_LH.csv
[WARN] empty CSV skipped: D:\JHAhn\CTI_repeatbility\Val\HYPEPT02_Pre\Results\Stats\Auto_CTI_ALPS_index_LH.csv
[WARN] CTI single-line format not matched: D:\JHAhn\CTI_repeatbility\Val\HYPEPT02_Pre\Results\Stats\Auto_CTI_ALPS_index_RH.csv
[WARN] empty CSV skipped: D:\JHAhn\CTI_repeatbility\Val\HYPEPT02_Pre\Results\Stats\Auto_CTI_ALPS_index_RH.csv
[WARN] CTI single-line format not matched: D:\JHAhn\CTI_repeatbility\Val\HYPEPT08_Post\Results\Stats\Auto_CTI_ALPS_index_LH.csv
[WARN] empty CSV skipped: D:\JHAhn\CTI_repeatbility\Val\HYPEPT08_Post\Results\Stats\Auto_CTI_ALPS_index_LH.csv
[WARN] CTI single-line format not matched: D:\JHAhn\CTI_repeatbility\Val\HYPEPT08_Post\Results\Stats\Auto_CTI_ALPS_index_RH.csv
[WARN] empty CSV skipped: D:\JHAhn\CTI_repeatbility\Val\HYPEPT08_Post\Results\Stats\Auto_CTI_ALPS_index_RH.csv
[WARN] CTI single-line format not matched: D:\JHAhn\CTI_repeatbility\Val\HYPEPT08_Pre\Results\Stats\Auto_CTI_ALPS_index_LH.csv
[WARN] empty CSV skipped: D:\JHAhn\CTI_repeatbility\Val\HYPEPT08_Pre\Results\Stats\Auto_CTI_ALPS_index_LH.csv
[WARN] CTI single-line format not matched: D:\JHAhn\CTI_repeatbility\Val\HYPEPT08_Pre\Results\Stats\Auto_CTI_ALPS_index_RH.csv
[WARN] empty CSV skipped: D:\JHAhn\CTI_repeatbility\Val\HYPEPT08_Pre\Results\Stats\Auto_CTI_ALPS_index_RH.csv
[WARN] CTI single-line format not matched: D:\JHAhn\CTI_repeatbility\Val\HYPEPT14_Post\Results\Stats\Auto_CTI_ALPS_index_LH.csv
[WARN] empty CSV skipped: D:\JHAhn\CTI_repeatbility\Val\HYPEPT14_Post\Results\Stats\Auto_CTI_ALPS_index_LH.csv
[WARN] CTI single-line format not matched: D:\JHAhn\CTI_repeatbility\Val\HYPEPT14_Post\Results\Stats\Auto_CTI_ALPS_index_RH.csv
[WARN] empty CSV skipped: D:\JHAhn\CTI_repeatbility\Val\HYPEPT14_Post\Results\Stats\Auto_CTI_ALPS_index_RH.csv
[WARN] CTI single-line format not matched: D:\JHAhn\CTI_repeatbility\Val\HYPEPT14_Pre\Results\Stats\Auto_CTI_ALPS_index_LH.csv
[WARN] empty CSV skipped: D:\JHAhn\CTI_repeatbility\Val\HYPEPT14_Pre\Results\Stats\Auto_CTI_ALPS_index_LH.csv
[WARN] CTI single-line format not matched: D:\JHAhn\CTI_repeatbility\Val\HYPEPT14_Pre\Results\Stats\Auto_CTI_ALPS_index_RH.csv
[WARN] empty CSV skipped: D:\JHAhn\CTI_repeatbility\Val\HYPEPT14_Pre\Results\Stats\Auto_CTI_ALPS_index_RH.csv
[WARN] CTI single-line format not matched: D:\JHAhn\CTI_repeatbility\Val\HYPEPT18_Post\Results\Stats\Auto_CTI_ALPS_index_LH.csv
[WARN] empty CSV skipped: D:\JHAhn\CTI_repeatbility\Val\HYPEPT18_Post\Results\Stats\Auto_CTI_ALPS_index_LH.csv
[WARN] CTI single-line format not matched: D:\JHAhn\CTI_repeatbility\Val\HYPEPT18_Post\Results\Stats\Auto_CTI_ALPS_index_RH.csv
[WARN] empty CSV skipped: D:\JHAhn\CTI_repeatbility\Val\HYPEPT18_Post\Results\Stats\Auto_CTI_ALPS_index_RH.csv
[WARN] CTI single-line format not matched: D:\JHAhn\CTI_repeatbility\Val\HYPEPT18_Pre\Results\Stats\Auto_CTI_ALPS_index_LH.csv
[WARN] empty CSV skipped: D:\JHAhn\CTI_repeatbility\Val\HYPEPT18_Pre\Results\Stats\Auto_CTI_ALPS_index_LH.csv
[WARN] CTI single-line format not matched: D:\JHAhn\CTI_repeatbility\Val\HYPEPT18_Pre\Results\Stats\Auto_CTI_ALPS_index_RH.csv
[WARN] empty CSV skipped: D:\JHAhn\CTI_repeatbility\Val\HYPEPT18_Pre\Results\Stats\Auto_CTI_ALPS_index_RH.csv
[WARN] CTI single-line format not matched: D:\JHAhn\CTI_repeatbility\Val\HYPEPT19_Post\Results\Stats\Auto_CTI_ALPS_index_LH.csv
[WARN] empty CSV skipped: D:\JHAhn\CTI_repeatbility\Val\HYPEPT19_Post\Results\Stats\Auto_CTI_ALPS_index_LH.csv
[WARN] CTI single-line format not matched: D:\JHAhn\CTI_repeatbility\Val\HYPEPT19_Post\Results\Stats\Auto_CTI_ALPS_index_RH.csv
[WARN] empty CSV skipped: D:\JHAhn\CTI_repeatbility\Val\HYPEPT19_Post\Results\Stats\Auto_CTI_ALPS_index_RH.csv
[WARN] CTI single-line format not matched: D:\JHAhn\CTI_repeatbility\Val\HYPEPT19_Pre\Results\Stats\Auto_CTI_ALPS_index_LH.csv
[WARN] empty CSV skipped: D:\JHAhn\CTI_repeatbility\Val\HYPEPT19_Pre\Results\Stats\Auto_CTI_ALPS_index_LH.csv
[WARN] CTI single-line format not matched: D:\JHAhn\CTI_repeatbility\Val\HYPEPT19_Pre\Results\Stats\Auto_CTI_ALPS_index_RH.csv
[WARN] empty CSV skipped: D:\JHAhn\CTI_repeatbility\Val\HYPEPT19_Pre\Results\Stats\Auto_CTI_ALPS_index_RH.csv
[WARN] CTI single-line format not matched: D:\JHAhn\CTI_repeatbility\Val\HYPEPT21_Post\Results\Stats\Auto_CTI_ALPS_index_LH.csv
[WARN] empty CSV skipped: D:\JHAhn\CTI_repeatbility\Val\HYPEPT21_Post\Results\Stats\Auto_CTI_ALPS_index_LH.csv
[WARN] CTI single-line format not matched: D:\JHAhn\CTI_repeatbility\Val\HYPEPT21_Post\Results\Stats\Auto_CTI_ALPS_index_RH.csv
[WARN] empty CSV skipped: D:\JHAhn\CTI_repeatbility\Val\HYPEPT21_Post\Results\Stats\Auto_CTI_ALPS_index_RH.csv
[WARN] CTI single-line format not matched: D:\JHAhn\CTI_repeatbility\Val\HYPEPT21_Pre\Results\Stats\Auto_CTI_ALPS_index_LH.csv
[WARN] empty CSV skipped: D:\JHAhn\CTI_repeatbility\Val\HYPEPT21_Pre\Results\Stats\Auto_CTI_ALPS_index_LH.csv
[WARN] CTI single-line format not matched: D:\JHAhn\CTI_repeatbility\Val\HYPEPT21_Pre\Results\Stats\Auto_CTI_ALPS_index_RH.csv
[WARN] empty CSV skipped: D:\JHAhn\CTI_repeatbility\Val\HYPEPT21_Pre\Results\Stats\Auto_CTI_ALPS_index_RH.csv

Merging ALPS per subject: 100%|██████████████████████████████████████████████████████| 16/16 [00:00<00:00, 87.73subj/s]

Shape: (16, 57)

,PDI,LT_ALL_Dxx_proj,LT_ALL_Dyy_proj,LT_ALL_Dzz_proj,LT_ALL_Dxx_assoc,LT_ALL_Dyy_assoc,LT_ALL_Dzz_assoc,LT_ALL_ALPS index,LT_b800_Dxx_proj,LT_b800_Dyy_proj,...,LT_CTI_Assoc_Dyy,LT_CTI_Assoc_Dzz,LT_CTI-ALPS index,RT_CTI_Proj_Dxx,RT_CTI_Proj_Dyy,RT_CTI_Proj_Dzz,RT_CTI_Assoc_Dxx,RT_CTI_Assoc_Dyy,RT_CTI_Assoc_Dzz,RT_CTI-ALPS index
0,HYPEPT02_Post,0.670685,0.668682,1.103914,0.810171,1.064792,0.603963,1.163605,0.666788,0.668147,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,HYPEPT02_Pre,0.693707,0.555415,1.129927,0.804811,1.077580,0.484312,1.441261,0.693436,0.553563,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,HYPEPT08_Post,0.724638,0.787779,1.101371,0.794060,1.100974,0.513703,1.166899,0.721739,0.784170,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,HYPEPT08_Pre,0.659906,0.684717,1.069681,0.716962,1.164287,0.414090,1.253057,0.657055,0.678516,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,HYPEPT14_Post,0.599062,0.601874,1.067199,0.784866,1.015246,0.544233,1.207503,0.597958,0.603099,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,HYPEPT14_Pre,0.720254,0.682554,1.194912,0.980216,1.113577,0.600612,1.325214,0.720476,0.678191,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,HYPEPT18_Post,0.793160,0.602836,1.110248,0.853183,1.157009,0.422863,1.605094,0.792804,0.598347,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,HYPEPT18_Pre,0.715555,0.443824,0.989053,0.739391,1.026480,0.384979,1.755479,0.715804,0.439802,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,HYPEPT19_Post,0.678935,0.531603,1.058283,0.798490,1.031517,0.434660,1.529009,0.676652,0.529352,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,HYPEPT19_Pre,0.668866,0.515009,0.945164,0.726756,0.942204,0.308454,1.694821,0.666833,0.513865,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,HYPEPT21_Post,0.703578,0.648097,1.037049,0.749823,1.053748,0.441734,1.333602,0.701180,0.645911,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11,HYPEPT21_Pre,0.684310,0.537506,1.054728,0.815996,0.979962,0.448863,1.521039,0.683447,0.533998,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12,YCN05_1st_KSB,0.659412,0.494386,1.231925,0.940030,0.981895,0.538096,1.549123,0.661584,0.493236,...,0.152124,0.076490,1.367389,0.084353,0.087781,0.349406,0.148616,0.211675,0.149289,0.982697
13,YCN05_2nd_KSB,0.241530,0.099928,0.845761,0.506492,0.652657,0.090466,3.928811,0.239962,0.088697,...,0.152981,0.089862,1.574728,0.090793,0.106781,0.321933,0.195573,0.218577,0.153081,1.101992
14,YCN06_1st_KHJ,0.597831,0.449733,1.032084,0.627861,0.782606,0.321285,1.589706,0.595469,0.448098,...,0.228142,0.155622,1.307996,0.218928,0.204100,0.490953,0.217013,0.256282,0.216719,1.035934
15,YCN06_2nd_KHJ,0.899569,0.736997,1.238498,0.941528,1.042809,0.567138,1.411738,0.897137,0.733573,...,0.208922,0.134403,1.289712,0.164759,0.154888,0.430427,0.177732,0.262397,0.188879,0.996288

In [28]:
# os.makedirs(out_dir, exist_ok=True)
df_all.to_excel(os.path.join(base, "merged-RepeatedPTs_ALPS_DTI+CTI.xlsx"), index=False)