In [56]:
import pandas as pd
import os
import re
import numpy as np

In [2]:
# Defines
def analyse_df(df):
    nan_cnt = df.isnull().sum()
    nan_rto = df.isnull().mean()*100
    unique_vals_cnt = df.nunique()

    ana_result = pd.DataFrame({
        'NaN Counts' : nan_cnt
        , 'NaN Ratio (%)' : nan_rto
        , 'Unique Values' : unique_vals_cnt
    })
    return ana_result

In [47]:
# Pandas :: view ALL
pd.set_option('display.max_rows', None)
pd.set_option('display.max_columns', None)
pd.set_option('display.width', None)
pd.set_option('display.max_colwidth', None)

In [50]:
# Pandas :: Default view
pd.reset_option('display.max_rows')
pd.reset_option('display.max_columns')
pd.reset_option('display.width')
pd.reset_option('display.max_colwidth')

In [3]:
b1 = r"D:\JHAhn\8641_conductivity\DTI_ALPS\DTI_ALPS_Result\2_Dementia"
b2_ = r"D:\JHAhn\8641_conductivity\DTI_ALPS"
b2 = r"\\10.100.174.19\Raw_image\1_내 연구 PAR_REC 모음\2020_2024_Conductivity_MyelinWater_중견연구\8641_CNMCIAD_Conductivity_MWI"

In [25]:
b2f_ = os.path.join(b2_, "김민서Final 8641 conductivity MWF_2024_11_22_이학영.xlsx")
b2f = os.path.join(b2, "(8641최종본)Final 8641 conductivity MWF_2024_12_31_건대.xlsx")

b2_AD = pd.read_excel(b2f_, sheet_name="dementiaMRI", dtype={"ID": str})
b2_AD.rename(columns={"ID": "PID"}, inplace=True)
b2_AD["PID"] = b2_AD["PID"].astype(str)
b2_AD["Code"] = b2_AD["Code"].astype(str)
print(b2_AD)

b2AD = pd.read_excel(b2f, sheet_name="dementiaMRI", dtype={"ID": str})
b2AD = b2AD.rename(columns={'Code': 'Origin Code'})
b2AD = b2AD.rename(columns={'미수코드': 'Code'})
b2AD["Code"] = b2AD["Code"].astype(str)
print(b2AD)

for df in (b2_AD, b2AD):
    df['Code'] = df['Code'].astype(str)
print(len(b2AD))
b2AD = (b2AD.set_index('Code').join(b2_AD.set_index('Code')[['PID']], how='left')
        .reset_index())
print(len(b2AD))
cols = b2AD.columns.tolist()
cols.insert(cols.index('인원') + 1, cols.pop(cols.index('Code')))
cols.insert(cols.index('Code') + 1, cols.pop(cols.index('PID')))
b2AD = b2AD[cols]
b2AD = b2AD.loc[:, ~b2AD.columns.str.startswith('Unnamed:')]
b2AD

    건대분석정보                                                 인원         Code  \
0      NaN                                               2018          nan
1      NaN  /Raw_image/Year2018ParRec/Brain/Dementia_NODDI...          nan
2      Yes                                                NaN          nan
3      Yes                                                NaN          nan
4      Yes                                                NaN          nan
..     ...                                                ...          ...
340     No                                                NaN  EPT2024AD10
341     No                                                NaN  EPT2024AD11
342     No                                                NaN  EPT2024AD12
343     No                                                NaN  EPT2024AD13
344    NaN                                             Finish          nan

     미수코드       PID 논문사용                                          final ddx  \
0     NaN       nan  NaN                                                NaN
1     NaN       nan  NaN                                                NaN
2     NaN  00580577  NaN         possible EOAD without amyloid uptake, aMCI
3     NaN  01042065  NaN      확정(주) Dementia in Alzheimer's disease with...
4     NaN  01146318  NaN                                                NaN
..    ...       ...  ...                                                ...
340   NaN  07295104  NaN                                            검사결과 없음
341   NaN  07760856  NaN                                            검사결과 없음
342   NaN  10130501  NaN            moderate AD (with positive amyloid PET)
343   NaN  10466131  NaN                                                NaN
344   NaN       nan  NaN                                                NaN

    Name   Age  Sex  ... global GMV global WMV global CSFV MR_3DT1_TFE  \
0    NaN   NaN  NaN  ...        NaN        NaN         NaN         NaN
1    NaN   NaN  NaN  ...        NaN        NaN         NaN         NaN
2    김승례  67.0    F  ...        NaN        NaN         NaN         NaN
3    이정희  84.0    F  ...        NaN        NaN         NaN         NaN
4    지영분  84.0    F  ...        NaN        NaN         NaN         NaN
..   ...   ...  ...  ...        ...        ...         ...         ...
340  김춘자  77.0    F  ...        NaN        NaN         NaN         NaN
341  김현자  70.0    F  ...        NaN        NaN         NaN         NaN
342  임대식  58.0    M  ...        NaN        NaN         NaN         NaN
343  이태옥  77.0    F  ...        NaN        NaN         NaN         NaN
344  NaN   NaN  NaN  ...        NaN        NaN         NaN         NaN

    MR_3DGRASE_MWI  MR_3DGRASE_REF  MREPT_TSE NODDI MREPT_3DbFFE  \
0              NaN             NaN        NaN   NaN          NaN
1              NaN             NaN        NaN   NaN          NaN
2              NaN             NaN        NaN   NaN          NaN
3              NaN             NaN        NaN   NaN          NaN
4              NaN             NaN        NaN   NaN          NaN
..             ...             ...        ...   ...          ...
340            NaN             NaN        NaN   NaN          NaN
341            NaN             NaN        NaN   NaN          NaN
342            NaN             NaN        NaN   NaN          NaN
343            NaN             NaN        NaN   NaN          NaN
344            NaN             NaN        NaN   NaN          NaN

                                      MRI판독 conclusion
0                                                  NaN
1                                                  NaN
2                   Mild WM hyperitensity in deep WM.
3    Developmental venous anomaly at left prefronta...
4    Focal encephalomalacia at left prefrontal cort...
..                                                 ...
340  Mild small vessel disease.\nVuno: atrophy at l...
341  Chronic infarction at right corona radiata.\nM...
342  ICAD.\nMultiple microbleeds; \nddx amyloid ang...
343  Chronic contusions atbilateral orbitofrontal r...
344                                                NaN

[345 rows x 35 columns]
    건대분석정보   인원 Origin Code         Code   Age Sex Education(Year)  \
0      Yes  NaN         NaN          nan  67.0   F             NaN
1      Yes  NaN         NaN          nan  84.0   F             NaN
2      Yes  NaN         NaN          nan  84.0   F             NaN
3      Yes  NaN         NaN          nan  70.0   F             NaN
4      Yes  NaN         NaN          nan  64.0   F             NaN
..     ...  ...         ...          ...   ...  ..             ...
319     No  NaN         NaN  EPT2024AD09  79.0   F             NaN
320     No  NaN         NaN  EPT2024AD10  77.0   F             NaN
321     No  NaN         NaN  EPT2024AD11  70.0   F             NaN
322     No  NaN         NaN  EPT2024AD12  58.0   M             NaN
323     No  NaN         NaN  EPT2024AD13  77.0   F             NaN

                       Clinical Info(진료교수)  \
0                       기억력저하(이학영), 고지혈증,
1                      memory decline(이학영)
2                           기억력저하(이학영) 고혈압
3    기억력저하(이학영) 고지혈증     HTN, dyslipidemia
4                   cognitive decline(이학영)
..                                     ...
319                                (조아랑교수)
320                                  (노경철)
321                                  (노경철)
322                                  (노경철)
323                                (조아랑교수)

                                              최종진단 DDX       SNSB StudyDate  \
0           possible EOAD without amyloid uptake, aMCI  2018-08-24 00:00:00
1        확정(주) Dementia in Alzheimer's disease with...  2018-11-06 00:00:00
2                                                  NaN  2018-10-30 00:00:00
3                          amnestic MCI, single domain  2018-11-02 00:00:00
4                                               R/O AD  2018-12-19 00:00:00
..                                                 ...                  ...
319  Dementia in Alzheimer's disease, unspecified, ...          2024-06-11
320                                            검사결과 없음  2024-03-01 00:00:00
321                                            검사결과 없음                  NaN
322            moderate AD (with positive amyloid PET)  2024-03-29 00:00:00
323                                    MCI, depression  2024-03-04 00:00:00

     ... MR_3DT1_TFE  MR_3DGRASE_MWI  MR_3DGRASE_REF MREPT_TSE NODDI  \
0    ...         NaN             NaN             NaN       NaN   NaN
1    ...         NaN             NaN             NaN       NaN   NaN
2    ...         NaN             NaN             NaN       NaN   NaN
3    ...         NaN             NaN             NaN       NaN   NaN
4    ...         NaN             NaN             NaN       NaN   NaN
..   ...         ...             ...             ...       ...   ...
319  ...         NaN             NaN             NaN       NaN   NaN
320  ...         NaN             NaN             NaN       NaN   NaN
321  ...         NaN             NaN             NaN       NaN   NaN
322  ...         NaN             NaN             NaN       NaN   NaN
323  ...         NaN             NaN             NaN       NaN   NaN

    MREPT_3DbFFE Unnamed: 29  \
0            NaN         NaN
1            NaN         NaN
2            NaN         NaN
3            NaN         NaN
4            NaN         NaN
..           ...         ...
319          NaN         NaN
320          NaN         NaN
321          NaN         NaN
322          NaN         NaN
323          NaN         NaN

                                             final ddx Unnamed: 31  논문사용
0           possible EOAD without amyloid uptake, aMCI         NaN   NaN
1        확정(주) Dementia in Alzheimer's disease with...         NaN   NaN
2                                                  NaN         NaN   NaN
3                          amnestic MCI, single domain         NaN   NaN
4                                               R/O AD         NaN   NaN
..                                                 ...         ...   ...
319                                                NaN         NaN   NaN
320                                            검사결과 없음         NaN   NaN
321                                            검사결과 없음         NaN   NaN
322            moderate AD (with positive amyloid PET)         NaN   NaN
323                                                NaN         NaN   NaN

[324 rows x 33 columns]
324
3249

,건대분석정보,인원,Origin Code,Code,PID,Age,Sex,Education(Year),Clinical Info(진료교수),최종진단 DDX,...,global WMV,global CSFV,MR_3DT1_TFE,MR_3DGRASE_MWI,MR_3DGRASE_REF,MREPT_TSE,NODDI,MREPT_3DbFFE,final ddx,논문사용
0,Yes,NaN,MREPT2019AD01,AD2019_BrMRA01,03735478,70.0,F,14,HTN mdMCI,multiple domain aMCI,...,431.903364,427.441118,O,O,O,O,NODDI32,X,multiple domain aMCI,mdMCI03
1,Yes,NaN,MREPT2019AD02,AD2019_BrMRA02,04381137,68.0,F,13,"HTN, 고지혈증, ICAaneurysm aMCI",amnestic MCI,...,485.314945,315.153808,O,O,O,O,NODDI32,X,amnestic MCI,"HFC,LFC,MWI 사용"
2,Yes,탈락,MREPT2019AD03,AD2019_BrMRA03,04452316,67.0,F,9,"(조아랑) mild NCD(amnestic type), depression","mild NCD(amnestic type), depression",...,404.586605,308.493634,O,O,O,O,NODDI32,X,"mild NCD(amnestic type), depression",HFC
3,Yes,NaN,MREPT2019AD04,AD2019_BrMRA04,04681566,66.0,M,12,subjective cognitive decline,subjective cognitive decline,...,524.819073,337.671219,O,O,O,O,NODDI32,X,subjective cognitive decline,HFC
4,Yes,NaN,MREPT2019AD05,AD2019_BrMRA05,07205823,77.0,F,6,mild SVD aMCI,amnestic MCI,...,414.490405,382.888115,O,O,O,O,NODDI32,X,amnestic MCI,"HFC,LFC,MWI 사용"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3244,No,NaN,NaN,nan,nan,89.0,F,NaN,"dementia, HTN history(진은선)",NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3245,No,NaN,NaN,nan,nan,89.0,F,NaN,"dementia, HTN history(진은선)",NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3246,No,NaN,NaN,nan,nan,89.0,F,NaN,"dementia, HTN history(진은선)",NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3247,No,NaN,NaN,nan,nan,89.0,F,NaN,"dementia, HTN history(진은선)",NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3248,No,NaN,NaN,nan,nan,89.0,F,NaN,"dementia, HTN history(진은선)",NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [27]:
print(f"Rows before Filtering: {len(b2AD):,}")
b2AD = (
    b2AD[
        b2AD['Code'].notna()  & b2AD['PID'].notna() &
        (b2AD['Code'].str.strip().str.lower() != 'nan') &
        (b2AD['PID'].str.strip().str.lower()  != 'nan') &
        (b2AD['Code'].str.strip() != '') &
        (b2AD['PID'].str.strip()  != '')
    ]
    .reset_index(drop=True)
)

print(f"Rows after filtering: {len(b2AD):,}")
print(b2AD[['Code', 'PID']].head())

Rows before Filtering: 3,249
Rows after filtering: 277
             Code        PID
0  AD2019_BrMRA01   03735478
1  AD2019_BrMRA02   04381137
2  AD2019_BrMRA03  04452316
3  AD2019_BrMRA04  04681566
4  AD2019_BrMRA05  07205823

In [28]:
print('-'*80)
b2_CN = pd.read_excel(b2f_, sheet_name="8641CN모집", dtype={"ID": str})
b2_CN.rename(columns={"ID": "PID"}, inplace=True)
b2_CN["PID"] = b2_CN["PID"].astype(str)
print(b2_CN)

b2CN = pd.read_excel(b2f, sheet_name="8641CN모집")
# b2CN['AD_MWI_Code'] = (b2CN['AD_MWI_Code'].astype(str)
#                        .str.replace(r'\(.*$', '', regex=True)
#                        .str.strip()
#                       )
# print(b2CN[['AD_MWI_Code']].head(10))
# print(b2CN)

for df in (b2_CN, b2CN):
    df['AD_MWI_Code'] = df['AD_MWI_Code'].astype(str)

b2CN = (b2CN.set_index('AD_MWI_Code').join(b2_CN.set_index('AD_MWI_Code')[['PID']], how='left')
        .reset_index())
# b2CN
cols = b2CN.columns.tolist()
cols.insert(cols.index('인원') + 1, cols.pop(cols.index('AD_MWI_Code')))
cols.insert(cols.index('논문사용') + 1, cols.pop(cols.index('PID')))
b2CN = b2CN[cols]
b2CN = b2CN.loc[:, ~b2CN.columns.str.startswith('Unnamed:')]
b2CN

--------------------------------------------------------------------------------
    건대분석정보                인원 AD_MWI_Code  미수코드       논문사용        PID Name  \
0      Yes                 1    MWI_CN01  8641  HFC,LFC사용  00145616   강난희
1      Yes  Screen 탈락(본인 취소)         NaN   NaN        NaN   01086907  정병금
2      Yes  Screen 탈락(본인 취소)         NaN   NaN        NaN   06116101  이복례
3      Yes                 2    MWI_CN04  8641     HFC 사용   02716077  송승숙
4      Yes                 3    MWI_CN05  8641  HFC,LFC사용   00469852  이순상
..     ...               ...         ...   ...        ...        ...  ...
108    NaN               NaN         NaN   NaN        NaN        nan  NaN
109    NaN               NaN         NaN   NaN        NaN        nan  NaN
110    NaN               NaN         NaN   NaN        NaN        nan  NaN
111    NaN               NaN         NaN   NaN        NaN        nan  NaN
112    NaN               NaN         NaN   NaN       2022        nan  NaN

     Age  Sex Education (Year)  ...      MRI StudyDate  \
0     70    F               16  ...    2019-10-24(12시)
1    NaN  NaN              NaN  ...                NaN
2    NaN  NaN              NaN  ...                NaN
3     62    F               12  ...  2019-09-11(17:33)
4     72    M               16  ...  2019-09-16(12:09)
..   ...  ...              ...  ...                ...
108  NaN  NaN              NaN  ...                NaN
109  NaN  NaN              NaN  ...                NaN
110  NaN  NaN              NaN  ...                NaN
111  NaN  NaN              NaN  ...                NaN
112  NaN  NaN              NaN  ...                NaN

                        MRI판독 conclusion MR_3DT1_TFE MR_3DGRASE_MWI  \
0                  Within normal limits          NaN            NaN
1                                    NaN         NaN            NaN
2                                    NaN         NaN            NaN
3      Normal finding of brain MRI & MRA         NaN            NaN
4    Normal finding of brain MRI and MRA         NaN            NaN
..                                   ...         ...            ...
108                                  NaN         NaN            NaN
109                                  NaN         NaN            NaN
110                                  NaN         NaN            NaN
111                                  NaN         NaN            NaN
112                                  NaN         NaN            NaN

     MR_3DGRASE_REF  MREPT_TSE  NODDI  MREPT_3DbFFE Unnamed: 30  \
0               NaN        NaN    NaN           NaN         NaN
1               NaN        NaN    NaN           NaN         NaN
2               NaN        NaN    NaN           NaN         NaN
3               NaN        NaN    NaN           NaN         NaN
4               NaN        NaN    NaN           NaN         NaN
..              ...        ...    ...           ...         ...
108             NaN        NaN    NaN           NaN         NaN
109             NaN        NaN    NaN           NaN         NaN
110             NaN        NaN    NaN           NaN         NaN
111             NaN        NaN    NaN           NaN         NaN
112             NaN        NaN    NaN           NaN         NaN

                                                 보호자정보
0                                             최천웅교수 모친
1                                                  NaN
2                                                  NaN
3                                        010-5342-9268
4    010-9016-1310;         02-426-1310;        010...
..                                                 ...
108                                                NaN
109                                                NaN
110                                                NaN
111                                                NaN
112                                                NaN

[113 rows x 32 columns]

,건대분석정보,인원,미수코드,AD_MWI_Code,논문사용,PID,Age,Sex,Education (Year),Screen fail/Drop 이유,...,MREPT_3DbFFE,SWI,T2_OBL_COR,FLAIR,MWF,VOLUME,HFC,"LFC(EC,IC)","SMT(ED,ID)","IVF,EIC"
0,Yes,1,8641,MWI_CN01,"HFC,LFC사용",00145616,70,F,16,Control 모집,...,x,O,O,O,O,O,O,O,O,O
1,No,1,8641,MWI_CN02(ver2),NaN,02123108,74,M,NaN,"Control 모집(SNSB, MRI)",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,No,2,8641,MWI_CN03(ver2),NaN,00078594,67,F,NaN,"Control 모집(SNSB, MRI)",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Yes,2,8641,MWI_CN04,HFC 사용,02716077,62,F,12,Control 모집,...,x,O,O,O,O,O,O,O,O,O
4,Yes,3,8641,MWI_CN05,"HFC,LFC사용",00469852,72,M,16,Control 모집,...,x,O,O,O,O,O,O,O,O,O
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
79,No,6,8641,MWI_CN80(ver2),NaN,10474812,78,F,NaN,"Control 모집(SNSB, MRI)",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
80,No,7,8641,MWI_CN81(ver2),NaN,10482577,66,M,NaN,"Control 모집(SNSB, MRI)",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
81,No,8,8641,MWI_CN82(ver2),NaN,10412747,74,M,NaN,"Control 모집(SNSB, MRI)",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
82,No,9,8641,MWI_CN83(ver2),NaN,10474783,74,F,NaN,"Control 모집(SNSB, MRI)",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
83,No,10,8641,MWI_CN84(ver2),NaN,10474798,74,F,NaN,"Control 모집(SNSB, MRI)",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [29]:
# analyse_df(b2AD)
b2AD

,건대분석정보,인원,Origin Code,Code,PID,Age,Sex,Education(Year),Clinical Info(진료교수),최종진단 DDX,...,global WMV,global CSFV,MR_3DT1_TFE,MR_3DGRASE_MWI,MR_3DGRASE_REF,MREPT_TSE,NODDI,MREPT_3DbFFE,final ddx,논문사용
0,Yes,NaN,MREPT2019AD01,AD2019_BrMRA01,03735478,70.0,F,14,HTN mdMCI,multiple domain aMCI,...,431.903364,427.441118,O,O,O,O,NODDI32,X,multiple domain aMCI,mdMCI03
1,Yes,NaN,MREPT2019AD02,AD2019_BrMRA02,04381137,68.0,F,13,"HTN, 고지혈증, ICAaneurysm aMCI",amnestic MCI,...,485.314945,315.153808,O,O,O,O,NODDI32,X,amnestic MCI,"HFC,LFC,MWI 사용"
2,Yes,탈락,MREPT2019AD03,AD2019_BrMRA03,04452316,67.0,F,9,"(조아랑) mild NCD(amnestic type), depression","mild NCD(amnestic type), depression",...,404.586605,308.493634,O,O,O,O,NODDI32,X,"mild NCD(amnestic type), depression",HFC
3,Yes,NaN,MREPT2019AD04,AD2019_BrMRA04,04681566,66.0,M,12,subjective cognitive decline,subjective cognitive decline,...,524.819073,337.671219,O,O,O,O,NODDI32,X,subjective cognitive decline,HFC
4,Yes,NaN,MREPT2019AD05,AD2019_BrMRA05,07205823,77.0,F,6,mild SVD aMCI,amnestic MCI,...,414.490405,382.888115,O,O,O,O,NODDI32,X,amnestic MCI,"HFC,LFC,MWI 사용"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
272,Yes,NaN,MREPT2020AD24_YYS_NODDI32,MREPT2020AD24,08700631,60.0,F,6,"조아랑 Alzheimer's dementia, early onset, depression","Alzheimer's dementia, early onset, depression",...,336.016348,460.074360,O,O,O,O,NODDI32,X,"Alzheimer's dementia, early onset, depression","HFC,LFC사용"
273,Yes,NaN,MREPT2020AD25_YSJ_NODDI32,MREPT2020AD25,08655418,76.0,F,9,amnestic MCI,amnestic MCI,...,341.371124,402.802737,O,O,O,O,NODDI32,X,amnestic MCI,NaN
274,Yes,NaN,MREPT2020AD26_HMH_NODDI32,MREPT2020AD26,08655425,77.0,M,6,"DM, HTN 고지혈증, 이학영 multiple domain aMCI",multiple domain amnestic MCI,...,454.385693,512.686386,O,O,O,O,NODDI32,X,multiple domain amnestic MCI,NaN
275,Yes,탈락-venous anomaly,MREPT2020AD27_YJJ_NODDI32,MREPT2020AD27,00577752,71.0,F,NaN,"depressive, 이학영 multiple domain non-amnestic MCI",mutiple domain non-amnestic MCI,...,487.814184,468.901713,O,O,O,O,NODDI32,X,mutiple domain non-amnestic MCI,NaN
276,Yes,NaN,MREPT2020AD28_YYL_NODDI32,MREPT2020AD28,05533209,80.0,F,0,"조아랑 Alzheimer's dementia, late onset","Alzheimer's dementia, late onset",...,353.353720,485.691918,O,O,O,O,NODDI32,X,"Alzheimer's dementia, late onset","HFC,LFC사용"

In [30]:
b2CN

,건대분석정보,인원,미수코드,AD_MWI_Code,논문사용,PID,Age,Sex,Education (Year),Screen fail/Drop 이유,...,MREPT_3DbFFE,SWI,T2_OBL_COR,FLAIR,MWF,VOLUME,HFC,"LFC(EC,IC)","SMT(ED,ID)","IVF,EIC"
0,Yes,1,8641,MWI_CN01,"HFC,LFC사용",00145616,70,F,16,Control 모집,...,x,O,O,O,O,O,O,O,O,O
1,No,1,8641,MWI_CN02(ver2),NaN,02123108,74,M,NaN,"Control 모집(SNSB, MRI)",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,No,2,8641,MWI_CN03(ver2),NaN,00078594,67,F,NaN,"Control 모집(SNSB, MRI)",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Yes,2,8641,MWI_CN04,HFC 사용,02716077,62,F,12,Control 모집,...,x,O,O,O,O,O,O,O,O,O
4,Yes,3,8641,MWI_CN05,"HFC,LFC사용",00469852,72,M,16,Control 모집,...,x,O,O,O,O,O,O,O,O,O
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
79,No,6,8641,MWI_CN80(ver2),NaN,10474812,78,F,NaN,"Control 모집(SNSB, MRI)",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
80,No,7,8641,MWI_CN81(ver2),NaN,10482577,66,M,NaN,"Control 모집(SNSB, MRI)",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
81,No,8,8641,MWI_CN82(ver2),NaN,10412747,74,M,NaN,"Control 모집(SNSB, MRI)",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
82,No,9,8641,MWI_CN83(ver2),NaN,10474783,74,F,NaN,"Control 모집(SNSB, MRI)",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
83,No,10,8641,MWI_CN84(ver2),NaN,10474798,74,F,NaN,"Control 모집(SNSB, MRI)",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [31]:
with pd.ExcelWriter(os.path.join(b2_, "0723_8641_fin_Conductivity MWF.xlsx")
                    , engine="xlsxwriter") as writer:
    b2AD.to_excel(writer, sheet_name="dementiaMRI", index=False)
    b2CN.to_excel(writer, sheet_name="8641CN모집", index=False)

In [4]:
# load results file
b1f = os.path.join(b1, "Auto_ALPS_index_19-24.xlsx")
b1AD = pd.read_excel(b1f, sheet_name="AD", dtype={"PID": str})
b1AD["PID"] = b1AD["PID"].astype(str)
b1CN = pd.read_excel(b1f, sheet_name="CN-MCI", dtype={"PID": str})
b1CN["PID"] = b1CN["PID"].astype(str)
for df in (b1AD, b1CN):
    unnamed = [c for c in df.columns if c.startswith('Unnamed')]
    drop_cols = [c for c in unnamed if df[c].isnull().all()]
    df.drop(columns=drop_cols, inplace=True)
print(b1AD, b1CN)
print('-'*80)

     index                        PDI        PID  Year  LH-ALL_Dxx_proj  \
0        1  MREPT2019AD01_KMO_NODDI32   03735478  2019         0.644891
1        2  MREPT2019AD02_JSJ_NODDI32   04381137  2019         0.711342
2        3  MREPT2019AD03_OHS_NODDI32  04452316   2019         0.817484
3        4  MREPT2019AD04_CSY_NODDI32  04681566   2019         0.636522
4        5  MREPT2019AD05_KJI_NODDI32  07205823   2019         0.884875
..     ...                        ...        ...   ...              ...
206    207    EPT2024AD09_CSO_NODDI32   05212646  2024         0.777790
207    208    EPT2024AD10_KCJ_NODDI32   07295104  2024         0.703165
208    209    EPT2024AD11_KHJ_NODDI32   07760856  2024         0.695299
209    210    EPT2024AD12_LDS_NODDI32   10130501  2024         0.758654
210    211    EPT2024AD13_LTO_NODDI32   10466131  2024         0.672885

     LH-ALL_Dyy_proj  LH-ALL_Dzz_proj  LH-ALL_Dxx_assoc  LH-ALL_Dyy_assoc  \
0           0.617538         1.173563          0.838976          1.092285
1           0.473727         1.183256          0.801073          1.124653
2           0.701432         1.253393          0.921833          1.174945
3           0.566616         1.020413          0.824179          0.994313
4           0.763448         1.324970          1.043850          1.245618
..               ...              ...               ...               ...
206         0.751147         1.083035          0.980567          1.264496
207         0.449837         1.133783          0.799426          1.147285
208         0.652078         1.204808          0.964770          1.229719
209         0.879287         1.034725          1.054118          0.944798
210         0.600487         1.233325          0.774175          1.059713

     LH-ALL_Dzz_assoc  ...  Hippocampus_ID_IVF  Insula_ID_IVF  \
0            0.606418  ...                 NaN            NaN
1            0.628264  ...            0.002197       0.002015
2            0.667998  ...                 NaN            NaN
3            0.478768  ...                 NaN            NaN
4            0.718111  ...            0.002079       0.001917
..                ...  ...                 ...            ...
206          0.673572  ...                 NaN            NaN
207          0.547185  ...                 NaN            NaN
208          0.694285  ...                 NaN            NaN
209          0.616008  ...                 NaN            NaN
210          0.615325  ...                 NaN            NaN

     Precuneus_SMT_ID_IVF  MTG_ID_IVF  ParaHippocampus_SMT_ID_IVF  \
0                     NaN         NaN                         NaN
1                0.001693    0.001687                    0.002003
2                     NaN         NaN                         NaN
3                     NaN         NaN                         NaN
4                0.001859    0.001672                    0.001945
..                    ...         ...                         ...
206                   NaN         NaN                         NaN
207                   NaN         NaN                         NaN
208                   NaN         NaN                         NaN
209                   NaN         NaN                         NaN
210                   NaN         NaN                         NaN

     Hippocampus_IVF  Insula IVF  Precuneus_IVF  MTG_IVF  \
0                NaN         NaN            NaN      NaN
1           0.335837    0.359402       0.314762  0.33937
2                NaN         NaN            NaN      NaN
3                NaN         NaN            NaN      NaN
4           0.307935    0.327340       0.249932  0.29929
..               ...         ...            ...      ...
206              NaN         NaN            NaN      NaN
207              NaN         NaN            NaN      NaN
208              NaN         NaN            NaN      NaN
209              NaN         NaN            NaN      NaN
210              NaN         NaN            NaN      NaN

     ParaHippocampus_SMT_IVF
0                        NaN
1                   0.313549
2                        NaN
3                        NaN
4                   0.277217
..                       ...
206                      NaN
207                      NaN
208                      NaN
209                      NaN
210                      NaN

[211 rows x 106 columns]     index                   PDI        PID    Year  LH-ALL_Dxx_proj  \
0       1  MWI_CN01_KNH_NODDI32  00145616   2019.0         0.853582
1       2  MWI_CN04_SSS_NODDI32   02716077  2019.0         0.721595
2       3  MWI_CN05_LSS_NODDI32   00469852  2019.0         0.648850
3       4  MWI_CN06_KDS_NODDI32   02296061  2019.0         0.776232
4       5  MWI_CN07_KSB_NODDI32   00316024  2019.0         0.760503
5       6  MWI_CN09_YKJ_NODDI32   00080969  2019.0         0.721305
6       7  MWI_CN10_CJS_NODDI32   01147259  2019.0         0.766402
7       8  MWI_CN12_LJK_NODDI32   05871888  2019.0         0.809517
8       9   MWI_CN13_KH_NODDI32   06476189  2019.0         0.661128
9      10  MWI_CN14_PYJ_NODDI32   04341115  2019.0         0.667318
10     11  MWI_CN15_YCJ_NODDI32   01607233  2019.0         0.783634
11     12  MWI_CN16_LCS_NODDI32   01190888  2019.0         0.750492
12     13  MWI_CN17_LPS_NODDI32  04825611   2019.0         0.812866
13     14  MWI_CN18_HCS_NODDI32  02022033   2019.0         0.805717
14     15  MWI_CN19_CSO_NODDI32  04073053   2019.0         0.637047
15     16  MWI_CN20_PYJ_NODDI32   01382411  2020.0         0.649847
16     17  MWI_CN21_PYB_NODDI32   04086417  2020.0        89.345674
17     18  MWI_CN22_YYJ_NODDI32   00875397  2020.0         0.771681
18     19  MWI_CN23_HJL_NODDI32   08481071  2020.0         0.861621
19     20  MWI_CN24_PKJ_NODDI32   08481058  2020.0         0.780769
20     21  MWI_CN25_NKJ_NODDI32   08500417  2020.0         0.809053
21     22  MWI_CN26_LSR_NODDI32   08510171  2020.0         0.651656
22     23  MWI_CN27_LSJ_NODDI32   08510155  2020.0         0.785996
23     24  MWI_CN28_KOS_NODDI32   00213101  2020.0         0.821979
24     25  MWI_CN29_KSH_NODDI32   00243749  2020.0         0.652968
25     26  MWI_CN30_PYS_NODDI32   08519137  2020.0         0.659945
26     27  MWI_CN31_LOH_NODDI32   02528398  2020.0         0.636865
27     28  MWI_CN32_KYH_NODDI32   08664289  2020.0         0.696205
28     29  MWI_CN33_LSH_NODDI32   01206895  2020.0         0.638877
29     30  MWI_CN34_OJS_NODDI32   04727886  2020.0         0.687721
30     31  MWI_CN35_LES_NODDI32   08696493  2020.0         0.763828
31     32  MWI_CN36_KER_NODDI32   00738146  2020.0         0.747137
32     33  MWI_CN37_KJR_NODDI32   01283958  2020.0         1.267064
33     34  MWI_CN38_JJB_NODDI32   02022042  2020.0         0.697029
34     35  MWI_CN39_LTS_NODDI32   00613165  2020.0         0.676112
35     36  MWI_CN40_LDS_NODDI32   08129675  2020.0         0.680826
36     37  MWI_CN41_JHL_NODDI32   04920375  2020.0         0.730996
37     38  MWI_CN57_YHY_NODDI32   08527223  2022.0         0.629832
38     39  MWI_CN58_LSB_NODDI32   00213324  2022.0         0.707732
39     40  MWI_CN61_CHS_NODDI32   01422655  2022.0         0.691838
40     41  MWI_CN65_PYS_NODDI32   09524528  2022.0         0.742088
41     42  MWI_CN66_CSY_NODDI32   00766581  2022.0         0.663827
42     43  MWI_CN67_KOS_NODDI32   09577263  2022.0         0.625652
43     44  MWI_CN68_CDL_NODDI32   00641619  2022.0         0.825319
44     45  MWI_CN69_LSL_NODDI32   09588015  2022.0         0.567737
45     46  MWI_CN70_LCJ_NODDI32   02202449  2022.0         0.771396
46     47  MWI_CN71_LSH_NODDI32   00863315  2022.0         0.635816
47     48  MWI_CN73_GIS_NODDI32   04074843  2022.0         0.614696
48     49  MWI_CN74_LKY_NODDI32   09605724  2022.0         0.636038
49     50  MWI_CN75_KKS_NODDI32   09605754  2022.0         0.839752
50     51  MWI_CN76_PHJ_NODDI32   00359871  2022.0         0.974929
51     52  MWI_CN77_PJC_NODDI32   07090169     NaN         0.666742
52     53  MWI_CN79_CYE_NODDI32   10412739     NaN         0.753935
53     54  MWI_CN80_LSR_NODDI32   10474812     NaN         0.602834
54     55  MWI_CN81_CSH_NODDI32   10482577     NaN         0.638415
55     56  MWI_CN82_LMR_NODDI32   10412747     NaN         0.789849
56     57  MWI_CN83_LYS_NODDI32   10474783     NaN         0.572063
57     58  MWI_CN84_LHS_NODDI32   10474798     NaN         0.647483

    LH-ALL_Dyy_proj  LH-ALL_Dzz_proj  LH-ALL_Dxx_assoc  LH-ALL_Dyy_assoc  \
0          0.731372         1.259900          1.086533          1.012292
1          0.654347         1.212313          0.875281          1.239043
2          0.534350         1.036836          0.781160          1.029860
3          0.855603         0.955848          0.964658          0.958752
4          0.692654         1.243302          0.877096          1.144913
5          0.585058         1.168966          0.807095          1.140908
6          0.500861         1.051554          0.775147          0.896206
7          0.506511         1.159348          1.022137          0.895856
8          0.740881         1.190856          0.836728          1.072988
9          0.716731         1.135098          0.797246          1.217310
10         0.542104         1.197984          0.810296          1.157182
11         0.767349         1.155198          1.084923          1.265144
12         0.996424         1.218665          0.992245          1.356309
13         0.608529         1.132986          0.879473          1.205904
14         0.484846         1.023011          0.689319          1.038350
15         0.728100         0.978214          0.746785          1.095501
16        85.156431        85.893714        102.774043         97.815652
17         0.663884         0.996707          0.821504          1.230176
18         0.685175         1.368943          0.848066          1.327288
19         0.805937         1.189413          0.871540          1.407582
20         0.628974         1.200095          0.822395          1.080473
21         0.516872         1.081359          0.738009          1.078824
22         0.609021         1.140311          0.748307          1.253957
23         0.734907         0.993994          0.937452          1.039852
24         0.485778         1.078290          0.759060          0.934854
25         0.500463         0.978506          0.804329          0.916356
26         0.624176         1.164440          0.775352          1.091314
27         0.723061         1.101509          0.903287          1.094731
28         0.698796         1.098446          0.761060          1.133910
29         0.524964         1.058712          0.874680          1.200491
30         0.533087         1.089920          0.853114          1.193487
31         0.516512         1.174375          0.878996          1.076370
32         1.244017         1.117839          1.269628          1.258637
33         0.773143         1.046729          0.801487          1.138984
34         0.748491         1.064096          0.886808          1.172366
35         0.595489         1.151737          0.856426          1.065426
36         0.606768         1.137128          1.017152          1.050933
37         0.574801         0.976331          0.773797          0.881921
38         0.692642         1.101284          0.887895          1.048043
39         0.513470         1.145116          0.671059          1.297181
40         0.611022         1.156521          0.850296          1.222221
41         0.725533         1.045238          0.839034          1.135543
42         0.643337         1.160600          0.799541          1.107464
43         0.661257         1.253624          1.041866          1.176894
44         0.528092         1.266596          0.772384          1.072283
45         0.632500         1.171522          0.887840          1.099671
46         0.511072         1.056698          0.825567          0.929914
47         0.510977         1.052888          0.812034          1.064029
48         0.581639         0.989334          0.811474          1.088186
49         0.745258         1.373741          0.998471          1.189541
50         0.802987         1.458045          1.291569          1.189480
51         0.643739         1.125764          0.830681          1.076399
52         0.504262         1.198478          0.907089          1.106855
53         0.559894         1.037194          0.866400          1.013780
54         0.664246         1.101576          0.802995          1.033883
55         0.802365         1.201563          0.835766          1.131215
56         0.531833         1.064045          0.738442          0.933197
57         0.572705         1.053408          0.821964          1.005473

    LH-ALL_Dzz_assoc  ...  Hippocampus_ID_IVF  Insula_ID_IVF  \
0           0.845369  ...            0.002063       0.001983
1           0.555101  ...                 NaN            NaN
2           0.513538  ...            0.002116       0.001970
3           0.661455  ...            0.002248       0.001914
4           0.597675  ...                 NaN            NaN
5           0.511759  ...                 NaN            NaN
6           0.576431  ...                 NaN            NaN
7           0.680670  ...                 NaN            NaN
8           0.530080  ...            0.002145       0.001944
9           0.580188  ...                 NaN            NaN
10          0.503133  ...                 NaN            NaN
11          0.825563  ...                 NaN            NaN
12          0.826216  ...                 NaN            NaN
13          0.698878  ...            0.002139       0.002013
14          0.444999  ...                 NaN            NaN
15          0.367056  ...            0.002253       0.002038
16         93.503079  ...                 NaN            NaN
17          0.499316  ...                 NaN            NaN
18          0.593957  ...                 NaN            NaN
19          0.637534  ...            0.002059       0.001962
20          0.504197  ...            0.002259       0.002109
21          0.485794  ...            0.002164       0.001990
22          0.378579  ...            0.002123       0.002064
23          0.579029  ...            0.002254       0.001948
24          0.476488  ...            0.002153       0.002000
25          0.433298  ...                 NaN            NaN
26          0.481007  ...                 NaN            NaN
27          0.498591  ...            0.002178       0.002090
28          0.573942  ...            0.002183       0.001977
29          0.539645  ...            0.002315       0.002063
30          0.427649  ...                 NaN            NaN
31          0.520884  ...                 NaN            NaN
32          1.136036  ...                 NaN            NaN
33          0.510707  ...            0.002176       0.001952
34          0.542684  ...            0.002345       0.002043
35          0.673452  ...            0.002382       0.002128
36          0.585597  ...            0.002126       0.002086
37          0.454999  ...                 NaN            NaN
38          0.490397  ...                 NaN            NaN
39          0.547471  ...                 NaN            NaN
40          0.570590  ...                 NaN            NaN
41          0.602104  ...                 NaN            NaN
42          0.584152  ...                 NaN            NaN
43          0.762897  ...                 NaN            NaN
44          0.675864  ...                 NaN            NaN
45          0.643634  ...                 NaN            NaN
46          0.456447  ...                 NaN            NaN
47          0.609057  ...                 NaN            NaN
48          0.491145  ...                 NaN            NaN
49          0.703382  ...                 NaN            NaN
50          0.910831  ...                 NaN            NaN
51          0.580091  ...                 NaN            NaN
52          0.553258  ...                 NaN            NaN
53          0.606750  ...                 NaN            NaN
54          0.522940  ...                 NaN            NaN
55          0.545787  ...                 NaN            NaN
56          0.458701  ...                 NaN            NaN
57          0.624160  ...                 NaN            NaN

    Precuneus_SMT_ID_IVF  MTG_ID_IVF  ParaHippocampus_SMT_ID_IVF  \
0               0.001745    0.001673                    0.001914
1                    NaN         NaN                         NaN
2               0.001867    0.001690                    0.001977
3               0.001788    0.001664                    0.002037
4                    NaN         NaN                         NaN
5                    NaN         NaN                         NaN
6                    NaN         NaN                         NaN
7                    NaN         NaN                         NaN
8               0.001746    0.001659                    0.001970
9                    NaN         NaN                         NaN
10                   NaN         NaN                         NaN
11                   NaN         NaN                         NaN
12                   NaN         NaN                         NaN
13              0.001861    0.001651                    0.001956
14                   NaN         NaN                         NaN
15              0.001868    0.001655                    0.001978
16                   NaN         NaN                         NaN
17                   NaN         NaN                         NaN
18                   NaN         NaN                         NaN
19              0.001960    0.001692                    0.001936
20              0.001881    0.001792                    0.002085
21              0.001975    0.001699                    0.001950
22              0.001883    0.001675                    0.001949
23              0.001789    0.001625                    0.002063
24              0.001839    0.001616                    0.001994
25                   NaN         NaN                         NaN
26                   NaN         NaN                         NaN
27              0.001929    0.001911                    0.002091
28              0.001813    0.001699                    0.002012
29              0.001980    0.001734                    0.002176
30                   NaN         NaN                         NaN
31                   NaN         NaN                         NaN
32                   NaN         NaN                         NaN
33              0.001814    0.001698                    0.002075
34              0.001906    0.001770                    0.002115
35              0.001953    0.001709                    0.002240
36              0.001925    0.001709                    0.001975
37                   NaN         NaN                         NaN
38                   NaN         NaN                         NaN
39                   NaN         NaN                         NaN
40                   NaN         NaN                         NaN
41                   NaN         NaN                         NaN
42                   NaN         NaN                         NaN
43                   NaN         NaN                         NaN
44                   NaN         NaN                         NaN
45                   NaN         NaN                         NaN
46                   NaN         NaN                         NaN
47                   NaN         NaN                         NaN
48                   NaN         NaN                         NaN
49                   NaN         NaN                         NaN
50                   NaN         NaN                         NaN
51                   NaN         NaN                         NaN
52                   NaN         NaN                         NaN
53                   NaN         NaN                         NaN
54                   NaN         NaN                         NaN

In [5]:
b1AD

,index,PDI,PID,Year,LH-ALL_Dxx_proj,LH-ALL_Dyy_proj,LH-ALL_Dzz_proj,LH-ALL_Dxx_assoc,LH-ALL_Dyy_assoc,LH-ALL_Dzz_assoc,...,Hippocampus_ID_IVF,Insula_ID_IVF,Precuneus_SMT_ID_IVF,MTG_ID_IVF,ParaHippocampus_SMT_ID_IVF,Hippocampus_IVF,Insula IVF,Precuneus_IVF,MTG_IVF,ParaHippocampus_SMT_IVF
0,1,MREPT2019AD01_KMO_NODDI32,03735478,2019,0.644891,0.617538,1.173563,0.838976,1.092285,0.606418,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2,MREPT2019AD02_JSJ_NODDI32,04381137,2019,0.711342,0.473727,1.183256,0.801073,1.124653,0.628264,...,0.002197,0.002015,0.001693,0.001687,0.002003,0.335837,0.359402,0.314762,0.33937,0.313549
2,3,MREPT2019AD03_OHS_NODDI32,04452316,2019,0.817484,0.701432,1.253393,0.921833,1.174945,0.667998,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,4,MREPT2019AD04_CSY_NODDI32,04681566,2019,0.636522,0.566616,1.020413,0.824179,0.994313,0.478768,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,5,MREPT2019AD05_KJI_NODDI32,07205823,2019,0.884875,0.763448,1.324970,1.043850,1.245618,0.718111,...,0.002079,0.001917,0.001859,0.001672,0.001945,0.307935,0.327340,0.249932,0.29929,0.277217
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
206,207,EPT2024AD09_CSO_NODDI32,05212646,2024,0.777790,0.751147,1.083035,0.980567,1.264496,0.673572,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
207,208,EPT2024AD10_KCJ_NODDI32,07295104,2024,0.703165,0.449837,1.133783,0.799426,1.147285,0.547185,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
208,209,EPT2024AD11_KHJ_NODDI32,07760856,2024,0.695299,0.652078,1.204808,0.964770,1.229719,0.694285,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
209,210,EPT2024AD12_LDS_NODDI32,10130501,2024,0.758654,0.879287,1.034725,1.054118,0.944798,0.616008,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
210,211,EPT2024AD13_LTO_NODDI32,10466131,2024,0.672885,0.600487,1.233325,0.774175,1.059713,0.615325,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [6]:
b1CN

,index,PDI,PID,Year,LH-ALL_Dxx_proj,LH-ALL_Dyy_proj,LH-ALL_Dzz_proj,LH-ALL_Dxx_assoc,LH-ALL_Dyy_assoc,LH-ALL_Dzz_assoc,...,Hippocampus_ID_IVF,Insula_ID_IVF,Precuneus_SMT_ID_IVF,MTG_ID_IVF,ParaHippocampus_SMT_ID_IVF,Hippocampus_IVF,Insula IVF,Precuneus_IVF,MTG_IVF,ParaHippocampus_SMT_IVF
0,1,MWI_CN01_KNH_NODDI32,00145616,2019.0,0.853582,0.731372,1.259900,1.086533,1.012292,0.845369,...,0.002063,0.001983,0.001745,0.001673,0.001914,0.317179,0.376434,0.259582,0.330822,0.288121
1,2,MWI_CN04_SSS_NODDI32,02716077,2019.0,0.721595,0.654347,1.212313,0.875281,1.239043,0.555101,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,3,MWI_CN05_LSS_NODDI32,00469852,2019.0,0.648850,0.534350,1.036836,0.781160,1.029860,0.513538,...,0.002116,0.001970,0.001867,0.001690,0.001977,0.305807,0.338011,0.245334,0.284724,0.287061
3,4,MWI_CN06_KDS_NODDI32,02296061,2019.0,0.776232,0.855603,0.955848,0.964658,0.958752,0.661455,...,0.002248,0.001914,0.001788,0.001664,0.002037,0.319215,0.319163,0.227113,0.280718,0.286061
4,5,MWI_CN07_KSB_NODDI32,00316024,2019.0,0.760503,0.692654,1.243302,0.877096,1.144913,0.597675,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,6,MWI_CN09_YKJ_NODDI32,00080969,2019.0,0.721305,0.585058,1.168966,0.807095,1.140908,0.511759,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,7,MWI_CN10_CJS_NODDI32,01147259,2019.0,0.766402,0.500861,1.051554,0.775147,0.896206,0.576431,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,8,MWI_CN12_LJK_NODDI32,05871888,2019.0,0.809517,0.506511,1.159348,1.022137,0.895856,0.680670,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,9,MWI_CN13_KH_NODDI32,06476189,2019.0,0.661128,0.740881,1.190856,0.836728,1.072988,0.530080,...,0.002145,0.001944,0.001746,0.001659,0.001970,0.281156,0.314280,0.293469,0.271209,0.277787
9,10,MWI_CN14_PYJ_NODDI32,04341115,2019.0,0.667318,0.716731,1.135098,0.797246,1.217310,0.580188,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,11,MWI_CN15_YCJ_NODDI32,01607233,2019.0,0.783634,0.542104,1.197984,0.810296,1.157182,0.503133,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11,12,MWI_CN16_LCS_NODDI32,01190888,2019.0,0.750492,0.767349,1.155198,1.084923,1.265144,0.825563,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12,13,MWI_CN17_LPS_NODDI32,04825611,2019.0,0.812866,0.996424,1.218665,0.992245,1.356309,0.826216,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13,14,MWI_CN18_HCS_NODDI32,02022033,2019.0,0.805717,0.608529,1.132986,0.879473,1.205904,0.698878,...,0.002139,0.002013,0.001861,0.001651,0.001956,0.342518,0.370684,0.284883,0.327972,0.310638
14,15,MWI_CN19_CSO_NODDI32,04073053,2019.0,0.637047,0.484846,1.023011,0.689319,1.038350,0.444999,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15,16,MWI_CN20_PYJ_NODDI32,01382411,2020.0,0.649847,0.728100,0.978214,0.746785,1.095501,0.367056,...,0.002253,0.002038,0.001868,0.001655,0.001978,0.325599,0.381604,0.292508,0.317153,0.285835
16,17,MWI_CN21_PYB_NODDI32,04086417,2020.0,89.345674,85.156431,85.893714,102.774043,97.815652,93.503079,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
17,18,MWI_CN22_YYJ_NODDI32,00875397,2020.0,0.771681,0.663884,0.996707,0.821504,1.230176,0.499316,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
18,19,MWI_CN23_HJL_NODDI32,08481071,2020.0,0.861621,0.685175,1.368943,0.848066,1.327288,0.593957,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
19,20,MWI_CN24_PKJ_NODDI32,08481058,2020.0,0.780769,0.805937,1.189413,0.871540,1.407582,0.637534,...,0.002059,0.001962,0.001960,0.001692,0.001936,0.323608,0.371669,0.278651,0.332182,0.297825
20,21,MWI_CN25_NKJ_NODDI32,08500417,2020.0,0.809053,0.628974,1.200095,0.822395,1.080473,0.504197,...,0.002259,0.002109,0.001881,0.001792,0.002085,0.324960,0.368734,0.278570,0.331214,0.303363
21,22,MWI_CN26_LSR_NODDI32,08510171,2020.0,0.651656,0.516872,1.081359,0.738009,1.078824,0.485794,...,0.002164,0.001990,0.001975,0.001699,0.001950,0.362811,0.395823,0.294354,0.352133,0.312945
22,23,MWI_CN27_LSJ_NODDI32,08510155,2020.0,0.785996,0.609021,1.140311,0.748307,1.253957,0.378579,...,0.002123,0.002064,0.001883,0.001675,0.001949,0.339940,0.397310,0.289435,0.338610,0.309178
23,24,MWI_CN28_KOS_NODDI32,00213101,2020.0,0.821979,0.734907,0.993994,0.937452,1.039852,0.579029,...,0.002254,0.001948,0.001789,0.001625,0.002063,0.336613,0.341983,0.259110,0.292436,0.304181
24,25,MWI_CN29_KSH_NODDI32,00243749,2020.0,0.652968,0.485778,1.078290,0.759060,0.934854,0.476488,...,0.002153,0.002000,0.001839,0.001616,0.001994,0.295477,0.346097,0.295710,0.294481,0.288724
25,26,MWI_CN30_PYS_NODDI32,08519137,2020.0,0.659945,0.500463,0.978506,0.804329,0.916356,0.433298,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
26,27,MWI_CN31_LOH_NODDI32,02528398,2020.0,0.636865,0.624176,1.164440,0.775352,1.091314,0.481007,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
27,28,MWI_CN32_KYH_NODDI32,08664289,2020.0,0.696205,0.723061,1.101509,0.903287,1.094731,0.498591,...,0.002178,0.002090,0.001929,0.001911,0.002091,0.303079,0.342878,0.241746,0.290830,0.290699
28,29,MWI_CN33_LSH_NODDI32,01206895,2020.0,0.638877,0.698796,1.098446,0.761060,1.133910,0.573942,...,0.002183,0.001977,0.001813,0.001699,0.002012,0.319583,0.370290,0.285611,0.332771,0.309487
29,30,MWI_CN34_OJS_NODDI32,04727886,2020.0,0.687721,0.524964,1.058712,0.874680,1.200491,0.539645,...,0.002315,0.002063,0.001980,0.001734,0.002176,0.301722,0.339289,0.294069,0.302767,0.296584
30,31,MWI_CN35_LES_NODDI32,08696493,2020.0,0.763828,0.533087,1.089920,0.853114,1.193487,0.427649,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
31,32,MWI_CN36_KER_NODDI32,00738146,2020.0,0.747137,0.516512,1.174375,0.878996,1.076370,0.520884,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
32,33,MWI_CN37_KJR_NODDI32,01283958,2020.0,1.267064,1.244017,1.117839,1.269628,1.258637,1.136036,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
33,34,MWI_CN38_JJB_NODDI32,02022042,2020.0,0.697029,0.773143,1.046729,0.801487,1.138984,0.510707,...,0.002176,0.001952,0.001814,0.001698,0.002075,0.266885,0.328058,0.234085,0.267591,0.255923
34,35,MWI_CN39_LTS_NODDI32,00613165,2020.0,0.676112,0.748491,1.064096,0.886808,1.172366,0.542684,...,0.002345,0.002043,0.001906,0.001770,0.002115,0.324565,0.350751,0.251041,0.304753,0.302692
35,36,MWI_CN40_LDS_NODDI32,08129675,2020.0,0.680826,0.595489,1.151737,0.856426,1.065426,0.673452,...,0.002382,0.002128,0.001953,0.001709,0.002240,0.356873,0.365843,0.262270,0.291764,0.337466
36,37,MWI_CN41_JHL_NODDI32,04920375,2020.0,0.730996,0.606768,1.137128,1.017152,1.050933,0.585597,...,0.002126,0.002086,0.001925,0.001709,0.001975,0.315960,0.331445,0.267208,0.317698,0.293759
37,38,MWI_CN57_YHY_NODDI32,08527223,2022.0,0.629832,0.574801,0.976331,0.773797,0.881921,0.454999,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
38,39,MWI_CN58_LSB_NODDI32,00213324,2022.0,0.707732,0.692642,1.101284,0.887895,1.048043,0.490397,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
39,40,MWI_CN61_CHS_NODDI32,01422655,2022.0,0.691838,0.513470,1.145116,0.671059,1.297181,0.547471,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
40,41,MWI_CN65_PYS_NODDI32,09524528,2022.0,0.742088,0.611022,1.156521,0.850296,1.222221,0.570590,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
41,42,MWI_CN66_CSY_NODDI32,00766581,2022.0,0.663827,0.725533,1.045238,0.839034,1.135543,0.602104,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
42,43,MWI_CN67_KOS_NODDI32,09577263,2022.0,0.625652,0.643337,1.160600,0.799541,1.107464,0.584152,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
43,44,MWI_CN68_CDL_NODDI32,00641619,2022.0,0.825319,0.661257,1.253624,1.041866,1.176894,0.762897,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
44,45,MWI_CN69_LSL_NODDI32,09588015,2022.0,0.567737,0.528092,1.266596,0.772384,1.072283,0.675864,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
45,46,MWI_CN70_LCJ_NODDI32,02202449,2022.0,0.771396,0.632500,1.171522,0.887840,1.099671,0.643634,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
46,47,MWI_CN71_LSH_NODDI32,00863315,2022.0,0.635816,0.511072,1.056698,0.825567,0.929914,0.456447,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
47,48,MWI_CN73_GIS_NODDI32,04074843,2022.0,0.614696,0.510977,1.052888,0.812034,1.064029,0.609057,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
48,49,MWI_CN74_LKY_NODDI32,09605724,2022.0,0.636038,0.581639,0.989334,0.811474,1.088186,0.491145,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
49,50,MWI_CN75_KKS_NODDI32,09605754,2022.0,0.839752,0.745258,1.373741,0.998471,1.189541,0.703382,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
50,51,MWI_CN76_PHJ_NODDI32,00359871,2022.0,0.974929,0.802987,1.458045,1.291569,1.189480,0.910831,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
51,52,MWI_CN77_PJC_NODDI32,07090169,NaN,0.666742,0.643739,1.125764,0.830681,1.076399,0.580091,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
52,53,MWI_CN79_CYE_NODDI32,10412739,NaN,0.753935,0.504262,1.198478,0.907089,1.106855,0.553258,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
53,54,MWI_CN80_LSR_NODDI32,10474812,NaN,0.602834,0.559894,1.037194,0.866400,1.013780,0.606750,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
54,55,MWI_CN81_CSH_NODDI32,10482577,NaN,0.638415,0.664246,1.101576,0.802995,1.033883,0.522940,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
55,56,MWI_CN82_LMR_NODDI32,10412747,NaN,0.789849,0.802365,1.201563,0.835766,1.131215,0.545787,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
56,57,MWI_CN83_LYS_NODDI32,10474783,NaN,0.572063,0.531833,1.064045,0.738442,0.933197,0.458701,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
57,58,MWI_CN84_LHS_NODDI32,10474798,NaN,0.647483,0.572705,1.053408,0.821964,1.005473,0.624160,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [7]:
# load demographic file
# b2f = os.path.join(b2, "김민서Final 8641 conductivity MWF_2024_11_22_이학영.xlsx")
b2f = os.path.join(b2_, "0723_8641_fin_Conductivity MWF.xlsx")

b2AD = pd.read_excel(b2f, sheet_name="dementiaMRI", dtype={"ID": str})
b2AD.rename(columns={"ID": "PID"}, inplace=True)
b2AD["PID"] = b2AD["PID"].astype(str)
print(b2AD)

b2CN = pd.read_excel(b2f, sheet_name="8641CN모집", dtype={"ID": str})
b2CN.rename(columns={"ID": "PID"}, inplace=True)
b2CN["PID"] = b2CN["PID"].astype(str)
print(b2CN)

    건대분석정보                 인원                Origin Code            Code  \
0      Yes                NaN              MREPT2019AD01  AD2019_BrMRA01
1      Yes                NaN              MREPT2019AD02  AD2019_BrMRA02
2      Yes                탈락               MREPT2019AD03  AD2019_BrMRA03
3      Yes                NaN              MREPT2019AD04  AD2019_BrMRA04
4      Yes                NaN              MREPT2019AD05  AD2019_BrMRA05
..     ...                ...                        ...             ...
272    Yes                NaN  MREPT2020AD24_YYS_NODDI32   MREPT2020AD24
273    Yes                NaN  MREPT2020AD25_YSJ_NODDI32   MREPT2020AD25
274    Yes                NaN  MREPT2020AD26_HMH_NODDI32   MREPT2020AD26
275    Yes  탈락-venous anomaly  MREPT2020AD27_YJJ_NODDI32   MREPT2020AD27
276    Yes                NaN  MREPT2020AD28_YYL_NODDI32   MREPT2020AD28

         PID   Age Sex Education(Year)  \
0    3735478  70.0   F              14
1    4381137  68.0   F              13
2    4452316  67.0   F               9
3    4681566  66.0   M              12
4    7205823  77.0   F               6
..       ...   ...  ..             ...
272  8700631  60.0   F               6
273  8655418  76.0   F               9
274  8655425  77.0   M               6
275   577752  71.0   F             NaN
276  5533209  80.0   F               0

                                   Clinical Info(진료교수)  \
0                                            HTN mdMCI
1                         HTN, 고지혈증, ICAaneurysm aMCI
2            (조아랑) mild NCD(amnestic type), depression
3                         subjective cognitive decline
4                                       mild SVD aMCI
..                                                 ...
272  조아랑 Alzheimer's dementia, early onset, depression
273                                       amnestic MCI
274             DM, HTN 고지혈증, 이학영 multiple domain aMCI
275  depressive, 이학영 multiple domain non-amnestic MCI
276               조아랑 Alzheimer's dementia, late onset

                                          최종진단 DDX  ...  global WMV  \
0                             multiple domain aMCI  ...  431.903364
1                                     amnestic MCI  ...  485.314945
2              mild NCD(amnestic type), depression  ...  404.586605
3                     subjective cognitive decline  ...  524.819073
4                                     amnestic MCI  ...  414.490405
..                                             ...  ...         ...
272  Alzheimer's dementia, early onset, depression  ...  336.016348
273                                   amnestic MCI  ...  341.371124
274                   multiple domain amnestic MCI  ...  454.385693
275                mutiple domain non-amnestic MCI  ...  487.814184
276               Alzheimer's dementia, late onset  ...  353.353720

    global CSFV  MR_3DT1_TFE  MR_3DGRASE_MWI  MR_3DGRASE_REF MREPT_TSE  \
0    427.441118            O               O               O         O
1    315.153808            O               O               O         O
2    308.493634            O               O               O         O
3    337.671219            O               O               O         O
4    382.888115            O               O               O         O
..          ...          ...             ...             ...       ...
272  460.074360            O               O               O         O
273  402.802737            O               O               O         O
274  512.686386            O               O               O         O
275  468.901713            O               O               O         O
276  485.691918            O               O               O         O

       NODDI MREPT_3DbFFE                                      final ddx  \
0    NODDI32            X                           multiple domain aMCI
1    NODDI32            X                                   amnestic MCI
2    NODDI32            X            mild NCD(amnestic type), depression
3    NODDI32            X                   subjective cognitive decline
4    NODDI32            X                                   amnestic MCI
..       ...          ...                                            ...
272  NODDI32            X  Alzheimer's dementia, early onset, depression
273  NODDI32            X                                   amnestic MCI
274  NODDI32            X                   multiple domain amnestic MCI
275  NODDI32            X                mutiple domain non-amnestic MCI
276  NODDI32            X               Alzheimer's dementia, late onset

               논문사용
0           mdMCI03
1    HFC,LFC,MWI 사용
2               HFC
3               HFC
4    HFC,LFC,MWI 사용
..              ...
272       HFC,LFC사용
273             NaN
274             NaN
275             NaN
276       HFC,LFC사용

[277 rows x 32 columns]
   건대분석정보  인원  미수코드     AD_MWI_Code       논문사용       PID  Age Sex  \
0     Yes   1  8641        MWI_CN01  HFC,LFC사용    145616   70   F
1      No   1  8641  MWI_CN02(ver2)        NaN   2123108   74   M
2      No   2  8641  MWI_CN03(ver2)        NaN     78594   67   F
3     Yes   2  8641        MWI_CN04     HFC 사용   2716077   62   F
4     Yes   3  8641        MWI_CN05  HFC,LFC사용    469852   72   M
..    ...  ..   ...             ...        ...       ...  ...  ..
79     No   6  8641  MWI_CN80(ver2)        NaN  10474812   78   F
80     No   7  8641  MWI_CN81(ver2)        NaN  10482577   66   M
81     No   8  8641  MWI_CN82(ver2)        NaN  10412747   74   M
82     No   9  8641  MWI_CN83(ver2)        NaN  10474783   74   F
83     No  10  8641  MWI_CN84(ver2)        NaN  10474798   74   F

   Education (Year)    Screen fail/Drop 이유  ... MREPT_3DbFFE  SWI T2_OBL_COR  \
0                16             Control 모집  ...            x    O          O
1               NaN  Control 모집(SNSB, MRI)  ...          NaN  NaN        NaN
2               NaN  Control 모집(SNSB, MRI)  ...          NaN  NaN        NaN
3                12             Control 모집  ...            x    O          O
4                16             Control 모집  ...            x    O          O
..              ...                    ...  ...          ...  ...        ...
79              NaN  Control 모집(SNSB, MRI)  ...          NaN  NaN        NaN
80              NaN  Control 모집(SNSB, MRI)  ...          NaN  NaN        NaN
81              NaN  Control 모집(SNSB, MRI)  ...          NaN  NaN        NaN
82              NaN  Control 모집(SNSB, MRI)  ...          NaN  NaN        NaN
83              NaN  Control 모집(SNSB, MRI)  ...          NaN  NaN        NaN

    FLAIR  MWF  VOLUME  HFC LFC(EC,IC) SMT(ED,ID) IVF,EIC
0       O    O       O    O          O          O       O
1     NaN  NaN     NaN  NaN        NaN        NaN     NaN
2     NaN  NaN     NaN  NaN        NaN        NaN     NaN
3       O    O       O    O          O          O       O
4       O    O       O    O          O          O       O
..    ...  ...     ...  ...        ...        ...     ...
79    NaN  NaN     NaN  NaN        NaN        NaN     NaN
80    NaN  NaN     NaN  NaN        NaN        NaN     NaN
81    NaN  NaN     NaN  NaN        NaN        NaN     NaN
82    NaN  NaN     NaN  NaN        NaN        NaN     NaN
83    NaN  NaN     NaN  NaN        NaN        NaN     NaN

[84 rows x 41 columns]

In [8]:
b2AD

,건대분석정보,인원,Origin Code,Code,PID,Age,Sex,Education(Year),Clinical Info(진료교수),최종진단 DDX,...,global WMV,global CSFV,MR_3DT1_TFE,MR_3DGRASE_MWI,MR_3DGRASE_REF,MREPT_TSE,NODDI,MREPT_3DbFFE,final ddx,논문사용
0,Yes,NaN,MREPT2019AD01,AD2019_BrMRA01,3735478,70.0,F,14,HTN mdMCI,multiple domain aMCI,...,431.903364,427.441118,O,O,O,O,NODDI32,X,multiple domain aMCI,mdMCI03
1,Yes,NaN,MREPT2019AD02,AD2019_BrMRA02,4381137,68.0,F,13,"HTN, 고지혈증, ICAaneurysm aMCI",amnestic MCI,...,485.314945,315.153808,O,O,O,O,NODDI32,X,amnestic MCI,"HFC,LFC,MWI 사용"
2,Yes,탈락,MREPT2019AD03,AD2019_BrMRA03,4452316,67.0,F,9,"(조아랑) mild NCD(amnestic type), depression","mild NCD(amnestic type), depression",...,404.586605,308.493634,O,O,O,O,NODDI32,X,"mild NCD(amnestic type), depression",HFC
3,Yes,NaN,MREPT2019AD04,AD2019_BrMRA04,4681566,66.0,M,12,subjective cognitive decline,subjective cognitive decline,...,524.819073,337.671219,O,O,O,O,NODDI32,X,subjective cognitive decline,HFC
4,Yes,NaN,MREPT2019AD05,AD2019_BrMRA05,7205823,77.0,F,6,mild SVD aMCI,amnestic MCI,...,414.490405,382.888115,O,O,O,O,NODDI32,X,amnestic MCI,"HFC,LFC,MWI 사용"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
272,Yes,NaN,MREPT2020AD24_YYS_NODDI32,MREPT2020AD24,8700631,60.0,F,6,"조아랑 Alzheimer's dementia, early onset, depression","Alzheimer's dementia, early onset, depression",...,336.016348,460.074360,O,O,O,O,NODDI32,X,"Alzheimer's dementia, early onset, depression","HFC,LFC사용"
273,Yes,NaN,MREPT2020AD25_YSJ_NODDI32,MREPT2020AD25,8655418,76.0,F,9,amnestic MCI,amnestic MCI,...,341.371124,402.802737,O,O,O,O,NODDI32,X,amnestic MCI,NaN
274,Yes,NaN,MREPT2020AD26_HMH_NODDI32,MREPT2020AD26,8655425,77.0,M,6,"DM, HTN 고지혈증, 이학영 multiple domain aMCI",multiple domain amnestic MCI,...,454.385693,512.686386,O,O,O,O,NODDI32,X,multiple domain amnestic MCI,NaN
275,Yes,탈락-venous anomaly,MREPT2020AD27_YJJ_NODDI32,MREPT2020AD27,577752,71.0,F,NaN,"depressive, 이학영 multiple domain non-amnestic MCI",mutiple domain non-amnestic MCI,...,487.814184,468.901713,O,O,O,O,NODDI32,X,mutiple domain non-amnestic MCI,NaN
276,Yes,NaN,MREPT2020AD28_YYL_NODDI32,MREPT2020AD28,5533209,80.0,F,0,"조아랑 Alzheimer's dementia, late onset","Alzheimer's dementia, late onset",...,353.353720,485.691918,O,O,O,O,NODDI32,X,"Alzheimer's dementia, late onset","HFC,LFC사용"

In [9]:
b2CN

,건대분석정보,인원,미수코드,AD_MWI_Code,논문사용,PID,Age,Sex,Education (Year),Screen fail/Drop 이유,...,MREPT_3DbFFE,SWI,T2_OBL_COR,FLAIR,MWF,VOLUME,HFC,"LFC(EC,IC)","SMT(ED,ID)","IVF,EIC"
0,Yes,1,8641,MWI_CN01,"HFC,LFC사용",145616,70,F,16,Control 모집,...,x,O,O,O,O,O,O,O,O,O
1,No,1,8641,MWI_CN02(ver2),NaN,2123108,74,M,NaN,"Control 모집(SNSB, MRI)",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,No,2,8641,MWI_CN03(ver2),NaN,78594,67,F,NaN,"Control 모집(SNSB, MRI)",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Yes,2,8641,MWI_CN04,HFC 사용,2716077,62,F,12,Control 모집,...,x,O,O,O,O,O,O,O,O,O
4,Yes,3,8641,MWI_CN05,"HFC,LFC사용",469852,72,M,16,Control 모집,...,x,O,O,O,O,O,O,O,O,O
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
79,No,6,8641,MWI_CN80(ver2),NaN,10474812,78,F,NaN,"Control 모집(SNSB, MRI)",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
80,No,7,8641,MWI_CN81(ver2),NaN,10482577,66,M,NaN,"Control 모집(SNSB, MRI)",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
81,No,8,8641,MWI_CN82(ver2),NaN,10412747,74,M,NaN,"Control 모집(SNSB, MRI)",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
82,No,9,8641,MWI_CN83(ver2),NaN,10474783,74,F,NaN,"Control 모집(SNSB, MRI)",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
83,No,10,8641,MWI_CN84(ver2),NaN,10474798,74,F,NaN,"Control 모집(SNSB, MRI)",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [10]:
df = b1AD
for column in df.columns:
    print(f"Col name: {column}")
    print(f"Data type: {df[column].dtype}")
    print(f"Unique values: {len(df[column].unique())}")
    print(df[column].unique())
    print('-'*40)

Col name: index
Data type: int64
Unique values: 211
[  1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17  18
  19  20  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35  36
  37  38  39  40  41  42  43  44  45  46  47  48  49  50  51  52  53  54
  55  56  57  58  59  60  61  62  63  64  65  66  67  68  69  70  71  72
  73  74  75  76  77  78  79  80  81  82  83  84  85  86  87  88  89  90
  91  92  93  94  95  96  97  98  99 100 101 102 103 104 105 106 107 108
 109 110 111 112 113 114 115 116 117 118 119 120 121 122 123 124 125 126
 127 128 129 130 131 132 133 134 135 136 137 138 139 140 141 142 143 144
 145 146 147 148 149 150 151 152 153 154 155 156 157 158 159 160 161 162
 163 164 165 166 167 168 169 170 171 172 173 174 175 176 177 178 179 180
 181 182 183 184 185 186 187 188 189 190 191 192 193 194 195 196 197 198
 199 200 201 202 203 204 205 206 207 208 209 210 211]
----------------------------------------
Col name: PDI
Data type: object
Unique values: 211
['MREPT2019AD01_KMO_NODDI32' 'MREPT2019AD02_JSJ_NODDI32'
 'MREPT2019AD03_OHS_NODDI32' 'MREPT2019AD04_CSY_NODDI32'
 'MREPT2019AD05_KJI_NODDI32' 'MREPT2019AD06_CKJ_NODDI32'
 'MREPT2019AD07_LJH_NODDI32' 'MREPT2019AD09_LKS_NODDI32'
 'MREPT2019AD10_KJL_NODDI32' 'MREPT2019AD11_CKS_NODDI32'
 'MREPT2019AD13_KHS_NODDI32' 'MREPT2019AD14_CMJ_NODDI32'
 'ADEPT01_YSJ_NODDI24' 'ADEPT02_LKY_NODDI24' 'ADEPT03_YKJ_NODDI24'
 'ADEPT04_JWS_NODDI24' 'ADEPT05_CBK_NODDI24' 'ADEPT06_PHJ_NODDI24'
 'ADEPT07_JG_NODDI24' 'ADEPT08_KMJ_NODDI24' 'ADEPT09_JCJ_NODDI24'
 'ADEPT10_YPL_NODDI24' 'ADEPT16_LJS_NODDI24' 'ADEPT18_PST_NODDI24'
 'ADEPT21_CJM_NODDI24' 'ADEPT22_KBS_NODDI24' 'ADEPT23_PYS_NODDI24'
 'ADEPT24_KJH_NODDI24' 'ADEPT25_JKR_NODDI24' 'ADEPT26_KYJ_NODDI24'
 'ADEPT27_KKS_NODDI24' 'ADEPT28_MSH_NODDI24' 'ADEPT29_LBS_NODDI24'
 'ADEPT30_WJS_NODDI24' 'ADEPT31_PTL_NODDI24' 'ADEPT32_KSW_NODDI24'
 'ADEPT33_YCY_NODDI24' 'ADEPT34_PDY_NODDI24' 'ADEPT36_JJS_NODDI24'
 'ADEPT37_KTY_NODDI24' 'ADEPT38_KWW_NODDI24' 'ADEPT39_KKS_NODDI24'
 'ADEPT40_JOS_NODDI24' 'ADEPT41_YBO_NODDI24' 'ADEPT42_PSJ_NODDI24'
 'ADEPT43_SSY_NODDI24' 'ADEPT44_WDS_NODDI24' 'ADEPT45_KKJ_NODDI24'
 'ADEPT46_LJB_NODDI24' 'ADEPT47_SJH_NODDI24' 'ADEPT48_CJK_NODDI24'
 'ADEPT49_LKJ_NODDI24' 'ADEPT50_LJK_NODDI24' 'ADEPT51_HBH_NODDI24'
 'ADEPT52_YCW_NODDI24' 'ADEPT53_PDL_NODDI24' 'ADEPT54_HCS_NODDI24'
 'ADEPT55_HJS_NODDI24' 'ADEPT56_CKJ_NODDI24' 'ADEPT57_LHS_NODDI24'
 'ADEPT58_PJR_NODDI24' 'ADEPT59_KJS_NODDI24' 'ADEPT60_PNS_NODDI24'
 'ADEPT61_YJS_NODDI24' 'ADEPT62_HSO_NODDI24' 'ADEPT63_JMS_NODDI24'
 'ADEPT64_PMS_NODDI24' 'ADEPT65_CMR_NODDI24' 'ADEPT66_LDS_NODDI24'
 'ADEPT67_JKJ_NODDI24' 'HFC2020AD01_KYM_NODDI32' 'HFC2020AD02_KS_NODDI32'
 'MREPT2020AD01_CGS_NODDI32' 'MREPT2020AD02_HMJ_NODDI32'
 'MREPT2020AD03_KJH_NODDI32' 'MREPT2020AD04_NGR_NODDI32'
 'MREPT2020AD05_PJE_NODDI32' 'MREPT2020AD06_JHK_NODDI32'
 'MREPT2020AD07_KYG_NODDI32' 'MREPT2020AD08_CYS_NODDI32'
 'MREPT2020AD09_PJJ_NODDI32' 'MREPT2020AD10_CYJ_NODDI32'
 'MREPT2020AD11_KHJ_NODDI32' 'MREPT2020AD12_KOB_NODDI32'
 'MREPT2020AD13_SBS_NODDI32' 'MREPT2020AD14_CIL_NODDI32'
 'MREPT2020AD15_LHS_NODDI32' 'MREPT2020AD16_CKL_NODDI32'
 'MREPT2020AD17_LSH_NODDI32' 'MREPT2020AD18_YHS_NODDI32'
 'MREPT2020AD19_PKS_NODDI32' 'MREPT2020AD20_LSK_NODDI32'
 'MREPT2020AD21_CBS_NODDI32' 'MREPT2020AD22_KYH_NODDI32'
 'MREPT2020AD23_LSH_NODDI32' 'MREPT2020AD24_YYS_NODDI32'
 'MREPT2020AD25_YSJ_NODDI32' 'MREPT2020AD26_HMH_NODDI32'
 'MREPT2020AD27_YJJ_NODDI32' 'MREPT2020AD28_YYL_NODDI32'
 'HFC2021AD01_YMB_NODDI32' 'HFC2021AD02_SHS_NODDI32'
 'EPT2022AD01_KDKM_NODDI32' 'EPT2022AD02_SKM_NODDI32'
 'EPT2022AD03_KKS_NODDI32' 'EPT2022AD04_KSS_NODDI32'
 'EPT2022AD05_KIJD_NODDI32' 'EPT2022AD063_BPB_NODDI32'
 'EPT2022AD064_LYS_NODDI32' 'EPT2022AD065_CGS_NODDI32'
 'EPT2022AD066_AIS_NODDI32' 'EPT2022AD067_JSO_NODDI32'
 'EPT2022AD068_NSE_NODDI32' 'EPT2022AD069_LBD_NODDI32'
 'EPT2022AD06_JOJ_NODDI32' 'EPT2022AD070_KSH_NODDI32'
 'EPT2022AD071_KSJ_NODDI32' 'EPT2022AD072_SDY_NODDI32'
 'EPT2022AD073_KHR_NODDI32' 'EPT2022AD074_LGR_NODDI32'
 'EPT2022AD07_YMY_NODDI32' 'EPT2022AD08_JIL_NODDI32'
 'EPT2022AD09_JYS_NODDI32' 'EPT2022AD10_HSY_NODDI32'
 'EPT2022AD11_PSI_NODDI32' 'EPT2022AD12_SYS_NODDI32'
 'EPT2022AD13_SYJ_NODDI32' 'EPT2022AD14_PYS_NODDI32'
 'EPT2022AD15_YSH_NODDI32' 'EPT2022AD16_CKJ_NODDI32'
 'EPT2022AD17_KHS_NODDI32' 'EPT2022AD18_PKW_NODDI32'
 'EPT2022AD19_YJH_NODDI32' 'EPT2022AD20_KYS_NODDI32'
 'EPT2022AD21_KOJ_NODDI32' 'EPT2022AD22_NSC_NODDI32'
 'EPT2022AD23_SKSH_NODDI32' 'EPT2022AD24_KJS_NODDI32'
 'EPT2022AD25_KMS_NODDI32' 'EPT2022AD26_PSO_NODDI32'
 'EPT2022AD27_KDS_NODDI32' 'EPT2022AD28_GMS_NODDI32v'
 'EPT2022AD29_LKH_NODDI32' 'EPT2022AD30_NNO_NODDI32'
 'EPT2022AD31_HSB_NODDI32' 'EPT2022AD32_CDR_NODDI32'
 'EPT2022AD33_KTY_NODDI32' 'EPT2022AD34_KMB_NODDI32'
 'EPT2022AD35_HHS_NODDI32' 'EPT2022AD36_JYS_NODDI32'
 'EPT2022AD37_CEH_NODDI32' 'EPT2022AD38_YYS_NODDI32'
 'EPT2022AD39_LJS_NODDI32' 'EPT2022AD40_RKJ_NODDI32'
 'EPT2022AD41_SIJ_NODDI32' 'EPT2022AD42_HPB_NODDI32'
 'EPT2022AD43_CDH_NODDI32' 'EPT2022AD44_LKJ_NODDI32'
 'EPT2022AD45_CHS_NODDI32' 'EPT2022AD46_KOS_NODDI32'
 'EPT2022AD47_KPK_NODDI32' 'EPT2022AD48_HJJ_NODDI32'
 'EPT2022AD49_PCS_NODDI32' 'EPT2022AD50_YYH_NODDI32'
 'EPT2022AD51_KBS_NODDI32' 'EPT2022AD52_POA_NODDI32'
 'EPT2022AD53_KJD_NODDI32' 'EPT2022AD54_GJJ_NODDI32'
 'EPT2022AD55_SSB_NODDI32' 'EPT2022AD56_SKS_NODDI32'
 'EPT2022AD57_KYS_NODDI32' 'EPT2022AD58_PYR_NODDI32'
 'EPT2022AD59_SNO_NODDI32' 'EPT2022AD60_KYD_NODDI32'
 'EPT2022AD61_KYJ_NODDI32' 'EPT2022AD62_LHJ_NODDI32'
 'EPT2023AD01_KMH_NODDI32' 'EPT2023AD02_HUI_NODDI32'
 'EPT2023AD03_MSJ_NODDI32' 'EPT2023AD04_KJU_NODDI32'
 'EPT2023AD05_JIS_NODDI32' 'EPT2023AD06_LSJ_NODDI32'
 'EPT2023AD07_WGJ_NODDI32' 'EPT2023AD08_KMS_NODDI32'
 'EPT2023AD09_LSU_NODDI32' 'EPT2023AD10_JBY_NODDI32'
 'EPT2023AD11_HSY_NODDI32' 'EPT2023AD12_YJS_NODDI32'
 'EPT2023AD13_WOB_NODDI32' 'EPT2023AD14_LMS_NODDI32'
 'EPT2023AD15_LSJ_NODDI32' 'EPT2023AD16_JHG_NODDI32'
 'EPT2023AD17_LHG_NODDI32' 'EPT2023AD18_LMS_NODDI32'
 'EPT2023AD19_KTG_NODDI32' 'EPT2023AD20_CGJ_NODDI32'
 'EPT2023AD21_PDB_NODDI32' 'EPT2023AD22_KID_NODDI32'
 'EPT2024AD01_KJI_NODDI32' 'EPT2024AD02_HUY_NODDI32'
 'EPT2024AD03_NGS_NODDI32' 'EPT2024AD04_LDS_NODDI32'
 'EPT2024AD05_KEJ_NODDI32' 'EPT2024AD06_PYG_NODDI32'
 'EPT2024AD07_JGJ_NODDI32' 'EPT2024AD08_LMS_NODDI32'
 'EPT2024AD09_CSO_NODDI32' 'EPT2024AD10_KCJ_NODDI32'
 'EPT2024AD11_KHJ_NODDI32' 'EPT2024AD12_LDS_NODDI32'
 'EPT2024AD13_LTO_NODDI32']
----------------------------------------
Col name: PID
Data type: object
Unique values: 210
['03735478' '04381137' '04452316 ' '04681566 ' '07205823 ' '07771796 '
 '08079583 ' '01349735' '04569609' '05065323' '05118195' '06762937'
 '06349063' '00556441' '03028284' '05430317' '07814522' '00320473'
 '07400255' '07253938' '00921333' '03408262' '03260817' '06273815'
 '07548022' '07721083' '07824705' '02423072' '00872381' '03138315'
 '04697696' '04615571' '00920713' '04495624' '06307525' '07862995'
 '07823239' '07858926' '07436362' '04237986' '00005786' '05482896'
 '00680085' '04062186' '07922086' '03163821' '00755865' '03024048'
 '07912763' '07397337' '02394924' '01967627 ' '02657475 ' '00322738 '
 '05433458 ' '03474477 ' '02459562 ' '07774945 ' '04100729 ' '06033539 '
 '03942467 ' '07390313 ' '02537456 ' '08039551 ' '08086932 ' '00628187 '
 '02731906 ' '08072285' '05465081 ' '05563773 ' '03236196' '08808855'
 '01509705 ' '04738348 ' '04717899 ' '01514027 ' '02671227 ' '00129148 '
 '08324575 ' '02933875 ' '05603012' '08276845' '08365068' '08542934'
 '08571878' '07843678' '03076738' '00749365' '04662699' '04058635' 'nan'
 '08344895' '00069764' '00908575' '08700631' '08655418' '08655425'
 '00577752' '05533209' '00049831 ' '00657015 ' '00310282' '00454439'
 '00461257' '00513795' '00612238' '00840132' '01083182' '01563188'
 '01749412' '01881945' '02636118' '03281139' '00710431' '03677627'
 '04920903' '05244936' '07351639' '09845319' '01246647' '01386714'
 '01468626' '01868298' '01932252' '02603988' '02642792' '02717687'
 '02986989' '03157194' '03417996' '03532605' '03600925' '03633402'
 '03929844' '04039744' '04600082' '05209834' '05216745' '05406746'
 '06683962' '06916248' '07641504' '07740365' '07816717' '07819979'
 '07835052' '08306655' '08407468' '08584615' '08625084' '09124745'
 '09295332' '09463703' '09468039' '09481205' '09481613' '09491375'
 '09520331' '09522162' '09572617' '09589097' '09589671' '09634219'
 '09648051' '09648799' '09712897' '09734851' '00477555' '02065045'
 '04067051' '04301889' '04797497' '08481752' '09682931' '09822672'
 '01408745' '05282874' '01436161' '02345264' '04345988' '06318811'
 '09076435' '08511252' '08787368' '10228094' '02669298' '07953325'
 '00235415' '00672299' '00672300' '00915984' '01207865' '01835793'
 '03133994' '04100729' '05912132' '06763469' '01727943' '01818063'
 '01934947' '00463081' '02750266' '03691537' '04331042' '05035723'
 '05212646' '07295104' '07760856' '10130501' '10466131']
----------------------------------------
Col name: Year
Data type: int64
Unique values: 6
[2019 2020 2021 2022 2023 2024]
----------------------------------------
Col name: LH-ALL_Dxx_proj
Data type: float64
Unique values: 211
[0.644891 0.711342 0.817484 0.636522 0.884875 0.676956 0.93257  0.614387
 0.71064  0.961293 0.889609 0.514302 0.592921 0.677527 0.713658 0.636028
 0.571027 0.717123 0.653122 0.691966 0.774121 0.75679  0.662992 1.114345
 0.689547 0.590511 0.803339 0.639105 0.907575 0.877886 0.75639  0.773788
 0.663161 0.648225 0.954817 0.865298 0.640273 0.715607 0.735767 0.74697
 0.748909 0.895995 0.720429 0.777927 1.015249 0.781611 0.843801 0.663736
 0.854032 0.842673 0.802067 0.611383 0.84441  0.819996 0.809939 0.937027
 0.745723 0.641687 0.631024 0.781388 0.741792 0.730203 0.744956 0.692357
 0.856909 0.863502 0.745848 0.621174 0.57812  1.01296  1.04424  0.787674
 0.624646 1.006665 0.704174 0.687615 0.830949 0.804617 0.669022 0.558741
 0.567549 0.789869 0.712472 0.558187 0.687167 0.757712 0.634075 0.850102
 0.737843 0.774412 0.772595 0.608213 0.835621 0.738897 0.617877 0.744526
 0.666114 0.529166 0.71907  0.99115  0.639082 0.632195 0.687428 0.884833
 0.688375 0.720827 0.687521 0.725325 0.702311 0.687835 1.019929 0.661129
 0.682913 0.714135 0.648407 0.691957 0.848691 0.593003 0.660658 0.773617
 0.671343 0.704028 0.748985 0.721774 0.842524 0.899839 0.647298 0.525954
 1.290105 0.621754 0.581737 0.628854 0.800095 0.685723 0.787983 0.716869
 0.735545 0.713494 0.779564 0.706848 0.672512 0.809665 0.961617 0.70738
 0.645374 0.942717 0.873445 0.713498 0.570495 0.651328 0.662054 0.75147
 0.738034 0.776002 0.716783 0.904237 0.627554 0.709479 0.725724 0.605083
 0.676401 0.767485 0.789217 0.688869 0.76261  0.832842 0.593976 0.667726
 0.585434 0.859103 0.684419 0.752241 0.664335 0.706332 0.690737 0.603933
 0.743637 0.649097 0.787064 0.726438 0.504589 0.823662 0.666029 0.509156
 0.726724 0.879091 0.756672 0.840838 0.633278 0.600937 0.577736 0.903688
 0.875751 0.927418 0.704612 0.667106 0.708895 0.712821 0.560355 0.737402
 0.762363 0.609003 0.849374 0.718001 0.554956 0.870257 0.77779  0.703165
 0.695299 0.758654 0.672885]
----------------------------------------
Col name: LH-ALL_Dyy_proj
Data type: float64
Unique values: 211
[0.617538 0.473727 0.701432 0.566616 0.763448 0.526778 0.760346 0.618671
 0.595827 0.788093 0.946564 0.760812 0.721707 0.608793 0.587548 0.501966
 0.69419  0.654582 0.593881 0.57356  0.599718 0.6805   0.485697 1.13647
 0.690658 0.565186 0.898682 0.57812  0.922679 0.814766 0.66776  0.669394
 0.674745 0.703882 0.996151 0.97801  0.504455 0.611504 0.697976 0.701052
 0.821993 0.87645  0.563148 0.688483 0.767308 0.756681 0.813423 0.621885
 0.797136 0.871819 0.752622 0.627337 0.805356 0.615363 0.739668 0.862638
 0.68161  0.578162 0.581794 0.58581  0.64637  0.838856 0.699794 0.585167
 0.888376 0.656735 0.638285 0.5888   0.607669 1.020676 1.09976  0.617017
 0.630584 1.030653 0.654193 0.664407 0.728287 0.73864  0.743052 0.604754
 0.615347 0.753    0.757548 0.481649 0.82203  0.727023 0.504538 0.671135
 0.573432 0.625499 0.66416  0.538205 0.671285 0.769913 0.747627 0.698216
 0.466302 0.485423 0.633371 1.075484 0.570807 0.790451 0.61544  1.023749
 0.571691 0.791427 0.567993 0.690994 0.585001 0.658264 0.993018 0.728565
 0.627002 0.681928 0.544407 0.824765 0.687105 0.49497  0.504997 1.021624
 0.669964 0.54911  0.859231 0.619341 0.789933 0.697691 0.517673 0.562131
 1.398008 0.593717 0.6927   0.606006 0.669203 0.479119 0.672785 0.637086
 0.722219 0.583667 0.591612 0.656015 0.640494 0.810742 0.97116  0.74557
 0.704022 0.843918 0.759741 0.479734 0.658749 0.547181 0.652495 0.788713
 0.663406 0.681788 0.601077 0.718277 0.56842  0.452861 0.651998 0.663665
 0.67313  0.84888  0.863602 0.620125 0.653173 0.739725 0.603444 0.593122
 0.617385 0.880303 0.689697 0.809204 0.648147 0.643079 0.656903 0.5378
 0.712603 0.545406 0.700333 0.620235 0.638047 0.681381 0.674297 0.599337
 0.886689 0.847366 0.801607 0.849529 0.505991 0.617344 0.634232 0.988417
 0.801455 1.001147 0.680323 0.765529 0.816064 0.692009 0.449772 0.674642
 0.611719 0.617758 0.895185 0.722943 0.519521 0.795042 0.751147 0.449837
 0.652078 0.879287 0.600487]
----------------------------------------
Col name: LH-ALL_Dzz_proj
Data type: float64
Unique values: 211
[1.173563 1.183256 1.253393 1.020413 1.32497  1.209016 1.05923  1.152475
 1.16552  1.231277 1.392888 1.054812 0.953535 1.174983 1.225626 1.161122
 0.940595 1.285027 0.933188 1.136913 1.105498 1.139714 1.019973 1.311477
 1.168954 0.991124 1.152376 1.326906 1.544416 1.287628 1.143752 1.072732
 1.083806 1.127048 1.338331 1.111304 0.951965 1.038915 1.253557 1.099733
 1.148538 1.21212  1.020135 1.192634 1.330943 1.285459 1.400683 1.247357
 1.276026 1.184347 0.993692 1.102121 1.229697 1.136695 1.241362 1.351159
 1.205742 1.169518 1.202354 1.188711 1.279406 1.209409 1.304296 1.080796
 1.189395 1.165041 1.188179 1.050407 0.904655 1.411023 1.178006 1.275187
 1.159289 1.433256 1.357517 0.945684 1.208114 1.201483 1.18772  1.166113
 1.129179 1.275562 1.141273 0.95778  1.132069 1.272343 0.954832 1.334508
 1.21977  1.115456 0.998493 1.186532 1.445683 1.244719 0.89601  1.384122
 1.103041 0.964057 1.091623 1.367142 1.258236 0.959016 1.088453 1.23767
 1.306685 1.263251 1.001067 1.190966 1.093793 1.200729 1.482874 1.130937
 1.170377 1.167826 1.175009 0.965649 1.266008 1.051231 1.22675  1.241025
 1.161513 1.255289 1.191667 1.139735 1.019088 1.092184 1.203802 1.190894
 1.337141 1.120976 1.234771 0.995007 1.284719 1.101015 1.183734 1.111928
 1.295058 1.070543 1.047948 0.992941 0.888912 1.210563 1.175082 1.081639
 1.388936 1.336587 1.412562 0.990042 1.206562 0.997239 1.211629 1.110113
 1.280886 1.246253 1.086461 1.38513  0.99959  1.214573 1.200198 1.361676
 1.101452 1.187652 1.121345 1.094482 1.161554 1.360636 1.12618  1.167856
 1.081996 1.386154 1.230143 1.207672 1.187767 1.117737 1.120207 1.124211
 1.073078 1.318155 1.199532 1.253553 0.992412 1.180936 1.126598 1.015179
 1.255365 1.253365 1.260176 1.141428 0.993647 0.985532 1.078126 1.079517
 1.347431 1.151275 1.199374 1.200726 1.318295 1.141931 1.14957  1.023465
 1.194518 1.179504 1.12248  0.908882 1.061184 1.373576 1.083035 1.133783
 1.204808 1.034725 1.233325]
----------------------------------------
Col name: LH-ALL_Dxx_assoc
Data type: float64
Unique values: 211
[0.838976 0.801073 0.921833 0.824179 1.04385  0.817479 1.132849 0.791892
 0.855245 1.156825 1.040997 0.903745 0.787849 0.775191 0.906233 0.799743
 0.632146 0.951714 0.782767 0.858335 0.867577 0.919467 0.719685 0.832461
 0.753924 0.846036 1.255407 0.888593 1.281477 0.885574 0.830649 1.016928
 0.904594 0.801505 1.026453 1.010401 0.717183 0.880957 0.885155 0.81809
 0.990955 0.963625 0.790004 0.928297 1.186851 0.906332 1.059758 0.942335
 0.917875 0.983731 0.979747 0.9333   0.940769 0.99725  0.947076 1.165415
 1.006692 0.806274 0.898562 0.850873 0.894469 0.918098 0.872957 0.81423
 1.13413  0.985183 0.948638 0.785135 0.732054 1.142308 0.995355 0.887617
 0.862724 1.014844 0.856473 0.766374 0.961554 0.997862 0.869926 0.796144
 0.806529 0.852835 0.934288 0.680757 0.885165 0.711826 0.778661 1.140621
 0.856247 1.185462 0.776901 0.689059 1.024967 0.875901 0.766804 1.139358
 0.82401  0.519688 0.750454 1.231468 0.769729 0.644696 0.838373 0.976871
 0.87463  0.913582 0.855315 0.871609 0.711879 0.919309 1.191792 0.823551
 1.01671  0.917573 0.761119 0.813292 1.033745 0.851669 0.65651  0.822064
 0.823256 0.826074 0.867975 0.869587 0.980562 0.964868 0.925968 0.915221
 0.960323 0.930059 0.871766 0.75493  0.914381 0.704292 0.772743 0.87245
 0.989024 0.834654 0.974291 0.839412 0.780336 0.910227 0.939582 0.889503
 0.745681 1.260075 0.975437 0.753426 0.907602 0.673688 0.957962 0.911906
 0.910703 0.918422 0.810802 1.298066 0.72403  0.780219 0.767325 0.689703
 0.811871 0.949841 0.709945 0.792752 0.824909 1.0804   0.84812  0.857463
 0.808918 0.965197 0.854568 0.93758  0.845652 0.888594 0.754139 0.733467
 0.786659 0.818217 1.056564 0.806187 0.925783 0.747263 0.822836 0.810267
 0.829209 0.964632 0.987495 0.869121 0.798203 1.149777 0.92123  1.053755
 0.964594 1.00318  0.742082 0.957538 1.022304 0.890171 0.653193 0.81435
 0.865598 0.941755 0.972638 0.859744 0.730744 1.017396 0.980567 0.799426
 0.96477  1.054118 0.774175]
----------------------------------------
Col name: LH-ALL_Dyy_assoc
Data type: float64
Unique values: 211
[1.092285 1.124653 1.174945 0.994313 1.245618 1.012696 1.070788 1.111372
 1.062072 1.231913 1.3492   1.155211 1.019401 1.257166 1.081944 1.030088
 1.064741 1.128002 1.007868 1.102447 0.986188 0.986806 1.036263 0.921122
 1.175664 0.976966 1.345043 1.033081 1.446659 1.25399  1.071612 1.047515
 1.184812 1.029303 1.430111 1.187303 1.045966 1.051864 1.115176 1.110409
 1.200892 1.156169 1.075739 1.187087 1.283007 1.18606  1.241912 1.029773
 1.320642 1.217097 1.178886 0.99395  1.036446 0.952094 1.262267 1.222713
 1.055096 1.075779 1.134696 1.194312 1.049631 1.185011 1.154161 1.118488
 1.259774 1.172744 1.064176 1.139161 1.220206 1.433776 1.273453 1.242271
 1.076538 1.299039 1.113002 0.98321  1.125534 1.274288 1.202416 1.062793
 1.047234 1.231025 1.140748 0.941293 1.18384  1.266497 0.856075 1.265204
 1.118918 1.227039 1.205574 1.097773 1.109423 1.101445 1.055847 1.166928
 0.895553 0.684828 1.061202 1.493726 1.145157 1.185012 1.15284  1.144774
 1.211957 1.196111 0.99492  1.067436 1.187508 1.148149 1.351247 1.275065
 1.037244 1.0296   1.051568 1.056257 1.058758 0.78495  1.101994 1.090073
 1.076299 1.189661 1.340311 1.056145 1.142484 1.169068 1.125231 1.09132
 1.322028 1.092903 0.895165 1.043278 1.113467 1.071523 1.227777 1.136501
 1.082821 1.134355 1.043867 1.08979  0.936096 1.121149 1.205323 1.071692
 1.178663 1.144298 1.216299 1.07405  1.034255 1.057587 1.261073 1.281855
 1.230181 1.220402 1.110347 1.045444 0.998872 0.948145 1.252237 1.056053
 1.298126 1.227467 1.219886 0.999128 1.132937 1.270685 1.316283 0.970917
 1.096929 1.154592 1.207507 1.231816 1.051286 1.086016 1.045555 1.01289
 1.067521 1.137089 1.209361 1.100793 1.147235 1.185787 1.058059 0.976246
 1.249789 1.210266 1.191637 1.047765 1.077811 1.032455 1.166439 1.244024
 1.115723 1.146188 1.2148   1.175152 0.938854 1.135228 1.176845 1.17006
 1.031168 1.026952 1.167011 1.166467 0.902089 1.279346 1.264496 1.147285
 1.229719 0.944798 1.059713]
----------------------------------------
Col name: LH-ALL_Dzz_assoc
Data type: float64
Unique values: 211
[0.606418 0.628264 0.667998 0.478768 0.718111 0.557788 0.605129 0.535729
 0.612792 0.626233 0.877985 0.631289 0.486244 0.551411 0.695951 0.477891
 0.44015  0.73054  0.582893 0.589392 0.523164 0.568369 0.493767 0.618127
 0.556969 0.438695 1.076184 0.802274 1.105614 0.687131 0.62431  0.657951
 0.506352 0.791511 0.801012 0.896075 0.392546 0.58218  0.602692 0.586882
 0.692511 0.689121 0.498519 0.737543 0.997766 0.766176 0.830416 0.840773
 0.735951 0.707564 0.55945  0.575082 0.658792 0.704571 0.830014 0.878679
 0.667571 0.62558  0.578805 0.608919 0.680156 0.691683 0.686668 0.591298
 0.793744 0.610555 0.722859 0.483133 0.422743 0.89413  0.703069 0.64996

In [13]:
df = b2CN
for column in df.columns:
    print(f"Col name: {column}")
    print(f"Data type: {df[column].dtype}")
    print(f"Unique values: {len(df[column].unique())}")
    print(df[column].unique())
    print('-'*40)

Col name: 건대분석정보
Data type: object
Unique values: 2
['Yes' 'No']
----------------------------------------
Col name: 인원
Data type: object
Unique values: 43
[1 2 3 4 5 '6탈락1-1' '7탈락1-2' '8탈락1-3' '9탈락1-4' 10 11 '12탈락1-5' '13탈락1-6'
 '14탈락1-7' 15 16 17 18 19 20 21 22 23 24 25 26 27 28 6 '7탈락2-1' 8 9 12 13
 14 '19탈락2-2' '22탈락2-3' '5탈락3-1' 7 '9탈락3-2' '10탈락3-3' '13탈락3-4' '4탈락-']
----------------------------------------
Col name: 미수코드
Data type: int64
Unique values: 1
[8641]
----------------------------------------
Col name: AD_MWI_Code
Data type: object
Unique values: 84
['MWI_CN01' 'MWI_CN02(ver2)' 'MWI_CN03(ver2)' 'MWI_CN04' 'MWI_CN05'
 'MWI_CN06' 'MWI_CN07' 'MWI_CN08' 'MWI_CN09' 'MWI_CN10' 'MWI_CN11'
 'MWI_CN12' 'MWI_CN13' 'MWI_CN14' 'MWI_CN15' 'MWI_CN16' 'MWI_CN17'
 'MWI_CN18' 'MWI_CN19' 'MWI_CN20' 'MWI_CN21' 'MWI_CN22' 'MWI_CN23'
 'MWI_CN24' 'MWI_CN25' 'MWI_CN26' 'MWI_CN27' 'MWI_CN28' 'MWI_CN29'
 'MWI_CN30' 'MWI_CN31' 'MWI_CN32' 'MWI_CN33' 'MWI_CN34' 'MWI_CN35'
 'MWI_CN36' 'MWI_CN37' 'MWI_CN38' 'MWI_CN39' 'MWI_CN40' 'MWI_CN41'
 'MWI_CN42' 'MWI_CN43' 'MWI_CN44' 'MWI_CN45' 'MWI_CN46' 'MWI_CN47'
 'MWI_CN48' 'MWI_CN49' 'MWI_CN50' 'MWI_CN51' 'MWI_CN52' 'MWI_CN53'
 'MWI_CN54' 'MWI_CN55' 'MWI_CN56(ver1.2)' 'MWI_CN57(ver2)'
 'MWI_CN58(ver2)' 'MWI_CN59(ver2)' 'MWI_CN60(ver2)' 'MWI_CN61(ver2)'
 'MWI_CN62(ver2)' 'MWI_CN63(ver2)' 'MWI_CN64(ver2)' 'MWI_CN65(ver2)'
 'MWI_CN66(ver2)' 'MWI_CN67(ver2)' 'MWI_CN68(ver2)' 'MWI_CN69(ver2)'
 'MWI_CN70(ver2)' 'MWI_CN71(ver2)' 'MWI_CN72(ver2)' 'MWI_CN73(ver2)'
 'MWI_CN74(ver2)' 'MWI_CN75(ver2)' 'MWI_CN76(ver2)' 'MWI_CN77(ver2)'
 'MWI_CN78(ver2)' 'MWI_CN79(ver2)' 'MWI_CN80(ver2)' 'MWI_CN81(ver2)'
 'MWI_CN82(ver2)' 'MWI_CN83(ver2)' 'MWI_CN84(ver2)']
----------------------------------------
Col name: 논문사용
Data type: object
Unique values: 6
['HFC,LFC사용' nan 'HFC 사용' 'mdMCI22' 'aMCI17' 'newMWI_CN 27명 추가']
----------------------------------------
Col name: PID
Data type: object
Unique values: 84
['145616' '2123108' '78594' '2716077' '469852' '2296061' '316024'
 '1950627' '80969' '1147259' '3773938' '5871888' '6476189' '4341115'
 '1607233' '1190888' '4825611' '2022033' '4073053' '1382411' '4086417'
 '875397' '8481071' '8481058' '8500417' '8510171' '8510155' '213101'
 '243749' '8519137' '2528398' '8664289' '1206895' '4727886' '8696493'
 '738146' '1283958' '2022042' '613165' '8129675' '4920375' '8402901'
 '57983' '2989539' '736914' '9135702' '1551514' '2968625' '9138544'
 '9138558' '1578465' '1511745' '9168261' '9168529' '1794662' '3261945'
 '8527223' '213324' '218652' '9850469' '1422655' '4642795' '5243616'
 '22375' '9524528' '766581' '9577263' '641619' '9588015' '2202449'
 '863315' '7074105' '4074843' '9605724' '9605754' '359871' '7090169'
 '10412752' '10412739' '10474812' '10482577' '10412747' '10474783'
 '10474798']
----------------------------------------
Col name: Age
Data type: int64
Unique values: 26
[70 74 67 62 72 66 76 65 82 69 75 63 68 64 79 81 77 61 71 83 84 88 73 85
 80 78]
----------------------------------------
Col name: Sex
Data type: object
Unique values: 2
['F' 'M']
----------------------------------------
Col name: Education (Year)
Data type: object
Unique values: 21
[16 nan 12 6 9 0.5 7 14 15 0 8 3 '15(대학중퇴)' '4(초등중퇴)' '18(대학원)' '6(초등졸업)'
 '11(고중퇴)' '12(고졸)' '6(국졸)' '9(중졸)' '무학']
----------------------------------------
Col name: Screen fail/Drop 이유
Data type: object
Unique values: 17
['Control 모집' 'Control 모집(SNSB, MRI)' '건망증(영상 implant artifact)'
 'non-amnestic' 'Behcet disease' 'Hypertension, DM (영상 artifact)'
 '낮은 MMSE 점수' '이학영교수진료' '   이학영교수 환자' '변정익교수 환자' '신원철교수 인지장애진료'
 'non amnestic MCI' '기준에 부합하지 않음' '(Lt frontal infarction)인팍으로 탈락'
 'non-amnestic MCI' '   이학영교수 Control 모집(SNSB, MRI)' 'Metal artifact로 탈락']
----------------------------------------
Col name: 임상정보 추가
Data type: object
Unique values: 7
[nan '    subjective memory complaints' 'DM, HTN'
 'NL(CDR 0.5 이나, 세부항목에서의 의미있는 저하는 없음.)'
 'NL(K-BNT 점수가 낮으나, CDR 0으로 일단 정상으로 분류함.)' '(변정익교수진료-수면장애)' '기준에 부합하지 않음']
----------------------------------------
Col name: 최종진단 DDX
Data type: object
Unique values: 14
['NL' nan 'non-amnestic MCI' 'single domain aMCI'
 '    multiple domain aMCI' '   amnestic MCI' '정상, NL'
 'multiple domain amnestic MCI' 'non amnestic MCI' '기준에 부합하지 않음'
 'multiple domain aMCI' 'amnestic MCI' 'mild AD' 'NL ']
----------------------------------------
Col name: SNSB StudyDate
Data type: object
Unique values: 65
[datetime.datetime(2019, 10, 24, 0, 0) nan
 datetime.datetime(2019, 5, 2, 0, 0) datetime.datetime(2019, 3, 29, 0, 0)
 datetime.datetime(2019, 1, 29, 0, 0) datetime.datetime(2019, 1, 28, 0, 0)
 datetime.datetime(2019, 2, 20, 0, 0) datetime.datetime(2019, 11, 2, 0, 0)
 datetime.datetime(2019, 11, 9, 0, 0)
 datetime.datetime(2019, 12, 21, 0, 0)
 datetime.datetime(2019, 12, 7, 0, 0)
 datetime.datetime(2019, 12, 14, 0, 0)
 datetime.datetime(2019, 11, 12, 0, 0)
 datetime.datetime(2020, 5, 14, 0, 0) datetime.datetime(2020, 4, 8, 0, 0)
 datetime.datetime(2020, 4, 9, 0, 0) datetime.datetime(2020, 4, 17, 0, 0)
 datetime.datetime(2020, 4, 21, 0, 0) datetime.datetime(2020, 5, 12, 0, 0)
 datetime.datetime(2020, 8, 18, 0, 0) datetime.datetime(2020, 9, 9, 0, 0)
 datetime.datetime(2020, 9, 8, 0, 0) datetime.datetime(2020, 10, 10, 0, 0)
 datetime.datetime(2020, 9, 29, 0, 0)
 datetime.datetime(2019, 11, 15, 0, 0)
 datetime.datetime(2019, 11, 21, 0, 0)
 datetime.datetime(2020, 6, 30, 0, 0) datetime.datetime(2020, 7, 13, 0, 0)
 datetime.datetime(2021, 6, 4, 0, 0) datetime.datetime(2020, 3, 1, 0, 0)
 datetime.datetime(2021, 2, 24, 0, 0) datetime.datetime(2021, 3, 12, 0, 0)
 datetime.datetime(2021, 6, 19, 0, 0)
 datetime.datetime(2020, 10, 20, 0, 0) datetime.datetime(2021, 2, 3, 0, 0)
 datetime.datetime(2021, 7, 8, 0, 0) '2021-06-26(09:30)' '2021-07-10(토)'
 '7월 28일 3시 검사' '2021-07-12 3시' '2021-07-16 3시' '2021-07-27 4시'
 datetime.datetime(2022, 2, 15, 0, 0) datetime.datetime(2022, 2, 7, 0, 0)
 datetime.datetime(2022, 8, 26, 0, 0) datetime.datetime(2022, 8, 25, 0, 0)
 datetime.datetime(2022, 1, 25, 0, 0) datetime.datetime(2022, 1, 28, 0, 0)
 datetime.datetime(2022, 2, 10, 0, 0) datetime.datetime(2022, 2, 4, 0, 0)
 datetime.datetime(2022, 2, 28, 0, 0) datetime.datetime(2022, 3, 2, 0, 0)
 datetime.datetime(2022, 2, 24, 0, 0) datetime.datetime(2022, 3, 4, 0, 0)
 datetime.datetime(2022, 3, 11, 0, 0) datetime.datetime(2022, 8, 30, 0, 0)
 datetime.datetime(2022, 5, 4, 0, 0) datetime.datetime(2022, 3, 8, 0, 0)
 datetime.datetime(2022, 6, 13, 0, 0)
 datetime.datetime(2023, 11, 14, 0, 0)
 datetime.datetime(2023, 11, 15, 0, 0)
 datetime.datetime(2023, 11, 22, 0, 0)
 datetime.datetime(2024, 1, 31, 0, 0) datetime.datetime(2024, 2, 6, 0, 0)
 datetime.datetime(2024, 1, 29, 0, 0)]
----------------------------------------
Col name: MMSE
Data type: float64
Unique values: 15
[30. nan 28. 29. 26. 27. 23. 14. 25. 32. 24. 21. 19. 13. 20.]
----------------------------------------
Col name: CDR
Data type: float64
Unique values: 4
[0.  nan 0.5 1. ]
----------------------------------------
Col name: CDRSB
Data type: float64
Unique values: 9
[0.5 nan 0.  1.  2.  3.  1.5 4.5 4. ]
----------------------------------------
Col name: GDS
Data type: float64
Unique values: 6
[ 2. nan  3.  1.  5.  4.]
----------------------------------------
Col name: Barthel A DL
Data type: object
Unique values: 3
['20/20' nan '19/20']
----------------------------------------
Col name: Instrumental A DL
Data type: object
Unique values: 20
['1/11=0.09' nan '1/10=0.1' '0/11=0' '2/9=0.22' '2/10=0.2' '0/10=0'
 '1/9=0.11' '0/10=1' '1/11=0.1' '1/10=0' '2/11=0.18' '3/10=0.3' '0/11'
 '6/9=0.67' '1/10=0.10' '1/11=0.9' '0/9=0' '5/10=0.5' '1/11-0/09']
----------------------------------------
Col name: NPI
Data type: object
Unique values: 17
['0/44' nan '3/144' '0/144' '4/144' 'SGDS 0/15' 'SGDS 1/15 normal'
 'SGDS 3/15' 'SGDS 1/15' 'SGDS 8/15' '13/15(moderate)' 'SGDS 10/15'
 'SGDS 6/15' 'SGDS=13/15' 'SGDS=1/15' '3/15(normal)' '2/15(normal)']
----------------------------------------
Col name: MRI StudyDate
Data type: object
Unique values: 71
['2019-10-24(12시)' nan '2019-09-11(17:33)' '2019-09-16(12:09)'
 '2019-10-08(11:45)' '2019-10-04(11:45)' '2019-10-02(11:44)'
 '2019-10-22(12시)' '2019-10-18(12시)' '2019-11-01(17:10)'
 '2019-10-30(16:55)' '2019-10-30(17:48)' '2019-11-05(11:57)'
 '2019-11-09(12:18)' '2019-11-12(12:05)' '2019-11-14(16:56)'
 '2019-11-27(12:05)' '2019-11-28(11:58)' '2020-04-19(13:30)'
 '2020-04-19(14:41)' '2020-04-30(09:12)' '2020-05-01(13:25)'
 '2020-05-01(14:18)' '2020-05-05(13:46)' '2020-05-17(10:31)'
 '2020-05-17(09:23)' '2020-05-22(17:24)' '2020-05-21(09:42)'
 '2020-05-22(17:25)' '2020-08-29(15:31)' '2020-08-08(15:32)'
 '2020-09-12(15:24)' '2020-09-12(14:20)' '2020-10-10(11:05)'
 '2020-10-09(15:23)' '2020-10-09(14:25)' '2020-10-23(12:00)'
 '2020-10-29(11:00)' '2020-11-06(11:52)' '2020-11-07(14:40)'
 '2021-06-12(08:33)' '2021-06-12(14:09)' '2021-06-12(15:07)'
 '2021-06-19(15:40)' '2021-06-19(15:10)' '2021-06-26(10:22)'
 datetime.datetime(2021, 7, 3, 0, 0) datetime.datetime(2021, 7, 8, 0, 0)
 '2021-06-26(11:25)' datetime.datetime(2021, 7, 10, 0, 0) '7월 28일 5시'
 '7월 12일 5시' '2021-07-16 5시' datetime.datetime(2021, 7, 27, 0, 0)
 '2022-02-15(12:00)' '2022-02-07(17:20)'
 datetime.datetime(2022, 8, 26, 0, 0) datetime.datetime(2022, 8, 25, 0, 0)
 '2022-01-29(14:30)' '2022-01-28(17:00)' '2022-02-10(17:00)'
 '2022-02-05(14:30)' '2022-02-05(15:30)'
 datetime.datetime(2022, 2, 28, 0, 0) datetime.datetime(2022, 3, 2, 0, 0)
 datetime.datetime(2022, 3, 5, 0, 0) datetime.datetime(2022, 3, 11, 0, 0)
 datetime.datetime(2022, 8, 29, 0, 0) '2022-04-26(17:00)'
 datetime.datetime(2022, 3, 18, 0, 0) datetime.datetime(2022, 6, 3, 0, 0)]
----------------------------------------
Col name: MRI판독 conclusion
Data type: object
Unique values: 56
['Within normal limits ' nan 'Normal finding of brain MRI & MRA'
 'Normal finding of brain MRI and MRA'
 'Mild small vessel disease\nNormal finding of brain MRA'
 'implant artifact, may be not use    Mild global atrophy\nNormal finding of brain MRA'
 'x' 'Within normal limits.' 'artifact, do not use'
 'Mild\xa0white\xa0matter\xa0hyperintensities'
 'Mild\xa0small\xa0vesse\xa0disease.' 'Within normal limits. '
 'Within normal limits. Microbleed\xa0at\xa0left\xa0middle\xa0cbll\xa0peduncle '
 'Within normal limits. Mild\xa0WM\xa0hyperintensity '
 'Within normal limits. Microbleed\xa0at\xa0left\xa0cingulate\xa0gyrus '
 'Within normal limits. Normal\xa0finding\xa0of\xa0brain\xa0MRA '
 'Within normal limits. Mild\xa0small\xa0vesse\xa0disease.'
 'MIld\xa0global\xa0atrophy.' 'Normal\xa0MRI\xa0of\xa0the\xa0brain. '
 'Mild WM hyperintensities, PVWM/deep WM, Otherwise, unremarkable '
 'Normal MRI of the brain. ' 'Within normal limit. '
 'Mild small vessel disease, Mild to moderate stenosis at right distal M1 '
 'Mild small vessel disease, Normal finding of brain MRA '
 'Mild WM hyperintensities, Normal finding of brain MRI, MRA '
 'Moderate WM hyperintensities, PVWM/deep WM, Normal finding of brain MRA'
 '(결과 전화함)Moderate small vessel disease. Mild brain atrophy. '
 '(결과 전화함-진료요청) Mild small vessel disease. Ddx junctaional dilatation > aneurysm, bilateral distal ICAs.'
 '(결과 전화함)Within normal limits. '
 '(결과 전화함)Mild small vessel disease. Right mastoiditis. '
 '(결과 전화함)Moderate small vessel disease. '
 '(결과 전화함)Mild brain atrophy. Mild small vessel disease. '
 '(결과 전화함)Within\xa0normal\xa0limits '
 '(결과 전화함-진료요청) Moderate small vessel disease'
 '(결과 전화함-진료요청) Mild small vessel disease. Ddx aneurysm vs junctional dilatation, right distal ICA'
 '(결과 전화함)Moderate\xa0brain\xa0atrophy. '
 '(결과 전화함-진료요청)Mild small vessel disease'
 '(결과 전화함-진료요청)Moderate\xa0small\xa0vessel\xa0disease'
 '(결과 전화함-진료요청) Moderate small vessel disease. Segmental severe stenosis, ,left M1. '
 '(결과 전화함)Moderate\xa0small\xa0vessel\xa0disease'
 '(결과 전화함-진료요청)Mild\xa0leukoaraiosis\xa0in\xa0bilateral\xa0cerebral\xa0subcortical\xa0white\xa0matter. Mild\xa0stenosis,\xa0right\xa0P2. '
 'Left ICA hypophyseal aneurysm, REC) cerebral angiography '
 'Chronic\xa0lacune\xa0at\xa0left\xa0frontal\xa0corona\xa0radiata                        Moderate WM hyperintensities Normal finding of brain MRA '
 'Descending colon cancer. Normal finding of brain MRI                                Left ICA, superior hypophyseal aneurysm (3mm)'
 'Normal finding of brain MRI. R/O ACoA aneurysm, 2mm'
 'normal finding of brain MRI. Occlusion of right ICA. Left ICA dorsal wall aneurysm.REC) cerebral angiography '
 'Mild WM hyperintensitie. Moderate medial temporal atrophy. Normal finding of brain MRA'
 'Moderate WM hyperintensities. Normal finding of brain MRA '
 'Within normal limit'
 'Within normal limit. Microbleed at left occipital lobe '
 'Mild WM hyperintensities, PVWM. Microbleed at Rt superior frontal gyrus\nNormal finding of brain MRA '
 'Mild global atrophy. Mild WM hyperintensities, PVWM. Normal finding of brain MRA. Enlarged ventricle and atrophy at bilateral hippocampi'
 'Mild small vessel disease.\nVuno: WNL ' 'Mild small vessel disease. '
 'Within normal limits of brain parenchyma.\nMild stenosis, left V4.'
 'Mild small vessel disease.\nVuno volumetric report: atrophy at right hippocampus. ']
----------------------------------------
Col name: TIV
Data type: float64
Unique values: 70
[1447.28397916           nan 1260.32824748 1492.92206163 1648.67403107
 1571.03098202 1424.53780276 1576.7736909  1444.45291448 1592.8144484
 1279.17874045 1338.41291045 1509.89081619 1259.32142525 1205.87212794
 1433.05542167 1601.02997959 1442.43223506 1334.63701233 1617.28391518
 1501.00816084 1351.69847878 1242.52438102 1520.36372943 1162.6828975
 1471.07028413 1413.43440971 1271.74987035 1495.39192315 1271.28004723
 1505.42777156 1392.61409605 1394.07176402 1400.32071168 1599.48630852
 1435.93661645 1313.28840422 1271.58858323 1429.03022293 1336.08256294
 1537.02813023 1448.85865469 1307.37650856 1208.47990065 1317.25642501
 1401.21597529 1325.99035296 1378.11633469 1358.46877315 1506.84040172
 1258.11431492 1595.84151546 1553.44844324 1210.95173074 1672.20452099
 1671.79095428 1344.11536942 1237.56966654 1604.50997263 1264.01023226
 1273.87382166 1317.43954639 1373.31689214 1447.19837052 1387.04764883
 1187.52343011 1377.38205637 1236.32161755 1689.67483971 1472.81496733]
----------------------------------------
Col name: global GMV
Data type: float64
Unique values: 70
[546.97666864          nan 524.85261719 576.77272773 618.6940494
 623.47989563 548.55524203 639.27492736 545.31834834 584.66644824
 519.2036609  535.63801596 571.78697133 511.20647963 521.58027546
 563.90862222 608.09534038 616.47157627 533.1266191  628.62412804
 603.07208784 534.36468714 507.41702058 626.33048008 484.02431352
 596.38385287 587.81814285 515.48670791 517.29520886 530.19805005
 548.57895474 565.13133401 570.04822665 524.26674578 604.43415428
 512.9737294  514.59407087 486.83682462 533.56332836 503.18363814
 554.33607037 522.9826558  497.15268746 476.20116989 539.64086548
 505.12075703 515.32544859 465.46791418 531.4914773  559.70460389
 455.77903249 635.19438013 632.01784318 497.18343914 621.39233513
 628.10622065 532.47306662 492.4059232  565.90687822 474.07886308
 537.07868879 428.99918172 476.67962165 562.69606741 511.80966401
 506.70717985 465.91736912 509.17071172 592.58817975 552.71846273]
----------------------------------------
Col name: global WMV
Data type: float64
Unique values: 70
[501.94249233          nan 475.17746464 501.10409369 478.79283533
 563.68824564 446.33426989 568.33300559 520.08907761 503.09816472
 430.15005035 428.35035472 434.73891921 437.63511758 408.38401899
 523.05883493 571.99701261 535.4452697  488.67391228 602.69465912
 497.36926149 387.41519955 441.18396606 507.22034776 345.10708391
 501.88139087 488.29330781 381.85923011 416.92910342 392.19384073
 519.93222483 505.18580143 501.34883742 490.01124693 452.43763338
 440.54470643 406.09587246 432.49329116 371.86946962 426.41948629
 487.41270988 394.88917819 404.39175955 376.02208665 432.23885551
 443.83015642 403.28816983 405.49585138 421.17151889 431.68521107
 425.70678876 515.36246372 536.87178043 362.77482983 531.85594385
 552.57173487 428.66323974 389.62392777 530.99889663 439.42268965
 413.34997056 363.27348556 414.87964491 453.18875104 401.52374778
 387.99348978 411.32769848 415.63341621 553.65947102 455.53155246]
----------------------------------------
Col name: global CSFV
Data type: float64
Unique values: 70
[396.97433976          nan 259.66698138 412.71102064 547.50934627
 380.83241727 429.64829084 367.43466382 376.32334734 498.00921539
 329.82502919 374.42453977 503.36492565 309.00075358 274.67111195
 346.08796452 418.42598722 289.34265177 310.31275171 382.11571258
 399.41113309 428.83438816 292.70663752 384.21108175 332.93750009
 366.7280603  337.32295905 373.6575402  557.77324239 347.29606241
 429.16764676 321.04775671 321.81295097 386.04271897 538.30720334
 478.48988261 390.75904524 337.77426742 523.59742495 406.4794385
 495.27934998 530.9868207  405.83206155 356.25664411 345.37670402
 452.26506184 407.37673454 507.15256913 405.80577696 515.45058676
 376.62849368 445.28467162 384.55881963 350.99346177 518.95624201
 491.11299875 382.97906306 355.53981556 507.60419779 350.50867953
 323.4451623  525.16687911 481.75762559 431.31355207 473.71423705
 292.82276047 500.13698877 311.51748962 543.42718895 464.56495214]
----------------------------------------
Col name: MR_3DT1_TFE
Data type: object
Unique values: 2
['O' nan]
----------------------------------------
Col name: MR_3DGRASE_MWI
Data type: object
Unique values: 2
['O' nan]
----------------------------------------
Col name: MR_3DGRASE_REF
Data type: object
Unique values: 2
['O' nan]
----------------------------------------
Col name: MREPT_TSE
Data type: object
Unique values: 2
['O' nan]
----------------------------------------
Col name: NODDI
Data type: object
Unique values: 3
['NODDI32' nan 'DKI']
----------------------------------------
Col name: MREPT_3DbFFE
Data type: object
Unique values: 2
['x' nan]
----------------------------------------
Col name: SWI
Data type: object
Unique values: 3
['O' nan "'X'"]
----------------------------------------
Col name: T2_OBL_COR
Data type: object
Unique values: 3
['O' nan "'X'"]
----------------------------------------
Col name: FLAIR
Data type: object
Unique values: 3
['O' nan "'X'"]
----------------------------------------
Col name: MWF
Data type: object
Unique values: 2
['O' nan]
----------------------------------------
Col name: VOLUME
Data type: object
Unique values: 2
['O' nan]
----------------------------------------
Col name: HFC
Data type: object
Unique values: 2
['O' nan]
----------------------------------------
Col name: LFC(EC,IC)
Data type: object
Unique values: 3
['O' nan "'X'"]
----------------------------------------
Col name: SMT(ED,ID)
Data type: object
Unique values: 3
['O' nan "'X'"]
----------------------------------------
Col name: IVF,EIC
Data type: object
Unique values: 3
['O' nan "'X'"]
----------------------------------------

In [14]:
# Find duplicate PIDs
b2AD['PID'].replace('nan', pd.NA, inplace=True)
b2AD = b2AD.dropna(subset=['PID'])
b2AD = b2AD[b2AD['PID'].str.lower() != 'nan']
b2AD = b2AD[b2AD['PID'].notna()]

dup_counts_AD = b2AD['PID'].value_counts()
dup_AD = dup_counts_AD[dup_counts_AD > 1]
print("b1AD: Duplicated PID / n :")
print(dup_AD)
dup_mask_AD = b2AD['PID'].duplicated(keep=False)
print("b2AD: Duplicate PID rows")
print(b2AD[dup_mask_AD])


print('-'*80)
b2CN['PID'].replace('nan', pd.NA, inplace=True)
b2CN = b2CN.dropna(subset=['PID'])
b2CN = b2CN[b2CN['PID'].str.lower() != 'nan']
b2CN = b2CN[b2CN['PID'].notna()]

dup_counts_CN = b2CN['PID'].value_counts()
dup_CN = dup_counts_CN[dup_counts_CN > 1]
print("\nb2AD: Duplicated PID / n :")
print(dup_CN)
dup_mask_CN = b2CN['PID'].duplicated(keep=False)
print("b2CN: Duplicate PID rows")
print(b2CN[dup_mask_CN])

b1AD: Duplicated PID / n :
PID
4100729    2
6763469    2
3281139    2
Name: count, dtype: int64
b2AD: Duplicate PID rows
    건대분석정보   인원               Origin Code          Code      PID   Age Sex  \
69     Yes  NaN       ADEPT56_CKJ_NODDI24       ADEPT56  4100729  72.0   F
93     Yea  NaN  EPT2022AD069_LBD_NODDI32  EPT2022AD069  3281139  77.0   F
174     No  NaN                       NaN   EPT2023AD20  4100729  76.0   F
176     No  NaN                       NaN   EPT2023AD22  6763469  80.0   F
202    Yes  NaN       HFC2021AD09_KID_DKI   HFC2021AD09  6763469  78.0   F
222    Yes  NaN       HFC2021AD29_LBD_DKI   HFC2021AD29  3281139  76.0   F

    Education(Year)                                Clinical Info(진료교수)  \
69                3        MCA An post clip, frontal dysfunction naMCI
93              NaN  고혈압, 당뇨, 녹내장, 백내장, 고지혈증(이학영)확정(주) Dementia in ...
174             NaN                         환청, 환시, 망상적 사고 동반((조아랑교수))
176             NaN      기억장애(이학영)    E3/E4     Lt caudate lacune, ...
202              12                      HTN (이학영) mutiple domain aMCI
222               6  기억력저하, 고혈압, 당뇨, 녹내장, 백내장, 고지혈증, 경도치매(이학영) mild...

                                              최종진단 DDX  ...  global WMV  \
69       non-amnestid MCI + drug-induced encephalop...  ...  396.677415
93                                           ADD, mild  ...  433.668560
174  Dementia in lewy body(ies) (disease)\nr.o. Sen...  ...         NaN
176                               multiple domain aMCI  ...         NaN
202                                mutiple domain aMCI  ...  390.434001
222                                          mild AD    ...  440.800421

    global CSFV  MR_3DT1_TFE  MR_3DGRASE_MWI  MR_3DGRASE_REF MREPT_TSE  \
69   384.306081            O               X               X         O
93   417.701548            O               O               O         O
174         NaN          NaN             NaN             NaN       NaN
176         NaN          NaN             NaN             NaN       NaN
202  346.321205            O               O               O         O
222  418.356821            O               O               O         O

       NODDI MREPT_3DbFFE                                          final ddx  \
69   NODDI24            X      non-amnestid MCI + drug-induced encephalop...
93   NODDI32            X                                          ADD, mild
174      NaN          NaN                                                NaN
176      NaN          NaN                               multiple domain aMCI
202      DKI            X                                mutiple domain aMCI
222      DKI            X                                            mild AD

           논문사용
69          NaN
93   2022 하반기영상
174         NaN
176         NaN
202   HFC,LFC사용
222  2021 하반기영상

[6 rows x 32 columns]
--------------------------------------------------------------------------------

b2AD: Duplicated PID / n :
Series([], Name: count, dtype: int64)
b2CN: Duplicate PID rows
Empty DataFrame
Columns: [건대분석정보, 인원, 미수코드, AD_MWI_Code, 논문사용, PID, Age, Sex, Education (Year), Screen fail/Drop 이유, 임상정보 추가, 최종진단 DDX, SNSB StudyDate, MMSE, CDR, CDRSB, GDS, Barthel A DL, Instrumental A DL, NPI, MRI StudyDate, MRI판독 conclusion, TIV, global GMV, global WMV, global CSFV, MR_3DT1_TFE, MR_3DGRASE_MWI, MR_3DGRASE_REF, MREPT_TSE, NODDI, MREPT_3DbFFE, SWI, T2_OBL_COR, FLAIR, MWF, VOLUME, HFC, LFC(EC,IC), SMT(ED,ID), IVF,EIC]
Index: []

[0 rows x 41 columns]

In [15]:
# # b2AD: Duplicated n --> Left first row
# print("Before dedup, b2AD length:", len(b2AD))
# b2AD = b2AD.drop_duplicates(subset=['PID'], keep='first')
# print("After dedup, b2AD length:", len(b2AD))

# # b2CN: Remove meaningless rows & left first row
# rows_remove = [
#     '1', '2'
# ]
# if rows_remove:
#     print(f"\nRemoving selected PIDs: {rows_remove}")
#     b2CN = b2CN[~b2CN['PID'].isin(rows_remove)]
# print("Before dedup (remaining), b2CN length:", len(b2CN))
# b2CN = b2CN.drop_duplicates(subset=['PID'], keep='first')
# print("After dedup, b2CN length:", len(b2CN))

b2AD['PID']  = b2AD['PID'].replace('nan', pd.NA)
b2AD['Code'] = b2AD['Code'].replace('nan', pd.NA)

# ── 2) PID 기준으로 그룹핑해 병합 ──
def merge_group(g: pd.DataFrame) -> pd.Series:
    """그룹(DataFrame) 내에서 첫 행을 복사한 뒤,
       각 컬럼의 NaN을 다른 행의 최초 non-null 값으로 채워 반환."""
    base = g.iloc[0].copy()          # ‘첫 행’을 기준으로 삼음
    for col in g.columns:
        if pd.isna(base[col]):       # 기준 행이 NaN이면
            # 그 컬럼에서 non-null 값 찾기
            non_null = g[col].dropna()
            if not non_null.empty:
                base[col] = non_null.iloc[0]  # 가장 첫 non-null 값으로 채움
    return base

# sort=False → 원본 순서 보존, as_index=False → PID를 컬럼으로 남김
b2AD = (
    b2AD.groupby('PID', as_index=False, sort=False)
         .apply(merge_group)
         .reset_index(drop=True)
)

print(f"n of after duplication: {len(b2AD):,}")
print(b2AD[['Code', 'PID']].head())

n of after duplication: 274
             Code      PID
0  AD2019_BrMRA01  3735478
1  AD2019_BrMRA02  4381137
2  AD2019_BrMRA03  4452316
3  AD2019_BrMRA04  4681566
4  AD2019_BrMRA05  7205823

In [16]:
b2AD

,건대분석정보,인원,Origin Code,Code,PID,Age,Sex,Education(Year),Clinical Info(진료교수),최종진단 DDX,...,global WMV,global CSFV,MR_3DT1_TFE,MR_3DGRASE_MWI,MR_3DGRASE_REF,MREPT_TSE,NODDI,MREPT_3DbFFE,final ddx,논문사용
0,Yes,NaN,MREPT2019AD01,AD2019_BrMRA01,3735478,70.0,F,14,HTN mdMCI,multiple domain aMCI,...,431.903364,427.441118,O,O,O,O,NODDI32,X,multiple domain aMCI,mdMCI03
1,Yes,NaN,MREPT2019AD02,AD2019_BrMRA02,4381137,68.0,F,13,"HTN, 고지혈증, ICAaneurysm aMCI",amnestic MCI,...,485.314945,315.153808,O,O,O,O,NODDI32,X,amnestic MCI,"HFC,LFC,MWI 사용"
2,Yes,탈락,MREPT2019AD03,AD2019_BrMRA03,4452316,67.0,F,9,"(조아랑) mild NCD(amnestic type), depression","mild NCD(amnestic type), depression",...,404.586605,308.493634,O,O,O,O,NODDI32,X,"mild NCD(amnestic type), depression",HFC
3,Yes,NaN,MREPT2019AD04,AD2019_BrMRA04,4681566,66.0,M,12,subjective cognitive decline,subjective cognitive decline,...,524.819073,337.671219,O,O,O,O,NODDI32,X,subjective cognitive decline,HFC
4,Yes,NaN,MREPT2019AD05,AD2019_BrMRA05,7205823,77.0,F,6,mild SVD aMCI,amnestic MCI,...,414.490405,382.888115,O,O,O,O,NODDI32,X,amnestic MCI,"HFC,LFC,MWI 사용"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
269,Yes,NaN,MREPT2020AD24_YYS_NODDI32,MREPT2020AD24,8700631,60.0,F,6,"조아랑 Alzheimer's dementia, early onset, depression","Alzheimer's dementia, early onset, depression",...,336.016348,460.074360,O,O,O,O,NODDI32,X,"Alzheimer's dementia, early onset, depression","HFC,LFC사용"
270,Yes,NaN,MREPT2020AD25_YSJ_NODDI32,MREPT2020AD25,8655418,76.0,F,9,amnestic MCI,amnestic MCI,...,341.371124,402.802737,O,O,O,O,NODDI32,X,amnestic MCI,NaN
271,Yes,NaN,MREPT2020AD26_HMH_NODDI32,MREPT2020AD26,8655425,77.0,M,6,"DM, HTN 고지혈증, 이학영 multiple domain aMCI",multiple domain amnestic MCI,...,454.385693,512.686386,O,O,O,O,NODDI32,X,multiple domain amnestic MCI,NaN
272,Yes,탈락-venous anomaly,MREPT2020AD27_YJJ_NODDI32,MREPT2020AD27,577752,71.0,F,NaN,"depressive, 이학영 multiple domain non-amnestic MCI",mutiple domain non-amnestic MCI,...,487.814184,468.901713,O,O,O,O,NODDI32,X,mutiple domain non-amnestic MCI,NaN
273,Yes,NaN,MREPT2020AD28_YYL_NODDI32,MREPT2020AD28,5533209,80.0,F,0,"조아랑 Alzheimer's dementia, late onset","Alzheimer's dementia, late onset",...,353.353720,485.691918,O,O,O,O,NODDI32,X,"Alzheimer's dementia, late onset","HFC,LFC사용"

In [17]:
b2CN

,건대분석정보,인원,미수코드,AD_MWI_Code,논문사용,PID,Age,Sex,Education (Year),Screen fail/Drop 이유,...,MREPT_3DbFFE,SWI,T2_OBL_COR,FLAIR,MWF,VOLUME,HFC,"LFC(EC,IC)","SMT(ED,ID)","IVF,EIC"
0,Yes,1,8641,MWI_CN01,"HFC,LFC사용",145616,70,F,16,Control 모집,...,x,O,O,O,O,O,O,O,O,O
1,No,1,8641,MWI_CN02(ver2),NaN,2123108,74,M,NaN,"Control 모집(SNSB, MRI)",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,No,2,8641,MWI_CN03(ver2),NaN,78594,67,F,NaN,"Control 모집(SNSB, MRI)",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Yes,2,8641,MWI_CN04,HFC 사용,2716077,62,F,12,Control 모집,...,x,O,O,O,O,O,O,O,O,O
4,Yes,3,8641,MWI_CN05,"HFC,LFC사용",469852,72,M,16,Control 모집,...,x,O,O,O,O,O,O,O,O,O
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
79,No,6,8641,MWI_CN80(ver2),NaN,10474812,78,F,NaN,"Control 모집(SNSB, MRI)",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
80,No,7,8641,MWI_CN81(ver2),NaN,10482577,66,M,NaN,"Control 모집(SNSB, MRI)",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
81,No,8,8641,MWI_CN82(ver2),NaN,10412747,74,M,NaN,"Control 모집(SNSB, MRI)",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
82,No,9,8641,MWI_CN83(ver2),NaN,10474783,74,F,NaN,"Control 모집(SNSB, MRI)",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
83,No,10,8641,MWI_CN84(ver2),NaN,10474798,74,F,NaN,"Control 모집(SNSB, MRI)",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [19]:
df = b2CN
for column in df.columns:
    print(f"Col name: {column}")
    print(f"Data type: {df[column].dtype}")
    print(f"Unique values: {len(df[column].unique())}")
    print(df[column].unique())
    print('-'*40)

Col name: 건대분석정보
Data type: object
Unique values: 2
['Yes' 'No']
----------------------------------------
Col name: 인원
Data type: object
Unique values: 43
[1 2 3 4 5 '6탈락1-1' '7탈락1-2' '8탈락1-3' '9탈락1-4' 10 11 '12탈락1-5' '13탈락1-6'
 '14탈락1-7' 15 16 17 18 19 20 21 22 23 24 25 26 27 28 6 '7탈락2-1' 8 9 12 13
 14 '19탈락2-2' '22탈락2-3' '5탈락3-1' 7 '9탈락3-2' '10탈락3-3' '13탈락3-4' '4탈락-']
----------------------------------------
Col name: 미수코드
Data type: int64
Unique values: 1
[8641]
----------------------------------------
Col name: AD_MWI_Code
Data type: object
Unique values: 84
['MWI_CN01' 'MWI_CN02(ver2)' 'MWI_CN03(ver2)' 'MWI_CN04' 'MWI_CN05'
 'MWI_CN06' 'MWI_CN07' 'MWI_CN08' 'MWI_CN09' 'MWI_CN10' 'MWI_CN11'
 'MWI_CN12' 'MWI_CN13' 'MWI_CN14' 'MWI_CN15' 'MWI_CN16' 'MWI_CN17'
 'MWI_CN18' 'MWI_CN19' 'MWI_CN20' 'MWI_CN21' 'MWI_CN22' 'MWI_CN23'
 'MWI_CN24' 'MWI_CN25' 'MWI_CN26' 'MWI_CN27' 'MWI_CN28' 'MWI_CN29'
 'MWI_CN30' 'MWI_CN31' 'MWI_CN32' 'MWI_CN33' 'MWI_CN34' 'MWI_CN35'
 'MWI_CN36' 'MWI_CN37' 'MWI_CN38' 'MWI_CN39' 'MWI_CN40' 'MWI_CN41'
 'MWI_CN42' 'MWI_CN43' 'MWI_CN44' 'MWI_CN45' 'MWI_CN46' 'MWI_CN47'
 'MWI_CN48' 'MWI_CN49' 'MWI_CN50' 'MWI_CN51' 'MWI_CN52' 'MWI_CN53'
 'MWI_CN54' 'MWI_CN55' 'MWI_CN56(ver1.2)' 'MWI_CN57(ver2)'
 'MWI_CN58(ver2)' 'MWI_CN59(ver2)' 'MWI_CN60(ver2)' 'MWI_CN61(ver2)'
 'MWI_CN62(ver2)' 'MWI_CN63(ver2)' 'MWI_CN64(ver2)' 'MWI_CN65(ver2)'
 'MWI_CN66(ver2)' 'MWI_CN67(ver2)' 'MWI_CN68(ver2)' 'MWI_CN69(ver2)'
 'MWI_CN70(ver2)' 'MWI_CN71(ver2)' 'MWI_CN72(ver2)' 'MWI_CN73(ver2)'
 'MWI_CN74(ver2)' 'MWI_CN75(ver2)' 'MWI_CN76(ver2)' 'MWI_CN77(ver2)'
 'MWI_CN78(ver2)' 'MWI_CN79(ver2)' 'MWI_CN80(ver2)' 'MWI_CN81(ver2)'
 'MWI_CN82(ver2)' 'MWI_CN83(ver2)' 'MWI_CN84(ver2)']
----------------------------------------
Col name: 논문사용
Data type: object
Unique values: 6
['HFC,LFC사용' nan 'HFC 사용' 'mdMCI22' 'aMCI17' 'newMWI_CN 27명 추가']
----------------------------------------
Col name: PID
Data type: object
Unique values: 84
['145616' '2123108' '78594' '2716077' '469852' '2296061' '316024'
 '1950627' '80969' '1147259' '3773938' '5871888' '6476189' '4341115'
 '1607233' '1190888' '4825611' '2022033' '4073053' '1382411' '4086417'
 '875397' '8481071' '8481058' '8500417' '8510171' '8510155' '213101'
 '243749' '8519137' '2528398' '8664289' '1206895' '4727886' '8696493'
 '738146' '1283958' '2022042' '613165' '8129675' '4920375' '8402901'
 '57983' '2989539' '736914' '9135702' '1551514' '2968625' '9138544'
 '9138558' '1578465' '1511745' '9168261' '9168529' '1794662' '3261945'
 '8527223' '213324' '218652' '9850469' '1422655' '4642795' '5243616'
 '22375' '9524528' '766581' '9577263' '641619' '9588015' '2202449'
 '863315' '7074105' '4074843' '9605724' '9605754' '359871' '7090169'
 '10412752' '10412739' '10474812' '10482577' '10412747' '10474783'
 '10474798']
----------------------------------------
Col name: Age
Data type: int64
Unique values: 26
[70 74 67 62 72 66 76 65 82 69 75 63 68 64 79 81 77 61 71 83 84 88 73 85
 80 78]
----------------------------------------
Col name: Sex
Data type: object
Unique values: 2
['F' 'M']
----------------------------------------
Col name: Education (Year)
Data type: object
Unique values: 21
[16 nan 12 6 9 0.5 7 14 15 0 8 3 '15(대학중퇴)' '4(초등중퇴)' '18(대학원)' '6(초등졸업)'
 '11(고중퇴)' '12(고졸)' '6(국졸)' '9(중졸)' '무학']
----------------------------------------
Col name: Screen fail/Drop 이유
Data type: object
Unique values: 17
['Control 모집' 'Control 모집(SNSB, MRI)' '건망증(영상 implant artifact)'
 'non-amnestic' 'Behcet disease' 'Hypertension, DM (영상 artifact)'
 '낮은 MMSE 점수' '이학영교수진료' '   이학영교수 환자' '변정익교수 환자' '신원철교수 인지장애진료'
 'non amnestic MCI' '기준에 부합하지 않음' '(Lt frontal infarction)인팍으로 탈락'
 'non-amnestic MCI' '   이학영교수 Control 모집(SNSB, MRI)' 'Metal artifact로 탈락']
----------------------------------------
Col name: 임상정보 추가
Data type: object
Unique values: 7
[nan '    subjective memory complaints' 'DM, HTN'
 'NL(CDR 0.5 이나, 세부항목에서의 의미있는 저하는 없음.)'
 'NL(K-BNT 점수가 낮으나, CDR 0으로 일단 정상으로 분류함.)' '(변정익교수진료-수면장애)' '기준에 부합하지 않음']
----------------------------------------
Col name: 최종진단 DDX
Data type: object
Unique values: 14
['NL' nan 'non-amnestic MCI' 'single domain aMCI'
 '    multiple domain aMCI' '   amnestic MCI' '정상, NL'
 'multiple domain amnestic MCI' 'non amnestic MCI' '기준에 부합하지 않음'
 'multiple domain aMCI' 'amnestic MCI' 'mild AD' 'NL ']
----------------------------------------
Col name: SNSB StudyDate
Data type: object
Unique values: 65
[datetime.datetime(2019, 10, 24, 0, 0) nan
 datetime.datetime(2019, 5, 2, 0, 0) datetime.datetime(2019, 3, 29, 0, 0)
 datetime.datetime(2019, 1, 29, 0, 0) datetime.datetime(2019, 1, 28, 0, 0)
 datetime.datetime(2019, 2, 20, 0, 0) datetime.datetime(2019, 11, 2, 0, 0)
 datetime.datetime(2019, 11, 9, 0, 0)
 datetime.datetime(2019, 12, 21, 0, 0)
 datetime.datetime(2019, 12, 7, 0, 0)
 datetime.datetime(2019, 12, 14, 0, 0)
 datetime.datetime(2019, 11, 12, 0, 0)
 datetime.datetime(2020, 5, 14, 0, 0) datetime.datetime(2020, 4, 8, 0, 0)
 datetime.datetime(2020, 4, 9, 0, 0) datetime.datetime(2020, 4, 17, 0, 0)
 datetime.datetime(2020, 4, 21, 0, 0) datetime.datetime(2020, 5, 12, 0, 0)
 datetime.datetime(2020, 8, 18, 0, 0) datetime.datetime(2020, 9, 9, 0, 0)
 datetime.datetime(2020, 9, 8, 0, 0) datetime.datetime(2020, 10, 10, 0, 0)
 datetime.datetime(2020, 9, 29, 0, 0)
 datetime.datetime(2019, 11, 15, 0, 0)
 datetime.datetime(2019, 11, 21, 0, 0)
 datetime.datetime(2020, 6, 30, 0, 0) datetime.datetime(2020, 7, 13, 0, 0)
 datetime.datetime(2021, 6, 4, 0, 0) datetime.datetime(2020, 3, 1, 0, 0)
 datetime.datetime(2021, 2, 24, 0, 0) datetime.datetime(2021, 3, 12, 0, 0)
 datetime.datetime(2021, 6, 19, 0, 0)
 datetime.datetime(2020, 10, 20, 0, 0) datetime.datetime(2021, 2, 3, 0, 0)
 datetime.datetime(2021, 7, 8, 0, 0) '2021-06-26(09:30)' '2021-07-10(토)'
 '7월 28일 3시 검사' '2021-07-12 3시' '2021-07-16 3시' '2021-07-27 4시'
 datetime.datetime(2022, 2, 15, 0, 0) datetime.datetime(2022, 2, 7, 0, 0)
 datetime.datetime(2022, 8, 26, 0, 0) datetime.datetime(2022, 8, 25, 0, 0)
 datetime.datetime(2022, 1, 25, 0, 0) datetime.datetime(2022, 1, 28, 0, 0)
 datetime.datetime(2022, 2, 10, 0, 0) datetime.datetime(2022, 2, 4, 0, 0)
 datetime.datetime(2022, 2, 28, 0, 0) datetime.datetime(2022, 3, 2, 0, 0)
 datetime.datetime(2022, 2, 24, 0, 0) datetime.datetime(2022, 3, 4, 0, 0)
 datetime.datetime(2022, 3, 11, 0, 0) datetime.datetime(2022, 8, 30, 0, 0)
 datetime.datetime(2022, 5, 4, 0, 0) datetime.datetime(2022, 3, 8, 0, 0)
 datetime.datetime(2022, 6, 13, 0, 0)
 datetime.datetime(2023, 11, 14, 0, 0)
 datetime.datetime(2023, 11, 15, 0, 0)
 datetime.datetime(2023, 11, 22, 0, 0)
 datetime.datetime(2024, 1, 31, 0, 0) datetime.datetime(2024, 2, 6, 0, 0)
 datetime.datetime(2024, 1, 29, 0, 0)]
----------------------------------------
Col name: MMSE
Data type: float64
Unique values: 15
[30. nan 28. 29. 26. 27. 23. 14. 25. 32. 24. 21. 19. 13. 20.]
----------------------------------------
Col name: CDR
Data type: float64
Unique values: 4
[0.  nan 0.5 1. ]
----------------------------------------
Col name: CDRSB
Data type: float64
Unique values: 9
[0.5 nan 0.  1.  2.  3.  1.5 4.5 4. ]
----------------------------------------
Col name: GDS
Data type: float64
Unique values: 6
[ 2. nan  3.  1.  5.  4.]
----------------------------------------
Col name: Barthel A DL
Data type: object
Unique values: 3
['20/20' nan '19/20']
----------------------------------------
Col name: Instrumental A DL
Data type: object
Unique values: 20
['1/11=0.09' nan '1/10=0.1' '0/11=0' '2/9=0.22' '2/10=0.2' '0/10=0'
 '1/9=0.11' '0/10=1' '1/11=0.1' '1/10=0' '2/11=0.18' '3/10=0.3' '0/11'
 '6/9=0.67' '1/10=0.10' '1/11=0.9' '0/9=0' '5/10=0.5' '1/11-0/09']
----------------------------------------
Col name: NPI
Data type: object
Unique values: 17
['0/44' nan '3/144' '0/144' '4/144' 'SGDS 0/15' 'SGDS 1/15 normal'
 'SGDS 3/15' 'SGDS 1/15' 'SGDS 8/15' '13/15(moderate)' 'SGDS 10/15'
 'SGDS 6/15' 'SGDS=13/15' 'SGDS=1/15' '3/15(normal)' '2/15(normal)']
----------------------------------------
Col name: MRI StudyDate
Data type: object
Unique values: 71
['2019-10-24(12시)' nan '2019-09-11(17:33)' '2019-09-16(12:09)'
 '2019-10-08(11:45)' '2019-10-04(11:45)' '2019-10-02(11:44)'
 '2019-10-22(12시)' '2019-10-18(12시)' '2019-11-01(17:10)'
 '2019-10-30(16:55)' '2019-10-30(17:48)' '2019-11-05(11:57)'
 '2019-11-09(12:18)' '2019-11-12(12:05)' '2019-11-14(16:56)'
 '2019-11-27(12:05)' '2019-11-28(11:58)' '2020-04-19(13:30)'
 '2020-04-19(14:41)' '2020-04-30(09:12)' '2020-05-01(13:25)'
 '2020-05-01(14:18)' '2020-05-05(13:46)' '2020-05-17(10:31)'
 '2020-05-17(09:23)' '2020-05-22(17:24)' '2020-05-21(09:42)'
 '2020-05-22(17:25)' '2020-08-29(15:31)' '2020-08-08(15:32)'
 '2020-09-12(15:24)' '2020-09-12(14:20)' '2020-10-10(11:05)'
 '2020-10-09(15:23)' '2020-10-09(14:25)' '2020-10-23(12:00)'
 '2020-10-29(11:00)' '2020-11-06(11:52)' '2020-11-07(14:40)'
 '2021-06-12(08:33)' '2021-06-12(14:09)' '2021-06-12(15:07)'
 '2021-06-19(15:40)' '2021-06-19(15:10)' '2021-06-26(10:22)'
 datetime.datetime(2021, 7, 3, 0, 0) datetime.datetime(2021, 7, 8, 0, 0)
 '2021-06-26(11:25)' datetime.datetime(2021, 7, 10, 0, 0) '7월 28일 5시'
 '7월 12일 5시' '2021-07-16 5시' datetime.datetime(2021, 7, 27, 0, 0)
 '2022-02-15(12:00)' '2022-02-07(17:20)'
 datetime.datetime(2022, 8, 26, 0, 0) datetime.datetime(2022, 8, 25, 0, 0)
 '2022-01-29(14:30)' '2022-01-28(17:00)' '2022-02-10(17:00)'
 '2022-02-05(14:30)' '2022-02-05(15:30)'
 datetime.datetime(2022, 2, 28, 0, 0) datetime.datetime(2022, 3, 2, 0, 0)
 datetime.datetime(2022, 3, 5, 0, 0) datetime.datetime(2022, 3, 11, 0, 0)
 datetime.datetime(2022, 8, 29, 0, 0) '2022-04-26(17:00)'
 datetime.datetime(2022, 3, 18, 0, 0) datetime.datetime(2022, 6, 3, 0, 0)]
----------------------------------------
Col name: MRI판독 conclusion
Data type: object
Unique values: 56
['Within normal limits ' nan 'Normal finding of brain MRI & MRA'
 'Normal finding of brain MRI and MRA'
 'Mild small vessel disease\nNormal finding of brain MRA'
 'implant artifact, may be not use    Mild global atrophy\nNormal finding of brain MRA'
 'x' 'Within normal limits.' 'artifact, do not use'
 'Mild\xa0white\xa0matter\xa0hyperintensities'
 'Mild\xa0small\xa0vesse\xa0disease.' 'Within normal limits. '
 'Within normal limits. Microbleed\xa0at\xa0left\xa0middle\xa0cbll\xa0peduncle '
 'Within normal limits. Mild\xa0WM\xa0hyperintensity '
 'Within normal limits. Microbleed\xa0at\xa0left\xa0cingulate\xa0gyrus '
 'Within normal limits. Normal\xa0finding\xa0of\xa0brain\xa0MRA '
 'Within normal limits. Mild\xa0small\xa0vesse\xa0disease.'
 'MIld\xa0global\xa0atrophy.' 'Normal\xa0MRI\xa0of\xa0the\xa0brain. '
 'Mild WM hyperintensities, PVWM/deep WM, Otherwise, unremarkable '
 'Normal MRI of the brain. ' 'Within normal limit. '
 'Mild small vessel disease, Mild to moderate stenosis at right distal M1 '
 'Mild small vessel disease, Normal finding of brain MRA '
 'Mild WM hyperintensities, Normal finding of brain MRI, MRA '
 'Moderate WM hyperintensities, PVWM/deep WM, Normal finding of brain MRA'
 '(결과 전화함)Moderate small vessel disease. Mild brain atrophy. '
 '(결과 전화함-진료요청) Mild small vessel disease. Ddx junctaional dilatation > aneurysm, bilateral distal ICAs.'
 '(결과 전화함)Within normal limits. '
 '(결과 전화함)Mild small vessel disease. Right mastoiditis. '
 '(결과 전화함)Moderate small vessel disease. '
 '(결과 전화함)Mild brain atrophy. Mild small vessel disease. '
 '(결과 전화함)Within\xa0normal\xa0limits '
 '(결과 전화함-진료요청) Moderate small vessel disease'
 '(결과 전화함-진료요청) Mild small vessel disease. Ddx aneurysm vs junctional dilatation, right distal ICA'
 '(결과 전화함)Moderate\xa0brain\xa0atrophy. '
 '(결과 전화함-진료요청)Mild small vessel disease'
 '(결과 전화함-진료요청)Moderate\xa0small\xa0vessel\xa0disease'
 '(결과 전화함-진료요청) Moderate small vessel disease. Segmental severe stenosis, ,left M1. '
 '(결과 전화함)Moderate\xa0small\xa0vessel\xa0disease'
 '(결과 전화함-진료요청)Mild\xa0leukoaraiosis\xa0in\xa0bilateral\xa0cerebral\xa0subcortical\xa0white\xa0matter. Mild\xa0stenosis,\xa0right\xa0P2. '
 'Left ICA hypophyseal aneurysm, REC) cerebral angiography '
 'Chronic\xa0lacune\xa0at\xa0left\xa0frontal\xa0corona\xa0radiata                        Moderate WM hyperintensities Normal finding of brain MRA '
 'Descending colon cancer. Normal finding of brain MRI                                Left ICA, superior hypophyseal aneurysm (3mm)'
 'Normal finding of brain MRI. R/O ACoA aneurysm, 2mm'
 'normal finding of brain MRI. Occlusion of right ICA. Left ICA dorsal wall aneurysm.REC) cerebral angiography '
 'Mild WM hyperintensitie. Moderate medial temporal atrophy. Normal finding of brain MRA'
 'Moderate WM hyperintensities. Normal finding of brain MRA '
 'Within normal limit'
 'Within normal limit. Microbleed at left occipital lobe '
 'Mild WM hyperintensities, PVWM. Microbleed at Rt superior frontal gyrus\nNormal finding of brain MRA '
 'Mild global atrophy. Mild WM hyperintensities, PVWM. Normal finding of brain MRA. Enlarged ventricle and atrophy at bilateral hippocampi'
 'Mild small vessel disease.\nVuno: WNL ' 'Mild small vessel disease. '
 'Within normal limits of brain parenchyma.\nMild stenosis, left V4.'
 'Mild small vessel disease.\nVuno volumetric report: atrophy at right hippocampus. ']
----------------------------------------
Col name: TIV
Data type: float64
Unique values: 70
[1447.28397916           nan 1260.32824748 1492.92206163 1648.67403107
 1571.03098202 1424.53780276 1576.7736909  1444.45291448 1592.8144484
 1279.17874045 1338.41291045 1509.89081619 1259.32142525 1205.87212794
 1433.05542167 1601.02997959 1442.43223506 1334.63701233 1617.28391518
 1501.00816084 1351.69847878 1242.52438102 1520.36372943 1162.6828975
 1471.07028413 1413.43440971 1271.74987035 1495.39192315 1271.28004723
 1505.42777156 1392.61409605 1394.07176402 1400.32071168 1599.48630852
 1435.93661645 1313.28840422 1271.58858323 1429.03022293 1336.08256294
 1537.02813023 1448.85865469 1307.37650856 1208.47990065 1317.25642501
 1401.21597529 1325.99035296 1378.11633469 1358.46877315 1506.84040172
 1258.11431492 1595.84151546 1553.44844324 1210.95173074 1672.20452099
 1671.79095428 1344.11536942 1237.56966654 1604.50997263 1264.01023226
 1273.87382166 1317.43954639 1373.31689214 1447.19837052 1387.04764883
 1187.52343011 1377.38205637 1236.32161755 1689.67483971 1472.81496733]
----------------------------------------
Col name: global GMV
Data type: float64
Unique values: 70
[546.97666864          nan 524.85261719 576.77272773 618.6940494
 623.47989563 548.55524203 639.27492736 545.31834834 584.66644824
 519.2036609  535.63801596 571.78697133 511.20647963 521.58027546
 563.90862222 608.09534038 616.47157627 533.1266191  628.62412804
 603.07208784 534.36468714 507.41702058 626.33048008 484.02431352
 596.38385287 587.81814285 515.48670791 517.29520886 530.19805005
 548.57895474 565.13133401 570.04822665 524.26674578 604.43415428
 512.9737294  514.59407087 486.83682462 533.56332836 503.18363814
 554.33607037 522.9826558  497.15268746 476.20116989 539.64086548
 505.12075703 515.32544859 465.46791418 531.4914773  559.70460389
 455.77903249 635.19438013 632.01784318 497.18343914 621.39233513
 628.10622065 532.47306662 492.4059232  565.90687822 474.07886308
 537.07868879 428.99918172 476.67962165 562.69606741 511.80966401
 506.70717985 465.91736912 509.17071172 592.58817975 552.71846273]
----------------------------------------
Col name: global WMV
Data type: float64
Unique values: 70
[501.94249233          nan 475.17746464 501.10409369 478.79283533
 563.68824564 446.33426989 568.33300559 520.08907761 503.09816472
 430.15005035 428.35035472 434.73891921 437.63511758 408.38401899
 523.05883493 571.99701261 535.4452697  488.67391228 602.69465912
 497.36926149 387.41519955 441.18396606 507.22034776 345.10708391
 501.88139087 488.29330781 381.85923011 416.92910342 392.19384073
 519.93222483 505.18580143 501.34883742 490.01124693 452.43763338
 440.54470643 406.09587246 432.49329116 371.86946962 426.41948629
 487.41270988 394.88917819 404.39175955 376.02208665 432.23885551
 443.83015642 403.28816983 405.49585138 421.17151889 431.68521107
 425.70678876 515.36246372 536.87178043 362.77482983 531.85594385
 552.57173487 428.66323974 389.62392777 530.99889663 439.42268965
 413.34997056 363.27348556 414.87964491 453.18875104 401.52374778
 387.99348978 411.32769848 415.63341621 553.65947102 455.53155246]
----------------------------------------
Col name: global CSFV
Data type: float64
Unique values: 70
[396.97433976          nan 259.66698138 412.71102064 547.50934627
 380.83241727 429.64829084 367.43466382 376.32334734 498.00921539
 329.82502919 374.42453977 503.36492565 309.00075358 274.67111195
 346.08796452 418.42598722 289.34265177 310.31275171 382.11571258
 399.41113309 428.83438816 292.70663752 384.21108175 332.93750009
 366.7280603  337.32295905 373.6575402  557.77324239 347.29606241
 429.16764676 321.04775671 321.81295097 386.04271897 538.30720334
 478.48988261 390.75904524 337.77426742 523.59742495 406.4794385
 495.27934998 530.9868207  405.83206155 356.25664411 345.37670402
 452.26506184 407.37673454 507.15256913 405.80577696 515.45058676
 376.62849368 445.28467162 384.55881963 350.99346177 518.95624201
 491.11299875 382.97906306 355.53981556 507.60419779 350.50867953
 323.4451623  525.16687911 481.75762559 431.31355207 473.71423705
 292.82276047 500.13698877 311.51748962 543.42718895 464.56495214]
----------------------------------------
Col name: MR_3DT1_TFE
Data type: object
Unique values: 2
['O' nan]
----------------------------------------
Col name: MR_3DGRASE_MWI
Data type: object
Unique values: 2
['O' nan]
----------------------------------------
Col name: MR_3DGRASE_REF
Data type: object
Unique values: 2
['O' nan]
----------------------------------------
Col name: MREPT_TSE
Data type: object
Unique values: 2
['O' nan]
----------------------------------------
Col name: NODDI
Data type: object
Unique values: 3
['NODDI32' nan 'DKI']
----------------------------------------
Col name: MREPT_3DbFFE
Data type: object
Unique values: 2
['x' nan]
----------------------------------------
Col name: SWI
Data type: object
Unique values: 3
['O' nan "'X'"]
----------------------------------------
Col name: T2_OBL_COR
Data type: object
Unique values: 3
['O' nan "'X'"]
----------------------------------------
Col name: FLAIR
Data type: object
Unique values: 3
['O' nan "'X'"]
----------------------------------------
Col name: MWF
Data type: object
Unique values: 2
['O' nan]
----------------------------------------
Col name: VOLUME
Data type: object
Unique values: 2
['O' nan]
----------------------------------------
Col name: HFC
Data type: object
Unique values: 2
['O' nan]
----------------------------------------
Col name: LFC(EC,IC)
Data type: object
Unique values: 3
['O' nan "'X'"]
----------------------------------------
Col name: SMT(ED,ID)
Data type: object
Unique values: 3
['O' nan "'X'"]
----------------------------------------
Col name: IVF,EIC
Data type: object
Unique values: 3
['O' nan "'X'"]
----------------------------------------

In [20]:
with pd.ExcelWriter(os.path.join(b2_, "sorted(0723_8641_fin_Conductivity).xlsx")
                    , engine="xlsxwriter") as writer:
    b2CN.to_excel(writer, sheet_name="CN", index=False)
    b2AD.to_excel(writer, sheet_name="Dementia", index=False)

In [22]:
b2f = os.path.join(b2_, "sorted(0723_8641_fin_Conductivity).xlsx")

b2AD = pd.read_excel(b2f, sheet_name="Dementia", dtype={"PID": str})
print(b2AD)

b2CN = pd.read_excel(b2f, sheet_name="CN", dtype={"PID": str})
print(b2CN)

    건대분석정보                 인원                Origin Code            Code  \
0      Yes                NaN              MREPT2019AD01  AD2019_BrMRA01
1      Yes                NaN              MREPT2019AD02  AD2019_BrMRA02
2      Yes                탈락               MREPT2019AD03  AD2019_BrMRA03
3      Yes                NaN              MREPT2019AD04  AD2019_BrMRA04
4      Yes                NaN              MREPT2019AD05  AD2019_BrMRA05
..     ...                ...                        ...             ...
269    Yes                NaN  MREPT2020AD24_YYS_NODDI32   MREPT2020AD24
270    Yes                NaN  MREPT2020AD25_YSJ_NODDI32   MREPT2020AD25
271    Yes                NaN  MREPT2020AD26_HMH_NODDI32   MREPT2020AD26
272    Yes  탈락-venous anomaly  MREPT2020AD27_YJJ_NODDI32   MREPT2020AD27
273    Yes                NaN  MREPT2020AD28_YYL_NODDI32   MREPT2020AD28

         PID   Age Sex Education(Year)  \
0    3735478  70.0   F              14
1    4381137  68.0   F              13
2    4452316  67.0   F               9
3    4681566  66.0   M              12
4    7205823  77.0   F               6
..       ...   ...  ..             ...
269  8700631  60.0   F               6
270  8655418  76.0   F               9
271  8655425  77.0   M               6
272   577752  71.0   F             NaN
273  5533209  80.0   F               0

                                   Clinical Info(진료교수)  \
0                                            HTN mdMCI
1                         HTN, 고지혈증, ICAaneurysm aMCI
2            (조아랑) mild NCD(amnestic type), depression
3                         subjective cognitive decline
4                                       mild SVD aMCI
..                                                 ...
269  조아랑 Alzheimer's dementia, early onset, depression
270                                       amnestic MCI
271             DM, HTN 고지혈증, 이학영 multiple domain aMCI
272  depressive, 이학영 multiple domain non-amnestic MCI
273               조아랑 Alzheimer's dementia, late onset

                                          최종진단 DDX  ...  global WMV  \
0                             multiple domain aMCI  ...  431.903364
1                                             aMCI  ...  485.314945
2              mild NCD(amnestic type), depression  ...  404.586605
3                     subjective cognitive decline  ...  524.819073
4                                             aMCI  ...  414.490405
..                                             ...  ...         ...
269  Alzheimer's dementia, early onset, depression  ...  336.016348
270                                           aMCI  ...  341.371124
271                           multiple domain aMCI  ...  454.385693
272                mutiple domain non-amnestic MCI  ...  487.814184
273               Alzheimer's dementia, late onset  ...  353.353720

    global CSFV  MR_3DT1_TFE  MR_3DGRASE_MWI  MR_3DGRASE_REF MREPT_TSE  \
0    427.441118            O               O               O         O
1    315.153808            O               O               O         O
2    308.493634            O               O               O         O
3    337.671219            O               O               O         O
4    382.888115            O               O               O         O
..          ...          ...             ...             ...       ...
269  460.074360            O               O               O         O
270  402.802737            O               O               O         O
271  512.686386            O               O               O         O
272  468.901713            O               O               O         O
273  485.691918            O               O               O         O

       NODDI MREPT_3DbFFE                                      final ddx  \
0    NODDI32            X                           multiple domain aMCI
1    NODDI32            X                                   amnestic MCI
2    NODDI32            X            mild NCD(amnestic type), depression
3    NODDI32            X                   subjective cognitive decline
4    NODDI32            X                                   amnestic MCI
..       ...          ...                                            ...
269  NODDI32            X  Alzheimer's dementia, early onset, depression
270  NODDI32            X                                   amnestic MCI
271  NODDI32            X                   multiple domain amnestic MCI
272  NODDI32            X                mutiple domain non-amnestic MCI
273  NODDI32            X               Alzheimer's dementia, late onset

               논문사용
0           mdMCI03
1    HFC,LFC,MWI 사용
2               HFC
3               HFC
4    HFC,LFC,MWI 사용
..              ...
269       HFC,LFC사용
270             NaN
271             NaN
272             NaN
273       HFC,LFC사용

[274 rows x 32 columns]
   건대분석정보  인원  미수코드     AD_MWI_Code              논문사용      PID  Age Sex  \
0     Yes   1  8641        MWI_CN01         HFC,LFC사용   145616   70   F
1     Yes   2  8641        MWI_CN04            HFC 사용  2716077   62   F
2     Yes   3  8641        MWI_CN05         HFC,LFC사용   469852   72   M
3     Yes   4  8641        MWI_CN06         HFC,LFC사용  2296061   72   M
4     Yes   5  8641        MWI_CN07            HFC 사용   316024   66   M
..    ...  ..   ...             ...               ...      ...  ...  ..
64    Yes  14  8641  MWI_CN71(ver2)  newMWI_CN 27명 추가   863315   73   F
65    Yes  15  8641  MWI_CN73(ver2)  newMWI_CN 27명 추가  4074843   74   F
66    Yes  16  8641  MWI_CN74(ver2)  newMWI_CN 27명 추가  9605724   71   F
67    Yes  17  8641  MWI_CN75(ver2)  newMWI_CN 27명 추가  9605754   73   M
68     No  18  8641  MWI_CN76(ver2)               NaN   359871   78   F

   Education (Year)             Screen fail/Drop 이유  ... MREPT_3DbFFE SWI  \
0                16                      Control 모집  ...            x   O
1                12                      Control 모집  ...            x   O
2                16                      Control 모집  ...            x   O
3                 6                      Control 모집  ...            x   O
4                 9                      Control 모집  ...            x   O
..              ...                             ...  ...          ...  ..
64              NaN                      Control 모집  ...            x   O
65               무학     이학영교수 Control 모집(SNSB, MRI)  ...            x   O
66              NaN                      Control 모집  ...            x   O
67              NaN                      Control 모집  ...            x   O
68              NaN                      Control 모집  ...            x   O

   T2_OBL_COR  FLAIR  MWF  VOLUME  HFC LFC(EC,IC) SMT(ED,ID) IVF,EIC
0           O      O    O       O    O          O          O       O
1           O      O    O       O    O          O          O       O
2           O      O    O       O    O          O          O       O
3           O      O    O       O    O          O          O       O
4           O      O    O       O    O          O          O       O
..        ...    ...  ...     ...  ...        ...        ...     ...
64          O      O    O       O    O          O          O       O
65          O      O    O       O    O          O          O       O
66          O      O    O       O    O          O          O       O
67          O      O    O       O    O          O          O       O
68          O      O    O       O    O          O          O       O

[69 rows x 41 columns]

In [23]:
# Find duplicate PIDs
b1AD['PID'].replace('nan', pd.NA, inplace=True)
b1AD = b1AD.dropna(subset=['PID'])
b1AD = b1AD[b1AD['PID'].str.lower() != 'nan']
b1AD = b1AD[b1AD['PID'].notna()]

dup_counts_AD = b1AD['PID'].value_counts()
dup_AD = dup_counts_AD[dup_counts_AD > 1]
print("b1AD: Duplicated PID / n :")
print(dup_AD)
# dup_mask_AD = b1AD['PID'].duplicated(keep=False)
# if dup_mask_AD.any():
#     print("\nb1AD: Duplicated PID rows:")
#     print(b1AD[dup_mask_AD])
#     b1AD = b1AD.drop_duplicates(subset=['PID'], keep='first')
#     print("\nb1AD: After dropping duplicates, remaining PID counts:")
#     print(b1AD['PID'].value_counts()[b1AD['PID'].value_counts() == 1])

print('-'*80)
dup_counts_CN = b1CN['PID'].value_counts()
dup_CN = dup_counts_CN[dup_counts_CN > 1]
print("\nb2AD: Duplicated PID / n :")
print(dup_CN)

b1AD: Duplicated PID / n :
Series([], Name: count, dtype: int64)
--------------------------------------------------------------------------------

b2AD: Duplicated PID / n :
Series([], Name: count, dtype: int64)

In [24]:
for df in (b2AD, b2CN):
    df['PID'] = (
        df['PID']                       # 기존 값
          .astype(str)                  # 문자열 변환
          .str.replace(r'\D+', '', regex=True)  # 숫자 외 제거
          .str.zfill(8)                 # 8자리로 왼쪽 0-패딩
          .replace('00000000', pd.NA)   # 무의미한 전부 0 → 결측 처리
    )
print(b2AD, '\n', '-'*80, '\n', b2CN)

    건대분석정보                 인원                Origin Code            Code  \
0      Yes                NaN              MREPT2019AD01  AD2019_BrMRA01
1      Yes                NaN              MREPT2019AD02  AD2019_BrMRA02
2      Yes                탈락               MREPT2019AD03  AD2019_BrMRA03
3      Yes                NaN              MREPT2019AD04  AD2019_BrMRA04
4      Yes                NaN              MREPT2019AD05  AD2019_BrMRA05
..     ...                ...                        ...             ...
269    Yes                NaN  MREPT2020AD24_YYS_NODDI32   MREPT2020AD24
270    Yes                NaN  MREPT2020AD25_YSJ_NODDI32   MREPT2020AD25
271    Yes                NaN  MREPT2020AD26_HMH_NODDI32   MREPT2020AD26
272    Yes  탈락-venous anomaly  MREPT2020AD27_YJJ_NODDI32   MREPT2020AD27
273    Yes                NaN  MREPT2020AD28_YYL_NODDI32   MREPT2020AD28

          PID   Age Sex Education(Year)  \
0    03735478  70.0   F              14
1    04381137  68.0   F              13
2    04452316  67.0   F               9
3    04681566  66.0   M              12
4    07205823  77.0   F               6
..        ...   ...  ..             ...
269  08700631  60.0   F               6
270  08655418  76.0   F               9
271  08655425  77.0   M               6
272  00577752  71.0   F             NaN
273  05533209  80.0   F               0

                                   Clinical Info(진료교수)  \
0                                            HTN mdMCI
1                         HTN, 고지혈증, ICAaneurysm aMCI
2            (조아랑) mild NCD(amnestic type), depression
3                         subjective cognitive decline
4                                       mild SVD aMCI
..                                                 ...
269  조아랑 Alzheimer's dementia, early onset, depression
270                                       amnestic MCI
271             DM, HTN 고지혈증, 이학영 multiple domain aMCI
272  depressive, 이학영 multiple domain non-amnestic MCI
273               조아랑 Alzheimer's dementia, late onset

                                          최종진단 DDX  ...  global WMV  \
0                             multiple domain aMCI  ...  431.903364
1                                             aMCI  ...  485.314945
2              mild NCD(amnestic type), depression  ...  404.586605
3                     subjective cognitive decline  ...  524.819073
4                                             aMCI  ...  414.490405
..                                             ...  ...         ...
269  Alzheimer's dementia, early onset, depression  ...  336.016348
270                                           aMCI  ...  341.371124
271                           multiple domain aMCI  ...  454.385693
272                mutiple domain non-amnestic MCI  ...  487.814184
273               Alzheimer's dementia, late onset  ...  353.353720

    global CSFV  MR_3DT1_TFE  MR_3DGRASE_MWI  MR_3DGRASE_REF MREPT_TSE  \
0    427.441118            O               O               O         O
1    315.153808            O               O               O         O
2    308.493634            O               O               O         O
3    337.671219            O               O               O         O
4    382.888115            O               O               O         O
..          ...          ...             ...             ...       ...
269  460.074360            O               O               O         O
270  402.802737            O               O               O         O
271  512.686386            O               O               O         O
272  468.901713            O               O               O         O
273  485.691918            O               O               O         O

       NODDI MREPT_3DbFFE                                      final ddx  \
0    NODDI32            X                           multiple domain aMCI
1    NODDI32            X                                   amnestic MCI
2    NODDI32            X            mild NCD(amnestic type), depression
3    NODDI32            X                   subjective cognitive decline
4    NODDI32            X                                   amnestic MCI
..       ...          ...                                            ...
269  NODDI32            X  Alzheimer's dementia, early onset, depression
270  NODDI32            X                                   amnestic MCI
271  NODDI32            X                   multiple domain amnestic MCI
272  NODDI32            X                mutiple domain non-amnestic MCI
273  NODDI32            X               Alzheimer's dementia, late onset

               논문사용
0           mdMCI03
1    HFC,LFC,MWI 사용
2               HFC
3               HFC
4    HFC,LFC,MWI 사용
..              ...
269       HFC,LFC사용
270             NaN
271             NaN
272             NaN
273       HFC,LFC사용

[274 rows x 32 columns]
 --------------------------------------------------------------------------------
    건대분석정보  인원  미수코드     AD_MWI_Code              논문사용       PID  Age Sex  \
0     Yes   1  8641        MWI_CN01         HFC,LFC사용  00145616   70   F
1     Yes   2  8641        MWI_CN04            HFC 사용  02716077   62   F
2     Yes   3  8641        MWI_CN05         HFC,LFC사용  00469852   72   M
3     Yes   4  8641        MWI_CN06         HFC,LFC사용  02296061   72   M
4     Yes   5  8641        MWI_CN07            HFC 사용  00316024   66   M
..    ...  ..   ...             ...               ...       ...  ...  ..
64    Yes  14  8641  MWI_CN71(ver2)  newMWI_CN 27명 추가  00863315   73   F
65    Yes  15  8641  MWI_CN73(ver2)  newMWI_CN 27명 추가  04074843   74   F
66    Yes  16  8641  MWI_CN74(ver2)  newMWI_CN 27명 추가  09605724   71   F
67    Yes  17  8641  MWI_CN75(ver2)  newMWI_CN 27명 추가  09605754   73   M
68     No  18  8641  MWI_CN76(ver2)               NaN  00359871   78   F

   Education (Year)             Screen fail/Drop 이유  ... MREPT_3DbFFE SWI  \
0                16                      Control 모집  ...            x   O
1                12                      Control 모집  ...            x   O
2                16                      Control 모집  ...            x   O
3                 6                      Control 모집  ...            x   O
4                 9                      Control 모집  ...            x   O
..              ...                             ...  ...          ...  ..
64              NaN                      Control 모집  ...            x   O
65               무학     이학영교수 Control 모집(SNSB, MRI)  ...            x   O
66              NaN                      Control 모집  ...            x   O
67              NaN                      Control 모집  ...            x   O
68              NaN                      Control 모집  ...            x   O

   T2_OBL_COR  FLAIR  MWF  VOLUME  HFC LFC(EC,IC) SMT(ED,ID) IVF,EIC
0           O      O    O       O    O          O          O       O
1           O      O    O       O    O          O          O       O
2           O      O    O       O    O          O          O       O
3           O      O    O       O    O          O          O       O
4           O      O    O       O    O          O          O       O
..        ...    ...  ...     ...  ...        ...        ...     ...
64          O      O    O       O    O          O          O       O
65          O      O    O       O    O          O          O       O
66          O      O    O       O    O          O          O       O
67          O      O    O       O    O          O          O       O
68          O      O    O       O    O          O          O       O

[69 rows x 41 columns]

In [25]:
def merge_pipeline(b1df, b2df):
    # key column to --> idx
    b1df = b1df.set_index('PID')
    b2df = b2df.set_index('PID')

    # Col mapping
    mapping = {
        'Age': 'Age',
        'Gender': 'Sex',
        'MMSE': 'MMSE',
        'TIV': 'TIV',
        'global GMV': 'global GMV',
        'global WMV': 'global WMV',
        'global CSFV': 'global CSFV',
        'DDX': '최종진단 DDX'
    }
    for tgt, src in mapping.items():
        b1df[tgt] = b2df[src]

    # Column init
    b1df['Group'] = ''

    # col 'Sex' (col 'Gender' → F:0 / M:1)
    b1df['sex'] = b1df['Gender'].map({'F': 0, 'M': 1})

    # Add cols (only exists in DF 'b2*')
    extras = ['CDR', 'CDRSB', 'GDS', 'Barthel A DL', 'Instrumental A DL', 'SGDS', 'NPI']
    for col in extras:
        b1df[col] = b2df.get(col)

    # Cols sorting: insert col 'extras' behind col 'MMSE'
    cols = list(b1df.columns)
    for col in extras:
        cols.remove(col)
    insert_at = cols.index('MMSE') + 1
    for col in reversed(extras):
        cols.insert(insert_at, col)
    b1df = b1df[cols]

    # Reset idx
    return b1df.reset_index()

In [26]:
b1AD = merge_pipeline(b1AD, b2AD)
b1CN = merge_pipeline(b1CN, b2CN)

In [27]:
print("b2CN columns:")
print(b2CN.columns.tolist())

b2CN columns:
['건대분석정보', '인원', '미수코드', 'AD_MWI_Code', '논문사용', 'PID', 'Age', 'Sex', 'Education (Year)', 'Screen fail/Drop 이유', '임상정보 추가', '최종진단 DDX', 'SNSB StudyDate', 'MMSE', 'CDR', 'CDRSB', 'GDS', 'Barthel A DL', 'Instrumental A DL', 'NPI', 'MRI StudyDate', 'MRI판독 conclusion', 'TIV', 'global GMV', 'global WMV', 'global CSFV', 'MR_3DT1_TFE', 'MR_3DGRASE_MWI', 'MR_3DGRASE_REF', 'MREPT_TSE', 'NODDI', 'MREPT_3DbFFE', 'SWI', 'T2_OBL_COR', 'FLAIR', 'MWF', 'VOLUME', 'HFC', 'LFC(EC,IC)', 'SMT(ED,ID)', 'IVF,EIC']

In [28]:
b1AD

,PID,index,PDI,Year,LH-ALL_Dxx_proj,LH-ALL_Dyy_proj,LH-ALL_Dzz_proj,LH-ALL_Dxx_assoc,LH-ALL_Dyy_assoc,LH-ALL_Dzz_assoc,...,Hippocampus_ID_IVF,Insula_ID_IVF,Precuneus_SMT_ID_IVF,MTG_ID_IVF,ParaHippocampus_SMT_ID_IVF,Hippocampus_IVF,Insula IVF,Precuneus_IVF,MTG_IVF,ParaHippocampus_SMT_IVF
0,03735478,1,MREPT2019AD01_KMO_NODDI32,2019,0.644891,0.617538,1.173563,0.838976,1.092285,0.606418,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,04381137,2,MREPT2019AD02_JSJ_NODDI32,2019,0.711342,0.473727,1.183256,0.801073,1.124653,0.628264,...,0.002197,0.002015,0.001693,0.001687,0.002003,0.335837,0.359402,0.314762,0.33937,0.313549
2,04452316,3,MREPT2019AD03_OHS_NODDI32,2019,0.817484,0.701432,1.253393,0.921833,1.174945,0.667998,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,04681566,4,MREPT2019AD04_CSY_NODDI32,2019,0.636522,0.566616,1.020413,0.824179,0.994313,0.478768,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,07205823,5,MREPT2019AD05_KJI_NODDI32,2019,0.884875,0.763448,1.324970,1.043850,1.245618,0.718111,...,0.002079,0.001917,0.001859,0.001672,0.001945,0.307935,0.327340,0.249932,0.29929,0.277217
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
204,05212646,207,EPT2024AD09_CSO_NODDI32,2024,0.777790,0.751147,1.083035,0.980567,1.264496,0.673572,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
205,07295104,208,EPT2024AD10_KCJ_NODDI32,2024,0.703165,0.449837,1.133783,0.799426,1.147285,0.547185,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
206,07760856,209,EPT2024AD11_KHJ_NODDI32,2024,0.695299,0.652078,1.204808,0.964770,1.229719,0.694285,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
207,10130501,210,EPT2024AD12_LDS_NODDI32,2024,0.758654,0.879287,1.034725,1.054118,0.944798,0.616008,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
208,10466131,211,EPT2024AD13_LTO_NODDI32,2024,0.672885,0.600487,1.233325,0.774175,1.059713,0.615325,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [29]:
b1CN

,PID,index,PDI,Year,LH-ALL_Dxx_proj,LH-ALL_Dyy_proj,LH-ALL_Dzz_proj,LH-ALL_Dxx_assoc,LH-ALL_Dyy_assoc,LH-ALL_Dzz_assoc,...,Hippocampus_ID_IVF,Insula_ID_IVF,Precuneus_SMT_ID_IVF,MTG_ID_IVF,ParaHippocampus_SMT_ID_IVF,Hippocampus_IVF,Insula IVF,Precuneus_IVF,MTG_IVF,ParaHippocampus_SMT_IVF
0,00145616,1,MWI_CN01_KNH_NODDI32,2019.0,0.853582,0.731372,1.259900,1.086533,1.012292,0.845369,...,0.002063,0.001983,0.001745,0.001673,0.001914,0.317179,0.376434,0.259582,0.330822,0.288121
1,02716077,2,MWI_CN04_SSS_NODDI32,2019.0,0.721595,0.654347,1.212313,0.875281,1.239043,0.555101,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,00469852,3,MWI_CN05_LSS_NODDI32,2019.0,0.648850,0.534350,1.036836,0.781160,1.029860,0.513538,...,0.002116,0.001970,0.001867,0.001690,0.001977,0.305807,0.338011,0.245334,0.284724,0.287061
3,02296061,4,MWI_CN06_KDS_NODDI32,2019.0,0.776232,0.855603,0.955848,0.964658,0.958752,0.661455,...,0.002248,0.001914,0.001788,0.001664,0.002037,0.319215,0.319163,0.227113,0.280718,0.286061
4,00316024,5,MWI_CN07_KSB_NODDI32,2019.0,0.760503,0.692654,1.243302,0.877096,1.144913,0.597675,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,00080969,6,MWI_CN09_YKJ_NODDI32,2019.0,0.721305,0.585058,1.168966,0.807095,1.140908,0.511759,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,01147259,7,MWI_CN10_CJS_NODDI32,2019.0,0.766402,0.500861,1.051554,0.775147,0.896206,0.576431,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,05871888,8,MWI_CN12_LJK_NODDI32,2019.0,0.809517,0.506511,1.159348,1.022137,0.895856,0.680670,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,06476189,9,MWI_CN13_KH_NODDI32,2019.0,0.661128,0.740881,1.190856,0.836728,1.072988,0.530080,...,0.002145,0.001944,0.001746,0.001659,0.001970,0.281156,0.314280,0.293469,0.271209,0.277787
9,04341115,10,MWI_CN14_PYJ_NODDI32,2019.0,0.667318,0.716731,1.135098,0.797246,1.217310,0.580188,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,01607233,11,MWI_CN15_YCJ_NODDI32,2019.0,0.783634,0.542104,1.197984,0.810296,1.157182,0.503133,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11,01190888,12,MWI_CN16_LCS_NODDI32,2019.0,0.750492,0.767349,1.155198,1.084923,1.265144,0.825563,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12,04825611,13,MWI_CN17_LPS_NODDI32,2019.0,0.812866,0.996424,1.218665,0.992245,1.356309,0.826216,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13,02022033,14,MWI_CN18_HCS_NODDI32,2019.0,0.805717,0.608529,1.132986,0.879473,1.205904,0.698878,...,0.002139,0.002013,0.001861,0.001651,0.001956,0.342518,0.370684,0.284883,0.327972,0.310638
14,04073053,15,MWI_CN19_CSO_NODDI32,2019.0,0.637047,0.484846,1.023011,0.689319,1.038350,0.444999,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15,01382411,16,MWI_CN20_PYJ_NODDI32,2020.0,0.649847,0.728100,0.978214,0.746785,1.095501,0.367056,...,0.002253,0.002038,0.001868,0.001655,0.001978,0.325599,0.381604,0.292508,0.317153,0.285835
16,04086417,17,MWI_CN21_PYB_NODDI32,2020.0,89.345674,85.156431,85.893714,102.774043,97.815652,93.503079,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
17,00875397,18,MWI_CN22_YYJ_NODDI32,2020.0,0.771681,0.663884,0.996707,0.821504,1.230176,0.499316,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
18,08481071,19,MWI_CN23_HJL_NODDI32,2020.0,0.861621,0.685175,1.368943,0.848066,1.327288,0.593957,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
19,08481058,20,MWI_CN24_PKJ_NODDI32,2020.0,0.780769,0.805937,1.189413,0.871540,1.407582,0.637534,...,0.002059,0.001962,0.001960,0.001692,0.001936,0.323608,0.371669,0.278651,0.332182,0.297825
20,08500417,21,MWI_CN25_NKJ_NODDI32,2020.0,0.809053,0.628974,1.200095,0.822395,1.080473,0.504197,...,0.002259,0.002109,0.001881,0.001792,0.002085,0.324960,0.368734,0.278570,0.331214,0.303363
21,08510171,22,MWI_CN26_LSR_NODDI32,2020.0,0.651656,0.516872,1.081359,0.738009,1.078824,0.485794,...,0.002164,0.001990,0.001975,0.001699,0.001950,0.362811,0.395823,0.294354,0.352133,0.312945
22,08510155,23,MWI_CN27_LSJ_NODDI32,2020.0,0.785996,0.609021,1.140311,0.748307,1.253957,0.378579,...,0.002123,0.002064,0.001883,0.001675,0.001949,0.339940,0.397310,0.289435,0.338610,0.309178
23,00213101,24,MWI_CN28_KOS_NODDI32,2020.0,0.821979,0.734907,0.993994,0.937452,1.039852,0.579029,...,0.002254,0.001948,0.001789,0.001625,0.002063,0.336613,0.341983,0.259110,0.292436,0.304181
24,00243749,25,MWI_CN29_KSH_NODDI32,2020.0,0.652968,0.485778,1.078290,0.759060,0.934854,0.476488,...,0.002153,0.002000,0.001839,0.001616,0.001994,0.295477,0.346097,0.295710,0.294481,0.288724
25,08519137,26,MWI_CN30_PYS_NODDI32,2020.0,0.659945,0.500463,0.978506,0.804329,0.916356,0.433298,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
26,02528398,27,MWI_CN31_LOH_NODDI32,2020.0,0.636865,0.624176,1.164440,0.775352,1.091314,0.481007,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
27,08664289,28,MWI_CN32_KYH_NODDI32,2020.0,0.696205,0.723061,1.101509,0.903287,1.094731,0.498591,...,0.002178,0.002090,0.001929,0.001911,0.002091,0.303079,0.342878,0.241746,0.290830,0.290699
28,01206895,29,MWI_CN33_LSH_NODDI32,2020.0,0.638877,0.698796,1.098446,0.761060,1.133910,0.573942,...,0.002183,0.001977,0.001813,0.001699,0.002012,0.319583,0.370290,0.285611,0.332771,0.309487
29,04727886,30,MWI_CN34_OJS_NODDI32,2020.0,0.687721,0.524964,1.058712,0.874680,1.200491,0.539645,...,0.002315,0.002063,0.001980,0.001734,0.002176,0.301722,0.339289,0.294069,0.302767,0.296584
30,08696493,31,MWI_CN35_LES_NODDI32,2020.0,0.763828,0.533087,1.089920,0.853114,1.193487,0.427649,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
31,00738146,32,MWI_CN36_KER_NODDI32,2020.0,0.747137,0.516512,1.174375,0.878996,1.076370,0.520884,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
32,01283958,33,MWI_CN37_KJR_NODDI32,2020.0,1.267064,1.244017,1.117839,1.269628,1.258637,1.136036,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
33,02022042,34,MWI_CN38_JJB_NODDI32,2020.0,0.697029,0.773143,1.046729,0.801487,1.138984,0.510707,...,0.002176,0.001952,0.001814,0.001698,0.002075,0.266885,0.328058,0.234085,0.267591,0.255923
34,00613165,35,MWI_CN39_LTS_NODDI32,2020.0,0.676112,0.748491,1.064096,0.886808,1.172366,0.542684,...,0.002345,0.002043,0.001906,0.001770,0.002115,0.324565,0.350751,0.251041,0.304753,0.302692
35,08129675,36,MWI_CN40_LDS_NODDI32,2020.0,0.680826,0.595489,1.151737,0.856426,1.065426,0.673452,...,0.002382,0.002128,0.001953,0.001709,0.002240,0.356873,0.365843,0.262270,0.291764,0.337466
36,04920375,37,MWI_CN41_JHL_NODDI32,2020.0,0.730996,0.606768,1.137128,1.017152,1.050933,0.585597,...,0.002126,0.002086,0.001925,0.001709,0.001975,0.315960,0.331445,0.267208,0.317698,0.293759
37,08527223,38,MWI_CN57_YHY_NODDI32,2022.0,0.629832,0.574801,0.976331,0.773797,0.881921,0.454999,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
38,00213324,39,MWI_CN58_LSB_NODDI32,2022.0,0.707732,0.692642,1.101284,0.887895,1.048043,0.490397,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
39,01422655,40,MWI_CN61_CHS_NODDI32,2022.0,0.691838,0.513470,1.145116,0.671059,1.297181,0.547471,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
40,09524528,41,MWI_CN65_PYS_NODDI32,2022.0,0.742088,0.611022,1.156521,0.850296,1.222221,0.570590,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
41,00766581,42,MWI_CN66_CSY_NODDI32,2022.0,0.663827,0.725533,1.045238,0.839034,1.135543,0.602104,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
42,09577263,43,MWI_CN67_KOS_NODDI32,2022.0,0.625652,0.643337,1.160600,0.799541,1.107464,0.584152,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
43,00641619,44,MWI_CN68_CDL_NODDI32,2022.0,0.825319,0.661257,1.253624,1.041866,1.176894,0.762897,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
44,09588015,45,MWI_CN69_LSL_NODDI32,2022.0,0.567737,0.528092,1.266596,0.772384,1.072283,0.675864,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
45,02202449,46,MWI_CN70_LCJ_NODDI32,2022.0,0.771396,0.632500,1.171522,0.887840,1.099671,0.643634,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
46,00863315,47,MWI_CN71_LSH_NODDI32,2022.0,0.635816,0.511072,1.056698,0.825567,0.929914,0.456447,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
47,04074843,48,MWI_CN73_GIS_NODDI32,2022.0,0.614696,0.510977,1.052888,0.812034,1.064029,0.609057,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
48,09605724,49,MWI_CN74_LKY_NODDI32,2022.0,0.636038,0.581639,0.989334,0.811474,1.088186,0.491145,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
49,09605754,50,MWI_CN75_KKS_NODDI32,2022.0,0.839752,0.745258,1.373741,0.998471,1.189541,0.703382,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
50,00359871,51,MWI_CN76_PHJ_NODDI32,2022.0,0.974929,0.802987,1.458045,1.291569,1.189480,0.910831,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
51,07090169,52,MWI_CN77_PJC_NODDI32,NaN,0.666742,0.643739,1.125764,0.830681,1.076399,0.580091,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
52,10412739,53,MWI_CN79_CYE_NODDI32,NaN,0.753935,0.504262,1.198478,0.907089,1.106855,0.553258,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
53,10474812,54,MWI_CN80_LSR_NODDI32,NaN,0.602834,0.559894,1.037194,0.866400,1.013780,0.606750,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
54,10482577,55,MWI_CN81_CSH_NODDI32,NaN,0.638415,0.664246,1.101576,0.802995,1.033883,0.522940,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
55,10412747,56,MWI_CN82_LMR_NODDI32,NaN,0.789849,0.802365,1.201563,0.835766,1.131215,0.545787,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
56,10474783,57,MWI_CN83_LYS_NODDI32,NaN,0.572063,0.531833,1.064045,0.738442,0.933197,0.458701,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
57,10474798,58,MWI_CN84_LHS_NODDI32,NaN,0.647483,0.572705,1.053408,0.821964,1.005473,0.624160,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [30]:
with pd.ExcelWriter(os.path.join(b1, "0725_Auto_ALPS_index_19-24_mgd.xlsx")
                    , engine="xlsxwriter") as writer:
    b1CN.to_excel(writer, sheet_name="CN", index=False)
    b1AD.to_excel(writer, sheet_name="AD", index=False)

In [31]:
b1f = os.path.join(b1, "0725_Auto_ALPS_index_19-24_mgd.xlsx")
b1AD = pd.read_excel(b1f, sheet_name="AD", dtype={"PID": str})
b1AD["PID"] = b1AD["PID"].astype(str)
b1CN = pd.read_excel(b1f, sheet_name="CN", dtype={"PID": str})
b1CN["PID"] = b1CN["PID"].astype(str)
for df in (b1AD, b1CN):
    unnamed = [c for c in df.columns if c.startswith('Unnamed')]
    drop_cols = [c for c in unnamed if df[c].isnull().all()]
    df.drop(columns=drop_cols, inplace=True)
print(b1AD, '\n', '-'*80, '\n', b1CN)

           PID  index                        PDI  Year  LH-ALL_Dxx_proj  \
0     03735478      1  MREPT2019AD01_KMO_NODDI32  2019         0.644891
1     04381137      2  MREPT2019AD02_JSJ_NODDI32  2019         0.711342
2    04452316       3  MREPT2019AD03_OHS_NODDI32  2019         0.817484
3    04681566       4  MREPT2019AD04_CSY_NODDI32  2019         0.636522
4    07205823       5  MREPT2019AD05_KJI_NODDI32  2019         0.884875
..         ...    ...                        ...   ...              ...
204   05212646    207    EPT2024AD09_CSO_NODDI32  2024         0.777790
205   07295104    208    EPT2024AD10_KCJ_NODDI32  2024         0.703165
206   07760856    209    EPT2024AD11_KHJ_NODDI32  2024         0.695299
207   10130501    210    EPT2024AD12_LDS_NODDI32  2024         0.758654
208   10466131    211    EPT2024AD13_LTO_NODDI32  2024         0.672885

     LH-ALL_Dyy_proj  LH-ALL_Dzz_proj  LH-ALL_Dxx_assoc  LH-ALL_Dyy_assoc  \
0           0.617538         1.173563          0.838976          1.092285
1           0.473727         1.183256          0.801073          1.124653
2           0.701432         1.253393          0.921833          1.174945
3           0.566616         1.020413          0.824179          0.994313
4           0.763448         1.324970          1.043850          1.245618
..               ...              ...               ...               ...
204         0.751147         1.083035          0.980567          1.264496
205         0.449837         1.133783          0.799426          1.147285
206         0.652078         1.204808          0.964770          1.229719
207         0.879287         1.034725          1.054118          0.944798
208         0.600487         1.233325          0.774175          1.059713

     LH-ALL_Dzz_assoc  ...  Hippocampus_ID_IVF  Insula_ID_IVF  \
0            0.606418  ...                 NaN            NaN
1            0.628264  ...            0.002197       0.002015
2            0.667998  ...                 NaN            NaN
3            0.478768  ...                 NaN            NaN
4            0.718111  ...            0.002079       0.001917
..                ...  ...                 ...            ...
204          0.673572  ...                 NaN            NaN
205          0.547185  ...                 NaN            NaN
206          0.694285  ...                 NaN            NaN
207          0.616008  ...                 NaN            NaN
208          0.615325  ...                 NaN            NaN

     Precuneus_SMT_ID_IVF  MTG_ID_IVF  ParaHippocampus_SMT_ID_IVF  \
0                     NaN         NaN                         NaN
1                0.001693    0.001687                    0.002003
2                     NaN         NaN                         NaN
3                     NaN         NaN                         NaN
4                0.001859    0.001672                    0.001945
..                    ...         ...                         ...
204                   NaN         NaN                         NaN
205                   NaN         NaN                         NaN
206                   NaN         NaN                         NaN
207                   NaN         NaN                         NaN
208                   NaN         NaN                         NaN

     Hippocampus_IVF  Insula IVF  Precuneus_IVF  MTG_IVF  \
0                NaN         NaN            NaN      NaN
1           0.335837    0.359402       0.314762  0.33937
2                NaN         NaN            NaN      NaN
3                NaN         NaN            NaN      NaN
4           0.307935    0.327340       0.249932  0.29929
..               ...         ...            ...      ...
204              NaN         NaN            NaN      NaN
205              NaN         NaN            NaN      NaN
206              NaN         NaN            NaN      NaN
207              NaN         NaN            NaN      NaN
208              NaN         NaN            NaN      NaN

     ParaHippocampus_SMT_IVF
0                        NaN
1                   0.313549
2                        NaN
3                        NaN
4                   0.277217
..                       ...
204                      NaN
205                      NaN
206                      NaN
207                      NaN
208                      NaN

[209 rows x 113 columns]
 --------------------------------------------------------------------------------
           PID  index                   PDI    Year  LH-ALL_Dxx_proj  \
0   00145616       1  MWI_CN01_KNH_NODDI32  2019.0         0.853582
1    02716077      2  MWI_CN04_SSS_NODDI32  2019.0         0.721595
2    00469852      3  MWI_CN05_LSS_NODDI32  2019.0         0.648850
3    02296061      4  MWI_CN06_KDS_NODDI32  2019.0         0.776232
4    00316024      5  MWI_CN07_KSB_NODDI32  2019.0         0.760503
5    00080969      6  MWI_CN09_YKJ_NODDI32  2019.0         0.721305
6    01147259      7  MWI_CN10_CJS_NODDI32  2019.0         0.766402
7    05871888      8  MWI_CN12_LJK_NODDI32  2019.0         0.809517
8    06476189      9   MWI_CN13_KH_NODDI32  2019.0         0.661128
9    04341115     10  MWI_CN14_PYJ_NODDI32  2019.0         0.667318
10   01607233     11  MWI_CN15_YCJ_NODDI32  2019.0         0.783634
11   01190888     12  MWI_CN16_LCS_NODDI32  2019.0         0.750492
12  04825611      13  MWI_CN17_LPS_NODDI32  2019.0         0.812866
13  02022033      14  MWI_CN18_HCS_NODDI32  2019.0         0.805717
14  04073053      15  MWI_CN19_CSO_NODDI32  2019.0         0.637047
15   01382411     16  MWI_CN20_PYJ_NODDI32  2020.0         0.649847
16   04086417     17  MWI_CN21_PYB_NODDI32  2020.0        89.345674
17   00875397     18  MWI_CN22_YYJ_NODDI32  2020.0         0.771681
18   08481071     19  MWI_CN23_HJL_NODDI32  2020.0         0.861621
19   08481058     20  MWI_CN24_PKJ_NODDI32  2020.0         0.780769
20   08500417     21  MWI_CN25_NKJ_NODDI32  2020.0         0.809053
21   08510171     22  MWI_CN26_LSR_NODDI32  2020.0         0.651656
22   08510155     23  MWI_CN27_LSJ_NODDI32  2020.0         0.785996
23   00213101     24  MWI_CN28_KOS_NODDI32  2020.0         0.821979
24   00243749     25  MWI_CN29_KSH_NODDI32  2020.0         0.652968
25   08519137     26  MWI_CN30_PYS_NODDI32  2020.0         0.659945
26   02528398     27  MWI_CN31_LOH_NODDI32  2020.0         0.636865
27   08664289     28  MWI_CN32_KYH_NODDI32  2020.0         0.696205
28   01206895     29  MWI_CN33_LSH_NODDI32  2020.0         0.638877
29   04727886     30  MWI_CN34_OJS_NODDI32  2020.0         0.687721
30   08696493     31  MWI_CN35_LES_NODDI32  2020.0         0.763828
31   00738146     32  MWI_CN36_KER_NODDI32  2020.0         0.747137
32   01283958     33  MWI_CN37_KJR_NODDI32  2020.0         1.267064
33   02022042     34  MWI_CN38_JJB_NODDI32  2020.0         0.697029
34   00613165     35  MWI_CN39_LTS_NODDI32  2020.0         0.676112
35   08129675     36  MWI_CN40_LDS_NODDI32  2020.0         0.680826
36   04920375     37  MWI_CN41_JHL_NODDI32  2020.0         0.730996
37   08527223     38  MWI_CN57_YHY_NODDI32  2022.0         0.629832
38   00213324     39  MWI_CN58_LSB_NODDI32  2022.0         0.707732
39   01422655     40  MWI_CN61_CHS_NODDI32  2022.0         0.691838
40   09524528     41  MWI_CN65_PYS_NODDI32  2022.0         0.742088
41   00766581     42  MWI_CN66_CSY_NODDI32  2022.0         0.663827
42   09577263     43  MWI_CN67_KOS_NODDI32  2022.0         0.625652
43   00641619     44  MWI_CN68_CDL_NODDI32  2022.0         0.825319
44   09588015     45  MWI_CN69_LSL_NODDI32  2022.0         0.567737
45   02202449     46  MWI_CN70_LCJ_NODDI32  2022.0         0.771396
46   00863315     47  MWI_CN71_LSH_NODDI32  2022.0         0.635816
47   04074843     48  MWI_CN73_GIS_NODDI32  2022.0         0.614696
48   09605724     49  MWI_CN74_LKY_NODDI32  2022.0         0.636038
49   09605754     50  MWI_CN75_KKS_NODDI32  2022.0         0.839752
50   00359871     51  MWI_CN76_PHJ_NODDI32  2022.0         0.974929
51   07090169     52  MWI_CN77_PJC_NODDI32     NaN         0.666742
52   10412739     53  MWI_CN79_CYE_NODDI32     NaN         0.753935
53   10474812     54  MWI_CN80_LSR_NODDI32     NaN         0.602834
54   10482577     55  MWI_CN81_CSH_NODDI32     NaN         0.638415
55   10412747     56  MWI_CN82_LMR_NODDI32     NaN         0.789849
56   10474783     57  MWI_CN83_LYS_NODDI32     NaN         0.572063
57   10474798     58  MWI_CN84_LHS_NODDI32     NaN         0.647483

    LH-ALL_Dyy_proj  LH-ALL_Dzz_proj  LH-ALL_Dxx_assoc  LH-ALL_Dyy_assoc  \
0          0.731372         1.259900          1.086533          1.012292
1          0.654347         1.212313          0.875281          1.239043
2          0.534350         1.036836          0.781160          1.029860
3          0.855603         0.955848          0.964658          0.958752
4          0.692654         1.243302          0.877096          1.144913
5          0.585058         1.168966          0.807095          1.140908
6          0.500861         1.051554          0.775147          0.896206
7          0.506511         1.159348          1.022137          0.895856
8          0.740881         1.190856          0.836728          1.072988
9          0.716731         1.135098          0.797246          1.217310
10         0.542104         1.197984          0.810296          1.157182
11         0.767349         1.155198          1.084923          1.265144
12         0.996424         1.218665          0.992245          1.356309
13         0.608529         1.132986          0.879473          1.205904
14         0.484846         1.023011          0.689319          1.038350
15         0.728100         0.978214          0.746785          1.095501
16        85.156431        85.893714        102.774043         97.815652
17         0.663884         0.996707          0.821504          1.230176
18         0.685175         1.368943          0.848066          1.327288
19         0.805937         1.189413          0.871540          1.407582
20         0.628974         1.200095          0.822395          1.080473
21         0.516872         1.081359          0.738009          1.078824
22         0.609021         1.140311          0.748307          1.253957
23         0.734907         0.993994          0.937452          1.039852
24         0.485778         1.078290          0.759060          0.934854
25         0.500463         0.978506          0.804329          0.916356
26         0.624176         1.164440          0.775352          1.091314
27         0.723061         1.101509          0.903287          1.094731
28         0.698796         1.098446          0.761060          1.133910
29         0.524964         1.058712          0.874680          1.200491
30         0.533087         1.089920          0.853114          1.193487
31         0.516512         1.174375          0.878996          1.076370
32         1.244017         1.117839          1.269628          1.258637
33         0.773143         1.046729          0.801487          1.138984
34         0.748491         1.064096          0.886808          1.172366
35         0.595489         1.151737          0.856426          1.065426
36         0.606768         1.137128          1.017152          1.050933
37         0.574801         0.976331          0.773797          0.881921
38         0.692642         1.101284          0.887895          1.048043
39         0.513470         1.145116          0.671059          1.297181
40         0.611022         1.156521          0.850296          1.222221
41         0.725533         1.045238          0.839034          1.135543
42         0.643337         1.160600          0.799541          1.107464
43         0.661257         1.253624          1.041866          1.176894
44         0.528092         1.266596          0.772384          1.072283
45         0.632500         1.171522          0.887840          1.099671
46         0.511072         1.056698          0.825567          0.929914
47         0.510977         1.052888          0.812034          1.064029
48         0.581639         0.989334          0.811474          1.088186
49         0.745258         1.373741          0.998471          1.189541
50         0.802987         1.458045          1.291569          1.189480
51         0.643739         1.125764          0.830681          1.076399
52         0.504262         1.198478          0.907089          1.106855
53         0.559894         1.037194          0.866400          1.013780
54         0.664246         1.101576          0.802995          1.033883
55         0.802365         1.201563          0.835766          1.131215
56         0.531833         1.064045          0.738442          0.933197
57         0.572705         1.053408          0.821964          1.005473

    LH-ALL_Dzz_assoc  ...  Hippocampus_ID_IVF  Insula_ID_IVF  \
0           0.845369  ...            0.002063       0.001983
1           0.555101  ...                 NaN            NaN
2           0.513538  ...            0.002116       0.001970
3           0.661455  ...            0.002248       0.001914
4           0.597675  ...                 NaN            NaN
5           0.511759  ...                 NaN            NaN
6           0.576431  ...                 NaN            NaN
7           0.680670  ...                 NaN            NaN
8           0.530080  ...            0.002145       0.001944
9           0.580188  ...                 NaN            NaN
10          0.503133  ...                 NaN            NaN
11          0.825563  ...                 NaN            NaN
12          0.826216  ...                 NaN            NaN
13          0.698878  ...            0.002139       0.002013
14          0.444999  ...                 NaN            NaN
15          0.367056  ...            0.002253       0.002038
16         93.503079  ...                 NaN            NaN
17          0.499316  ...                 NaN            NaN
18          0.593957  ...                 NaN            NaN
19          0.637534  ...            0.002059       0.001962
20          0.504197  ...            0.002259       0.002109
21          0.485794  ...            0.002164       0.001990
22          0.378579  ...            0.002123       0.002064
23          0.579029  ...            0.002254       0.001948
24          0.476488  ...            0.002153       0.002000
25          0.433298  ...                 NaN            NaN
26          0.481007  ...                 NaN            NaN
27          0.498591  ...            0.002178       0.002090
28          0.573942  ...            0.002183       0.001977
29          0.539645  ...            0.002315       0.002063
30          0.427649  ...                 NaN            NaN
31          0.520884  ...                 NaN            NaN
32          1.136036  ...                 NaN            NaN
33          0.510707  ...            0.002176       0.001952
34          0.542684  ...            0.002345       0.002043
35          0.673452  ...            0.002382       0.002128
36          0.585597  ...            0.002126       0.002086
37          0.454999  ...                 NaN            NaN
38          0.490397  ...                 NaN            NaN
39          0.547471  ...                 NaN            NaN
40          0.570590  ...                 NaN            NaN
41          0.602104  ...                 NaN            NaN
42          0.584152  ...                 NaN            NaN
43          0.762897  ...                 NaN            NaN
44          0.675864  ...                 NaN            NaN
45          0.643634  ...                 NaN            NaN
46          0.456447  ...                 NaN            NaN
47          0.609057  ...                 NaN            NaN
48          0.491145  ...                 NaN            NaN
49          0.703382  ...                 NaN            NaN
50          0.910831  ...                 NaN            NaN
51          0.580091  ...                 NaN            NaN
52          0.553258  ...                 NaN            NaN
53          0.606750  ...                 NaN            NaN
54          0.522940  ...                 NaN            NaN
55          0.545787  ...                 NaN            NaN
56          0.458701  ...                 NaN            NaN
57          0.624160  ...                 NaN            NaN

    Precuneus_SMT_ID_IVF  MTG_ID_IVF  ParaHippocampus_SMT_ID_IVF  \
0               0.001745    0.001673                    0.001914
1                    NaN         NaN                         NaN
2               0.001867    0.001690                    0.001977
3               0.001788    0.001664                    0.002037
4                    NaN         NaN                         NaN
5                    NaN         NaN                         NaN
6                    NaN         NaN                         NaN
7                    NaN         NaN                         NaN
8               0.001746    0.001659                    0.001970
9                    NaN         NaN                         NaN
10                   NaN         NaN                         NaN
11                   NaN         NaN                         NaN
12                   NaN         NaN                         NaN
13              0.001861    0.001651                    0.001956
14                   NaN         NaN                         NaN
15              0.001868    0.001655                    0.001978
16                   NaN         NaN                         NaN
17                   NaN         NaN                         NaN
18                   NaN         NaN                         NaN
19              0.001960    0.001692                    0.001936
20              0.001881    0.001792                    0.002085
21              0.001975    0.001699                    0.001950
22              0.001883    0.001675                    0.001949
23              0.001789    0.001625                    0.002063
24              0.001839    0.001616                    0.001994
25                   NaN         NaN                         NaN
26                   NaN         NaN                         NaN
27              0.001929    0.001911                    0.002091
28              0.001813    0.001699                    0.002012
29              0.001980    0.001734                    0.002176
30                   NaN         NaN                         NaN
31                   NaN         NaN                         NaN
32                   NaN         NaN                         NaN
33              0.001814    0.001698                    0.002075
34              0.001906    0.001770                    0.002115
35              0.001953    0.001709                    0.002240
36              0.001925    0.001709                    0.001975
37                   NaN         NaN                         NaN
38                   NaN         NaN                         NaN
39                   NaN         NaN                         NaN
40                   NaN         NaN                         NaN
41                   NaN         NaN                         NaN
42                   NaN         NaN                         NaN
43                   NaN         NaN                         NaN
44                   NaN         NaN                         NaN
45                   NaN         NaN                         NaN
46                   NaN         NaN                         NaN
47                   NaN         NaN                         NaN
48                   NaN         NaN                         NaN
49                   NaN         NaN                         NaN
50                   NaN         NaN                         NaN
51                   NaN         NaN                         NaN
52                   NaN         NaN                         NaN
53                   NaN         NaN                         NaN

In [34]:
df = b1AD[['DDX']]
for column in df.columns:
    print(f"Col name: {column}")
    print(f"Data type: {df[column].dtype}")
    print(f"Unique values: {len(df[column].unique())}")
    print(df[column].unique())
    print('-'*40)

Col name: DDX
Data type: object
Unique values: 75
['multiple domain aMCI' 'aMCI' nan 'mild AD' 'non-amnestid MCI' 'MCI'
 'aMCI ' 'r/o seizure' 'AD' 'severe AD' 'subcortical VaD'
 'non-amnestic MCI, multiple domain' 'cerebral infarction'
 'multiple domain aMCI, mild AD' 'r/o FTD' 'aMCI (early)'
 'possibly vascular congnitive impairment, not demented' 'depression'
 'non-amnestic MCI,  frontal dysfunction' 'SVD' 'AD with CVD' 'VCI'
 'non-amnestic MCI' 'NL' "Alzheimer's dementia, late onset"
 'vascular cognitive impairment, vacular cognitive impairment'
 'mild AD with CVD' 'in impulse control complaints of memory impairment'
 "Schizophrenia, unspecified, Alzheimer's dementia late onset"
 'possible depression' 'mutiple domain aMCI' 'DLB or PSP'
 "Alzheimer's dementia, early onset, depression"
 'mutiple domain non-amnestic MCI' 'ADD' 'amnestic MCI'
 "Alzheimer's disease dementia, mild degree "
 "Dementia in Alzheimer's disease with late onset "
 "Dementia in Alzheimer's disease with late onset\nDelusional disorder"
 'VD' 'VCI (ICH)' 'mild ADD' 'moderate ADD with CVD'
 'MCI, Recurrent depressive disorder, current episode mild' 'SNSB 시행 안함.'
 'multiple domain amnestic MCI' 'early AD' '이학영교수님 판독안함. 치매외 타질환 가능성 있음'
 'vascular cognitive impairment' 'multiple domain aMCI '
 'r/o central vertigo' '알츠하이머형 치매 CDR3' '알츠하이머형 치매 CDR2' 'r/o bvFTD'
 'drug-induced encephalopathy' 'tremor' 'PD'
 "Senile dementia, Alzheimer's type" 'brain tumor: meningioma' 'None AD 병'
 'amyloid PET (+), MCI d/t AD (SNSB 결과는 없음)'
 "Dementia in Alzheimer's dis., atypical or mixed type, depression"
 'MCI, panic dis.'
 "Dementia in Alzheimer's disease with late onset,\nDepression" '검사결과 없음.'
 'severe dementia, AD or AD with CVD;  traumatic SAH'
 'SNSB 검사없음 dementia r/o AD'
 'non-amnestid MCI + drug-induced encephalopathy'
 'mild AD (with positive amyloid PET)'
 "Dementia in Alzheimer's disease with late onset,\nDepressive disorder"
 "Dementia in Alzheimer's disease with late onset,\nAnxiety disorder"
 "Dementia in Alzheimer's disease, unspecified, depression" '검사결과 없음'
 'moderate AD (with positive amyloid PET)' 'MCI, depression']
----------------------------------------

In [38]:
PATTERNS = {
    'CN' : re.compile(r'\b(NL|normal\s*|cognitive\s*normal)\b', flags=re.I),

    'MCI': re.compile(
        r'\b('
        r'MCI|'                  # 단독 MCI
        r'aMCI|'                 # amnestic MCI
        r'non[-\s]?amnestic\s*MCI|' 
        r'multiple\s*domain\s*a?MCI|' 
        r'single\s*domain\s*a?MCI|' 
        r'mutiple\s*domain.*MCI'  # 오타 포함
        r')\b', flags=re.I),

    'AD' : re.compile(
        r'\b('
        r'AD\b|'                                     # AD
        r'Alzheimer|\bADD\b|'                        # Alzheimer variants
        r'알츠하이머형\s*치매|'
        r'dementia'                                  # any “dementia … AD”류
        r')', flags=re.I)
}

def classify_ddx(ddx):
    """Col 'DDX' values --> Col 'Group' CN / MCI / AD, Matching X --> None"""
    if not isinstance(ddx, str):
        return None
    for label, pat in PATTERNS.items():
        if pat.search(ddx):
            return label
    return None

for df in (b1AD, b1CN):
    df['Group'] = df['DDX'].apply(classify_ddx)
print(b1AD['Group'].value_counts(dropna=False))
print(b1CN['Group'].value_counts(dropna=False))

Group
MCI     82
None    74
AD      50
CN       3
Name: count, dtype: int64
Group
CN      28
MCI     19
None    11
Name: count, dtype: int64

In [40]:
df = b1CN[['Group']]
for column in df.columns:
    print(f"Col name: {column}")
    print(f"Data type: {df[column].dtype}")
    print(f"Unique values: {len(df[column].unique())}")
    print(df[column].unique())
    print('-'*40)

Col name: Group
Data type: object
Unique values: 3
[None 'CN' 'MCI']
----------------------------------------

In [41]:
with pd.ExcelWriter(os.path.join(b1, "0725_Auto_ALPS_index_19-24_mgd_M01.xlsx")
                    , engine="xlsxwriter") as writer:
    b1CN.to_excel(writer, sheet_name="CN", index=False)
    b1AD.to_excel(writer, sheet_name="AD", index=False)

In [42]:
SSD = r"E:\MR"
excel_fp = os.path.join(SSD, "Auto_ALPS_index_19-24_fin0728_M02.xlsx")

# ── 시트별 로드
dfCN = pd.read_excel(excel_fp, sheet_name="CN")
dfAD = pd.read_excel(excel_fp, sheet_name="Dementia")

print(dfCN.shape, dfAD.shape)

(58, 1094) (209, 1094)

In [43]:
rename_map = {
    'ROI1' : 'Conduct1(age+)_LH_Insula-Frontal',
    'ROI2' : 'Conduct2(age+)_RH_Insula-Frontal',
    'ROI3' : 'Conduct1(age-)_LH_MFG',
    'ROI4' : 'Conduct1(MMSE+)_RH_SFG',
    'ROI5' : 'Conduct1(MMSE-)_RH_PrecentralGyrus',
    'ROI6' : 'Conduct2(MMSE-)_LH_Insula-InferiorParietalLobule',
    'ROI7' : 'Conduct1(CN<MCI)_RH_LateralVentricleCSF',
    'ROI8' : 'Conduct2(CN<MCI)_LH_Caudate-CorpusCallosum',
    'ROI9' : 'Conduct1(CN>AD)_RH_SFG',
    'ROI10': 'Conduct1(CN<AD)_RH_LateralVentricleCSF',
    'ROI11': 'Conduct2(CN<AD)_Inter-Hemispheric'
}

roi_keys    = tuple(rename_map.keys())
roi_prefix  = tuple(rename_map.values())

def drop_roi_cols(df: pd.DataFrame) -> pd.DataFrame:
    """ROI1* / 새 prefix* 로 시작하는 컬럼을 삭제한 새 DataFrame 반환"""
    cols_to_drop = [
        c for c in df.columns
        if c.startswith(roi_keys) or c.startswith(roi_prefix)
    ]
    return df.drop(columns=cols_to_drop, errors="ignore")

# 2) 적용
dfCN = drop_roi_cols(dfCN)
dfAD = drop_roi_cols(dfAD)

print("After clean-up:", dfCN.shape, dfAD.shape)

After clean-up: (58, 203) (209, 203)

In [48]:
analyse_df(dfCN)

                            NaN Counts  NaN Ratio (%)  Unique Values
Unnamed: 0                           0       0.000000             58
PDI                                  0       0.000000             58
PID                                  0       0.000000             58
DDX                                  0       0.000000              5
Year                                 3       5.172414              5
Age                                  0       0.000000             22
sex                                  0       0.000000              2
Education_yr                        21      36.206897             10
LH-ALL_Dxx_proj                      0       0.000000             58
LH-ALL_Dyy_proj                      0       0.000000             58
LH-ALL_Dzz_proj                      0       0.000000             58
LH-ALL_Dxx_assoc                     0       0.000000             58
LH-ALL_Dyy_assoc                     0       0.000000             58
LH-ALL_Dzz_assoc                     0       0.000000             58
LH-ALL_ALPS index                    0       0.000000             58
LH-b800_Dxx_proj                     0       0.000000             58
LH-b800_Dyy_proj                     0       0.000000             58
LH-b800_Dzz_proj                     0       0.000000             58
LH-b800_Dxx_assoc                    0       0.000000             58
LH-b800_Dyy_assoc                    0       0.000000             58
LH-b800_Dzz_assoc                    0       0.000000             58
LH-b800_ALPS index                   0       0.000000             58
LH-b2000_Dxx_proj                    0       0.000000             58
LH-b2000_Dyy_proj                    0       0.000000             58
LH-b2000_Dzz_proj                    0       0.000000             58
LH-b2000_Dxx_assoc                   0       0.000000             58
LH-b2000_Dyy_assoc                   0       0.000000             58
LH-b2000_Dzz_assoc                   0       0.000000             58
LH-b2000_ALPS index                  0       0.000000             58
RH-ALL_Dxx_proj                      0       0.000000             58
RH-ALL_Dyy_proj                      0       0.000000             58
RH-ALL_Dzz_proj                      0       0.000000             58
RH-ALL_Dxx_assoc                     0       0.000000             58
RH-ALL_Dyy_assoc                     0       0.000000             58
RH-ALL_Dzz_assoc                     0       0.000000             58
RH-ALL_ALPS index                    0       0.000000             58
RH-b800_Dxx_proj                     0       0.000000             58
RH-b800_Dyy_proj                     0       0.000000             58
RH-b800_Dzz_proj                     0       0.000000             58
RH-b800_Dxx_assoc                    0       0.000000             58
RH-b800_Dyy_assoc                    0       0.000000             58
RH-b800_Dzz_assoc                    0       0.000000             58
RH-b800_ALPS index                   0       0.000000             58
RH-b2000_Dxx_proj                    0       0.000000             58
RH-b2000_Dyy_proj                    0       0.000000             58
RH-b2000_Dzz_proj                    0       0.000000             58
RH-b2000_Dxx_assoc                   0       0.000000             58
RH-b2000_Dyy_assoc                   0       0.000000             58
RH-b2000_Dzz_assoc                   0       0.000000             58
RH-b2000_ALPS index                  0       0.000000             58
MMSE                                 0       0.000000             11
TIV                                 17      29.310345             41
global GMV                          20      34.482759             38
global WMV                          20      34.482759             38
global CSFV                         20      34.482759             38
ChiQSM                               2       3.448276             56
CDR                                  0       0.000000              2
CDRSB                                0       0.000000              6
GDS                                  0       0.000000              3
Barthel A DL                         0       0.000000              1
Instrumental A DL                    0       0.000000             11
NPI                                 52      89.655172              3
SGDS                                48      82.758621              7
Hippocampus GMV                     39      67.241379             19
Insula GMV                          39      67.241379             19
Precuneus_GMV                       39      67.241379             19
MTG GMV                             39      67.241379             19
ParaHippocampus_GMV                 39      67.241379             19
Hippocampus WMV                     39      67.241379             19
Insula WMV                          39      67.241379             19
Precuneus_WMV                       39      67.241379             19
MTG_WMV                             39      67.241379             19
ParaHippocampus_WMV                 39      67.241379             19
Hippocampus CSF                     39      67.241379             19
Insula CSF                          39      67.241379             19
Precuneus_CSF                       39      67.241379             19
MTG_CSF                             39      67.241379             19
ParaHippocampus_CSF                 39      67.241379             19
Hippocampus_HFC                     39      67.241379             19
Insula_HFC                          39      67.241379             19
Precuneus_HFC                       39      67.241379             19
MTG_HFC                             39      67.241379             19
ParaHippocampus_HFC                 39      67.241379             19
Hippocampus EC                      39      67.241379             19
Insula_EC                           39      67.241379             19
Precuneus_EC                        39      67.241379             19
MTG_EC                              39      67.241379             19
ParaHippocampus_EC                  39      67.241379             19
Hippocampus_IC                      39      67.241379             19
Insula_IC                           39      67.241379             19
Precuneus_IC                        39      67.241379             19
MTG_IC                              39      67.241379             19
ParaHippocampus_IC                  39      67.241379             19
Hippocampus EIC                     39      67.241379             19
Insula_EIC                          39      67.241379             19
Precuneus_EIC                       39      67.241379             19
MTG_EIC                             39      67.241379             19
ParaHippocampus_EIC                 39      67.241379             19
Hippocampus_ED                      39      67.241379             19
Insula_ED                           39      67.241379             19
Precuneus_SMT_ED                    39      67.241379             19
MTG_ED                              39      67.241379             19
ParaHippocampus_SMT_ED              39      67.241379             19
Hippocampus_ID_IVF                  39      67.241379             19
Insula_ID_IVF                       39      67.241379             19
Precuneus_SMT_ID_IVF                39      67.241379             19
MTG_ID_IVF                          39      67.241379             19
ParaHippocampus_SMT_ID_IVF          39      67.241379             19
Hippocampus_IVF                     39      67.241379             19
Insula IVF                          39      67.241379             19
Precuneus_IVF                       39      67.241379             19
MTG_IVF                             39      67.241379             19
ParaHippocampus_SMT_IVF             39      67.241379             19
HFC_0102                            38      65.517241             20
HFC_0506                            38      65.517241             20
HFC_1314                            38      65.517241             20
HFC_2425                            38      65.517241             20
HFC_28                              38      65.517241             20
EC_0102                             38      65.517241             20
EC_0506                             38      65.517241             20
EC_1314                             38      65.517241             20
EC_2425                             38      65.517241             20
EC_28                               38      65.517241             20
EC_WM_0102                          38      65.517241             20
EC_WM_0506                          38      65.517241             20
EC_WM_1314                          38      65.517241             20
EC_WM_2425                          38      65.517241             20
EC_WM_28                            38      65.517241             20
IC_0102                             38      65.517241             20
IC_0506                             38      65.517241             20
IC_1314                             38      65.517241             20
IC_2425                             38      65.517241             20
IC_28                               38      65.517241             20
IC_WM_0102                          38      65.517241             20
IC_WM_0506                          38      65.517241             20
IC_WM_1314                          38      65.517241             20
IC_WM_2425                          38      65.517241             20
IC_WM_28                            38      65.517241             20
CSF_0102                            38      65.517241             20
CSF_0506                            38      65.517241             20
CSF_1314                            38      65.517241             20
CSF_2425                            38      65.517241             20
CSF_28                              38      65.517241             20
GMV_0102                            38      65.517241             20
GMV_0506                            38      65.517241             20
GMV_1314                            38      65.517241             20
GMV_2425                            38      65.517241             20
GMV_28                              38      65.517241             20
WMV_0102                            38      65.517241             20
WMV_0506                            38      65.517241             20
WMV_1314                            38      65.517241             20
WMV_2425                            38      65.517241             20
WMV_28                              38      65.517241             20
ADC_0102                            38      65.517241             20
ADC_0506                            38      65.517241             20
ADC_1314                            38      65.517241             20
ADC_2425                            38      65.517241             20
ADC_28                              38      65.517241             20
FA_0102                             38      65.517241             20
FA_0506                             38      65.517241             20
FA_1314                             38      65.517241             20
FA_2425                             38      65.517241             20
FA_28                               38      65.517241             20
MD_0102                             38      65.517241             20
MD_0506                             38      65.517241             20
MD_1314                             38      65.517241             20
MD_2425                             38      65.517241             20
MD_28                               38      65.517241             20
RD_0102                             38      65.517241             20
RD_0506                             38      65.517241             20
RD_1314                             38      65.517241             20
RD_2425                             38      65.517241             20
RD_28                               38      65.517241             20
ED_0102                             38      65.517241             20
ED_0506                             38      65.517241             20
ED_1314                             38      65.517241             20
ED_2425                             38      65.517241             20
ED_28                               38      65.517241             20
ED_EV_0102                          38      65.517241             20
ED_EV_0506                          38      65.517241             20
ED_EV_1314                          38      65.517241             20
ED_EV_2425                          38      65.517241             20
ED_EV_28                            38      65.517241             20
ED_EV_WM_0102                       38      65.517241             20
ED_EV_WM_0506                       38      65.517241             20
ED_EV_WM_1314                       38      65.517241             20
ED_EV_WM_2425                       38      65.517241             20
ED_EV_WM_28                         38      65.517241             20
ID_0102                             38      65.517241             20
ID_0506                             38      65.517241             20
ID_1314                             38      65.517241             20
ID_2425                             38      65.517241             20
ID_28                               38      65.517241             20
ID_IV_0102                          38      65.517241             20
ID_IV_0506                          38      65.517241             20
ID_IV_1314                          38      65.517241             20
ID_IV_2425                          38      65.517241             20
ID_IV_28                            38      65.517241             20
ID_IV_WM_0102                       38      65.517241             20
ID_IV_WM_0506                       38      65.517241             20
ID_IV_WM_1314                       38      65.517241             20
ID_IV_WM_2425                       38      65.517241             20
ID_IV_WM_28                         38      65.517241             20

In [58]:
hfc_dir = f'{SSD}\Conductivity\HFC관련 논문 data_Front Neurol 2022\환자정리'

hfc = pd.read_excel(os.path.join(hfc_dir, "환자정리최종.xlsx"), sheet_name="ROI")
hfc

,DDXIndex,ID,Name,Age,MMSE,TIV,Group,DDX,ROI1_Conduct,ROI2_Conduct,...,ROI11_GMV,ROI7_WMV,ROI8_WMV,ROI9_WMV,ROI10_WMV,ROI11_WMV,DDXIndex.1,ID.1,Name.1,DDX.1
0,AD01,1349735,이경순,72,22,1412,2,AD,0.605654,0.676924,...,0.459181,0.353072,0.273172,0.038932,0.482645,0.090323,AD01,1349735,이경순,AD
1,AD02,5118195,김화숙,73,19,1475,2,AD,0.633129,0.677433,...,0.321970,0.361569,0.328246,0.004990,0.481775,0.118875,AD02,5118195,김화숙,AD
2,AD03,5430317,주원심,76,16,1322,2,AD,0.636999,0.697268,...,0.428344,0.328688,0.256279,0.025015,0.420631,0.121405,AD03,5430317,주원심,AD
3,AD04,7814522,최병길,79,21,1454,2,AD,0.615969,0.667185,...,0.422778,0.341679,0.133372,0.012132,0.441813,0.124195,AD04,7814522,최병길,AD
4,AD05,449918,정욱,77,15,1302,2,AD,0.583444,0.551409,...,0.462634,0.435670,0.325794,0.002320,0.531227,0.128080,AD05,449918,정욱,AD
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
69,mdMCI18,2022033,현춘선,68,28,1300,1,MCI,0.542836,0.562514,...,0.532559,0.516284,0.382111,0.012649,0.603236,0.172609,mdMCI18,2022033,현춘선,MCI
70,mdMCI19,1509705,최계순,71,30,1295,1,MCI,0.612882,0.622778,...,0.495130,0.328301,0.284200,0.019441,0.464210,0.162883,mdMCI19,1509705,최계순,MCI
71,mdMCI20,129148,정호권,69,28,1696,1,MCI,0.534740,0.559296,...,0.507847,0.396101,0.373876,0.035645,0.510245,0.205655,mdMCI20,129148,정호권,MCI
72,mdMCI21,8324575,권영귀,77,26,1649,1,MCI,0.705858,0.688552,...,0.340031,0.229512,0.259630,0.012282,0.324915,0.079436,mdMCI21,8324575,권영귀,MCI
73,mdMCI22,2671227,박종애,79,23,1398,1,MCI,0.728307,0.755045,...,0.405008,0.279015,0.317386,0.009328,0.391207,0.161990,mdMCI22,2671227,박종애,MCI

In [59]:
hfc = hfc.rename(columns={'ID': 'PID'})
hfc['PID'] = (hfc['PID']
                .astype(str)
                .str.replace(r'\.0$', '', regex=True)
                .str.zfill(8))
print(hfc[['PID']])

roi_prefix_map = {
    'ROI1':  'Conduct1(age+)',
    'ROI2':  'Conduct2(age+)',
    'ROI3':  'Conduct1(age-)',
    'ROI4':  'Conduct1(MMSE+)',
    'ROI5':  'Conduct1(MMSE-)',
    'ROI6':  'Conduct2(MMSE-)',
    'ROI7':  'Conduct1(CN<MCI)',
    'ROI8':  'Conduct2(CN<MCI)',
    'ROI9':  'Conduct1(CN>AD)',
    'ROI10': 'Conduct1(CN<AD)',
    'ROI11': 'Conduct2(CN<AD)',
}

def rename_roi(col: str) -> str:
    """
    ROI9_WMV  →  Conduct1(CN>AD)_WMV
    접미사(_WMV 등)는 그대로 두고 접두사만 바꿔 준다
    """
    m = re.match(r'^(ROI\d{1,2})(_.+)$', col)
    if m and m.group(1) in roi_prefix_map:
        return f"{roi_prefix_map[m.group(1)]}{m.group(2)}"
    return col

hfc.columns = [rename_roi(c) for c in hfc.columns]

# ROI 열만 따로 추출 (+ PID)
roi_cols = [c for c in hfc.columns if re.match(r'^Conduct', c)]
hfc_roi  = hfc[['PID', *roi_cols]].copy()

hfc_roi

         PID
0   01349735
1   05118195
2   05430317
3   07814522
4   00449918
..       ...
69  02022033
70  01509705
71  00129148
72  08324575
73  02671227

[74 rows x 1 columns]

,PID,Conduct1(age+)_Conduct,Conduct2(age+)_Conduct,Conduct1(age-)_Conduct,Conduct1(MMSE+)_Conduct,Conduct1(MMSE-)_Conduct,Conduct2(MMSE-)_Conduct,Conduct1(age+)_GMV,Conduct2(age+)_GMV,Conduct1(age-)_GMV,...,Conduct1(CN<MCI)_GMV,Conduct2(CN<MCI)_GMV,Conduct1(CN>AD)_GMV,Conduct1(CN<AD)_GMV,Conduct2(CN<AD)_GMV,Conduct1(CN<MCI)_WMV,Conduct2(CN<MCI)_WMV,Conduct1(CN>AD)_WMV,Conduct1(CN<AD)_WMV,Conduct2(CN<AD)_WMV
0,01349735,0.605654,0.676924,0.280793,0.216159,0.633623,0.673540,0.374224,0.379449,0.114496,...,0.116808,0.314397,0.314397,0.143088,0.459181,0.353072,0.273172,0.038932,0.482645,0.090323
1,05118195,0.633129,0.677433,0.145895,0.160585,0.690116,0.715419,0.345735,0.329072,0.037032,...,0.089671,0.129864,0.129864,0.130442,0.321970,0.361569,0.328246,0.004990,0.481775,0.118875
2,05430317,0.636999,0.697268,0.179116,0.104017,0.627184,0.716127,0.418590,0.400956,0.097119,...,0.122286,0.287338,0.287338,0.167262,0.428344,0.328688,0.256279,0.025015,0.420631,0.121405
3,07814522,0.615969,0.667185,0.153798,0.172213,0.617612,0.645639,0.390750,0.385266,0.093218,...,0.126357,0.092517,0.092517,0.162754,0.422778,0.341679,0.133372,0.012132,0.441813,0.124195
4,00449918,0.583444,0.551409,0.132347,0.089884,0.579783,0.641816,0.412577,0.421279,0.029716,...,0.189917,0.354181,0.354181,0.203818,0.462634,0.435670,0.325794,0.002320,0.531227,0.128080
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
69,02022033,0.542836,0.562514,0.251524,0.270195,0.525465,0.630476,0.432250,0.441335,0.111919,...,0.158028,0.373096,0.373096,0.199782,0.532559,0.516284,0.382111,0.012649,0.603236,0.172609
70,01509705,0.612882,0.622778,0.223073,0.303619,0.617922,0.681474,0.382926,0.413276,0.138410,...,0.127660,0.377457,0.377457,0.171647,0.495130,0.328301,0.284200,0.019441,0.464210,0.162883
71,00129148,0.534740,0.559296,0.315555,0.284694,0.486478,0.558216,0.404494,0.411421,0.166080,...,0.129455,0.320718,0.320718,0.177486,0.507847,0.396101,0.373876,0.035645,0.510245,0.205655
72,08324575,0.705858,0.688552,0.225145,0.453964,0.618617,0.735421,0.328774,0.356541,0.207935,...,0.089885,0.157323,0.157323,0.140165,0.340031,0.229512,0.259630,0.012282,0.324915,0.079436
73,02671227,0.728307,0.755045,0.227169,0.229874,0.755406,0.807322,0.414878,0.399513,0.087204,...,0.115394,0.241480,0.241480,0.159159,0.405008,0.279015,0.317386,0.009328,0.391207,0.161990

In [60]:
def attach_roi(target: pd.DataFrame, roi_source: pd.DataFrame) -> pd.DataFrame:
    out = target.copy()
    out['PID'] = (
        out['PID'].astype(str)
                  .str.replace(r'\.0$', '', regex=True)
                  .str.zfill(8)
    )
    for c in roi_cols:
        if c not in out.columns:
            out[c] = np.nan
    merged = out.merge(roi_source, on='PID', how='left', suffixes=('', '_h'))

    for c in roi_cols:
        h_col = f'{c}_h'
        if h_col in merged.columns:
            out[c] = out[c].combine_first(merged[h_col])

    h_cols_to_drop = [col for col in out.columns if col.endswith('_h')]
    out.drop(columns=h_cols_to_drop, inplace=True)

    return out


# 적용
dfCN = attach_roi(dfCN, hfc_roi)
dfAD = attach_roi(dfAD, hfc_roi)

In [62]:
for frame in [dfCN, dfAD]:
    frame.drop(columns='Unnamed: 0', errors='ignore', inplace=True)
dfCN

,PDI,PID,DDX,Year,Age,sex,Education_yr,LH-ALL_Dxx_proj,LH-ALL_Dyy_proj,LH-ALL_Dzz_proj,...,Conduct1(CN<MCI)_GMV,Conduct2(CN<MCI)_GMV,Conduct1(CN>AD)_GMV,Conduct1(CN<AD)_GMV,Conduct2(CN<AD)_GMV,Conduct1(CN<MCI)_WMV,Conduct2(CN<MCI)_WMV,Conduct1(CN>AD)_WMV,Conduct1(CN<AD)_WMV,Conduct2(CN<AD)_WMV
0,MWI_CN01_KNH_NODDI32,00145616,NL,2019.0,70,F,16.0,0.853582,0.731372,1.259900,...,0.167457,0.349497,0.349497,0.193131,0.532865,0.465235,0.397332,0.035594,0.557611,0.231313
1,MWI_CN04_SSS_NODDI32,02716077,NL,2019.0,62,F,12.0,0.721595,0.654347,1.212313,...,0.175981,0.361656,0.361656,0.206283,0.617785,0.612903,0.476610,0.065599,0.654826,0.240354
2,MWI_CN05_LSS_NODDI32,00469852,NL,2019.0,72,M,16.0,0.648850,0.534350,1.036836,...,0.168533,0.348838,0.348838,0.213031,0.549838,0.474108,0.366645,0.043454,0.536630,0.169067
3,MWI_CN06_KDS_NODDI32,02296061,NL,2019.0,72,M,6.0,0.776232,0.855603,0.955848,...,0.160151,0.310811,0.310811,0.198166,0.520646,0.419997,0.316220,0.011297,0.503590,0.123183
4,MWI_CN07_KSB_NODDI32,00316024,NL,2019.0,66,M,9.0,0.760503,0.692654,1.243302,...,0.153674,0.329653,0.329653,0.183395,0.544250,0.533646,0.367877,0.032507,0.603880,0.178495
5,MWI_CN09_YKJ_NODDI32,00080969,NaMCI,2019.0,65,F,12.0,0.721305,0.585058,1.168966,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,MWI_CN10_CJS_NODDI32,01147259,Other,2019.0,66,F,9.0,0.766402,0.500861,1.051554,...,0.155215,0.317403,0.317403,0.183150,0.560956,0.491351,0.370764,0.025816,0.581022,0.175645
7,MWI_CN12_LJK_NODDI32,05871888,NL,2019.0,66,F,12.0,0.809517,0.506511,1.159348,...,0.162523,0.345765,0.345765,0.203357,0.523221,0.574373,0.394390,0.081852,0.620462,0.216185
8,MWI_CN13_KH_NODDI32,06476189,SaMCI,2019.0,69,M,16.0,0.661128,0.740881,1.190856,...,0.102180,0.380195,0.380195,0.144450,0.501961,0.213131,0.272522,0.058139,0.339196,0.150806
9,MWI_CN14_PYJ_NODDI32,04341115,NaMCI,2019.0,66,F,0.5,0.667318,0.716731,1.135098,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,MWI_CN15_YCJ_NODDI32,01607233,Other,2019.0,75,F,6.0,0.783634,0.542104,1.197984,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11,MWI_CN16_LCS_NODDI32,01190888,NaMCI,2019.0,74,M,12.0,0.750492,0.767349,1.155198,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12,MWI_CN17_LPS_NODDI32,04825611,MaMCI,2019.0,63,F,7.0,0.812866,0.996424,1.218665,...,0.204153,0.350456,0.350456,0.237186,0.536533,0.512919,0.399772,0.016888,0.596895,0.178904
13,MWI_CN18_HCS_NODDI32,02022033,MaMCI,2019.0,68,F,6.0,0.805717,0.608529,1.132986,...,0.158028,0.373096,0.373096,0.199782,0.532559,0.516284,0.382111,0.012649,0.603236,0.172609
14,MWI_CN19_CSO_NODDI32,04073053,NL,2019.0,64,F,9.0,0.637047,0.484846,1.023011,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15,MWI_CN20_PYJ_NODDI32,01382411,NL,2020.0,68,M,12.0,0.649847,0.728100,0.978214,...,0.168892,0.348418,0.348418,0.206283,0.577654,0.428407,0.389995,0.009011,0.523210,0.198958
16,MWI_CN21_PYB_NODDI32,04086417,NL,2020.0,66,F,14.0,89.345674,85.156431,85.893714,...,0.193583,0.396548,0.396548,0.241792,0.611549,0.544235,0.432011,0.052482,0.596816,0.209086
17,MWI_CN22_YYJ_NODDI32,00875397,NL,2020.0,66,F,16.0,0.771681,0.663884,0.996707,...,0.192371,0.382432,0.382432,0.220781,0.541266,0.566529,0.428822,0.064431,0.619612,0.245206
18,MWI_CN23_HJL_NODDI32,08481071,NL,2020.0,64,F,12.0,0.861621,0.685175,1.368943,...,0.166774,0.326409,0.326409,0.205544,0.535372,0.453169,0.405122,0.077714,0.562260,0.243911
19,MWI_CN24_PKJ_NODDI32,08481058,NL,2020.0,72,M,16.0,0.780769,0.805937,1.189413,...,0.163051,0.346796,0.346796,0.194219,0.559229,0.501062,0.390662,0.036062,0.563922,0.164870
20,MWI_CN25_NKJ_NODDI32,08500417,MaMCI,2020.0,79,F,6.0,0.809053,0.628974,1.200095,...,0.154649,0.362314,0.362314,0.198797,0.474488,0.454914,0.281011,0.008794,0.533708,0.118585
21,MWI_CN26_LSR_NODDI32,08510171,MaMCI,2020.0,69,F,6.0,0.651656,0.516872,1.081359,...,0.225244,0.413002,0.413002,0.251379,0.592819,0.554312,0.460856,0.049328,0.616605,0.219556
22,MWI_CN27_LSJ_NODDI32,08510155,NL,2020.0,68,M,9.0,0.785996,0.609021,1.140311,...,0.196405,0.353123,0.353123,0.233493,0.551870,0.448876,0.369993,0.033242,0.544964,0.159571
23,MWI_CN28_KOS_NODDI32,00213101,NL,2020.0,68,F,9.0,0.821979,0.734907,0.993994,...,0.210704,0.371234,0.371234,0.258842,0.590349,0.448706,0.359701,0.022078,0.534529,0.151222
24,MWI_CN29_KSH_NODDI32,00243749,SaMCI,2020.0,70,F,12.0,0.652968,0.485778,1.078290,...,0.126480,0.283865,0.283865,0.167040,0.472411,0.366299,0.281208,0.046859,0.476430,0.204018
25,MWI_CN30_PYS_NODDI32,08519137,MaMCI,2020.0,61,F,9.0,0.659945,0.500463,0.978506,...,0.210599,0.337953,0.337953,0.250633,0.557763,0.525152,0.376881,0.064297,0.586858,0.219898
26,MWI_CN31_LOH_NODDI32,02528398,MaMCI,2020.0,75,F,0.0,0.636865,0.624176,1.164440,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
27,MWI_CN32_KYH_NODDI32,08664289,SaMCI,2020.0,81,M,9.0,0.696205,0.723061,1.101509,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
28,MWI_CN33_LSH_NODDI32,01206895,NL,2020.0,68,F,12.0,0.638877,0.698796,1.098446,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
29,MWI_CN34_OJS_NODDI32,04727886,NL,2020.0,77,F,8.0,0.687721,0.524964,1.058712,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
30,MWI_CN35_LES_NODDI32,08696493,NL,2020.0,61,F,12.0,0.763828,0.533087,1.089920,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
31,MWI_CN36_KER_NODDI32,00738146,SaMCI,2020.0,64,F,12.0,0.747137,0.516512,1.174375,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
32,MWI_CN37_KJR_NODDI32,01283958,NaMCI,2020.0,65,M,12.0,1.267064,1.244017,1.117839,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
33,MWI_CN38_JJB_NODDI32,02022042,NL,2020.0,71,M,3.0,0.697029,0.773143,1.046729,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
34,MWI_CN39_LTS_NODDI32,00613165,NL,2020.0,77,M,12.0,0.676112,0.748491,1.064096,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
35,MWI_CN40_LDS_NODDI32,08129675,NL,2020.0,72,F,12.0,0.680826,0.595489,1.151737,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
36,MWI_CN41_JHL_NODDI32,04920375,NL,2020.0,83,F,6.0,0.730996,0.606768,1.137128,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
37,MWI_CN57_YHY_NODDI32,08527223,NL,2022.0,76,F,NaN,0.629832,0.574801,0.976331,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
38,MWI_CN58_LSB_NODDI32,00213324,NL,2022.0,70,M,NaN,0.707732,0.692642,1.101284,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
39,MWI_CN61_CHS_NODDI32,01422655,NL,2022.0,76,M,NaN,0.691838,0.513470,1.145116,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
40,MWI_CN65_PYS_NODDI32,09524528,NL,2022.0,72,F,NaN,0.742088,0.611022,1.156521,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
41,MWI_CN66_CSY_NODDI32,00766581,NaMCI,2022.0,71,F,NaN,0.663827,0.725533,1.045238,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
42,MWI_CN67_KOS_NODDI32,09577263,NaMCI,2022.0,82,F,NaN,0.625652,0.643337,1.160600,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
43,MWI_CN68_CDL_NODDI32,00641619,MaMCI,2022.0,74,F,NaN,0.825319,0.661257,1.253624,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
44,MWI_CN69_LSL_NODDI32,09588015,NL,2022.0,69,F,NaN,0.567737,0.528092,1.266596,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
45,MWI_CN70_LCJ_NODDI32,02202449,NaMCI,2022.0,80,F,NaN,0.771396,0.632500,1.171522,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
46,MWI_CN71_LSH_NODDI32,00863315,NL,2022.0,73,F,NaN,0.635816,0.511072,1.056698,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
47,MWI_CN73_GIS_NODDI32,04074843,MaMCI,2022.0,74,F,NaN,0.614696,0.510977,1.052888,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
48,MWI_CN74_LKY_NODDI32,09605724,SaMCI,2022.0,71,F,NaN,0.636038,0.581639,0.989334,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
49,MWI_CN75_KKS_NODDI32,09605754,SaMCI,2022.0,73,M,NaN,0.839752,0.745258,1.373741,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
50,MWI_CN76_PHJ_NODDI32,00359871,NL,2022.0,78,F,NaN,0.974929,0.802987,1.458045,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
51,MWI_CN77_PJC_NODDI32,07090169,NL,NaN,68,M,NaN,0.666742,0.643739,1.125764,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
52,MWI_CN79_CYE_NODDI32,10412739,SaMCI,2023.0,72,F,NaN,0.753935,0.504262,1.198478,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
53,MWI_CN80_LSR_NODDI32,10474812,MaMCI,NaN,78,F,NaN,0.602834,0.559894,1.037194,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
54,MWI_CN81_CSH_NODDI32,10482577,SaMCI,2024.0,66,M,NaN,0.638415,0.664246,1.101576,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
55,MWI_CN82_LMR_NODDI32,10412747,SaMCI,2023.0,74,M,NaN,0.789849,0.802365,1.201563,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
56,MWI_CN83_LYS_NODDI32,10474783,NL,NaN,74,F,NaN,0.572063,0.531833,1.064045,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
57,MWI_CN84_LHS_NODDI32,10474798,MaMCI,2024.0,74,F,NaN,0.647483,0.572705,1.053408,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [63]:
with pd.ExcelWriter(os.path.join(SSD, "Auto_ALPS_index_19-24_fin0728_M03.xlsx")
                    , engine="xlsxwriter") as writer:
    dfCN.to_excel(writer, sheet_name="CN", index=False)
    dfAD.to_excel(writer, sheet_name="Dementia", index=False)

In [ ]:
df = 
for column in df.columns:
    print(f"Col name: {column}")
    print(f"Data type: {df[column].dtype}")
    print(f"Unique values: {len(df[column].unique())}")
    print(df[column].unique())
    print('-'*40)